<%@ Page Language="C#" AutoEventWireup="true" CodeFile="test.aspx.cs" Inherits="eTraining_test" %>

<%@ Register assembly="Telerik.Web.UI" namespace="Telerik.Web.UI" tagprefix="telerik" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        <telerik:RadScriptManager ID="RadScriptManager1" Runat="server">
        </telerik:RadScriptManager>
        <br />
        <telerik:RadGrid ID="RadGrid1" runat="server" AutoGenerateDeleteColumn="True" 
            AutoGenerateEditColumn="True" CellSpacing="0" Culture="zh-TW" 
            DataSourceID="LinqDataSource1" GridLines="None" 
            onneeddatasource="RadGrid1_NeedDataSource">
<MasterTableView AutoGenerateColumns="False" DataKeyNames="c.iAutoKey" 
                DataSourceID="LinqDataSource1">
<CommandItemSettings ExportToPdfText="Export to PDF"></CommandItemSettings>

<RowIndicatorColumn FilterControlAltText="Filter RowIndicator column">
</RowIndicatorColumn>

<ExpandCollapseColumn FilterControlAltText="Filter ExpandColumn column">
</ExpandCollapseColumn>

    <Columns>
        <telerik:GridBoundColumn DataField="c.iAutoKey" DataType="System.Int32" 
            FilterControlAltText="Filter iAutoKey column" HeaderText="iAutoKey" 
            ReadOnly="True" SortExpression="iAutoKey" UniqueName="iAutoKey">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="c.sCode" 
            FilterControlAltText="Filter sCode column" HeaderText="sCode" 
            SortExpression="sCode" UniqueName="sCode">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="c.sName" 
            FilterControlAltText="Filter sName column" HeaderText="sName" 
            SortExpression="sName" UniqueName="sName">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="c.sKeyMan" 
            FilterControlAltText="Filter sKeyMan column" HeaderText="sKeyMan" 
            SortExpression="sKeyMan" UniqueName="sKeyMan">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="c.dKeyDate" DataType="System.DateTime" 
            FilterControlAltText="Filter dKeyDate column" HeaderText="dKeyDate" 
            SortExpression="dKeyDate" UniqueName="dKeyDate">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="i.iiKey" 
            FilterControlAltText="Filter iiKey column" HeaderText="iiKey" 
            UniqueName="iiKey">
        </telerik:GridBoundColumn>
    </Columns>

<EditFormSettings>
<EditColumn FilterControlAltText="Filter EditCommandColumn column"></EditColumn>
</EditFormSettings>
</MasterTableView>

<FilterMenu EnableImageSprites="False"></FilterMenu>

<HeaderContextMenu CssClass="GridContextMenu GridContextMenu_Default"></HeaderContextMenu>
        </telerik:RadGrid>
    
    </div>
    <asp:LinqDataSource ID="LinqDataSource1" runat="server" 
        ContextTypeName="dcTrainingDataContext" EnableDelete="True" EnableInsert="True" 
        EnableUpdate="True" EntityTypeName="" onselecting="LinqDataSource1_Selecting" 
        TableName="trNotifyTemplate">
    </asp:LinqDataSource>
    <telerik:RadUpload ID="RadUpload1" Runat="server" 
        ControlObjectsVisibility="CheckBoxes, RemoveButtons">
    </telerik:RadUpload>
    <br />
    <div>
            <telerik:RadTextBox ID="RadTextBox1" runat="server">
            </telerik:RadTextBox><telerik:RadButton ID="RadButton1" runat="server" 
                Text="RadButton" onclick="RadButton1_Click">
            </telerik:RadButton>
            <br />
            <telerik:RadGrid ID="RadGrid2" runat="server" Culture="zh-TW" 
                DataSourceID="SqlDataSource1" Visible="False">
<MasterTableView AutoGenerateColumns="False" DataSourceID="SqlDataSource1">
<CommandItemSettings ExportToPdfText="Export to PDF"></CommandItemSettings>

<RowIndicatorColumn FilterControlAltText="Filter RowIndicator column">
<HeaderStyle Width="20px"></HeaderStyle>
</RowIndicatorColumn>

<ExpandCollapseColumn FilterControlAltText="Filter ExpandColumn column">
<HeaderStyle Width="20px"></HeaderStyle>
</ExpandCollapseColumn>

    <Columns>
        <telerik:GridBoundColumn DataField="NAME_C" 
            FilterControlAltText="Filter NAME_C column" HeaderText="NAME_C" 
            SortExpression="NAME_C" UniqueName="NAME_C">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="sCode" 
            FilterControlAltText="Filter sCode column" HeaderText="sCode" 
            SortExpression="sCode" UniqueName="sCode">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="sName" 
            FilterControlAltText="Filter sName column" HeaderText="sName" 
            SortExpression="sName" UniqueName="sName">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="sCode1" 
            FilterControlAltText="Filter sCode1 column" HeaderText="sCode1" 
            SortExpression="sCode1" UniqueName="sCode1">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="sName1" 
            FilterControlAltText="Filter sName1 column" HeaderText="sName1" 
            SortExpression="sName1" UniqueName="sName1">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="iSession" DataType="System.Int32" 
            FilterControlAltText="Filter iSession column" HeaderText="iSession" 
            SortExpression="iSession" UniqueName="iSession">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="dDateA" DataType="System.DateTime" 
            FilterControlAltText="Filter dDateA column" HeaderText="dDateA" 
            SortExpression="dDateA" UniqueName="dDateA">
        </telerik:GridBoundColumn>
    </Columns>

<EditFormSettings>
<EditColumn FilterControlAltText="Filter EditCommandColumn column"></EditColumn>
</EditFormSettings>
</MasterTableView>

<FilterMenu EnableImageSprites="False"></FilterMenu>

<HeaderContextMenu CssClass="GridContextMenu GridContextMenu_Default"></HeaderContextMenu>
            </telerik:RadGrid>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
                ConnectionString="<%$ ConnectionStrings:eLearningConnectionString %>" SelectCommand="select b.NAME_C,cat.sCode,cat.sName,c.sCode,c.sName,dm.iSession,dm.dDateA from trTrainingStudentM sm
join trTrainingDetailM dm on sm.iClassAutoKey=dm.iAutoKey
join trCourse c on dm.trCourse_sCode = c.sCode
join trCategoryCourse cc on cc.sCourseCode = c.sCode
join trCategory cat on cc.sCateCode = cat.sCode
join BASE b on sm.sNobr=b.NOBR
where b.NAME_C= @name and
dm.iYear='2011'
order by dm.dDateA">
                <SelectParameters>
                    <asp:ControlParameter ControlID="RadTextBox1" DefaultValue="0" Name="name" 
                        PropertyName="Text" />
                </SelectParameters>
            </asp:SqlDataSource>
            <asp:Label ID="Label1" runat="server" Text="Label"></asp:Label>
            <br />
        </div>
    </form>
</body>
</html>
