#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HRM_API")]
	public partial class dcAppDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 擴充性方法定義
    partial void OnCreated();
    partial void InsertAppRegistryKey_Bind(AppRegistryKey_Bind instance);
    partial void UpdateAppRegistryKey_Bind(AppRegistryKey_Bind instance);
    partial void DeleteAppRegistryKey_Bind(AppRegistryKey_Bind instance);
    partial void InsertAppSetting_Configuration(AppSetting_Configuration instance);
    partial void UpdateAppSetting_Configuration(AppSetting_Configuration instance);
    partial void DeleteAppSetting_Configuration(AppSetting_Configuration instance);
    partial void InsertFencePoints(FencePoints instance);
    partial void UpdateFencePoints(FencePoints instance);
    partial void DeleteFencePoints(FencePoints instance);
    partial void InsertFencePointsOrigin(FencePointsOrigin instance);
    partial void UpdateFencePointsOrigin(FencePointsOrigin instance);
    partial void DeleteFencePointsOrigin(FencePointsOrigin instance);
    partial void InsertSSID_Identifier(SSID_Identifier instance);
    partial void UpdateSSID_Identifier(SSID_Identifier instance);
    partial void DeleteSSID_Identifier(SSID_Identifier instance);
    partial void InsertPunchCardType(PunchCardType instance);
    partial void UpdatePunchCardType(PunchCardType instance);
    partial void DeletePunchCardType(PunchCardType instance);
    partial void InsertQRCode_Verification(QRCode_Verification instance);
    partial void UpdateQRCode_Verification(QRCode_Verification instance);
    partial void DeleteQRCode_Verification(QRCode_Verification instance);
    partial void InsertCardAppDetails(CardAppDetails instance);
    partial void UpdateCardAppDetails(CardAppDetails instance);
    partial void DeleteCardAppDetails(CardAppDetails instance);
    partial void InsertCardAppImages(CardAppImages instance);
    partial void UpdateCardAppImages(CardAppImages instance);
    partial void DeleteCardAppImages(CardAppImages instance);
    #endregion
		
		public dcAppDataContext() : 
				base(global::Dal.Properties.Settings.Default.AppConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dcAppDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcAppDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcAppDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcAppDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AppRegistryKey_Bind> AppRegistryKey_Bind
		{
			get
			{
				return this.GetTable<AppRegistryKey_Bind>();
			}
		}
		
		public System.Data.Linq.Table<AppSetting_Configuration> AppSetting_Configuration
		{
			get
			{
				return this.GetTable<AppSetting_Configuration>();
			}
		}
		
		public System.Data.Linq.Table<FencePoints> FencePoints
		{
			get
			{
				return this.GetTable<FencePoints>();
			}
		}
		
		public System.Data.Linq.Table<FencePointsOrigin> FencePointsOrigin
		{
			get
			{
				return this.GetTable<FencePointsOrigin>();
			}
		}
		
		public System.Data.Linq.Table<SSID_Identifier> SSID_Identifier
		{
			get
			{
				return this.GetTable<SSID_Identifier>();
			}
		}
		
		public System.Data.Linq.Table<PunchCardType> PunchCardType
		{
			get
			{
				return this.GetTable<PunchCardType>();
			}
		}
		
		public System.Data.Linq.Table<QRCode_Verification> QRCode_Verification
		{
			get
			{
				return this.GetTable<QRCode_Verification>();
			}
		}
		
		public System.Data.Linq.Table<CardAppDetails> CardAppDetails
		{
			get
			{
				return this.GetTable<CardAppDetails>();
			}
		}
		
		public System.Data.Linq.Table<CardAppImages> CardAppImages
		{
			get
			{
				return this.GetTable<CardAppImages>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AppRegistryKey_Bind")]
	public partial class AppRegistryKey_Bind : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AutoKey;
		
		private string _Name;
		
		private string _Nobr;
		
		private string _APP_RegistryKey;
		
		private string _KeyMan;
		
		private System.Nullable<System.DateTime> _KeyDate;
		
		private System.Nullable<bool> _Status;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAutoKeyChanging(int value);
    partial void OnAutoKeyChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnNobrChanging(string value);
    partial void OnNobrChanged();
    partial void OnAPP_RegistryKeyChanging(string value);
    partial void OnAPP_RegistryKeyChanged();
    partial void OnKeyManChanging(string value);
    partial void OnKeyManChanged();
    partial void OnKeyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnKeyDateChanged();
    partial void OnStatusChanging(System.Nullable<bool> value);
    partial void OnStatusChanged();
    #endregion
		
		public AppRegistryKey_Bind()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoKey", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AutoKey
		{
			get
			{
				return this._AutoKey;
			}
			set
			{
				if ((this._AutoKey != value))
				{
					this.OnAutoKeyChanging(value);
					this.SendPropertyChanging();
					this._AutoKey = value;
					this.SendPropertyChanged("AutoKey");
					this.OnAutoKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nobr", DbType="NVarChar(50)")]
		public string Nobr
		{
			get
			{
				return this._Nobr;
			}
			set
			{
				if ((this._Nobr != value))
				{
					this.OnNobrChanging(value);
					this.SendPropertyChanging();
					this._Nobr = value;
					this.SendPropertyChanged("Nobr");
					this.OnNobrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APP_RegistryKey", DbType="NVarChar(50)")]
		public string APP_RegistryKey
		{
			get
			{
				return this._APP_RegistryKey;
			}
			set
			{
				if ((this._APP_RegistryKey != value))
				{
					this.OnAPP_RegistryKeyChanging(value);
					this.SendPropertyChanging();
					this._APP_RegistryKey = value;
					this.SendPropertyChanged("APP_RegistryKey");
					this.OnAPP_RegistryKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyMan", DbType="NVarChar(50)")]
		public string KeyMan
		{
			get
			{
				return this._KeyMan;
			}
			set
			{
				if ((this._KeyMan != value))
				{
					this.OnKeyManChanging(value);
					this.SendPropertyChanging();
					this._KeyMan = value;
					this.SendPropertyChanged("KeyMan");
					this.OnKeyManChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> KeyDate
		{
			get
			{
				return this._KeyDate;
			}
			set
			{
				if ((this._KeyDate != value))
				{
					this.OnKeyDateChanging(value);
					this.SendPropertyChanging();
					this._KeyDate = value;
					this.SendPropertyChanged("KeyDate");
					this.OnKeyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit")]
		public System.Nullable<bool> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AppSetting_Configuration")]
	public partial class AppSetting_Configuration : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AutoKey;
		
		private string _SettingValue;
		
		private string _SettingItem;
		
		private string _KeyMan;
		
		private System.Nullable<System.DateTime> _KeyDate;
		
		private string _Note;
		
		private string _Group;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAutoKeyChanging(int value);
    partial void OnAutoKeyChanged();
    partial void OnSettingValueChanging(string value);
    partial void OnSettingValueChanged();
    partial void OnSettingItemChanging(string value);
    partial void OnSettingItemChanged();
    partial void OnKeyManChanging(string value);
    partial void OnKeyManChanged();
    partial void OnKeyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnKeyDateChanged();
    partial void OnNoteChanging(string value);
    partial void OnNoteChanged();
    partial void OnGroupChanging(string value);
    partial void OnGroupChanged();
    #endregion
		
		public AppSetting_Configuration()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoKey", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AutoKey
		{
			get
			{
				return this._AutoKey;
			}
			set
			{
				if ((this._AutoKey != value))
				{
					this.OnAutoKeyChanging(value);
					this.SendPropertyChanging();
					this._AutoKey = value;
					this.SendPropertyChanged("AutoKey");
					this.OnAutoKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SettingValue", DbType="NVarChar(50)")]
		public string SettingValue
		{
			get
			{
				return this._SettingValue;
			}
			set
			{
				if ((this._SettingValue != value))
				{
					this.OnSettingValueChanging(value);
					this.SendPropertyChanging();
					this._SettingValue = value;
					this.SendPropertyChanged("SettingValue");
					this.OnSettingValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SettingItem", DbType="NVarChar(50)")]
		public string SettingItem
		{
			get
			{
				return this._SettingItem;
			}
			set
			{
				if ((this._SettingItem != value))
				{
					this.OnSettingItemChanging(value);
					this.SendPropertyChanging();
					this._SettingItem = value;
					this.SendPropertyChanged("SettingItem");
					this.OnSettingItemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyMan", DbType="NVarChar(50)")]
		public string KeyMan
		{
			get
			{
				return this._KeyMan;
			}
			set
			{
				if ((this._KeyMan != value))
				{
					this.OnKeyManChanging(value);
					this.SendPropertyChanging();
					this._KeyMan = value;
					this.SendPropertyChanged("KeyMan");
					this.OnKeyManChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> KeyDate
		{
			get
			{
				return this._KeyDate;
			}
			set
			{
				if ((this._KeyDate != value))
				{
					this.OnKeyDateChanging(value);
					this.SendPropertyChanging();
					this._KeyDate = value;
					this.SendPropertyChanged("KeyDate");
					this.OnKeyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(MAX)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this.OnNoteChanging(value);
					this.SendPropertyChanging();
					this._Note = value;
					this.SendPropertyChanged("Note");
					this.OnNoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Group]", Storage="_Group", DbType="NVarChar(50)")]
		public string Group
		{
			get
			{
				return this._Group;
			}
			set
			{
				if ((this._Group != value))
				{
					this.OnGroupChanging(value);
					this.SendPropertyChanging();
					this._Group = value;
					this.SendPropertyChanged("Group");
					this.OnGroupChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FencePoints")]
	public partial class FencePoints : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AutoKey;
		
		private System.Nullable<decimal> _oLatitude;
		
		private System.Nullable<decimal> _oLongitude;
		
		private System.Nullable<decimal> _Latitude;
		
		private System.Nullable<decimal> _Longitude;
		
		private System.Nullable<double> _Distance;
		
		private string _Address;
		
		private string _Note;
		
		private string _PointsGroup;
		
		private string _KeyMan;
		
		private System.Nullable<System.DateTime> _KeyDate;
		
		private System.Nullable<bool> _Status;
		
		private System.Nullable<bool> _isEffctive;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAutoKeyChanging(int value);
    partial void OnAutoKeyChanged();
    partial void OnoLatitudeChanging(System.Nullable<decimal> value);
    partial void OnoLatitudeChanged();
    partial void OnoLongitudeChanging(System.Nullable<decimal> value);
    partial void OnoLongitudeChanged();
    partial void OnLatitudeChanging(System.Nullable<decimal> value);
    partial void OnLatitudeChanged();
    partial void OnLongitudeChanging(System.Nullable<decimal> value);
    partial void OnLongitudeChanged();
    partial void OnDistanceChanging(System.Nullable<double> value);
    partial void OnDistanceChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnNoteChanging(string value);
    partial void OnNoteChanged();
    partial void OnPointsGroupChanging(string value);
    partial void OnPointsGroupChanged();
    partial void OnKeyManChanging(string value);
    partial void OnKeyManChanged();
    partial void OnKeyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnKeyDateChanged();
    partial void OnStatusChanging(System.Nullable<bool> value);
    partial void OnStatusChanged();
    partial void OnisEffctiveChanging(System.Nullable<bool> value);
    partial void OnisEffctiveChanged();
    #endregion
		
		public FencePoints()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoKey", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AutoKey
		{
			get
			{
				return this._AutoKey;
			}
			set
			{
				if ((this._AutoKey != value))
				{
					this.OnAutoKeyChanging(value);
					this.SendPropertyChanging();
					this._AutoKey = value;
					this.SendPropertyChanged("AutoKey");
					this.OnAutoKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oLatitude", DbType="Decimal(11,8)")]
		public System.Nullable<decimal> oLatitude
		{
			get
			{
				return this._oLatitude;
			}
			set
			{
				if ((this._oLatitude != value))
				{
					this.OnoLatitudeChanging(value);
					this.SendPropertyChanging();
					this._oLatitude = value;
					this.SendPropertyChanged("oLatitude");
					this.OnoLatitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oLongitude", DbType="Decimal(11,8)")]
		public System.Nullable<decimal> oLongitude
		{
			get
			{
				return this._oLongitude;
			}
			set
			{
				if ((this._oLongitude != value))
				{
					this.OnoLongitudeChanging(value);
					this.SendPropertyChanging();
					this._oLongitude = value;
					this.SendPropertyChanged("oLongitude");
					this.OnoLongitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitude", DbType="Decimal(11,8)")]
		public System.Nullable<decimal> Latitude
		{
			get
			{
				return this._Latitude;
			}
			set
			{
				if ((this._Latitude != value))
				{
					this.OnLatitudeChanging(value);
					this.SendPropertyChanging();
					this._Latitude = value;
					this.SendPropertyChanged("Latitude");
					this.OnLatitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitude", DbType="Decimal(11,8)")]
		public System.Nullable<decimal> Longitude
		{
			get
			{
				return this._Longitude;
			}
			set
			{
				if ((this._Longitude != value))
				{
					this.OnLongitudeChanging(value);
					this.SendPropertyChanging();
					this._Longitude = value;
					this.SendPropertyChanged("Longitude");
					this.OnLongitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Distance", DbType="Float")]
		public System.Nullable<double> Distance
		{
			get
			{
				return this._Distance;
			}
			set
			{
				if ((this._Distance != value))
				{
					this.OnDistanceChanging(value);
					this.SendPropertyChanging();
					this._Distance = value;
					this.SendPropertyChanged("Distance");
					this.OnDistanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(50)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(50)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this.OnNoteChanging(value);
					this.SendPropertyChanging();
					this._Note = value;
					this.SendPropertyChanged("Note");
					this.OnNoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PointsGroup", DbType="NVarChar(50)")]
		public string PointsGroup
		{
			get
			{
				return this._PointsGroup;
			}
			set
			{
				if ((this._PointsGroup != value))
				{
					this.OnPointsGroupChanging(value);
					this.SendPropertyChanging();
					this._PointsGroup = value;
					this.SendPropertyChanged("PointsGroup");
					this.OnPointsGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyMan", DbType="NVarChar(50)")]
		public string KeyMan
		{
			get
			{
				return this._KeyMan;
			}
			set
			{
				if ((this._KeyMan != value))
				{
					this.OnKeyManChanging(value);
					this.SendPropertyChanging();
					this._KeyMan = value;
					this.SendPropertyChanged("KeyMan");
					this.OnKeyManChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> KeyDate
		{
			get
			{
				return this._KeyDate;
			}
			set
			{
				if ((this._KeyDate != value))
				{
					this.OnKeyDateChanging(value);
					this.SendPropertyChanging();
					this._KeyDate = value;
					this.SendPropertyChanged("KeyDate");
					this.OnKeyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit")]
		public System.Nullable<bool> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isEffctive", DbType="Bit")]
		public System.Nullable<bool> isEffctive
		{
			get
			{
				return this._isEffctive;
			}
			set
			{
				if ((this._isEffctive != value))
				{
					this.OnisEffctiveChanging(value);
					this.SendPropertyChanging();
					this._isEffctive = value;
					this.SendPropertyChanged("isEffctive");
					this.OnisEffctiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FencePointsOrigin")]
	public partial class FencePointsOrigin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AutoKey;
		
		private System.Nullable<decimal> _Latitude;
		
		private System.Nullable<decimal> _Longitude;
		
		private System.Nullable<double> _Distance;
		
		private string _Address;
		
		private string _Note;
		
		private string _KeyMan;
		
		private System.Nullable<System.DateTime> _KeyDate;
		
		private System.Nullable<bool> _Status;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAutoKeyChanging(int value);
    partial void OnAutoKeyChanged();
    partial void OnLatitudeChanging(System.Nullable<decimal> value);
    partial void OnLatitudeChanged();
    partial void OnLongitudeChanging(System.Nullable<decimal> value);
    partial void OnLongitudeChanged();
    partial void OnDistanceChanging(System.Nullable<double> value);
    partial void OnDistanceChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnNoteChanging(string value);
    partial void OnNoteChanged();
    partial void OnKeyManChanging(string value);
    partial void OnKeyManChanged();
    partial void OnKeyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnKeyDateChanged();
    partial void OnStatusChanging(System.Nullable<bool> value);
    partial void OnStatusChanged();
    #endregion
		
		public FencePointsOrigin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoKey", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AutoKey
		{
			get
			{
				return this._AutoKey;
			}
			set
			{
				if ((this._AutoKey != value))
				{
					this.OnAutoKeyChanging(value);
					this.SendPropertyChanging();
					this._AutoKey = value;
					this.SendPropertyChanged("AutoKey");
					this.OnAutoKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitude", DbType="Decimal(11,8)")]
		public System.Nullable<decimal> Latitude
		{
			get
			{
				return this._Latitude;
			}
			set
			{
				if ((this._Latitude != value))
				{
					this.OnLatitudeChanging(value);
					this.SendPropertyChanging();
					this._Latitude = value;
					this.SendPropertyChanged("Latitude");
					this.OnLatitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitude", DbType="Decimal(11,8)")]
		public System.Nullable<decimal> Longitude
		{
			get
			{
				return this._Longitude;
			}
			set
			{
				if ((this._Longitude != value))
				{
					this.OnLongitudeChanging(value);
					this.SendPropertyChanging();
					this._Longitude = value;
					this.SendPropertyChanged("Longitude");
					this.OnLongitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Distance", DbType="Float")]
		public System.Nullable<double> Distance
		{
			get
			{
				return this._Distance;
			}
			set
			{
				if ((this._Distance != value))
				{
					this.OnDistanceChanging(value);
					this.SendPropertyChanging();
					this._Distance = value;
					this.SendPropertyChanged("Distance");
					this.OnDistanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(50)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(50)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this.OnNoteChanging(value);
					this.SendPropertyChanging();
					this._Note = value;
					this.SendPropertyChanged("Note");
					this.OnNoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyMan", DbType="NVarChar(50)")]
		public string KeyMan
		{
			get
			{
				return this._KeyMan;
			}
			set
			{
				if ((this._KeyMan != value))
				{
					this.OnKeyManChanging(value);
					this.SendPropertyChanging();
					this._KeyMan = value;
					this.SendPropertyChanged("KeyMan");
					this.OnKeyManChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> KeyDate
		{
			get
			{
				return this._KeyDate;
			}
			set
			{
				if ((this._KeyDate != value))
				{
					this.OnKeyDateChanging(value);
					this.SendPropertyChanging();
					this._KeyDate = value;
					this.SendPropertyChanged("KeyDate");
					this.OnKeyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit")]
		public System.Nullable<bool> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SSID_Identifier")]
	public partial class SSID_Identifier : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AutoKey;
		
		private string _SSID;
		
		private string _BSSID;
		
		private string _KeyMan;
		
		private System.Nullable<System.DateTime> _KeyDate;
		
		private System.Nullable<bool> _Status;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAutoKeyChanging(int value);
    partial void OnAutoKeyChanged();
    partial void OnSSIDChanging(string value);
    partial void OnSSIDChanged();
    partial void OnBSSIDChanging(string value);
    partial void OnBSSIDChanged();
    partial void OnKeyManChanging(string value);
    partial void OnKeyManChanged();
    partial void OnKeyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnKeyDateChanged();
    partial void OnStatusChanging(System.Nullable<bool> value);
    partial void OnStatusChanged();
    #endregion
		
		public SSID_Identifier()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoKey", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AutoKey
		{
			get
			{
				return this._AutoKey;
			}
			set
			{
				if ((this._AutoKey != value))
				{
					this.OnAutoKeyChanging(value);
					this.SendPropertyChanging();
					this._AutoKey = value;
					this.SendPropertyChanged("AutoKey");
					this.OnAutoKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SSID", DbType="NVarChar(50)")]
		public string SSID
		{
			get
			{
				return this._SSID;
			}
			set
			{
				if ((this._SSID != value))
				{
					this.OnSSIDChanging(value);
					this.SendPropertyChanging();
					this._SSID = value;
					this.SendPropertyChanged("SSID");
					this.OnSSIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BSSID", DbType="NVarChar(50)")]
		public string BSSID
		{
			get
			{
				return this._BSSID;
			}
			set
			{
				if ((this._BSSID != value))
				{
					this.OnBSSIDChanging(value);
					this.SendPropertyChanging();
					this._BSSID = value;
					this.SendPropertyChanged("BSSID");
					this.OnBSSIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyMan", DbType="NVarChar(50)")]
		public string KeyMan
		{
			get
			{
				return this._KeyMan;
			}
			set
			{
				if ((this._KeyMan != value))
				{
					this.OnKeyManChanging(value);
					this.SendPropertyChanging();
					this._KeyMan = value;
					this.SendPropertyChanged("KeyMan");
					this.OnKeyManChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> KeyDate
		{
			get
			{
				return this._KeyDate;
			}
			set
			{
				if ((this._KeyDate != value))
				{
					this.OnKeyDateChanging(value);
					this.SendPropertyChanging();
					this._KeyDate = value;
					this.SendPropertyChanged("KeyDate");
					this.OnKeyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit")]
		public System.Nullable<bool> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PunchCardType")]
	public partial class PunchCardType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AutoKey;
		
		private string _CardType;
		
		private string _CardName;
		
		private System.Nullable<int> _ItemOrder;
		
		private string _Note;
		
		private string _KeyMan;
		
		private System.Nullable<System.DateTime> _KeyDate;
		
		private System.Nullable<bool> _Status;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAutoKeyChanging(int value);
    partial void OnAutoKeyChanged();
    partial void OnCardTypeChanging(string value);
    partial void OnCardTypeChanged();
    partial void OnCardNameChanging(string value);
    partial void OnCardNameChanged();
    partial void OnItemOrderChanging(System.Nullable<int> value);
    partial void OnItemOrderChanged();
    partial void OnNoteChanging(string value);
    partial void OnNoteChanged();
    partial void OnKeyManChanging(string value);
    partial void OnKeyManChanged();
    partial void OnKeyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnKeyDateChanged();
    partial void OnStatusChanging(System.Nullable<bool> value);
    partial void OnStatusChanged();
    #endregion
		
		public PunchCardType()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoKey", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AutoKey
		{
			get
			{
				return this._AutoKey;
			}
			set
			{
				if ((this._AutoKey != value))
				{
					this.OnAutoKeyChanging(value);
					this.SendPropertyChanging();
					this._AutoKey = value;
					this.SendPropertyChanged("AutoKey");
					this.OnAutoKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardType", DbType="NVarChar(MAX)")]
		public string CardType
		{
			get
			{
				return this._CardType;
			}
			set
			{
				if ((this._CardType != value))
				{
					this.OnCardTypeChanging(value);
					this.SendPropertyChanging();
					this._CardType = value;
					this.SendPropertyChanged("CardType");
					this.OnCardTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardName", DbType="NVarChar(MAX)")]
		public string CardName
		{
			get
			{
				return this._CardName;
			}
			set
			{
				if ((this._CardName != value))
				{
					this.OnCardNameChanging(value);
					this.SendPropertyChanging();
					this._CardName = value;
					this.SendPropertyChanged("CardName");
					this.OnCardNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemOrder", DbType="Int")]
		public System.Nullable<int> ItemOrder
		{
			get
			{
				return this._ItemOrder;
			}
			set
			{
				if ((this._ItemOrder != value))
				{
					this.OnItemOrderChanging(value);
					this.SendPropertyChanging();
					this._ItemOrder = value;
					this.SendPropertyChanged("ItemOrder");
					this.OnItemOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(MAX)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this.OnNoteChanging(value);
					this.SendPropertyChanging();
					this._Note = value;
					this.SendPropertyChanged("Note");
					this.OnNoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyMan", DbType="NChar(10)")]
		public string KeyMan
		{
			get
			{
				return this._KeyMan;
			}
			set
			{
				if ((this._KeyMan != value))
				{
					this.OnKeyManChanging(value);
					this.SendPropertyChanging();
					this._KeyMan = value;
					this.SendPropertyChanged("KeyMan");
					this.OnKeyManChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> KeyDate
		{
			get
			{
				return this._KeyDate;
			}
			set
			{
				if ((this._KeyDate != value))
				{
					this.OnKeyDateChanging(value);
					this.SendPropertyChanging();
					this._KeyDate = value;
					this.SendPropertyChanged("KeyDate");
					this.OnKeyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit")]
		public System.Nullable<bool> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QRCode_Verification")]
	public partial class QRCode_Verification : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AutoKey;
		
		private string _GUID;
		
		private string _QRCode;
		
		private string _KeyMan;
		
		private System.Nullable<System.DateTime> _KeyDate;
		
		private System.Nullable<bool> _Status;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAutoKeyChanging(int value);
    partial void OnAutoKeyChanged();
    partial void OnGUIDChanging(string value);
    partial void OnGUIDChanged();
    partial void OnQRCodeChanging(string value);
    partial void OnQRCodeChanged();
    partial void OnKeyManChanging(string value);
    partial void OnKeyManChanged();
    partial void OnKeyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnKeyDateChanged();
    partial void OnStatusChanging(System.Nullable<bool> value);
    partial void OnStatusChanged();
    #endregion
		
		public QRCode_Verification()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoKey", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AutoKey
		{
			get
			{
				return this._AutoKey;
			}
			set
			{
				if ((this._AutoKey != value))
				{
					this.OnAutoKeyChanging(value);
					this.SendPropertyChanging();
					this._AutoKey = value;
					this.SendPropertyChanged("AutoKey");
					this.OnAutoKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID", DbType="NVarChar(50)")]
		public string GUID
		{
			get
			{
				return this._GUID;
			}
			set
			{
				if ((this._GUID != value))
				{
					this.OnGUIDChanging(value);
					this.SendPropertyChanging();
					this._GUID = value;
					this.SendPropertyChanged("GUID");
					this.OnGUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QRCode", DbType="NVarChar(50)")]
		public string QRCode
		{
			get
			{
				return this._QRCode;
			}
			set
			{
				if ((this._QRCode != value))
				{
					this.OnQRCodeChanging(value);
					this.SendPropertyChanging();
					this._QRCode = value;
					this.SendPropertyChanged("QRCode");
					this.OnQRCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyMan", DbType="NVarChar(50)")]
		public string KeyMan
		{
			get
			{
				return this._KeyMan;
			}
			set
			{
				if ((this._KeyMan != value))
				{
					this.OnKeyManChanging(value);
					this.SendPropertyChanging();
					this._KeyMan = value;
					this.SendPropertyChanged("KeyMan");
					this.OnKeyManChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> KeyDate
		{
			get
			{
				return this._KeyDate;
			}
			set
			{
				if ((this._KeyDate != value))
				{
					this.OnKeyDateChanging(value);
					this.SendPropertyChanging();
					this._KeyDate = value;
					this.SendPropertyChanged("KeyDate");
					this.OnKeyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit")]
		public System.Nullable<bool> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CardAppDetails")]
	public partial class CardAppDetails : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AutoKey;
		
		private string _Nobr;
		
		private string _SSID;
		
		private string _BSSID;
		
		private string _MAC;
		
		private string _IP_Address;
		
		private string _APP_RegistryKey;
		
		private string _CardTypeCode;
		
		private string _Address;
		
		private System.Nullable<decimal> _Latitude;
		
		private System.Nullable<decimal> _Longitude;
		
		private System.Nullable<System.DateTime> _CardStart;
		
		private System.Nullable<System.DateTime> _CardProcess;
		
		private System.Nullable<System.DateTime> _CardSend;
		
		private string _Reason;
		
		private string _Remarks;
		
		private System.Nullable<System.DateTime> _KeyDate;
		
		private string _QRCode;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAutoKeyChanging(int value);
    partial void OnAutoKeyChanged();
    partial void OnNobrChanging(string value);
    partial void OnNobrChanged();
    partial void OnSSIDChanging(string value);
    partial void OnSSIDChanged();
    partial void OnBSSIDChanging(string value);
    partial void OnBSSIDChanged();
    partial void OnMACChanging(string value);
    partial void OnMACChanged();
    partial void OnIP_AddressChanging(string value);
    partial void OnIP_AddressChanged();
    partial void OnAPP_RegistryKeyChanging(string value);
    partial void OnAPP_RegistryKeyChanged();
    partial void OnCardTypeCodeChanging(string value);
    partial void OnCardTypeCodeChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnLatitudeChanging(System.Nullable<decimal> value);
    partial void OnLatitudeChanged();
    partial void OnLongitudeChanging(System.Nullable<decimal> value);
    partial void OnLongitudeChanged();
    partial void OnCardStartChanging(System.Nullable<System.DateTime> value);
    partial void OnCardStartChanged();
    partial void OnCardProcessChanging(System.Nullable<System.DateTime> value);
    partial void OnCardProcessChanged();
    partial void OnCardSendChanging(System.Nullable<System.DateTime> value);
    partial void OnCardSendChanged();
    partial void OnReasonChanging(string value);
    partial void OnReasonChanged();
    partial void OnRemarksChanging(string value);
    partial void OnRemarksChanged();
    partial void OnKeyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnKeyDateChanged();
    partial void OnQRCodeChanging(string value);
    partial void OnQRCodeChanged();
    #endregion
		
		public CardAppDetails()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoKey", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AutoKey
		{
			get
			{
				return this._AutoKey;
			}
			set
			{
				if ((this._AutoKey != value))
				{
					this.OnAutoKeyChanging(value);
					this.SendPropertyChanging();
					this._AutoKey = value;
					this.SendPropertyChanged("AutoKey");
					this.OnAutoKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nobr", DbType="NVarChar(50)")]
		public string Nobr
		{
			get
			{
				return this._Nobr;
			}
			set
			{
				if ((this._Nobr != value))
				{
					this.OnNobrChanging(value);
					this.SendPropertyChanging();
					this._Nobr = value;
					this.SendPropertyChanged("Nobr");
					this.OnNobrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SSID", DbType="NVarChar(50)")]
		public string SSID
		{
			get
			{
				return this._SSID;
			}
			set
			{
				if ((this._SSID != value))
				{
					this.OnSSIDChanging(value);
					this.SendPropertyChanging();
					this._SSID = value;
					this.SendPropertyChanged("SSID");
					this.OnSSIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BSSID", DbType="NVarChar(50)")]
		public string BSSID
		{
			get
			{
				return this._BSSID;
			}
			set
			{
				if ((this._BSSID != value))
				{
					this.OnBSSIDChanging(value);
					this.SendPropertyChanging();
					this._BSSID = value;
					this.SendPropertyChanged("BSSID");
					this.OnBSSIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAC", DbType="NVarChar(50)")]
		public string MAC
		{
			get
			{
				return this._MAC;
			}
			set
			{
				if ((this._MAC != value))
				{
					this.OnMACChanging(value);
					this.SendPropertyChanging();
					this._MAC = value;
					this.SendPropertyChanged("MAC");
					this.OnMACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IP_Address", DbType="NVarChar(50)")]
		public string IP_Address
		{
			get
			{
				return this._IP_Address;
			}
			set
			{
				if ((this._IP_Address != value))
				{
					this.OnIP_AddressChanging(value);
					this.SendPropertyChanging();
					this._IP_Address = value;
					this.SendPropertyChanged("IP_Address");
					this.OnIP_AddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APP_RegistryKey", DbType="NVarChar(50)")]
		public string APP_RegistryKey
		{
			get
			{
				return this._APP_RegistryKey;
			}
			set
			{
				if ((this._APP_RegistryKey != value))
				{
					this.OnAPP_RegistryKeyChanging(value);
					this.SendPropertyChanging();
					this._APP_RegistryKey = value;
					this.SendPropertyChanged("APP_RegistryKey");
					this.OnAPP_RegistryKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardTypeCode", DbType="NVarChar(50)")]
		public string CardTypeCode
		{
			get
			{
				return this._CardTypeCode;
			}
			set
			{
				if ((this._CardTypeCode != value))
				{
					this.OnCardTypeCodeChanging(value);
					this.SendPropertyChanging();
					this._CardTypeCode = value;
					this.SendPropertyChanged("CardTypeCode");
					this.OnCardTypeCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(MAX)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitude", DbType="Decimal(11,8)")]
		public System.Nullable<decimal> Latitude
		{
			get
			{
				return this._Latitude;
			}
			set
			{
				if ((this._Latitude != value))
				{
					this.OnLatitudeChanging(value);
					this.SendPropertyChanging();
					this._Latitude = value;
					this.SendPropertyChanged("Latitude");
					this.OnLatitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitude", DbType="Decimal(11,8)")]
		public System.Nullable<decimal> Longitude
		{
			get
			{
				return this._Longitude;
			}
			set
			{
				if ((this._Longitude != value))
				{
					this.OnLongitudeChanging(value);
					this.SendPropertyChanging();
					this._Longitude = value;
					this.SendPropertyChanged("Longitude");
					this.OnLongitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardStart", DbType="DateTime")]
		public System.Nullable<System.DateTime> CardStart
		{
			get
			{
				return this._CardStart;
			}
			set
			{
				if ((this._CardStart != value))
				{
					this.OnCardStartChanging(value);
					this.SendPropertyChanging();
					this._CardStart = value;
					this.SendPropertyChanged("CardStart");
					this.OnCardStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardProcess", DbType="DateTime")]
		public System.Nullable<System.DateTime> CardProcess
		{
			get
			{
				return this._CardProcess;
			}
			set
			{
				if ((this._CardProcess != value))
				{
					this.OnCardProcessChanging(value);
					this.SendPropertyChanging();
					this._CardProcess = value;
					this.SendPropertyChanged("CardProcess");
					this.OnCardProcessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardSend", DbType="DateTime")]
		public System.Nullable<System.DateTime> CardSend
		{
			get
			{
				return this._CardSend;
			}
			set
			{
				if ((this._CardSend != value))
				{
					this.OnCardSendChanging(value);
					this.SendPropertyChanging();
					this._CardSend = value;
					this.SendPropertyChanged("CardSend");
					this.OnCardSendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reason", DbType="NVarChar(MAX)")]
		public string Reason
		{
			get
			{
				return this._Reason;
			}
			set
			{
				if ((this._Reason != value))
				{
					this.OnReasonChanging(value);
					this.SendPropertyChanging();
					this._Reason = value;
					this.SendPropertyChanged("Reason");
					this.OnReasonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="NVarChar(MAX)")]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this.OnRemarksChanging(value);
					this.SendPropertyChanging();
					this._Remarks = value;
					this.SendPropertyChanged("Remarks");
					this.OnRemarksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> KeyDate
		{
			get
			{
				return this._KeyDate;
			}
			set
			{
				if ((this._KeyDate != value))
				{
					this.OnKeyDateChanging(value);
					this.SendPropertyChanging();
					this._KeyDate = value;
					this.SendPropertyChanged("KeyDate");
					this.OnKeyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QRCode", DbType="NVarChar(MAX)")]
		public string QRCode
		{
			get
			{
				return this._QRCode;
			}
			set
			{
				if ((this._QRCode != value))
				{
					this.OnQRCodeChanging(value);
					this.SendPropertyChanging();
					this._QRCode = value;
					this.SendPropertyChanged("QRCode");
					this.OnQRCodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CardAppImages")]
	public partial class CardAppImages : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AutoKey;
		
		private System.Nullable<int> _CardAppDetailsID;
		
		private string _Nobr;
		
		private System.Nullable<System.DateTime> _UploadDate;
		
		private string _Path;
		
		private System.Nullable<System.DateTime> _KeyDate;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAutoKeyChanging(int value);
    partial void OnAutoKeyChanged();
    partial void OnCardAppDetailsIDChanging(System.Nullable<int> value);
    partial void OnCardAppDetailsIDChanged();
    partial void OnNobrChanging(string value);
    partial void OnNobrChanged();
    partial void OnUploadDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUploadDateChanged();
    partial void OnPathChanging(string value);
    partial void OnPathChanged();
    partial void OnKeyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnKeyDateChanged();
    #endregion
		
		public CardAppImages()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoKey", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AutoKey
		{
			get
			{
				return this._AutoKey;
			}
			set
			{
				if ((this._AutoKey != value))
				{
					this.OnAutoKeyChanging(value);
					this.SendPropertyChanging();
					this._AutoKey = value;
					this.SendPropertyChanged("AutoKey");
					this.OnAutoKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardAppDetailsID", DbType="Int")]
		public System.Nullable<int> CardAppDetailsID
		{
			get
			{
				return this._CardAppDetailsID;
			}
			set
			{
				if ((this._CardAppDetailsID != value))
				{
					this.OnCardAppDetailsIDChanging(value);
					this.SendPropertyChanging();
					this._CardAppDetailsID = value;
					this.SendPropertyChanged("CardAppDetailsID");
					this.OnCardAppDetailsIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nobr", DbType="NVarChar(50)")]
		public string Nobr
		{
			get
			{
				return this._Nobr;
			}
			set
			{
				if ((this._Nobr != value))
				{
					this.OnNobrChanging(value);
					this.SendPropertyChanging();
					this._Nobr = value;
					this.SendPropertyChanged("Nobr");
					this.OnNobrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UploadDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UploadDate
		{
			get
			{
				return this._UploadDate;
			}
			set
			{
				if ((this._UploadDate != value))
				{
					this.OnUploadDateChanging(value);
					this.SendPropertyChanging();
					this._UploadDate = value;
					this.SendPropertyChanged("UploadDate");
					this.OnUploadDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Path", DbType="NVarChar(MAX)")]
		public string Path
		{
			get
			{
				return this._Path;
			}
			set
			{
				if ((this._Path != value))
				{
					this.OnPathChanging(value);
					this.SendPropertyChanging();
					this._Path = value;
					this.SendPropertyChanged("Path");
					this.OnPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> KeyDate
		{
			get
			{
				return this._KeyDate;
			}
			set
			{
				if ((this._KeyDate != value))
				{
					this.OnKeyDateChanging(value);
					this.SendPropertyChanging();
					this._KeyDate = value;
					this.SendPropertyChanged("KeyDate");
					this.OnKeyDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
