<?xml version="1.0" encoding="utf-8"?><Database Name="HRM_API" Class="dcAppDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.1.12;Initial Catalog=PROD;User ID=jb" SettingsObjectName="Dal.Properties.Settings" SettingsPropertyName="AppConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AppRegistryKey_Bind" Member="AppRegistryKey_Bind">
    <Type Name="AppRegistryKey_Bind">
      <Column Name="AutoKey" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Nobr" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="APP_RegistryKey" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KeyMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KeyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AppSetting_Configuration" Member="AppSetting_Configuration">
    <Type Name="AppSetting_Configuration">
      <Column Name="AutoKey" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SettingValue" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SettingItem" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KeyMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KeyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[Group]" Member="Group" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FencePoints" Member="FencePoints">
    <Type Name="FencePoints">
      <Column Name="AutoKey" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="oLatitude" Type="System.Decimal" DbType="Decimal(11,8)" CanBeNull="true" />
      <Column Name="oLongitude" Type="System.Decimal" DbType="Decimal(11,8)" CanBeNull="true" />
      <Column Name="Latitude" Type="System.Decimal" DbType="Decimal(11,8)" CanBeNull="true" />
      <Column Name="Longitude" Type="System.Decimal" DbType="Decimal(11,8)" CanBeNull="true" />
      <Column Name="Distance" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PointsGroup" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KeyMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KeyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="isEffctive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FencePointsOrigin" Member="FencePointsOrigin">
    <Type Name="FencePointsOrigin">
      <Column Name="AutoKey" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Latitude" Type="System.Decimal" DbType="Decimal(11,8)" CanBeNull="true" />
      <Column Name="Longitude" Type="System.Decimal" DbType="Decimal(11,8)" CanBeNull="true" />
      <Column Name="Distance" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KeyMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KeyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SSID_Identifier" Member="SSID_Identifier">
    <Type Name="SSID_Identifier">
      <Column Name="AutoKey" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SSID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BSSID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KeyMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KeyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PunchCardType" Member="PunchCardType">
    <Type Name="PunchCardType">
      <Column Name="AutoKey" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CardType" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CardName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ItemOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="KeyMan" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="KeyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.QRCode_Verification" Member="QRCode_Verification">
    <Type Name="QRCode_Verification">
      <Column Name="AutoKey" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GUID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QRCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KeyMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KeyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CardAppDetails" Member="CardAppDetails">
    <Type Name="CardAppDetails">
      <Column Name="AutoKey" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nobr" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SSID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BSSID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MAC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IP_Address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="APP_RegistryKey" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CardTypeCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Latitude" Type="System.Decimal" DbType="Decimal(11,8)" CanBeNull="true" />
      <Column Name="Longitude" Type="System.Decimal" DbType="Decimal(11,8)" CanBeNull="true" />
      <Column Name="CardStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CardProcess" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CardSend" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Reason" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Remarks" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="KeyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="QRCode" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CardAppImages" Member="CardAppImages">
    <Type Name="CardAppImages">
      <Column Name="AutoKey" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CardAppDetailsID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Nobr" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UploadDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Path" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="KeyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>