#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HUNYAHR")]
	public partial class dcHrDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 擴充性方法定義
    partial void OnCreated();
    #endregion
		
		public dcHrDataContext() : 
				base(global::Dal.Properties.Settings.Default.HRConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dcHrDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcHrDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcHrDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcHrDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ViewJobl> ViewJobl
		{
			get
			{
				return this.GetTable<ViewJobl>();
			}
		}
		
		public System.Data.Linq.Table<ViewDept> ViewDept
		{
			get
			{
				return this.GetTable<ViewDept>();
			}
		}
		
		public System.Data.Linq.Table<ViewDeptTree> ViewDeptTree
		{
			get
			{
				return this.GetTable<ViewDeptTree>();
			}
		}
		
		public System.Data.Linq.Table<ViewJob> ViewJob
		{
			get
			{
				return this.GetTable<ViewJob>();
			}
		}
		
		public System.Data.Linq.Table<ViewDepta> ViewDepta
		{
			get
			{
				return this.GetTable<ViewDepta>();
			}
		}
		
		public System.Data.Linq.Table<ViewEmp> ViewEmp
		{
			get
			{
				return this.GetTable<ViewEmp>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.WriteRuleTable1ByNobr", IsComposable=true)]
		public IQueryable<WriteRuleTable1ByNobrResult> WriteRuleTable1ByNobr([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nobr", DbType="NVarChar(50)")] string nobr, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string comp, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> admin, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CheckDate", DbType="NVarChar(50)")] string checkDate)
		{
			return this.CreateMethodCallQuery<WriteRuleTable1ByNobrResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nobr, comp, admin, checkDate);
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ViewJobl")]
	public partial class ViewJobl
	{
		
		private string _Code;
		
		private string _DisplayCode;
		
		private string _Name;
		
		private string _EmpCategoryCode;
		
		public ViewJobl()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayCode", DbType="NVarChar(50)")]
		public string DisplayCode
		{
			get
			{
				return this._DisplayCode;
			}
			set
			{
				if ((this._DisplayCode != value))
				{
					this._DisplayCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpCategoryCode", DbType="NVarChar(50)")]
		public string EmpCategoryCode
		{
			get
			{
				return this._EmpCategoryCode;
			}
			set
			{
				if ((this._EmpCategoryCode != value))
				{
					this._EmpCategoryCode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ViewDept")]
	public partial class ViewDept
	{
		
		private string _Code;
		
		private string _DisplayCode;
		
		private string _Name;
		
		private System.Nullable<int> _DeptTree;
		
		private string _ParentCode;
		
		private string _ManagerEmpId;
		
		public ViewDept()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayCode", DbType="NVarChar(50)")]
		public string DisplayCode
		{
			get
			{
				return this._DisplayCode;
			}
			set
			{
				if ((this._DisplayCode != value))
				{
					this._DisplayCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeptTree", DbType="Int")]
		public System.Nullable<int> DeptTree
		{
			get
			{
				return this._DeptTree;
			}
			set
			{
				if ((this._DeptTree != value))
				{
					this._DeptTree = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentCode", DbType="NVarChar(50)")]
		public string ParentCode
		{
			get
			{
				return this._ParentCode;
			}
			set
			{
				if ((this._ParentCode != value))
				{
					this._ParentCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManagerEmpId", DbType="NVarChar(50)")]
		public string ManagerEmpId
		{
			get
			{
				return this._ManagerEmpId;
			}
			set
			{
				if ((this._ManagerEmpId != value))
				{
					this._ManagerEmpId = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ViewDeptTree")]
	public partial class ViewDeptTree
	{
		
		private string _Code;
		
		private string _Name;
		
		public ViewDeptTree()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ViewJob")]
	public partial class ViewJob
	{
		
		private string _Code;
		
		private string _DisplayCode;
		
		private string _Name;
		
		public ViewJob()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayCode", DbType="NVarChar(50)")]
		public string DisplayCode
		{
			get
			{
				return this._DisplayCode;
			}
			set
			{
				if ((this._DisplayCode != value))
				{
					this._DisplayCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ViewDepta")]
	public partial class ViewDepta
	{
		
		private string _Code;
		
		private string _DisplayCode;
		
		private string _Name;
		
		private System.Nullable<int> _DeptTree;
		
		private string _ParentCode;
		
		private string _ManagerEmpId;
		
		public ViewDepta()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayCode", DbType="NVarChar(50)")]
		public string DisplayCode
		{
			get
			{
				return this._DisplayCode;
			}
			set
			{
				if ((this._DisplayCode != value))
				{
					this._DisplayCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeptTree", DbType="Int")]
		public System.Nullable<int> DeptTree
		{
			get
			{
				return this._DeptTree;
			}
			set
			{
				if ((this._DeptTree != value))
				{
					this._DeptTree = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentCode", DbType="NVarChar(50)")]
		public string ParentCode
		{
			get
			{
				return this._ParentCode;
			}
			set
			{
				if ((this._ParentCode != value))
				{
					this._ParentCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManagerEmpId", DbType="NVarChar(50)")]
		public string ManagerEmpId
		{
			get
			{
				return this._ManagerEmpId;
			}
			set
			{
				if ((this._ManagerEmpId != value))
				{
					this._ManagerEmpId = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ViewEmp")]
	public partial class ViewEmp
	{
		
		private string _Code;
		
		private string _Name;
		
		private string _DeptCode;
		
		private string _DeptmCode;
		
		private string _JobCode;
		
		private string _JoblCode;
		
		private string _Password;
		
		private System.DateTime _DateA;
		
		private System.Nullable<System.DateTime> _DateD;
		
		private string _Email;
		
		private string _Ttscode;
		
		private string _CompCode;
		
		private System.Nullable<System.DateTime> _DateIn;
		
		private string _DI;
		
		public ViewEmp()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeptCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DeptCode
		{
			get
			{
				return this._DeptCode;
			}
			set
			{
				if ((this._DeptCode != value))
				{
					this._DeptCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeptmCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DeptmCode
		{
			get
			{
				return this._DeptmCode;
			}
			set
			{
				if ((this._DeptmCode != value))
				{
					this._DeptmCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string JobCode
		{
			get
			{
				return this._JobCode;
			}
			set
			{
				if ((this._JobCode != value))
				{
					this._JobCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JoblCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string JoblCode
		{
			get
			{
				return this._JoblCode;
			}
			set
			{
				if ((this._JoblCode != value))
				{
					this._JoblCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateA", DbType="DateTime NOT NULL")]
		public System.DateTime DateA
		{
			get
			{
				return this._DateA;
			}
			set
			{
				if ((this._DateA != value))
				{
					this._DateA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateD", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateD
		{
			get
			{
				return this._DateD;
			}
			set
			{
				if ((this._DateD != value))
				{
					this._DateD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(60)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ttscode", DbType="NVarChar(50)")]
		public string Ttscode
		{
			get
			{
				return this._Ttscode;
			}
			set
			{
				if ((this._Ttscode != value))
				{
					this._Ttscode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CompCode
		{
			get
			{
				return this._CompCode;
			}
			set
			{
				if ((this._CompCode != value))
				{
					this._CompCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateIn", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateIn
		{
			get
			{
				return this._DateIn;
			}
			set
			{
				if ((this._DateIn != value))
				{
					this._DateIn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DI", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DI
		{
			get
			{
				return this._DI;
			}
			set
			{
				if ((this._DI != value))
				{
					this._DI = value;
				}
			}
		}
	}
	
	public partial class WriteRuleTable1ByNobrResult
	{
		
		private string _NOBR;
		
		private string _DATAGROUP;
		
		public WriteRuleTable1ByNobrResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOBR", DbType="NVarChar(50)")]
		public string NOBR
		{
			get
			{
				return this._NOBR;
			}
			set
			{
				if ((this._NOBR != value))
				{
					this._NOBR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATAGROUP", DbType="NVarChar(50)")]
		public string DATAGROUP
		{
			get
			{
				return this._DATAGROUP;
			}
			set
			{
				if ((this._DATAGROUP != value))
				{
					this._DATAGROUP = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
