<?xml version="1.0" encoding="utf-8"?><Database Name="HUNYAHR" Class="dcHrDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=211.78.84.42;Initial Catalog=EIPHRSYS;Persist Security Info=True;User ID=JBDBsql" SettingsObjectName="Dal.Properties.Settings" SettingsPropertyName="HRConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ViewJobl" Member="ViewJobl">
    <Type Name="ViewJobl">
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DisplayCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmpCategoryCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ViewDept" Member="ViewDept">
    <Type Name="ViewDept">
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DisplayCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DeptTree" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ManagerEmpId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ViewDeptTree" Member="ViewDeptTree">
    <Type Name="ViewDeptTree">
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ViewJob" Member="ViewJob">
    <Type Name="ViewJob">
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DisplayCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ViewDepta" Member="ViewDepta">
    <Type Name="ViewDepta">
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DisplayCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DeptTree" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ManagerEmpId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ViewEmp" Member="ViewEmp">
    <Type Name="ViewEmp">
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DeptCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DeptmCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="JobCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="JoblCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DateA" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="Ttscode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CompCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DateIn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DI" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.WriteRuleTable1ByNobr" Method="WriteRuleTable1ByNobr" IsComposable="true">
    <Parameter Name="Nobr" Parameter="nobr" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="comp" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="admin" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="CheckDate" Parameter="checkDate" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="WriteRuleTable1ByNobrResult">
      <Column Name="NOBR" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DATAGROUP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>