<?xml version="1.0" encoding="utf-8"?><Database Name="EMC_Performance" Class="dcPerformanceDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.1.12;Initial Catalog=Performance;Persist Security Info=True;User ID=jb" SettingsObjectName="Dal.Properties.Settings" SettingsPropertyName="PerformanceConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PerformanceBase" Member="PerformanceBase">
    <Type Name="PerformanceBase">
      <Column Name="AutoKey" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PerformanceMainCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmpId" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmpName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PerformanceDeptCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DeptCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DeptName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="JobCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="JobName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="JoblCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="JoblName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="WorkCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="WorkName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CompCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmpCategoryCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="WorkPerformance" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="MannerEsteem" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="AbilityEsteem" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="Encourage" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="TotalIntegrate" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="RatingCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BonusCardinal" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="InWorkSpecific" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="BonusTotal" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="BonusDeduct" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="BonusMax" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="BonusAdjust" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="BonusReal" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="DateIn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="G01" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="G02" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="G03" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="G04" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="G05" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="F01" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="F02" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="F03" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="F04" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="F05" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SumAward" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="AvgIntegrate" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="ExceptionBonusAll" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ExceptionBonus" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ExceptionNote" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="InsertMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InsertDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PerformanceScoreLimits" Member="PerformanceScoreLimits">
    <Type Name="PerformanceScoreLimits">
      <Column Name="AutoKey" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="JobCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ReportContentCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ScoreLimits" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="Sort" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="InsertMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InsertDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PerformanceBaseLog" Member="PerformanceBaseLog">
    <Type Name="PerformanceBaseLog">
      <Column Name="AutoKey" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PerformanceFlowNodeCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PerformanceMainCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmpId" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmpName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PerformanceDeptCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DeptCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DeptName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="JobCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="JobName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="JoblCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="JoblName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="WorkCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="WorkName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CompCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmpCategoryCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="WorkPerformance" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="MannerEsteem" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="AbilityEsteem" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="Encourage" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="TotalIntegrate" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="RatingCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BonusCardinal" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="InWorkSpecific" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="BonusTotal" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="BonusDeduct" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="BonusMax" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="BonusAdjust" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="BonusReal" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="DateIn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="G01" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="G02" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="G03" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="G04" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="G05" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="F01" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="F02" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="F03" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="F04" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="F05" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SumAward" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="AvgIntegrate" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="ExceptionBonusAll" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ExceptionBonus" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ExceptionNote" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="InsertMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InsertDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PerformanceDept" Member="PerformanceDept">
    <Type Name="PerformanceDept">
      <Column Name="AutoKey" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PerformanceMainCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="DisplayCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DeptTree" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeptTreeB" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeptTreeE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParentCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ManagerId" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ManagerName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ParentManagerId" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="JobCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="JobName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="JoblCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="JoblName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Mail" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="BonusMax" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="BonusUse" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="BonusBalance" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="PathCode" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PathName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="InsertMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InsertDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PerformanceDeptPer" Member="PerformanceDeptPer">
    <Type Name="PerformanceDeptPer">
      <Column Name="AutoKey" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Month" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BonusPer" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="InsertMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InsertDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PerformanceDeptRating" Member="PerformanceDeptRating">
    <Type Name="PerformanceDeptRating">
      <Column Name="AutoKey" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PerformanceMainCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PerformanceDeptCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PerformanceRatingCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NumPer" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InsertMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InsertDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PerformanceFlow" Member="PerformanceFlow">
    <Type Name="PerformanceFlow">
      <Column Name="AutoKey" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PerformanceMainCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PerformanceDeptCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsFinish" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsCancel" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsError" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeptTreeB" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeptTreeE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeptTree" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InsertMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InsertDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PerformanceFlowNode" Member="PerformanceFlowNode">
    <Type Name="PerformanceFlowNode">
      <Column Name="AutoKey" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PerformanceFlowCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ParentCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PerformanceDeptCodeDefault" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmpIdDefault" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PerformanceDeptCodeReal" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmpIdReal" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsFinish" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeptTree" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeptSort" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ActiveCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Sort" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InsertMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InsertDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PerformanceFlowSign" Member="PerformanceFlowSign">
    <Type Name="PerformanceFlowSign">
      <Column Name="AutoKey" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PerformanceFlowCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PerformanceFlowNodeCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmpId" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmpName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="JobCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="JobName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ActiveCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Sort" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="InfoLog" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="InsertMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InsertDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PerformanceJob" Member="PerformanceJob">
    <Type Name="PerformanceJob">
      <Column Name="AutoKey" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PerformanceMainCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="DisplayCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InsertMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InsertDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PerformanceMain" Member="PerformanceMain">
    <Type Name="PerformanceMain">
      <Column Name="AutoKey" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="ReportName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Yymm" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Seq" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TypeCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmpCategoryCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DateBase" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateA" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateD" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Sort" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeptTreeB" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeptTreeE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PerformanceRatingCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="InsertMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InsertDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PerformanceRating" Member="PerformanceRating">
    <Type Name="PerformanceRating">
      <Column Name="AutoKey" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmpCategoryCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PerformanceRatingGroupCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BonusPerMax" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BonusPerMin" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NumPerMax" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NumPerMin" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NumPer" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Num" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CheckNote" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Sort" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InsertMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InsertDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PerformanceRatingGroup" Member="PerformanceRatingGroup">
    <Type Name="PerformanceRatingGroup">
      <Column Name="AutoKey" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NumPerMax" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NumPerMin" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NumPer" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Num" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Sort" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InsertMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InsertDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PerformanceReportContent" Member="PerformanceReportContent">
    <Type Name="PerformanceReportContent">
      <Column Name="AutoKey" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PerformanceReportTypeCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ReportContentCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ContentTargetType" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ContentTargetRef" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Sort" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InsertMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InsertDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PerformanceReportContentDept" Member="PerformanceReportContentDept">
    <Type Name="PerformanceReportContentDept">
      <Column Name="AutoKey" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PerformanceReportTypeCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PerformanceMainCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PerformanceDeptCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ReportContentCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ContentTargetType" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ContentTargetRef" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Sort" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InsertMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InsertDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PerformanceReportType" Member="PerformanceReportType">
    <Type Name="PerformanceReportType">
      <Column Name="AutoKey" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmpCategoryCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DateA" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateD" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ContentHead" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ContentFooter" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Sort" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InsertMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InsertDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PerformanceReportTypeDept" Member="PerformanceReportTypeDept">
    <Type Name="PerformanceReportTypeDept">
      <Column Name="AutoKey" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PerformanceReportTypeCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DeptCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DeptName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Sort" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InsertMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InsertDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PerformanceReportTypeJob" Member="PerformanceReportTypeJob">
    <Type Name="PerformanceReportTypeJob">
      <Column Name="AutoKey" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PerformanceReportTypeCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="JobCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="JobName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Sort" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InsertMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InsertDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateMan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>