
/****** Object:  Table [dbo].[QQType]    Script Date: 2013/6/27 上午 10:12:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[QQType](
	[Code] [nvarchar](50) NOT NULL,
	[Name] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_QQType] PRIMARY KEY CLUSTERED 
(
	[Code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

