USE [HOLYHRDB]
GO

/****** Object:  Table [dbo].[RESUME]    Script Date: 07/10/2013 23:53:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RESUME](
	[PNO] [nvarchar](50) NOT NULL,
	[PHOTO] [nvarchar](1000) NULL,
	[UIDENTID] [nvarchar](50) NULL,
	[HECNAME] [nvarchar](50) NULL,
	[PDATE] [datetime] NULL,
	[HEENAME] [nvarchar](50) NULL,
	[SEX] [nvarchar](10) NULL,
	[BIRTHDAY] [datetime] NULL,
	[WEIGHT] [decimal](16, 2) NULL,
	[TALL] [decimal](16, 2) NULL,
	[MARRY] [nvarchar](10) NULL,
	[TEL] [nvarchar](50) NULL,
	[MOBILNO] [nvarchar](50) NULL,
	[BLOOD] [nvarchar](10) NULL,
	[DOMIPLACE] [nvarchar](50) NULL,
	[BESTDIP] [nvarchar](50) NULL,
	[GRSCHOOL] [nvarchar](50) NULL,
	[OTHERJU_1] [nvarchar](50) NULL,
	[GRYM] [nvarchar](10) NULL,
	[DNDEPT] [nvarchar](10) NULL,
	[MAINSTU] [nvarchar](50) NULL,
	[NESTDIP] [nvarchar](50) NULL,
	[NGRSCHOOL] [nvarchar](50) NULL,
	[OTHERJU_2] [nvarchar](50) NULL,
	[NGRYM] [nvarchar](10) NULL,
	[NDNDEPT] [nvarchar](10) NULL,
	[NMAINSTU] [nvarchar](50) NULL,
	[RESUME] [nvarchar](100) NULL,
	[ENTER] [nvarchar](100) NULL,
	[EMAIL] [nvarchar](255) NULL,
	[BROKER] [nvarchar](50) NULL,
	[SET1] [nvarchar](10) NULL,
	[SET2] [nvarchar](10) NULL,
	[SET3] [nvarchar](10) NULL,
	[Q1] [nvarchar](100) NULL,
	[DOMIADDNO] [nvarchar](50) NULL,
	[DOMIADDR] [nvarchar](255) NULL,
	[NOWADDNO] [nvarchar](50) NULL,
	[NOWADDR] [nvarchar](255) NULL,
	[SET4] [nvarchar](1000) NULL,
	[SET5] [nvarchar](100) NULL,
	[SET6] [nvarchar](max) NULL,
	[NOTE] [nvarchar](max) NULL,
	[FILES] [nvarchar](max) NULL,
	[SET7] [nvarchar](10) NULL,
	[SET8] [nvarchar](10) NULL,
	[SET9] [nvarchar](10) NULL,
	[SET10] [nvarchar](10) NULL,
	[JMUSE] [nvarchar](100) NULL,
	[MEEDATE] [datetime] NULL,
	[SALTYPE] [nvarchar](10) NULL,
	[SALARY] [nvarchar](100) NULL,
	[WORKTYPE] [nvarchar](10) NULL,
	[WORKDATE] [datetime] NULL,
	[WORKDAY] [nvarchar](50) NULL,
	[OT1] [nvarchar](200) NULL,
	[MSET1] [nvarchar](10) NULL,
	[MSET2] [nvarchar](10) NULL,
	[MSET3] [nvarchar](10) NULL,
	[MSET4] [nvarchar](10) NULL,
	[MSET5] [nvarchar](10) NULL,
	[MSET6] [nvarchar](10) NULL,
	[MSETL] [nvarchar](10) NULL,
	[OT2] [nvarchar](200) NULL,
	[QSET7] [nvarchar](10) NULL,
	[QSET1] [nvarchar](10) NULL,
	[QSET2] [nvarchar](10) NULL,
	[QSET3] [nvarchar](10) NULL,
	[QSET4] [nvarchar](10) NULL,
	[QSET5] [nvarchar](10) NULL,
	[QSET6] [nvarchar](10) NULL,
	[OT3] [nvarchar](200) NULL,
	[LSET1] [nvarchar](10) NULL,
	[LSET2] [nvarchar](10) NULL,
	[LSET3] [nvarchar](10) NULL,
	[LSET4] [nvarchar](10) NULL,
	[LSET5] [nvarchar](10) NULL,
	[LSET6] [nvarchar](10) NULL,
	[LSET7] [nvarchar](10) NULL,
	[LSET8] [nvarchar](10) NULL,
	[LSET9] [nvarchar](10) NULL,
	[LSET10] [nvarchar](10) NULL,
	[LSET11] [nvarchar](10) NULL,
	[EMYCTNAME] [nvarchar](50) NULL,
	[EMYTELNO] [nvarchar](50) NULL,
	[EMYTELNO_1] [nvarchar](50) NULL,
	[BADYN] [nvarchar](10) NULL,
	[BADRESON] [nvarchar](max) NULL,
	[BADYN1] [nvarchar](10) NULL,
	[BADRESON1] [nvarchar](max) NULL,
	[REMAN_1] [nvarchar](50) NULL,
	[REMAN_2] [nvarchar](50) NULL,
	[REMAN_3] [nvarchar](50) NULL,
	[MUSER] [nvarchar](50) NULL,
	[MDATE] [datetime] NULL,
	[MTIME] [nvarchar](10) NULL,
	[BODY] [nvarchar](200) NULL,
	[INTERESTING] [nvarchar](max) NULL,
	[DOMITEL] [nvarchar](max) NULL,
	[EMYRELATION] [nvarchar](50) NULL,
	[EMYADDR] [nvarchar](255) NULL,
	[GRYN] [nvarchar](100) NULL,
	[GRPLACE] [nvarchar](100) NULL,
	[GRYN2] [nvarchar](100) NULL,
	[GRPLACE2] [nvarchar](100) NULL,
	[SOLYN] [nvarchar](10) NULL,
	[SOLRESON] [nvarchar](50) NULL,
	[SOLTYPE] [nvarchar](50) NULL,
	[SOLLEVEL] [nvarchar](50) NULL,
	[SOLSDATE] [datetime] NULL,
	[SOLDDATE] [datetime] NULL,
	[SOLIDYN] [nvarchar](50) NULL,
	[OVERSEAYN] [nvarchar](100) NULL,
	[WINWORD] [nvarchar](10) NULL,
	[WINEXCEL] [nvarchar](10) NULL,
	[POWERP] [nvarchar](10) NULL,
	[DBASE] [nvarchar](10) NULL,
	[AUTOCAD] [nvarchar](10) NULL,
	[MAC] [nvarchar](10) NULL,
	[LOTUS] [nvarchar](10) NULL,
	[OTHERS] [nvarchar](max) NULL,
	[Q2] [nvarchar](max) NULL,
	[Q3] [nvarchar](max) NULL,
	[Q4] [nvarchar](max) NULL,
	[Q5] [nvarchar](max) NULL,
	[Q6] [nvarchar](max) NULL,
 CONSTRAINT [PK_RESUME] PRIMARY KEY CLUSTERED 
(
	[PNO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

