USE [HOLYSTONEHR]
GO

/****** Object:  Table [dbo].[SiteMapSalaDr]    Script Date: 2013/1/22 下午 11:37:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SiteMapSalaDr](
	[Pid] [int] IDENTITY(1,1) NOT NULL,
	[SALADR_Code] [nvarchar](50) NOT NULL,
	[SiteMapUrl] [nvarchar](1024) NOT NULL,
 CONSTRAINT [PK_SiteMapSalaDr] PRIMARY KEY CLUSTERED 
(
	[Pid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

