<?xml version="1.0" encoding="utf-8"?><Database Name="HOLYSTONEHR" Class="InsDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.1.12;Initial Catalog=PLAZAHR;Persist Security Info=True;User ID=JB" SettingsObjectName="JBHR.Properties.Settings" SettingsPropertyName="JBHRConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BASE" Member="BASE">
    <Type Name="BASE">
      <Column Name="NOBR" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NAME_C" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NAME_E" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NAME_P" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SEX" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BIRDT" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="ADDR1" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="ADDR2" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="TEL1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TEL2" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BBCALL" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EMAIL" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="GSM" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IDNO" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CONT_MAN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CONT_TEL" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CONT_GSM" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CONT_MAN2" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CONT_TEL2" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CONT_GSM2" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BLOOD" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PASSWORD" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="POSTCODE1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="POSTCODE2" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BANK_CODE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BANKNO" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ACCOUNT_NO" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ACCOUNT_NA" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MARRY" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="COUNTRY" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="COUNT_MA" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ARMY" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PRO_MAN1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PRO_ADDR1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PRO_ID1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PRO_TEL1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PRO_MAN2" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PRO_ADDR2" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="PRO_ID2" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PRO_TEL2" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ARMY_TYPE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="N_NOBR" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NOBR_B" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PROVINCE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BORN_ADDR" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TAXCNT" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="KEY_MAN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KEY_DATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ID_TYPE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TAXNO" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PRETAX" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="CONT_REL1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CONT_REL2" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ACCOUNT_MA" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MATNO" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SUBTEL" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PHOTO" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="BASE_INPOLAB" Member="INPOLAB" ThisKey="NOBR" OtherKey="NOBR" Type="INPOLAB" />
      <Association Name="BASE_FAMILY" Member="FAMILY" ThisKey="NOBR" OtherKey="NOBR" Type="FAMILY" />
      <Association Name="BASE_INSLAB" Member="INSLAB" ThisKey="NOBR" OtherKey="NOBR" Type="INSLAB" />
      <Association Name="BASE_BASETTS" Member="BASETTS" ThisKey="NOBR" OtherKey="NOBR" Type="BASETTS" />
      <Association Name="WAGED_BASE" Member="WAGED" ThisKey="NOBR" OtherKey="NOBR" Type="WAGED" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.INPOLAB" Member="INPOLAB">
    <Type Name="INPOLAB">
      <Column Name="NOBR" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FA_IDNO" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="YYMM" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EXP" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="COMP" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="KEY_DATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="KEY_MAN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ADATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DAYS" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="RATE_CODE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="INSUR_TYPE" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="INSCD" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="SALADR" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="BASE_INPOLAB" Member="BASE" ThisKey="NOBR" OtherKey="NOBR" Type="BASE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FAMILY" Member="FAMILY">
    <Type Name="FAMILY">
      <Column Name="FA_IDNO" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FA_NAME" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="REL_CODE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FA_BIRDT" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="true" />
      <Column Name="NOBR" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="KEY_DATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="KEY_MAN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ADDR" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="TEL" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GSM" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BBC" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TAX" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AUTOINSLAB" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LIVE" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EDUCODE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="COMPNY" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TITLE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FAMFORN" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="BASE_FAMILY" Member="BASE" ThisKey="NOBR" OtherKey="NOBR" Type="BASE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.INSURLV" Member="INSURLV">
    <Type Name="INSURLV">
      <Column Name="AMT" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EFF_DATEL" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LFF_DATEL" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EFF_DATEH" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LFF_DATEH" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="KEY_MAN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KEY_DATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EFF_DATER" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LFF_DATER" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.WAGED" Member="WAGED">
    <Type Name="WAGED">
      <Column Name="NOBR" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="YYMM" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SEQ" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SAL_CODE" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AMT" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Association Name="WAGED_BASE" Member="BASE" ThisKey="NOBR" OtherKey="NOBR" Type="BASE" Cardinality="One" />
      <Association Name="WAGED_SALCODE" Member="SALCODE" ThisKey="SAL_CODE" OtherKey="SAL_CODE" Type="SALCODE" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.SALCODE" Member="SALCODE">
    <Type Name="SALCODE">
      <Column Name="SAL_CODE" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SAL_NAME" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SAL_ATTR" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KEY_MAN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KEY_DATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SOS_ID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="WEL" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="OT" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MAX_AMT" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="MIN_AMT" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="CAL_FREQ" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CAL_TYPE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HRS" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="MONTHTYPE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DEFINEDAYS" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="ADVPAY" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ACCCD" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ATT" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DAILY" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RETIRE" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FORBANK" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FORCASH" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NOTFREQ" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TAXRATE" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="YEARPAY" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ABSPAY" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="INSLAB" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LATER" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SAL_ENAME" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Association Name="SALCODE_SALATTR" Member="SALATTR" ThisKey="SAL_ATTR" OtherKey="SALATTR1" Type="SALATTR" Cardinality="One" />
      <Association Name="WAGED_SALCODE" Member="WAGED" ThisKey="SAL_CODE" OtherKey="SAL_CODE" Type="WAGED" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SALATTR" Member="SALATTR">
    <Type Name="SALATTR">
      <Column Name="SALATTR" Member="SALATTR1" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ATTR_NAME" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NOT_DISP" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="BASIC" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TYPE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FLAG" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TAX" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="SALCODE_SALATTR" Member="SALCODE" ThisKey="SALATTR1" OtherKey="SAL_ATTR" Type="SALCODE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.INSLAB" Member="INSLAB">
    <Type Name="INSLAB">
      <Column Name="NOBR" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FA_IDNO" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CODE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IN_DATE" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OUT_DATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LRATE_CODE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HRATE_CODE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="L_AMT" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="H_AMT" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="KEY_MAN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KEY_DATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SEQ" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CODE1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NOTE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="S_NO" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="R_AMT" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="SPTYP" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="WBSPTYP" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ROUT_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NOSUP" Type="System.Boolean" DbType="bit" CanBeNull="false" />
      <Association Name="BASE_INSLAB" Member="BASE" ThisKey="NOBR" OtherKey="NOBR" Type="BASE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ENRICH" Member="ENRICH">
    <Type Name="ENRICH">
      <Column Name="NOBR" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="YYMM" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SEQ" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SAL_CODE" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AMT" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="KEY_MAN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KEY_DATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MEMO" Type="System.String" DbType="NVarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="FA_IDNO" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IMPORT" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.U_SYS4" Member="U_SYS4">
    <Type Name="U_SYS4">
      <Column Name="AUTO" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LSALCODE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LABOVERSALCODE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LABREPAIRSALCODE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LJOBPER" Type="System.Decimal" DbType="Decimal(16,3)" CanBeNull="true" />
      <Column Name="LJOBPER1" Type="System.Decimal" DbType="Decimal(16,3)" CanBeNull="true" />
      <Column Name="RETIRERATE" Type="System.Decimal" DbType="Decimal(16,3)" CanBeNull="true" />
      <Column Name="RETIRERATE1" Type="System.Decimal" DbType="Decimal(16,3)" CanBeNull="true" />
      <Column Name="NRETIRERATE" Type="System.Decimal" DbType="Decimal(16,3)" CanBeNull="true" />
      <Column Name="NRETIRERATE1" Type="System.Decimal" DbType="Decimal(16,3)" CanBeNull="true" />
      <Column Name="RETSALCODE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.U_SYS5" Member="U_SYS5">
    <Type Name="U_SYS5">
      <Column Name="AUTO" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HSALCODE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HEALTHOVERSALCODE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HEALTHREPAIRSALCODE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EMPFAMILYCNT" Type="System.Decimal" DbType="Decimal(16,2)" CanBeNull="true" />
      <Column Name="COMPERSONCNT" Type="System.Decimal" DbType="Decimal(16,2)" CanBeNull="true" />
      <Column Name="HEACOMPRATE" Type="System.Decimal" DbType="Decimal(16,4)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.U_SYS6" Member="U_SYS6">
    <Type Name="U_SYS6">
      <Column Name="AUTO" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GROUPSALCD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GROUPEXP1" Type="System.Decimal" DbType="Decimal(16,2)" CanBeNull="true" />
      <Column Name="GROUPEXP2" Type="System.Decimal" DbType="Decimal(16,2)" CanBeNull="true" />
      <Column Name="GROUPEXP51" Type="System.Decimal" DbType="Decimal(16,2)" CanBeNull="true" />
      <Column Name="GROUPEXP52" Type="System.Decimal" DbType="Decimal(16,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.EXPLAB" Member="EXPLAB">
    <Type Name="EXPLAB">
      <Column Name="NOBR" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FA_IDNO" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="YYMM" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EXP" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="COMP" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="NOTEDIT" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="KEY_DATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="KEY_MAN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ADATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DAYS" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="RATE_CODE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="INSUR_TYPE" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="INSCD" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="SAL_CODE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="JOBAMT" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="FUNDAMT" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="S_NO" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SALADR" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BASETTS" Member="BASETTS">
    <Type Name="BASETTS">
      <Column Name="NOBR" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ADATE" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TTSCODE" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="INDT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CINDT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="OUDT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="STDT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="STINDT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="STOUDT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="COMP" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DEPT" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DEPTS" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="JOB" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="JOBL" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CARD" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ROTET" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DI" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KEY_MAN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KEY_DATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MANG" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="YR_DAYS" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="WK_YRS" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="SALTP" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="JOBS" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="WORKCD" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CARCD" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EMPCD" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OUTCD" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CALABS" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CALOT" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FULATT" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NOTER" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NOWEL" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NORET" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NOTLATE" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HOLI_CODE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NOOT" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NOSPEC" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NOCARD" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NOEAT" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="APGRPCD" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DEPTM" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TTSCD" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MENO" Type="System.String" DbType="NVarChar(180) NOT NULL" CanBeNull="false" />
      <Column Name="SALADR" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NOWAGE" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MANGE" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RETRATE" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="RETDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RETCHOO" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RETDATE1" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ONLYONTIME" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="JOBO" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="COUNT_PASS" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PASS_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MANG1" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AP_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GRP_AMT" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="TAX_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NOSPAMT" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FIXRATE" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TAX_EDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IS_SELFOUT" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="INSG_TYPE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="BASE_BASETTS" Member="BASE" ThisKey="NOBR" OtherKey="NOBR" Type="BASE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="" Member="InsCnApplyPay">
    <Type Name="InsCnApplyPay">
      <Column Name="Nobr" Type="System.String" CanBeNull="false" />
      <Column Name="" Member="ADate" Type="System.DateTime" CanBeNull="false" />
      <Column Name="DDate" Type="System.DateTime" CanBeNull="false" />
      <Column Name="InsCnType" Type="System.String" CanBeNull="false" />
      <Column Name="InsCnTypeName" Type="System.String" CanBeNull="false" />
      <Column Name="TtsCode" Type="System.String" CanBeNull="false" />
      <Column Name="SelfRate" Type="System.Decimal" CanBeNull="false" />
      <Column Name="CompRate" Type="System.Decimal" CanBeNull="false" />
      <Column Name="Amt" Type="System.Decimal" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="InsCnApplyStop">
    <Type Name="InsCnApplyStop">
      <Column Name="Nobr" Type="System.String" CanBeNull="false" />
      <Column Name="" Member="ADate" Type="System.DateTime" CanBeNull="false" />
      <Column Name="DDate" Type="System.DateTime" CanBeNull="false" />
      <Column Name="InsCnType" Type="System.String" CanBeNull="false" />
      <Column Name="InsCnTypeName" Type="System.String" CanBeNull="false" />
      <Column Name="TtsCode" Type="System.String" CanBeNull="false" />
      <Column Name="SelfRate" Type="System.Decimal" CanBeNull="false" />
      <Column Name="CompRate" Type="System.Decimal" CanBeNull="false" />
      <Column Name="Amt" Type="System.Decimal" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="InsCnApplyAdj">
    <Type Name="InsCnApplyAdj">
      <Column Name="Nobr" Type="System.String" CanBeNull="false" />
      <Column Name="" Member="ADate" Type="System.DateTime" CanBeNull="false" />
      <Column Name="DDate" Type="System.DateTime" CanBeNull="false" />
      <Column Name="InsCnType" Type="System.String" CanBeNull="false" />
      <Column Name="InsCnTypeName" Type="System.String" CanBeNull="false" />
      <Column Name="TtsCode" Type="System.String" CanBeNull="false" />
      <Column Name="SelfRate" Type="System.Decimal" CanBeNull="false" />
      <Column Name="CompRate" Type="System.Decimal" CanBeNull="false" />
      <Column Name="Amt" Type="System.Decimal" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="InsCnPatchApplyPay">
    <Type Name="InsCnPatchApplyPay">
      <Column Name="Nobr" Type="System.String" CanBeNull="false" />
      <Column Name="ADate" Type="System.DateTime" CanBeNull="false" />
      <Column Name="DDate" Type="System.DateTime" CanBeNull="false" />
      <Column Name="InsCnType" Type="System.String" CanBeNull="false" />
      <Column Name="InsCnTypeName" Type="System.String" CanBeNull="false" />
      <Column Name="TtsCode" Type="System.String" CanBeNull="false" />
      <Column Name="SelfRateBef" Type="System.Decimal" CanBeNull="false" />
      <Column Name="SelfRate" Type="System.Decimal" CanBeNull="false" />
      <Column Name="CompRateBef" Type="System.Decimal" CanBeNull="false" />
      <Column Name="CompRate" Type="System.Decimal" CanBeNull="false" />
      <Column Name="AmtBef" Type="System.Decimal" CanBeNull="false" />
      <Column Name="Amt" Type="System.Decimal" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.INSCOMP" Member="INSCOMP">
    <Type Name="INSCOMP">
      <Column Name="S_NO" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="INSNO" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="INSPO" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="INSIDNO" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="INSSUB" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="INSTEL" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="INSNAME" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="INSADDR" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KEY_MAN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KEY_DATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="INSMAN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="REL_MAN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="REL_TEL" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DEFA" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="S_NO_DISP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.YRINSUR" Member="YRINSUR">
    <Type Name="YRINSUR">
      <Column Name="AUTO" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="YEAR" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NOBR" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FA_IDNO" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="REL_LAB" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="REL_HEL" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="REL_GRP" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="KEY_MAN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KEY_DATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EQUAL" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SALADR" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="REL_SUP" Type="System.Decimal" DbType="Decimal(16,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.EXPSUP" Member="EXPSUP">
    <Type Name="EXPSUP">
      <Column Name="NOBR" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="YYMM" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SEQ" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SAL_CODE" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PAY_DATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FORMAT" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PAY_AMT" Type="System.Decimal" DbType="Decimal(14,4) NOT NULL" CanBeNull="false" />
      <Column Name="SUP_AMT" Type="System.Decimal" DbType="Decimal(14,4) NOT NULL" CanBeNull="false" />
      <Column Name="INS_HAMT" Type="System.Decimal" DbType="Decimal(14,4) NOT NULL" CanBeNull="false" />
      <Column Name="ADATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DDATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TOTAL_AMT" Type="System.Decimal" DbType="Decimal(14,4) NOT NULL" CanBeNull="false" />
      <Column Name="S_NO" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KEY_DATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="KEY_MAN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SALADR" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WAGE" Member="WAGE">
    <Type Name="WAGE">
      <Column Name="YYMM" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SEQ" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NOBR" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ADATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="BANKNO" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ACCOUNT_NO" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="WK_DAYS" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="CASH" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NOTE" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="KEY_MAN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KEY_DATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DATE_B" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DATE_E" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FORMAT" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TAXRATE" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="SALADR" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="COMP" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ATT_DATEB" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ATT_DATEE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.GetFilterByNobr" Method="GetFilterByNobr" IsComposable="true">
    <Parameter Name="nobr" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="userid" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="comp" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="admin" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Boolean" />
  </Function>
  <Function Name="dbo.UserReadDataGroupList" Method="UserReadDataGroupList" IsComposable="true">
    <Parameter Name="userid" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="comp" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="admin" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="UserReadDataGroupListResult">
      <Column Name="DATAGROUP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>