<?xml version="1.0" encoding="utf-8"?><Database Name="HOLYHRDB" Class="dcAttDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.1.24;Initial Catalog=HOLYSTONEHR;Persist Security Info=True;User ID=JB" SettingsObjectName="OldJBHR.Dll.Properties.Settings" SettingsPropertyName="JBHRConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="" Member="Card">
    <Type Name="Card">
      <Column Name="dAdate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="bLos" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="sOnTime" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="dDateTime" Type="System.DateTime" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="Abs2">
    <Type Name="Abs">
      <Column Name="dDateB" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="dDateE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="sTimeB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sTimeE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="iUse" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="sHoliCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sUint" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.JB_HR_Attend" Member="JB_HR_Attend">
    <Type Name="JB_HR_Attend">
      <Column Name="sNobr" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="dAdate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="sRoteCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="iLateMins" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="iEMins" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="bAbs" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="iForget" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.JB_HR_AttCard" Member="JB_HR_AttCard">
    <Type Name="JB_HR_AttCard">
      <Column Name="sNobr" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="dAdate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="sT1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sT2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sTT1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sTT2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.JB_HR_Ot" Member="JB_HR_Ot">
    <Type Name="JB_HR_Ot">
      <Column Name="sNobr" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="dDateB" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="sTimeB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sTimeE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="iTotHours" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="iOtHrs" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="iRestHrs" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="sNote" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="sYYMM" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sSerNo" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="iOtCar" Type="System.String" DbType="VarChar(41)" CanBeNull="true" />
      <Column Name="sOtDept" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sOtrcd" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sOtRote" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.JB_HR_Abs" Member="JB_HR_Abs">
    <Type Name="JB_HR_Abs">
      <Column Name="sNobr" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="dDateB" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="dDateE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="sTimeB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sTimeE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sHoliCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="iTolHours" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="sYYMM" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sAname" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="sSerNo" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.JB_HR_Abs1" Member="JB_HR_Abs1">
    <Type Name="JB_HR_Abs1">
      <Column Name="sNobr" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="dDateB" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="dDateE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="sTimeB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sTimeE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sHoliCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="iTolHours" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="sYYMM" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sAname" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="sSerNo" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.JB_HR_Rotechg" Member="JB_HR_Rotechg">
    <Type Name="JB_HR_Rotechg">
      <Column Name="dAdate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="sNobr" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sRoteCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.JB_HR_TmTable" Member="JB_HR_TmTable">
    <Type Name="JB_HR_TmTable">
      <Column Name="sYYMM" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sNobr" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="D1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="D2" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="D3" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="D4" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="D5" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="D6" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="D7" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="D8" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="D9" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="D10" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="D11" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="D12" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="D13" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="D14" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="D15" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="D16" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="D17" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="D18" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="D19" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="D20" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="D21" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="D22" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="D23" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="D24" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="D25" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="D26" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="D27" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="D28" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="D29" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="D30" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="D31" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="iNo" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="iHolis" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="iFreqNo" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.JB_HR_Holi" Member="JB_HR_Holi">
    <Type Name="JB_HR_Holi">
      <Column Name="dDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="sAttCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="bHoli" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="sHoliCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sOtHcode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.JB_HR_Holicd" Member="JB_HR_Holicd">
    <Type Name="JB_HR_Holicd">
      <Column Name="sHoliCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sHoliName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="bNoSet" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="sDateCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.JB_HR_Rotet" Member="JB_HR_Rotet">
    <Type Name="JB_HR_Rotet">
      <Column Name="sRotet" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sRotetName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sR1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sR2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sR3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sR4" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sR5" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sR6" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sR7" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sR8" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sR9" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sR10" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sFreq" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sInHoli" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="iSalHrs" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="iFreqDate" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="sFreqStart" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="iYrrestHrs" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ATTEND" Member="ATTEND">
    <Type Name="ATTEND">
      <Column Name="NOBR" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ADATE" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ROTE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KEY_MAN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KEY_DATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LATE_MINS" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="E_MINS" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="ABS" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ADJ_CODE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CANT_ADJ" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SER" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="NIGHT_HRS" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="FOODAMT" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="FOODSALCD" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FORGET" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="ATT_HRS" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="NIGAMT" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ATTCARD" Member="ATTCARD">
    <Type Name="ATTCARD">
      <Column Name="NOBR" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ADATE" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="T1" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="T2" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CODE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SER" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="KEY_MAN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KEY_DATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DD1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DD2" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LOST1" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LOST2" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TT1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TT2" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NOMODY" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="AttendRote">
    <Type Name="AttendRote">
      <Column Name="sNobr" Type="System.String" CanBeNull="false" />
      <Column Name="dDateB" Type="System.DateTime" CanBeNull="false" />
      <Column Name="dDateE" Type="System.DateTime" CanBeNull="false" />
      <Column Name="sTimeB" Type="System.String" CanBeNull="false" />
      <Column Name="sTimeE" Type="System.String" CanBeNull="false" />
      <Column Name="dDateTimeB" Type="System.DateTime" CanBeNull="false" />
      <Column Name="dDateTimeE" Type="System.DateTime" CanBeNull="false" />
      <Column Name="dDate" Type="System.DateTime" CanBeNull="false" />
      <Column Name="sOffTime2" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.JB_HR_Abst" Member="JB_HR_Abst">
    <Type Name="JB_HR_Abst">
      <Column Name="sNobr" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="dDateB" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="dDateE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="sHoliCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="iTolHours" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="sAname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sT1Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sT2Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sT3Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.JB_HR_Reason" Member="JB_HR_Reason">
    <Type Name="JB_HR_Reason">
      <Column Name="sReasonCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sReasonName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="bAtt" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="iSort" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.JB_HR_Card" Member="JB_HR_Card">
    <Type Name="JB_HR_Card">
      <Column Name="sCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sNobr" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="dAdate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="sOnTime" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sReasonCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="bLos" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="sMeno" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sSerNo" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="sIP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="bNotTran" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="Attend1">
    <Type Name="Attend">
      <Column Name="dDateB" Type="System.DateTime" CanBeNull="false" />
      <Column Name="dDateE" Type="System.DateTime" CanBeNull="false" />
      <Column Name="sTimeB" Type="System.String" CanBeNull="false" />
      <Column Name="sTimeE" Type="System.String" CanBeNull="false" />
      <Column Name="dDateTimeB" Type="System.DateTime" CanBeNull="false" />
      <Column Name="dDateTimeE" Type="System.DateTime" CanBeNull="false" />
      <Column Name="iSort" Type="System.Int32" CanBeNull="false" />
      <Column Name="sType" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.JB_HR_Otrcd" Member="JB_HR_Otrcd">
    <Type Name="JB_HR_Otrcd">
      <Column Name="sOtrCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sOtrName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="bDisplay" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="iSort" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bNoCalc" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.JB_HR_OtRate" Member="JB_HR_OtRate">
    <Type Name="JB_HR_OtRate">
      <Column Name="sOtRateCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sOtRateName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sOtRateTypew" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="iOtUnit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.JB_HR_Rote" Member="JB_HR_Rote">
    <Type Name="JB_HR_Rote">
      <Column Name="dAdate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="sName" Type="System.String" DbType="NVarChar(204)" CanBeNull="true" />
      <Column Name="sRoteCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sRoteName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sOnTime" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sOffTime" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="iWkHrs" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="iDkHrs" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="iMoHrs" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="sOffTime2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="iAlllates" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="sOtBegin" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="iAlllates1" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="sResBTime" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sResETime" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sResB1Time" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sResE1Time" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sResB2Time" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sResE2Time" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sResB3Time" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sResE3Time" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sResB4Time" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sResE4Time" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sAttEnd" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="iYrrestHrs" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="iSort" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="iHoliDayAddMin" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.JB_HR_Hcode" Member="JB_HR_Hcode">
    <Type Name="JB_HR_Hcode">
      <Column Name="sName" Type="System.String" DbType="NVarChar(101)" CanBeNull="true" />
      <Column Name="sHcode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sHname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sUnit" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="iMin" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="bInHoli" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="sYearRest" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="iMax" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="bCheck" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="sDcode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sSex" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="iAbsUint" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="bDisplayForm" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="bCalOt" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="bMang" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="iSort" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bNotDel" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="sHnameE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sFlowGo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sFlowFinal" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sGroupCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.JB_HR_AbsUnion" Member="JB_HR_AbsUnion">
    <Type Name="JB_HR_AbsUnion">
      <Column Name="sNobr" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="dDateB" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="dDateE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="sTimeB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sTimeE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="iUse" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="sYYMM" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sHoliCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sHoliName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sUint" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="iMin" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="bInHoli" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="sYearRest" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="iMax" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="bChe" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="sDcode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sSex" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="bDiscontent" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="bDisplayform" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="iInterval" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="sName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sSerno" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.JB_HR_Ot1" Member="JB_HR_Ot1">
    <Type Name="JB_HR_Ot1">
      <Column Name="sNobr" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="dDateB" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="sTimeB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sTimeE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="iTotHours" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="iOtHrs" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="iRestHrs" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="sNote" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="sYYMM" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sSerNo" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="iOtCar" Type="System.String" DbType="VarChar(41)" CanBeNull="true" />
      <Column Name="sOtDept" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sOtrcd" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sOtRote" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ABS1" Member="ABS1">
    <Type Name="ABS1">
      <Column Name="NOBR" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BDATE" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EDATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="BTIME" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ETIME" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="H_CODE" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TOL_HOURS" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="KEY_MAN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KEY_DATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="BDATE2" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EDATE2" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="BTIME2" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ETIME2" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BTIME3" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ETIME3" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GO_TYPE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ABORD" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="[CFM_MAN ]" Member="CFM_MAN_" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DEPT" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TARGET" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="REASON" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CUST" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NOT_DISP" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ONETOMANY" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NOTE" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="SEQ" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="YYMM" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SERNO" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ABS" Member="ABS">
    <Type Name="ABS">
      <Column Name="NOBR" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BDATE" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EDATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="BTIME" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ETIME" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="H_CODE" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TOL_HOURS" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="KEY_MAN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KEY_DATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="YYMM" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NOTEDIT" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NOTE" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="SYSCREATE" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TOL_DAY" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="A_NAME" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SERNO" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="nocalc" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SYSCREATE1" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ABSC" Member="ABSC">
    <Type Name="ABSC">
      <Column Name="AK" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOBR" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BDATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EDATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="BTIME" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ETIME" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="H_CODE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TOL_HOURS" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="KEY_MAN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KEY_DATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="YYMM" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NOTEDIT" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NOTE" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="SYSCREATE" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TOL_DAY" Type="System.Decimal" DbType="Decimal(16,2) NOT NULL" CanBeNull="false" />
      <Column Name="A_NAME" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SERNO" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="nocalc" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SYSCREATE1" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.GetCodeFilterByNobr" Method="GetCodeFilterByNobr" IsComposable="true">
    <Parameter Name="source" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Code" Parameter="code" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="NOBR" Parameter="nOBR" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="DATE" Parameter="dATE" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Boolean" />
  </Function>
  <Function Name="dbo.GetFilterByNobr" Method="GetFilterByNobr" IsComposable="true">
    <Parameter Name="nobr" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="userid" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="comp" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="admin" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Boolean" />
  </Function>
  <Function Name="dbo.AppConfigByNobr" Method="AppConfigByNobr" IsComposable="true">
    <Parameter Name="Nobr" Parameter="nobr" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Category" Parameter="category" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Parameter" Parameter="parameter" Type="System.String" DbType="NVarChar(1)" />
    <Parameter Name="DefaultValue" Parameter="defaultValue" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.String" />
  </Function>
</Database>