/****** Object:  Table [dbo].[ATTEND_ABNORMAL]    Script Date: 2020/9/8 ¤U¤È 02:04:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ATTEND_ABNORMAL](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOBR] [nvarchar](50) NOT NULL,
	[ADATE] [datetime] NOT NULL,
	[TYPE] [nvarchar](50) NOT NULL,
	[IS_ERROR] [bit] NOT NULL,
	[ERROR_MINS] [decimal](16, 2) NOT NULL,
	[ON_TIME] [nvarchar](50) NOT NULL,
	[OFF_TIME] [nvarchar](50) NOT NULL,
	[ON_TIME_ACTUAL] [nvarchar](50) NOT NULL,
	[OFF_TIME_ACTUAL] [nvarchar](50) NOT NULL,
	[ON_TIEM_BUFFER_MINS] [decimal](16, 2) NOT NULL,
	[OFF_TIME_BUFFER_MINS] [decimal](16, 2) NOT NULL,
	[ROTE_CODE] [nvarchar](50) NOT NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_MAN] [nvarchar](50) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_MAN] [nvarchar](50) NULL,
 CONSTRAINT [PK_ATTEND_ABNORMAL] PRIMARY KEY CLUSTERED 
(
	[NOBR] ASC,
	[ADATE] ASC,
	[TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


