--IF NOT  EXISTS (SELECT * FROM  U_PRG  WHERE  PROG ='FRM4K')
DELETE  FROM  [U_PRG]  WHERE  PROG  ='FRM4K'
 INSERT [dbo].[U_PRG] ([PROG], [PROG_NAME], [SYSTEM], [ROOT], [KEY_MAN], [KEY_DATE]) VALUES (N'FRM4K', N'非經常性期別資料', N'JBHR', 0, N'JBADMIN', GETDATE() )
DELETE  FROM  [U_CODE]  WHERE  FORMNAME  ='FRM4K'
INSERT [dbo].[U_CODE] ( [Q_CODE], [Q_NAME], [Q_FIELD], [Q_LENS], [Q_ATTR], [Q_ORDER], [FORMNAME], [KEY_DATE], [KEY_MAN], [SYSTEM], [Q_VAR], [FIELD1], [FIELD2]) VALUES ( N'4', N'期別', N'SEQ', CAST(1.00 AS Decimal(16, 2)), N'C', 1, N'FRM4K', CAST(N'2012-02-08T14:07:15.190' AS DateTime), N'JbDataImport', N'JBHR', 0, N'', N'')
GO
INSERT [dbo].[U_CODE] ( [Q_CODE], [Q_NAME], [Q_FIELD], [Q_LENS], [Q_ATTR], [Q_ORDER], [FORMNAME], [KEY_DATE], [KEY_MAN], [SYSTEM], [Q_VAR], [FIELD1], [FIELD2]) VALUES ( N'5', N'薪資代碼', N'SAL_CODE_DISP', CAST(3.00 AS Decimal(16, 2)), N'C', 1, N'FRM4K', CAST(N'2012-02-08T14:07:15.190' AS DateTime), N'JbDataImport', N'JBHR', 1, N'SALCODE.SAL_CODE=FRM4K.SAL_CODE', N'')
GO
INSERT [dbo].[U_CODE] (  [Q_CODE], [Q_NAME], [Q_FIELD], [Q_LENS], [Q_ATTR], [Q_ORDER], [FORMNAME], [KEY_DATE], [KEY_MAN], [SYSTEM], [Q_VAR], [FIELD1], [FIELD2]) VALUES ( N'1', N'員工編號', N'NOBR', CAST(10.00 AS Decimal(16, 2)), N'C', 1, N'FRM4K', CAST(N'2012-02-08T14:07:15.190' AS DateTime), N'JbDataImport', N'JBHR', 0, N'', N'')
GO
INSERT [dbo].[U_CODE] (  [Q_CODE], [Q_NAME], [Q_FIELD], [Q_LENS], [Q_ATTR], [Q_ORDER], [FORMNAME], [KEY_DATE], [KEY_MAN], [SYSTEM], [Q_VAR], [FIELD1], [FIELD2]) VALUES ( N'2', N'員工姓名', N'NAME_C', CAST(10.00 AS Decimal(16, 2)), N'C', 1, N'FRM4K', CAST(N'2012-02-08T14:07:15.190' AS DateTime), N'JbDataImport', N'JBHR', 0, N'', N'')
GO
INSERT [dbo].[U_CODE] (  [Q_CODE], [Q_NAME], [Q_FIELD], [Q_LENS], [Q_ATTR], [Q_ORDER], [FORMNAME], [KEY_DATE], [KEY_MAN], [SYSTEM], [Q_VAR], [FIELD1], [FIELD2]) VALUES ( N'3', N'計薪年月', N'YYMM', CAST(5.00 AS Decimal(16, 2)), N'C', 1, N'FRM4K', CAST(N'2012-02-08T14:07:15.190' AS DateTime), N'JbDataImport', N'JBHR', 0, N'', N'')
GO

 