BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.NotifyClass ADD
	NotifyDay int NULL
GO
ALTER TABLE dbo.NotifyClass SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
update NotifyClass set notifyday= (select top 1 notifyday from NotifyTemplate) where notifyday is null
go
ALTER TABLE dbo.NotifyClass
alter column	NotifyDay int not NULL
go

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.NotifyClass ADD
	RelationApp nvarchar(50) NULL
GO
ALTER TABLE dbo.NotifyClass SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
update mtcode set display=1 where category='NotifyTarget'
go
