/****** Object:  Table [dbo].[FOOD_CARD]    Script Date: 2020/10/27 ¤W¤È 11:41:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FOOD_CARD](
	[CODE] [nvarchar](50) NOT NULL,
	[NOBR] [nvarchar](50) NOT NULL,
	[ADATE] [datetime] NOT NULL,
	[ONTIME] [nvarchar](50) NOT NULL,
	[CARDNO] [nvarchar](50) NOT NULL,
	[KEY_DATE] [datetime] NOT NULL,
	[KEY_MAN] [nvarchar](50) NOT NULL,
	[NOT_TRAN] [bit] NOT NULL,
	[DAYS] [decimal](16, 2) NOT NULL,
	[REASON] [nvarchar](50) NOT NULL,
	[LOS] [bit] NOT NULL,
	[IPADD] [nvarchar](50) NOT NULL,
	[MENO] [nvarchar](50) NOT NULL,
	[SERNO] [nvarchar](50) NOT NULL,
	[FULLTIME] [datetime] NOT NULL,
 CONSTRAINT [PK_FOOD_CARD] PRIMARY KEY CLUSTERED 
(
	[NOBR] ASC,
	[ADATE] ASC,
	[ONTIME] ASC,
	[CARDNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


