 /****** Object:  Table [dbo].[SALENRICH]    Script Date: 2020/2/10 ¤U¤È 04:34:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SALENRICH](
	[AUTOKEY] [int] IDENTITY(1,1) NOT NULL,
	[NOBR] [nvarchar](50) NOT NULL,
	[YYMM] [nvarchar](50) NOT NULL,
	[SEQ] [nvarchar](50) NOT NULL,
	[SAL_CODE] [nvarchar](50) NOT NULL,
	[AMT] [decimal](16, 2) NOT NULL,
	[KEY_MAN] [nvarchar](50) NOT NULL,
	[KEY_DATE] [datetime] NOT NULL,
	[MEMO] [nvarchar](120) NOT NULL,
	[FA_IDNO] [nvarchar](50) NOT NULL,
	[IMPORT] [bit] NOT NULL,
 CONSTRAINT [PK_SALENRICH] PRIMARY KEY CLUSTERED 
(
	[AUTOKEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SALENRICH] ADD  CONSTRAINT [DF_SALENRICH_MEMO]  DEFAULT ('') FOR [MEMO]
GO

ALTER TABLE [dbo].[SALENRICH] ADD  CONSTRAINT [DF_SALENRICH_FA_IDNO]  DEFAULT ('') FOR [FA_IDNO]
GO

ALTER TABLE [dbo].[SALENRICH] ADD  CONSTRAINT [DF_SALENRICH_IMPORT]  DEFAULT ((0)) FOR [IMPORT]
GO

ALTER TABLE SALCODE ADD SALSEQ NVARCHAR(50) DEFAULT ('') NOT NULL
GO 



