/* 為了避免任何可能發生資料遺失的問題，您應該先詳細檢視此指令碼，然後才能在資料庫設計工具環境以外的位置執行。*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.NotifyDetail ADD
	ContentArgQuery nvarchar(MAX) NOT NULL CONSTRAINT DF_NotifyDetail_ContentArgQuery DEFAULT ''
GO
ALTER TABLE dbo.NotifyDetail SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

/* 為了避免任何可能發生資料遺失的問題，您應該先詳細檢視此指令碼，然後才能在資料庫設計工具環境以外的位置執行。*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.NotifyMaster ADD
	ContentArgQuery nvarchar(MAX) NOT NULL CONSTRAINT DF_NotifyMaster_ContentArgQuery DEFAULT ''
GO
ALTER TABLE dbo.NotifyMaster SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
