Alter Table HcodeType add HTYPE_DISP nvarchar(50) null
GO

update HcodeType
set HTYPE_DISP = HTYPE
GO

insert into CODE_FILTER (SOURCE,CODE,CODEGROUP,NOTE,KEY_DATE,KEY_MAN)
SELECT DISTINCT 'HcodeType',ht.HTYPE,cd.DATAGROUP,'',GETDATE(),'JB'
FROM  COMP_DATAGROUP cd 
JOIN HcodeType ht on ht.HTYPE = ht.HTYPE
GO