

CREATE TABLE [dbo].[RuleCode](
	[RuleCode] [nvarchar](50) NOT NULL,
	[RuleName] [nvarchar](50) NOT NULL,
	[Description] [nvarchar](max) NOT NULL,
	[KEY_DATE] [datetime] NOT NULL,
	[KEY_MAN] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_RuleCode] PRIMARY KEY CLUSTERED 
(
	[RuleCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


