/****** Object:  View [dbo].[FRM46]    Script Date: 2021/6/22 ¤U¤È 01:02:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[FRM46]
AS
SELECT  TOP (100) PERCENT dbo.SALBASD.ADATE, dbo.SALBASD.NOBR, dbo.SALBASD.SAL_CODE, dbo.SALBASD.AMT, dbo.SALBASD.KEY_MAN, 
               dbo.SALBASD.KEY_DATE, dbo.SALBASD.AMTB, dbo.SALBASD.MENO, dbo.SALBASD.DDATE, dbo.BASE.NAME_C, dbo.SALCODE.SAL_NAME, 
               dbo.SALCODE.SAL_CODE_DISP
FROM     dbo.SALBASD INNER JOIN
               dbo.BASE ON dbo.SALBASD.NOBR = dbo.BASE.NOBR INNER JOIN
               dbo.SALCODE ON dbo.SALBASD.SAL_CODE = dbo.SALCODE.SAL_CODE
GO


