/****** Object:  Table [dbo].[SALDIVOT]    Script Date: 2021/10/21 ¤U¤È 02:40:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SALDIVOT](
	[NOBR] [nvarchar](50) NOT NULL,
	[SAL_CODE] [nvarchar](50) NOT NULL,
	[AMT] [decimal](18, 2) NOT NULL,
	[ADATE] [datetime] NOT NULL,
	[DDATE] [datetime] NOT NULL,
	[KEY_DATE] [datetime] NOT NULL,
	[KEY_MAN] [nvarchar](50) NOT NULL,
	[OT_HRS] [decimal](18, 2) NOT NULL,
 CONSTRAINT [PK_SALTAXITEM] PRIMARY KEY CLUSTERED 
(
	[NOBR] ASC,
	[SAL_CODE] ASC,
	[ADATE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SALDIVOT] ADD  CONSTRAINT [DF_SALTAXITEM_ADATE]  DEFAULT ('1900/01/01') FOR [ADATE]
GO

ALTER TABLE [dbo].[SALDIVOT] ADD  CONSTRAINT [DF_SALTAXITEM_DDATE]  DEFAULT ('1900/01/01') FOR [DDATE]
GO

ALTER TABLE [dbo].[SALDIVOT] ADD  CONSTRAINT [DF_SALDIVOT_OT_HRS]  DEFAULT ((0)) FOR [OT_HRS]
GO


