ALTER TABLE dbo.YEAR_HOLIDAY DROP CONSTRAINT PK_YEAR_HOLIDAY
GO
ALTER TABLE dbo.YEAR_HOLIDAY ADD Auto int IDENTITY (1,1) NOT NULL
GO
ALTER TABLE dbo.YEAR_HOLIDAY ADD CONSTRAINT PK_YEAR_HOLIDAY PRIMARY KEY CLUSTERED (Auto);
GO
