/****** Object:  View [dbo].[FRM46B]    Script Date: 2021/7/27 ¤U¤È 05:30:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER VIEW [dbo].[FRM46B]
AS
SELECT          DBO.SALBASND.NOBR, DBO.SALBASND.YYMM_B, DBO.SALBASND.YYMM_E, DBO.SALBASND.SAL_CODE, 
                            DBO.SALBASND.SEQ, DBO.SALBASND.A_DATE, DBO.SALBASND.A_TYPE, DBO.SALBASND.A_PER, 
                            DBO.SALBASND.F_AMT, DBO.SALBASND.P_AMT, DBO.SALBASND.T_AMT, DBO.SALBASND.KEY_MAN, 
                            DBO.SALBASND.KEY_DATE, DBO.SALBASND.MEMO, DBO.SALBASND.DISPATCH, DBO.SALBASND.DE_DEPT, 
                            DBO.SALBASND.DE_MAN, DBO.SALBASND.DE_TEL, DBO.SALBASND.DE_ADD, DBO.SALBASND.LAW_DEPT, 
                            DBO.SALBASND.LAW_MAN, DBO.SALBASND.LAW_TEL, DBO.SALBASND.P_DATE, DBO.SALBASND.F_DATE, 
                            DBO.SALBASND.T_DATE, DBO.SALBASND.C_DATE, DBO.SALBASND.P_PER, DBO.SALBASND.ACNO, DBO.BASE.NAME_C, 
                            ISNULL(DBO.DEPT.D_NAME, N'') AS DEPT_NAME, DBO.DEPT.D_NO, DBO.SALCODE.SAL_NAME, 
                            DBO.SALBASND.MIN_COST_LIVING
FROM              DBO.DEPT INNER JOIN
                            DBO.BASETTS ON DBO.DEPT.D_NO = DBO.BASETTS.DEPT INNER JOIN
                            DBO.SALBASND LEFT OUTER JOIN
                            DBO.BASE ON DBO.SALBASND.NOBR = DBO.BASE.NOBR ON DBO.BASETTS.NOBR = DBO.BASE.NOBR AND CONVERT (nvarchar(50), GETDATE(), 111) 
                            BETWEEN DBO.BASETTS.ADATE AND DBO.BASETTS.DDATE INNER JOIN
                            DBO.SALCODE ON DBO.SALBASND.SAL_CODE = DBO.SALCODE.SAL_CODE
GO


