ALTER TABLE basetts¡@DROP CONSTRAINT DF_BASETTS_DDATE
GO
ALTER TABLE basetts¡@DROP CONSTRAINT DF_BASETTS_INDT
GO
ALTER TABLE basetts¡@DROP CONSTRAINT DF_BASETTS_CINDT 
GO
ALTER TABLE basetts¡@DROP CONSTRAINT DF_BASETTS_OUDT
GO
ALTER TABLE basetts¡@DROP CONSTRAINT DF_BASETTS_STDT
GO
ALTER TABLE basetts¡@DROP CONSTRAINT DF_BASETTS_STINDT
GO
ALTER TABLE basetts¡@DROP CONSTRAINT DF_BASETTS_STOUDT
GO
ALTER TABLE basetts¡@DROP CONSTRAINT DF_BASETTS_RETDATE
GO
ALTER TABLE basetts¡@DROP CONSTRAINT DF_BASETTS_RETDATE1
GO
ALTER TABLE basetts¡@DROP CONSTRAINT DF_BASETTS_PASS_DATE
GO
ALTER TABLE basetts¡@DROP CONSTRAINT DF_BASETTS_AP_DATE
GO
ALTER TABLE basetts¡@DROP CONSTRAINT DF_BASETTS_TAX_DATE
GO
ALTER TABLE basetts¡@DROP CONSTRAINT DF_BASETTS_TAX_EDATE
GO
ALTER TABLE basetts¡@DROP CONSTRAINT DF_BASETTS_ReinstateDate
GO
ALTER TABLE basetts¡@DROP CONSTRAINT DF_BASETTS_AuditDate
GO