IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'SqlUpdateTable')
BEGIN
	CREATE TABLE [dbo].[SqlUpdateTable](
		[AutoKey] [int] IDENTITY(1,1) NOT NULL,
		[FileName] [nvarchar](50) NOT NULL,
		[USERID] [nvarchar](50) NOT NULL,
		[TIMEB] datetime NULL,
		[TIMEE] datetime NULL,
		[NOTE] [text] NULL,
	 CONSTRAINT [PK_SqlUpdateTable] PRIMARY KEY CLUSTERED 
	(
		[AutoKey] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END