DROP TABLE [dbo].[EFFEMPLOY]
go 

/****** Object:  Table [dbo].[EFFEMPLOY]    Script Date: 2019/11/12 ¤U¤È 02:18:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EFFEMPLOY](
	[YYMM] [nvarchar](50) NOT NULL,
	[NOBR] [nvarchar](50) NOT NULL,
	[EFFSCORE] [decimal](16, 2) NOT NULL,
	[EFFLVL] [nvarchar](50) NOT NULL,
	[IMPORT] [bit] NOT NULL,
	[KEY_DATE] [datetime] NOT NULL,
	[KEY_MAN] [nvarchar](50) NOT NULL,
	[EFFTYPE] [nvarchar](50) NULL,
	[AUTOKEY] [int] IDENTITY(1,1) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[AUTOKEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO