CREATE TABLE [dbo].[ABS] (
    [NOBR]       NVARCHAR (50)   CONSTRAINT [DF_ABS_NOBR] DEFAULT ('') NOT NULL,
    [BDATE]      DATETIME        CONSTRAINT [DF_ABS_BDATE] DEFAULT (getdate()) NOT NULL,
    [EDATE]      DATETIME        CONSTRAINT [DF_ABS_EDATE] DEFAULT (getdate()) NOT NULL,
    [BTIME]      NVARCHAR (50)   CONSTRAINT [DF_ABS_BTIME] DEFAULT ('') NOT NULL,
    [ETIME]      NVARCHAR (50)   CONSTRAINT [DF_ABS_ETIME] DEFAULT ('') NOT NULL,
    [H_CODE]     NVARCHAR (50)   CONSTRAINT [DF_ABS_H_CODE] DEFAULT ('') NOT NULL,
    [TOL_HOURS]  DECIMAL (16, 2) CONSTRAINT [DF_ABS_TOL_HOURS] DEFAULT ((0)) NOT NULL,
    [KEY_MAN]    NVARCHAR (50)   CONSTRAINT [DF_ABS_KEY_MAN] DEFAULT ('') NOT NULL,
    [KEY_DATE]   DATETIME        CONSTRAINT [DF_ABS_KEY_DATE] DEFAULT (getdate()) NOT NULL,
    [YYMM]       NVARCHAR (50)   CONSTRAINT [DF_ABS_YYMM] DEFAULT ('') NOT NULL,
    [NOTEDIT]    BIT             NOT NULL,
    [NOTE]       NVARCHAR (200)  CONSTRAINT [DF_ABS_NOTE] DEFAULT ('') NOT NULL,
    [SYSCREATE]  BIT             NOT NULL,
    [TOL_DAY]    DECIMAL (16, 2) CONSTRAINT [DF_ABS_TOL_DAY] DEFAULT ((0)) NOT NULL,
    [A_NAME]     NVARCHAR (50)   CONSTRAINT [DF_ABS_A_NAME] DEFAULT ('') NOT NULL,
    [SERNO]      NVARCHAR (50)   CONSTRAINT [DF_ABS_SERNO] DEFAULT ('') NOT NULL,
    [nocalc]     BIT             NULL,
    [SYSCREATE1] BIT             NULL,
    [Balance]    DECIMAL (16, 2) NULL,
    [LeaveHours] DECIMAL (16, 2) NULL,
    [Guid]       NVARCHAR (50)   CONSTRAINT [DF_ABS_Guid] DEFAULT (newid()) NULL,
    CONSTRAINT [PK_ABS] PRIMARY KEY CLUSTERED ([NOBR] ASC, [BDATE] ASC, [BTIME] ASC, [H_CODE] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'請假資料，包含得假資料及請假資料from holystone db', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ABS';

