CREATE TABLE [dbo].[ABSD] (
    [AK]          INT             IDENTITY (1, 1) NOT NULL,
    [ABSADD]      NVARCHAR (50)   NOT NULL,
    [ABSSUBTRACT] NVARCHAR (50)   NOT NULL,
    [USEHOUR]     DECIMAL (16, 2) NOT NULL,
    [KEY_MAN]     NVARCHAR (50)   NOT NULL,
    [KEY_DATE]    DATETIME        NOT NULL,
    CONSTRAINT [PK_ABSD] PRIMARY KEY CLUSTERED ([AK] ASC)
);

