CREATE TABLE [dbo].[ABSPRE] (
    [NOBR]     NVARCHAR (50)   NOT NULL,
    [ADATE]    DATETIME        NOT NULL,
    [BTIME]    NVARCHAR (50)   NOT NULL,
    [ETIME]    NVARCHAR (50)   NOT NULL,
    [SUG_HRS]  DECIMAL (16, 2) NOT NULL,
    [ABS_HRS]  DECIMAL (16, 2) NOT NULL,
    [ABS1_HRS] DECIMAL (16, 2) NOT NULL,
    [ABS2_HRS] DECIMAL (16, 2) NOT NULL,
    [TRANS]    BIT             NOT NULL,
    [H_CODE]   NVARCHAR (50)   NOT NULL,
    [KEY_DATE] DATETIME        NOT NULL,
    [KEY_MAN]  NVARCHAR (50)   NOT NULL,
    [YYMM]     NVARCHAR (50)   NOT NULL,
    [DDATE]    DATETIME        NOT NULL,
    CONSTRAINT [PK_ABSPRE] PRIMARY KEY CLUSTERED ([NOBR] ASC, [ADATE] ASC, [BTIME] ASC, [ETIME] ASC)
);

