CREATE TABLE [dbo].[ABST] (
    [NOBR]      NVARCHAR (50)   CONSTRAINT [DF_ABST_NOBR] DEFAULT ('') NOT NULL,
    [BDATE]     DATETIME        CONSTRAINT [DF_ABST_BDATE] DEFAULT (getdate()) NOT NULL,
    [EDATE]     DATETIME        CONSTRAINT [DF_ABST_EDATE] DEFAULT (getdate()) NOT NULL,
    [H_CODE]    NVARCHAR (50)   CONSTRAINT [DF_ABST_H_CODE] DEFAULT ('') NOT NULL,
    [TOL_HOURS] DECIMAL (16, 2) CONSTRAINT [DF_ABST_TOL_HOURS] DEFAULT ((0)) NOT NULL,
    [T_CODE1]   NVARCHAR (50)   CONSTRAINT [DF_ABST_T_CODE1] DEFAULT ('') NOT NULL,
    [T_CODE2]   NVARCHAR (50)   CONSTRAINT [DF_ABST_T_CODE2] DEFAULT ('') NOT NULL,
    [T_CODE3]   NVARCHAR (50)   CONSTRAINT [DF_ABST_T_CODE3] DEFAULT ('') NOT NULL,
    [KEY_MAN]   NVARCHAR (50)   CONSTRAINT [DF_ABST_KEY_MAN] DEFAULT ('') NOT NULL,
    [KEY_DATE]  DATETIME        CONSTRAINT [DF_ABST_KEY_DATE] DEFAULT (getdate()) NOT NULL,
    [NOTE]      NVARCHAR (50)   CONSTRAINT [DF_ABST_NOTE] DEFAULT ('') NOT NULL,
    [A_NAME]    NVARCHAR (50)   CONSTRAINT [DF_ABST_A_NAME] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_ABST] PRIMARY KEY CLUSTERED ([NOBR] ASC, [BDATE] ASC, [EDATE] ASC, [H_CODE] ASC)
);

