CREATE TABLE [dbo].[ACCCD] (
    [ACCCD]      NVARCHAR (50) NOT NULL,
    [ACCNAME]    NVARCHAR (50) NOT NULL,
    [KEY_MAN]    NVARCHAR (50) NOT NULL,
    [KEY_DATE]   DATETIME      NOT NULL,
    [ACC_TR]     NVARCHAR (50) CONSTRAINT [DF_ACCCD_ACC_TR] DEFAULT ('') NOT NULL,
    [ACCCR]      NVARCHAR (50) CONSTRAINT [DF_ACCCD_ACCCR] DEFAULT ('') NOT NULL,
    [ACCDR]      NVARCHAR (50) CONSTRAINT [DF_ACCCD_ACCDR] DEFAULT ('') NOT NULL,
    [ACCNAME_E]  NVARCHAR (50) NOT NULL,
    [ACCCD_DISP] NVARCHAR (50) NULL,
    CONSTRAINT [PK_ACCCD] PRIMARY KEY CLUSTERED ([ACCCD] ASC)
);

