CREATE TABLE [dbo].[APGPCD] (
    [APGRPCD]   NVARCHAR (50)  NOT NULL,
    [APGRPNAME] NVARCHAR (50)  NOT NULL,
    [KEY_DATE]  DATETIME       NOT NULL,
    [KEY_MAN]   NVARCHAR (50)  NOT NULL,
    [APGNOTE]   NVARCHAR (200) CONSTRAINT [DF_APGPCD_APGNOTE] DEFAULT ('') NOT NULL,
    [APGNOTE1]  NVARCHAR (200) CONSTRAINT [DF_APGPCD_APGNOTE1] DEFAULT ('') NOT NULL,
    [APP1]      NVARCHAR (50)  CONSTRAINT [DF_APGPCD_APP1] DEFAULT ('') NOT NULL,
    [APP2]      NVARCHAR (50)  CONSTRAINT [DF_APGPCD_APP2] DEFAULT ('') NOT NULL,
    [APP3]      NVARCHAR (50)  CONSTRAINT [DF_APGPCD_APP3] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_APGPCD] PRIMARY KEY CLUSTERED ([APGRPCD] ASC)
);

