CREATE TABLE [dbo].[APGPIT] (
    [APGRPCD]  NVARCHAR (50)   NOT NULL,
    [ITEMCD]   NVARCHAR (50)   NOT NULL,
    [KEY_DATE] DATETIME        NOT NULL,
    [KEY_MAN]  NVARCHAR (50)   NOT NULL,
    [RATE]     DECIMAL (16, 2) NOT NULL,
    CONSTRAINT [PK_APGPIT] PRIMARY KEY CLUSTERED ([APGRPCD] ASC)
);

