CREATE TABLE [dbo].[APITEM] (
    [ITEMCD]   NVARCHAR (50) NOT NULL,
    [ITEMNAME] NVARCHAR (50) NOT NULL,
    [VALCD]    NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    [CONT]     NVARCHAR (50) NOT NULL,
    [TYEMCD]   NVARCHAR (50) CONSTRAINT [DF_APITEM_TYEMCD] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_APITEM] PRIMARY KEY CLUSTERED ([ITEMCD] ASC)
);

