CREATE TABLE [dbo].[APPDEPTM] (
    [YYMM]     NVARCHAR (50)   NOT NULL,
    [SER]      NVARCHAR (50)   NOT NULL,
    [DEPTM]    NVARCHAR (50)   NOT NULL,
    [AMT]      DECIMAL (16, 2) NOT NULL,
    [KEY_DATE] DATETIME        NOT NULL,
    [KEY_MAN]  NVARCHAR (50)   NOT NULL,
    [NOTE]     NVARCHAR (200)  NOT NULL,
    [DI]       NVARCHAR (50)   CONSTRAINT [DF_APPDEPTM_DI] DEFAULT ('') NOT NULL,
    [QTY]      DECIMAL (16, 2) CONSTRAINT [DF_APPDEPTM_QTY] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_APPDEPTM] PRIMARY KEY CLUSTERED ([YYMM] ASC, [SER] ASC, [DEPTM] ASC)
);

