CREATE TABLE [dbo].[ApplyUpdateBase] (
    [Pk]                  INT           IDENTITY (1, 1) NOT NULL,
    [Approve]             BIT           NULL,
    [ApproveMan]          NVARCHAR (50) NULL,
    [ApproveDatetime]     DATETIME      NULL,
    [ApplyMan]            NVARCHAR (50) NOT NULL,
    [ApplyDatetime]       DATETIME      NOT NULL,
    [GSM]                 NVARCHAR (50) NOT NULL,
    [EMAIL]               NVARCHAR (60) NOT NULL,
    [TEL1]                NVARCHAR (50) NOT NULL,
    [TEL2]                NVARCHAR (50) NOT NULL,
    [POSTCODE1]           NVARCHAR (50) NOT NULL,
    [ADDR1]               NVARCHAR (60) NOT NULL,
    [POSTCODE2]           NVARCHAR (50) NOT NULL,
    [ADDR2]               NVARCHAR (60) NOT NULL,
    [PROVINCE]            NVARCHAR (50) NOT NULL,
    [BORN_ADDR]           NVARCHAR (50) NOT NULL,
    [CONT_MAN]            NVARCHAR (50) NOT NULL,
    [CONT_REL1]           NVARCHAR (50) NOT NULL,
    [CONT_TEL]            NVARCHAR (50) NOT NULL,
    [CONT_GSM]            NVARCHAR (50) NOT NULL,
    [CONT_MAN2]           NVARCHAR (50) NOT NULL,
    [CONT_REL2]           NVARCHAR (50) NOT NULL,
    [CONT_TEL2]           NVARCHAR (50) NOT NULL,
    [CONT_GSM2]           NVARCHAR (50) NOT NULL,
    [GSM_Old]             NVARCHAR (50) NOT NULL,
    [EMAIL_Old]           NVARCHAR (60) NOT NULL,
    [TEL1_Old]            NVARCHAR (50) NOT NULL,
    [TEL2_Old]            NVARCHAR (50) NOT NULL,
    [POSTCODE1_Old]       NVARCHAR (50) NOT NULL,
    [ADDR1_Old]           NVARCHAR (60) NOT NULL,
    [POSTCODE2_Old]       NVARCHAR (50) NOT NULL,
    [ADDR2_Old]           NVARCHAR (60) NOT NULL,
    [PROVINCE_Old]        NVARCHAR (50) NOT NULL,
    [BORN_ADDR_Old]       NVARCHAR (50) NOT NULL,
    [CONT_MAN_Old]        NVARCHAR (50) NOT NULL,
    [CONT_REL1_Old]       NVARCHAR (50) NOT NULL,
    [CONT_TEL_Old]        NVARCHAR (50) NOT NULL,
    [CONT_GSM_Old]        NVARCHAR (50) NOT NULL,
    [CONT_MAN2_Old]       NCHAR (10)    NOT NULL,
    [CONT_REL2_Old]       NVARCHAR (50) NOT NULL,
    [CONT_TEL2_Old]       NVARCHAR (50) NOT NULL,
    [CONT_GSM2_Old]       NVARCHAR (50) NOT NULL,
    [GSM_IsChanged]       BIT           CONSTRAINT [DF_ApplyUpdateBase_GSM_IsChanged] DEFAULT ((0)) NOT NULL,
    [EMAIL_IsChanged]     BIT           CONSTRAINT [DF_ApplyUpdateBase_EMAIL_IsChanged] DEFAULT ((0)) NOT NULL,
    [TEL1_IsChanged]      BIT           CONSTRAINT [DF_ApplyUpdateBase_TEL1_IsChanged] DEFAULT ((0)) NOT NULL,
    [TEL2_IsChanged]      BIT           CONSTRAINT [DF_ApplyUpdateBase_TEL2_IsChanged] DEFAULT ((0)) NOT NULL,
    [POSTCODE1_IsChanged] BIT           CONSTRAINT [DF_ApplyUpdateBase_POSTCODE1_IsChanged] DEFAULT ((0)) NOT NULL,
    [ADDR1_IsChanged]     BIT           CONSTRAINT [DF_ApplyUpdateBase_ADDR1_IsChanged] DEFAULT ((0)) NOT NULL,
    [POSTCODE2_IsChanged] BIT           CONSTRAINT [DF_ApplyUpdateBase_POSTCODE2_IsChanged] DEFAULT ((0)) NOT NULL,
    [ADDR2_IsChanged]     BIT           CONSTRAINT [DF_ApplyUpdateBase_ADDR2_IsChanged] DEFAULT ((0)) NOT NULL,
    [PROVINCE_IsChanged]  BIT           CONSTRAINT [DF_ApplyUpdateBase_PROVINCE_IsChanged] DEFAULT ((0)) NOT NULL,
    [BORN_ADDR_IsChanged] BIT           CONSTRAINT [DF_ApplyUpdateBase_BORN_ADDR_IsChanged] DEFAULT ((0)) NOT NULL,
    [CONT_MAN_IsChanged]  BIT           CONSTRAINT [DF_ApplyUpdateBase_CONT_MAN_IsChanged] DEFAULT ((0)) NOT NULL,
    [CONT_REL1_IsChanged] BIT           CONSTRAINT [DF_ApplyUpdateBase_CONT_REL1_IsChanged] DEFAULT ((0)) NOT NULL,
    [CONT_TEL_IsChanged]  BIT           CONSTRAINT [DF_ApplyUpdateBase_CONT_TEL_IsChanged] DEFAULT ((0)) NOT NULL,
    [CONT_GSM_IsChanged]  BIT           CONSTRAINT [DF_ApplyUpdateBase_CONT_GSM_IsChanged] DEFAULT ((0)) NOT NULL,
    [CONT_MAN2_IsChanged] BIT           CONSTRAINT [DF_ApplyUpdateBase_CONT_MAN2_IsChanged] DEFAULT ((0)) NOT NULL,
    [CONT_REL2_IsChanged] BIT           CONSTRAINT [DF_ApplyUpdateBase_CONT_REL2_IsChanged] DEFAULT ((0)) NOT NULL,
    [CONT_TEL2_IsChanged] BIT           CONSTRAINT [DF_ApplyUpdateBase_CONT_TEL2_IsChanged] DEFAULT ((0)) NOT NULL,
    [CONT_GSM2_IsChanged] BIT           CONSTRAINT [DF_ApplyUpdateBase_CONT_GSM2_IsChanged] DEFAULT ((0)) NOT NULL,
    [SUBTEL]              NVARCHAR (50) NULL,
    [SUBTEL_Old]          NVARCHAR (50) NULL,
    [SUBTEL_IsChanged]    BIT           CONSTRAINT [DF_ApplyUpdateBase_SUBTEL_IsChanged] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_ApplyUpdateBase] PRIMARY KEY CLUSTERED ([Pk] ASC)
);

