CREATE TABLE [dbo].[APPRAMT] (
    [DEPTM]    NVARCHAR (50)   NOT NULL,
    [NOBR]     NVARCHAR (50)   NOT NULL,
    [YYMM]     NVARCHAR (50)   NOT NULL,
    [SER]      NVARCHAR (50)   NOT NULL,
    [ITEMCD]   NVARCHAR (50)   NOT NULL,
    [VV]       DECIMAL (16, 2) CONSTRAINT [DF_APPRAMT_VV] DEFAULT ((0)) NOT NULL,
    [V1]       DECIMAL (16, 2) NOT NULL,
    [V2]       DECIMAL (16, 2) NOT NULL,
    [RATE]     DECIMAL (16, 2) NOT NULL,
    [AMT]      DECIMAL (16, 2) NOT NULL,
    [AMT1]     DECIMAL (16, 2) CONSTRAINT [DF_APPRAMT_AMT1] DEFAULT ((0)) NOT NULL,
    [DAMT]     DECIMAL (16, 2) CONSTRAINT [DF_APPRAMT_DAMT] DEFAULT ((0)) NOT NULL,
    [KEY_DATE] DATETIME        CONSTRAINT [DF_APPRAMT_KEY_DATE] DEFAULT (getdate()) NOT NULL,
    [KEY_MAN]  NVARCHAR (50)   CONSTRAINT [DF_APPRAMT_KEY_MAN] DEFAULT ('') NOT NULL,
    [DI]       NVARCHAR (50)   CONSTRAINT [DF_APPRAMT_DI] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_APPRAMT] PRIMARY KEY CLUSTERED ([NOBR] ASC)
);

