CREATE TABLE [dbo].[APPRL] (
    [YEARB]    NVARCHAR (50)   NOT NULL,
    [YEARE]    NVARCHAR (50)   NOT NULL,
    [APPR]     DECIMAL (16, 2) NOT NULL,
    [KEY_DATE] DATETIME        NOT NULL,
    [KEY_MAN]  NVARCHAR (50)   NOT NULL,
    CONSTRAINT [PK_APPRL] PRIMARY KEY CLUSTERED ([YEARB] ASC, [YEARE] ASC)
);

