CREATE TABLE [dbo].[APPRA] (
    [NOBR]     NVARCHAR (50)   NOT NULL,
    [YYMM]     NVARCHAR (50)   NOT NULL,
    [SER]      NVARCHAR (50)   NOT NULL,
    [APGRPCD]  NVARCHAR (50)   NOT NULL,
    [APTYPE]   NVARCHAR (50)   NOT NULL,
    [KEY_DATE] DATETIME        NOT NULL,
    [KEY_MAN]  NVARCHAR (50)   NOT NULL,
    [NOTE]     NVARCHAR (200)  NOT NULL,
    [VT]       DECIMAL (16, 2) CONSTRAINT [DF_APPRA_VT] DEFAULT ((0)) NOT NULL,
    [VP]       NVARCHAR (50)   CONSTRAINT [DF_APPRA_VP] DEFAULT ('') NOT NULL,
    [VR]       NVARCHAR (50)   CONSTRAINT [DF_APPRA_VR] DEFAULT ('') NOT NULL,
    [VN]       DECIMAL (16, 2) CONSTRAINT [DF_APPRA_VN] DEFAULT ((0)) NOT NULL,
    [RATE]     DECIMAL (16, 2) CONSTRAINT [DF_APPRA_RATE] DEFAULT ((0)) NOT NULL,
    [ABS]      DECIMAL (16, 2) CONSTRAINT [DF_APPRA_ABS] DEFAULT ((0)) NOT NULL,
    [AP]       DECIMAL (16, 2) CONSTRAINT [DF_APPRA_AP] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_APPRA] PRIMARY KEY CLUSTERED ([NOBR] ASC, [YYMM] ASC, [SER] ASC)
);

