CREATE TABLE [dbo].[APPRAS] (
    [NOBR]   NVARCHAR (50)   NOT NULL,
    [YYMM]   NVARCHAR (50)   NOT NULL,
    [SER]    NVARCHAR (50)   NOT NULL,
    [ITEMCD] NVARCHAR (50)   NOT NULL,
    [V1]     DECIMAL (16, 2) NOT NULL,
    [V2]     DECIMAL (16, 2) NOT NULL,
    [NOTE]   NVARCHAR (200)  NOT NULL,
    [V3]     DECIMAL (16, 2) CONSTRAINT [DF_APPRAS_V3] DEFAULT ((0)) NOT NULL,
    [R1]     DECIMAL (16, 2) CONSTRAINT [DF_APPRAS_R1] DEFAULT ((0)) NOT NULL,
    [R2]     DECIMAL (16, 2) CONSTRAINT [DF_APPRAS_R2] DEFAULT ((0)) NOT NULL,
    [R3]     DECIMAL (16, 2) CONSTRAINT [DF_APPRAS_R3] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_APPRAS] PRIMARY KEY CLUSTERED ([NOBR] ASC)
);

