CREATE TABLE [dbo].[APPTYPE] (
    [TYEMCD]   NVARCHAR (50) NOT NULL,
    [TYEMNAME] NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_APPTYPE] PRIMARY KEY CLUSTERED ([TYEMCD] ASC)
);

