CREATE TABLE [dbo].[APPYEAR] (
    [NOBR]     NVARCHAR (50)   NOT NULL,
    [YYMM]     NVARCHAR (50)   NOT NULL,
    [FV1]      DECIMAL (16, 2) NOT NULL,
    [FV2]      DECIMAL (16, 2) NOT NULL,
    [FVT]      DECIMAL (16, 2) NOT NULL,
    [LV1]      DECIMAL (16, 2) NOT NULL,
    [LV2]      DECIMAL (16, 2) NOT NULL,
    [LVT]      DECIMAL (16, 2) NOT NULL,
    [TOT]      DECIMAL (16, 2) NOT NULL,
    [NOTE]     NVARCHAR (60)   NOT NULL,
    [KEY_MAN]  NVARCHAR (50)   NOT NULL,
    [KEY_DATE] DATETIME        NOT NULL,
    [EFV1]     DECIMAL (16, 2) CONSTRAINT [DF_APPYEAR_EFV1] DEFAULT ((0)) NOT NULL,
    [EFV2]     DECIMAL (16, 2) CONSTRAINT [DF_APPYEAR_EFV2] DEFAULT ((0)) NOT NULL,
    [EFVT]     DECIMAL (16, 2) CONSTRAINT [DF_APPYEAR_EFVT] DEFAULT ((0)) NOT NULL,
    [ELV1]     DECIMAL (16, 2) CONSTRAINT [DF_APPYEAR_ELV1] DEFAULT ((0)) NOT NULL,
    [ELV2]     DECIMAL (16, 2) CONSTRAINT [DF_APPYEAR_ELV2] DEFAULT ((0)) NOT NULL,
    [ELVT]     DECIMAL (16, 2) CONSTRAINT [DF_APPYEAR_ELVT] DEFAULT ((0)) NOT NULL,
    [ETOT]     DECIMAL (16, 2) CONSTRAINT [DF_APPYEAR_ETOT] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_APPYEAR] PRIMARY KEY CLUSTERED ([NOBR] ASC)
);

