CREATE TABLE [dbo].[APVALCD] (
    [VALCD]    NVARCHAR (50) NOT NULL,
    [V1]       NVARCHAR (50) NOT NULL,
    [V2]       NVARCHAR (50) NOT NULL,
    [V3]       NVARCHAR (50) NOT NULL,
    [V4]       NVARCHAR (50) NOT NULL,
    [V5]       NVARCHAR (50) NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL,
    CONSTRAINT [PK_APVALCD] PRIMARY KEY CLUSTERED ([VALCD] ASC)
);

