CREATE TABLE [dbo].[ATTCARD] (
    [NOBR]     NVARCHAR (50)   NOT NULL,
    [ADATE]    DATETIME        NOT NULL,
    [T1]       NVARCHAR (50)   NOT NULL,
    [T2]       NVARCHAR (50)   NOT NULL,
    [CODE]     NVARCHAR (50)   NOT NULL,
    [SER]      DECIMAL (16, 2) NOT NULL,
    [KEY_MAN]  NVARCHAR (50)   NOT NULL,
    [KEY_DATE] DATETIME        NOT NULL,
    [DD1]      NVARCHAR (50)   CONSTRAINT [DF_ATTCARD_DD1] DEFAULT ('') NOT NULL,
    [DD2]      NVARCHAR (50)   CONSTRAINT [DF_ATTCARD_DD2] DEFAULT ('') NOT NULL,
    [LOST1]    BIT             CONSTRAINT [DF_ATTCARD_LOST1] DEFAULT ((0)) NOT NULL,
    [LOST2]    BIT             CONSTRAINT [DF_ATTCARD_LOST2] DEFAULT ((0)) NOT NULL,
    [TT1]      NVARCHAR (50)   CONSTRAINT [DF_ATTCARD_TT1] DEFAULT ('') NOT NULL,
    [TT2]      NVARCHAR (50)   CONSTRAINT [DF_ATTCARD_TT2] DEFAULT ('') NOT NULL,
    [NOMODY]   BIT             CONSTRAINT [DF_ATTCARD_NOMODY] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_ATTCARD_1] PRIMARY KEY CLUSTERED ([NOBR] ASC, [ADATE] ASC, [T1] ASC)
);

