CREATE TABLE [dbo].[ATTEND] (
    [NOBR]       NVARCHAR (50)   NOT NULL,
    [ADATE]      DATETIME        NOT NULL,
    [ROTE]       NVARCHAR (50)   NOT NULL,
    [KEY_MAN]    NVARCHAR (50)   NOT NULL,
    [KEY_DATE]   DATETIME        NOT NULL,
    [LATE_MINS]  DECIMAL (16, 2) NOT NULL,
    [E_MINS]     DECIMAL (16, 2) NOT NULL,
    [ABS]        BIT             NOT NULL,
    [ADJ_CODE]   NVARCHAR (50)   NOT NULL,
    [CANT_ADJ]   BIT             NOT NULL,
    [SER]        DECIMAL (16, 2) NOT NULL,
    [NIGHT_HRS]  DECIMAL (16, 2) NOT NULL,
    [FOODAMT]    DECIMAL (16, 2) NOT NULL,
    [FOODSALCD]  NVARCHAR (50)   NOT NULL,
    [FORGET]     DECIMAL (16, 2) CONSTRAINT [DF_ATTEND_FORGET] DEFAULT ((0)) NOT NULL,
    [ATT_HRS]    DECIMAL (16, 2) CONSTRAINT [DF_ATTEND_ATT_HRS] DEFAULT ((0)) NOT NULL,
    [NIGAMT]     DECIMAL (16, 2) CONSTRAINT [DF_ATTEND_NIGAMT] DEFAULT ((0)) NOT NULL,
    [SPECAMT]    DECIMAL (16, 2) NULL,
    [SPECSALCD]  NVARCHAR (50)   NULL,
    [STATIONAMT] DECIMAL (16, 2) NULL,
    [EARLY_MINS] INT             NULL,
    [DELAY_MINS] INT             NULL,
    [REL_HRS]    DECIMAL (16, 2) NULL,
    [ROTE_H]     NVARCHAR (50)   CONSTRAINT [DF_ATTEND_ROTE_H] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_ATTEND] PRIMARY KEY CLUSTERED ([NOBR] ASC, [ADATE] ASC)
);



