CREATE TABLE [dbo].[attend_tmp] (
    [NOBR]      NVARCHAR (50)   NOT NULL,
    [ADATE]     DATETIME        NOT NULL,
    [ROTE]      NVARCHAR (50)   NOT NULL,
    [KEY_MAN]   NVARCHAR (50)   NOT NULL,
    [KEY_DATE]  DATETIME        NOT NULL,
    [LATE_MINS] DECIMAL (16, 2) NOT NULL,
    [E_MINS]    DECIMAL (16, 2) NOT NULL,
    [ABS]       BIT             NOT NULL,
    [ADJ_CODE]  NVARCHAR (50)   NOT NULL,
    [CANT_ADJ]  BIT             NOT NULL,
    [SER]       DECIMAL (16, 2) NOT NULL,
    [NIGHT_HRS] DECIMAL (16, 2) NOT NULL,
    [FOODAMT]   DECIMAL (16, 2) NOT NULL,
    [FOODSALCD] NVARCHAR (50)   NOT NULL,
    [FORGET]    DECIMAL (16, 2) NOT NULL,
    [ATT_HRS]   DECIMAL (16, 2) NOT NULL,
    [NIGAMT]    DECIMAL (16, 2) NOT NULL
);

