CREATE TABLE [dbo].[ATTEND_ABNORMAL_CHECK] (
    [ID]          INT            IDENTITY (1, 1) NOT NULL,
    [NOBR]        NVARCHAR (50)  NOT NULL,
    [ADATE]       DATETIME       NOT NULL,
    [TYPE]        NVARCHAR (50)  NOT NULL,
    [REMARK_TYPE] NVARCHAR (50)  NOT NULL,
    [REMARK]      NVARCHAR (MAX) NULL,
    [SERNO]       NVARCHAR (50)  NULL,
    [CREATE_DATE] DATETIME       NOT NULL,
    [CREATE_MAN]  NVARCHAR (50)  NOT NULL,
    [UPDATE_DATE] DATETIME       NOT NULL,
    [UPDATE_MAN]  NVARCHAR (50)  NOT NULL,
    CONSTRAINT [PK_ATTEND_ABNORMAL_CHECK] PRIMARY KEY CLUSTERED ([ID] ASC)
);

