CREATE TABLE [dbo].[ATTYEAR] (
    [NOBR]     NVARCHAR (50)   NOT NULL,
    [YYMM]     NVARCHAR (50)   NOT NULL,
    [ATTNO]    DECIMAL (16, 2) CONSTRAINT [DF_ATTYEAR_ATTNO] DEFAULT ((0)) NOT NULL,
    [KEY_MAN]  NVARCHAR (50)   NOT NULL,
    [KEY_DATE] DATETIME        NOT NULL,
    CONSTRAINT [PK_ATTYEAR] PRIMARY KEY CLUSTERED ([NOBR] ASC)
);

