CREATE TABLE [dbo].[AWARDCD] (
    [AWARD_CODE]      NVARCHAR (50) NOT NULL,
    [DESCR]           NVARCHAR (50) NOT NULL,
    [KEY_MAN]         NVARCHAR (50) NOT NULL,
    [KEY_DATE]        DATETIME      NOT NULL,
    [AWARD_CODE_DISP] NVARCHAR (50) NULL,
    CONSTRAINT [PK_AWARDCD] PRIMARY KEY CLUSTERED ([AWARD_CODE] ASC)
);

