CREATE TABLE [dbo].[AWARD] (
    [NOBR]       NVARCHAR (50)   NOT NULL,
    [ADATE]      DATETIME        NOT NULL,
    [AWARD_CODE] NVARCHAR (50)   NOT NULL,
    [AWARD1]     DECIMAL (16, 2) NOT NULL,
    [AWARD2]     DECIMAL (16, 2) NOT NULL,
    [AWARD3]     DECIMAL (16, 2) NOT NULL,
    [AWARD4]     DECIMAL (16, 2) NOT NULL,
    [AWARD5]     BIT             NOT NULL,
    [AWARD6]     DECIMAL (16, 2) CONSTRAINT [DF_AWARD_AWARD6] DEFAULT ((0)) NOT NULL,
    [FAULT1]     DECIMAL (16, 2) NOT NULL,
    [FAULT2]     DECIMAL (16, 2) NOT NULL,
    [FAULT3]     DECIMAL (16, 2) NOT NULL,
    [KEY_MAN]    NVARCHAR (50)   NOT NULL,
    [KEY_DATE]   DATETIME        NOT NULL,
    [NOTE]       NVARCHAR (200)  NOT NULL,
    [FAULT5]     DECIMAL (16, 2) CONSTRAINT [DF_AWARD_FAULT41] DEFAULT ((0)) NOT NULL,
    [FAULT4]     DECIMAL (16, 2) CONSTRAINT [DF_AWARD_FAULT4] DEFAULT ((0)) NOT NULL,
    [YYMM]       NVARCHAR (50)   CONSTRAINT [DF_AWARD_YYMM] DEFAULT ('') NOT NULL,
    [up1_name]   NVARCHAR (50)   NULL,
    [up1_file]   IMAGE           NULL,
    [up2_name]   NVARCHAR (50)   NULL,
    [up2_file]   IMAGE           NULL,
    [up3_name]   NVARCHAR (50)   NULL,
    [up3_file]   IMAGE           NULL,
    [up4_name]   NVARCHAR (50)   NULL,
    [up4_file]   IMAGE           NULL,
    [up5_name]   NVARCHAR (50)   NULL,
    [up5_file]   IMAGE           NULL,
    [AW_CHK]     BIT             NULL,
    [AW_CHK1]    BIT             NULL,
    [AW_CHK2]    BIT             NULL,
    [AW_CHK3]    BIT             NULL,
    CONSTRAINT [PK_AWARD] PRIMARY KEY CLUSTERED ([NOBR] ASC, [ADATE] ASC)
);

