CREATE TABLE [dbo].[BASE] (
    [NOBR]              NVARCHAR (50)   NOT NULL,
    [NAME_C]            NVARCHAR (50)   CONSTRAINT [DF_BASE_NAME_C] DEFAULT ('') NOT NULL,
    [NAME_E]            NVARCHAR (50)   CONSTRAINT [DF_BASE_NAME_E] DEFAULT ((0)) NOT NULL,
    [NAME_P]            NVARCHAR (50)   CONSTRAINT [DF_BASE_NAME_P] DEFAULT ((0)) NOT NULL,
    [SEX]               NVARCHAR (50)   CONSTRAINT [DF_BASE_SEX] DEFAULT ((0)) NOT NULL,
    [BIRDT]             SMALLDATETIME   NULL,
    [ADDR1]             NVARCHAR (60)   CONSTRAINT [DF_BASE_ADDR1] DEFAULT ('') NOT NULL,
    [ADDR2]             NVARCHAR (60)   CONSTRAINT [DF_BASE_ADDR2] DEFAULT ('') NOT NULL,
    [TEL1]              NVARCHAR (50)   CONSTRAINT [DF_BASE_TEL1] DEFAULT ('') NOT NULL,
    [TEL2]              NVARCHAR (50)   CONSTRAINT [DF_BASE_TEL2] DEFAULT ('') NOT NULL,
    [BBCALL]            NVARCHAR (50)   CONSTRAINT [DF_BASE_BBCALL] DEFAULT ('') NOT NULL,
    [EMAIL]             NVARCHAR (60)   CONSTRAINT [DF_BASE_EMAIL] DEFAULT ('') NOT NULL,
    [GSM]               NVARCHAR (50)   CONSTRAINT [DF_BASE_GSM] DEFAULT ('') NOT NULL,
    [IDNO]              NVARCHAR (50)   CONSTRAINT [DF_BASE_IDNO] DEFAULT ('') NOT NULL,
    [CONT_MAN]          NVARCHAR (50)   CONSTRAINT [DF_BASE_CONT_MAN] DEFAULT ('') NOT NULL,
    [CONT_TEL]          NVARCHAR (50)   CONSTRAINT [DF_BASE_CONT_TEL] DEFAULT ('') NOT NULL,
    [CONT_GSM]          NVARCHAR (50)   CONSTRAINT [DF_BASE_CONT_GSM] DEFAULT ('') NOT NULL,
    [CONT_MAN2]         NVARCHAR (50)   CONSTRAINT [DF_BASE_CONT_MAN2] DEFAULT ('') NOT NULL,
    [CONT_TEL2]         NVARCHAR (50)   NOT NULL,
    [CONT_GSM2]         NVARCHAR (50)   CONSTRAINT [DF_BASE_CONT_GSM2] DEFAULT ('') NOT NULL,
    [BLOOD]             NVARCHAR (50)   CONSTRAINT [DF_BASE_BLOOD] DEFAULT ('') NOT NULL,
    [PASSWORD]          NVARCHAR (50)   CONSTRAINT [DF_BASE_PASSWORD] DEFAULT ('') NOT NULL,
    [POSTCODE1]         NVARCHAR (50)   CONSTRAINT [DF_BASE_POSTCODE1] DEFAULT ('') NOT NULL,
    [POSTCODE2]         NVARCHAR (50)   CONSTRAINT [DF_BASE_POSTCODE2] DEFAULT ('') NOT NULL,
    [BANK_CODE]         NVARCHAR (50)   CONSTRAINT [DF_BASE_BANK_CODE] DEFAULT ('') NOT NULL,
    [BANKNO]            NVARCHAR (50)   CONSTRAINT [DF_BASE_BANKNO] DEFAULT ('') NOT NULL,
    [ACCOUNT_NO]        NVARCHAR (50)   CONSTRAINT [DF_BASE_ACCOUNT_NO] DEFAULT ('') NOT NULL,
    [ACCOUNT_NA]        NVARCHAR (50)   CONSTRAINT [DF_BASE_ACCOUNT_NA] DEFAULT ('') NOT NULL,
    [MARRY]             NVARCHAR (50)   CONSTRAINT [DF_BASE_MARRY] DEFAULT (N'''') NOT NULL,
    [COUNTRY]           NVARCHAR (50)   NOT NULL,
    [COUNT_MA]          BIT             NOT NULL,
    [ARMY]              NVARCHAR (50)   CONSTRAINT [DF_BASE_ARMY] DEFAULT ('') NOT NULL,
    [PRO_MAN1]          NVARCHAR (50)   CONSTRAINT [DF_BASE_PRO_MAN1] DEFAULT ('') NOT NULL,
    [PRO_ADDR1]         NVARCHAR (50)   CONSTRAINT [DF_BASE_PRO_ADDR1] DEFAULT ('') NOT NULL,
    [PRO_ID1]           NVARCHAR (50)   CONSTRAINT [DF_BASE_PRO_ID1] DEFAULT ('') NOT NULL,
    [PRO_TEL1]          NVARCHAR (50)   CONSTRAINT [DF_BASE_PRO_TEL1] DEFAULT ('') NOT NULL,
    [PRO_MAN2]          NVARCHAR (50)   CONSTRAINT [DF_BASE_PRO_MAN2] DEFAULT ('') NOT NULL,
    [PRO_ADDR2]         NVARCHAR (60)   CONSTRAINT [DF_BASE_PRO_ADDR2] DEFAULT ('') NOT NULL,
    [PRO_ID2]           NVARCHAR (50)   CONSTRAINT [DF_BASE_PRO_ID2] DEFAULT ('') NOT NULL,
    [PRO_TEL2]          NVARCHAR (50)   CONSTRAINT [DF_BASE_PRO_TEL2] DEFAULT ('') NOT NULL,
    [ARMY_TYPE]         NVARCHAR (50)   CONSTRAINT [DF_BASE_ARMY_TYPE] DEFAULT ('') NOT NULL,
    [N_NOBR]            NVARCHAR (50)   CONSTRAINT [DF_BASE_N_NOBR] DEFAULT ('') NOT NULL,
    [NOBR_B]            NVARCHAR (50)   CONSTRAINT [DF_BASE_NOBR_B] DEFAULT ('') NOT NULL,
    [PROVINCE]          NVARCHAR (50)   CONSTRAINT [DF_BASE_PROVINCE] DEFAULT ('') NOT NULL,
    [BORN_ADDR]         NVARCHAR (50)   CONSTRAINT [DF_BASE_BORN_ADDR] DEFAULT ('') NOT NULL,
    [TAXCNT]            DECIMAL (16, 2) CONSTRAINT [DF_BASE_TAXCNT] DEFAULT ((0)) NOT NULL,
    [KEY_MAN]           NVARCHAR (50)   CONSTRAINT [DF_BASE_KEY_MAN] DEFAULT ('') NOT NULL,
    [KEY_DATE]          DATETIME        CONSTRAINT [DF_BASE_KEY_DATE] DEFAULT (getdate()) NOT NULL,
    [ID_TYPE]           NVARCHAR (50)   NOT NULL,
    [TAXNO]             NVARCHAR (50)   CONSTRAINT [DF_BASE_TAXNO] DEFAULT ('') NOT NULL,
    [PRETAX]            DECIMAL (16, 2) CONSTRAINT [DF_BASE_PRETAX] DEFAULT ((0)) NOT NULL,
    [CONT_REL1]         NVARCHAR (50)   CONSTRAINT [DF_BASE_CONT_REL1] DEFAULT ('') NOT NULL,
    [CONT_REL2]         NVARCHAR (50)   CONSTRAINT [DF_BASE_CONT_REL2] DEFAULT ('') NOT NULL,
    [ACCOUNT_MA]        NVARCHAR (50)   CONSTRAINT [DF_BASE_ACCOUNT_MA] DEFAULT ('') NOT NULL,
    [MATNO]             NVARCHAR (50)   CONSTRAINT [DF_BASE_MATNO] DEFAULT ('') NOT NULL,
    [SUBTEL]            NVARCHAR (50)   CONSTRAINT [DF_BASE_SUBTEL] DEFAULT ('') NOT NULL,
    [PHOTO]             IMAGE           NULL,
    [up1_name]          NVARCHAR (50)   NULL,
    [up1_file]          IMAGE           NULL,
    [up2_name]          NVARCHAR (50)   NULL,
    [up2_file]          IMAGE           NULL,
    [up3_name]          NVARCHAR (50)   NULL,
    [up3_file]          IMAGE           NULL,
    [up4_name]          NVARCHAR (50)   NULL,
    [up4_file]          IMAGE           NULL,
    [up5_name]          NVARCHAR (50)   NULL,
    [up5_file]          IMAGE           NULL,
    [BASECD]            NVARCHAR (50)   NULL,
    [NAME_AD]           NVARCHAR (50)   NULL,
    [CandidateWays]     NVARCHAR (50)   NULL,
    [AdditionDate]      DATETIME        NULL,
    [AdditionNO]        NVARCHAR (50)   NULL,
    [AdmitDate]         DATETIME        NULL,
    [IntroductionBonus] BIT             NULL,
    [Introductor]       NVARCHAR (50)   NULL,
    [Aboriginal]        BIT             NULL,
    [Disability]        BIT             NULL,
    [Gift]              NVARCHAR (50)   NULL,
    CONSTRAINT [PK_BASE] PRIMARY KEY CLUSTERED ([NOBR] ASC)
);




GO
create trigger [dbo].[BASE_Log_Trigger] 
on [dbo].[BASE]
after insert,update,delete
as
begin try
declare @Source nvarchar(50)
set @Source='BASE'
declare @InsertedXml xml
declare @DeletedXml xml
if(exists(select 1 from inserted))--Add
set @InsertedXml=(select NOBR,NAME_C,NAME_E,NAME_P,SEX,BIRDT,ADDR1,ADDR2,TEL1,TEL2,BBCALL,EMAIL,GSM,IDNO,CONT_MAN,
CONT_TEL,CONT_GSM,CONT_MAN2,CONT_TEL2,CONT_GSM2,BLOOD,PASSWORD,POSTCODE1,POSTCODE2,BANK_CODE,BANKNO,ACCOUNT_NO,
ACCOUNT_NA,MARRY,COUNTRY,COUNT_MA,ARMY,PRO_MAN1,PRO_ADDR1,PRO_ID1,PRO_TEL1,PRO_MAN2,PRO_ADDR2,PRO_ID2,PRO_TEL2,
ARMY_TYPE,N_NOBR,NOBR_B,PROVINCE,BORN_ADDR,TAXCNT,KEY_MAN,KEY_DATE,ID_TYPE,TAXNO,PRETAX,CONT_REL1,CONT_REL2,ACCOUNT_MA,
MATNO,SUBTEL,up1_name,up2_name,up3_name,up4_name,up5_name,BASECD,NAME_AD,CandidateWays,AdditionDate,AdditionNO,AdmitDate,
IntroductionBonus,Introductor,Aboriginal,Disability,Gift
from inserted for xml raw)
if(exists(select 1 from deleted))--Add
set @DeletedXml=(select NOBR,NAME_C,NAME_E,NAME_P,SEX,BIRDT,ADDR1,ADDR2,TEL1,TEL2,BBCALL,EMAIL,GSM,IDNO,CONT_MAN,
CONT_TEL,CONT_GSM,CONT_MAN2,CONT_TEL2,CONT_GSM2,BLOOD,PASSWORD,POSTCODE1,POSTCODE2,BANK_CODE,BANKNO,ACCOUNT_NO,
ACCOUNT_NA,MARRY,COUNTRY,COUNT_MA,ARMY,PRO_MAN1,PRO_ADDR1,PRO_ID1,PRO_TEL1,PRO_MAN2,PRO_ADDR2,PRO_ID2,PRO_TEL2,
ARMY_TYPE,N_NOBR,NOBR_B,PROVINCE,BORN_ADDR,TAXCNT,KEY_MAN,KEY_DATE,ID_TYPE,TAXNO,PRETAX,CONT_REL1,CONT_REL2,ACCOUNT_MA,
MATNO,SUBTEL,up1_name,up2_name,up3_name,up4_name,up5_name,BASECD,NAME_AD,CandidateWays,AdditionDate,AdditionNO,AdmitDate,
IntroductionBonus,Introductor,Aboriginal,Disability,Gift from deleted for xml raw)
insert into TraceLog select @Source,@InsertedXml,@DeletedXml,GETDATE()
end try
begin catch
print(ERROR_MESSAGE() )
end catch