CREATE TABLE [dbo].[BASECD] (
    [BASECD]     NVARCHAR (50) NOT NULL,
    [BASECDNAME] NVARCHAR (50) NULL,
    [KEY_MAN]    NVARCHAR (50) NULL,
    [KEY_DATE]   NVARCHAR (50) NULL,
    CONSTRAINT [PK_BASECD] PRIMARY KEY CLUSTERED ([BASECD] ASC)
);

