CREATE TABLE [dbo].[CALC_CONDITION] (
    [AUTO]      INT           IDENTITY (1, 1) NOT NULL,
    [SOURCE]    NVARCHAR (50) NOT NULL,
    [CODE]      NVARCHAR (50) NOT NULL,
    [COND_TYPE] NVARCHAR (50) NOT NULL,
    [CONDITION] NVARCHAR (50) NOT NULL,
    [VALUE1]    NVARCHAR (50) NOT NULL,
    [VALUE2]    NVARCHAR (50) NOT NULL,
    [KEY_DATE]  DATETIME      NOT NULL,
    [KEY_MAN]   NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_CALC_CONDITION] PRIMARY KEY CLUSTERED ([AUTO] ASC)
);

