CREATE TABLE [dbo].[CANDIDATES_WAYS] (
    [Code]     NVARCHAR (50) NOT NULL,
    [WayName]  NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_CANDIDATES_WAYS] PRIMARY KEY CLUSTERED ([Code] ASC)
);

