CREATE TABLE [dbo].[CARCD] (
    [CARCD]    NVARCHAR (50) NOT NULL,
    [CARNAME]  NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_CARCD] PRIMARY KEY CLUSTERED ([CARCD] ASC)
);

