CREATE TABLE [dbo].[CARDTMP] (
    [CARDNO]   NVARCHAR (50) NOT NULL,
    [CARDNO1]  NVARCHAR (50) NOT NULL,
    [SER]      NVARCHAR (50) NOT NULL,
    [ADATE]    DATETIME      NOT NULL,
    [ONTIME]   NVARCHAR (50) NOT NULL,
    [WARN]     NVARCHAR (80) NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL
);

