CREATE TABLE [dbo].[CARDAPP] (
    [NOBR]     NVARCHAR (50) NOT NULL,
    [CARDNO]   NVARCHAR (50) NOT NULL,
    [BDATE]    DATETIME      NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      CONSTRAINT [DF_CARDAPP_KEY_DATE] DEFAULT (getdate()) NOT NULL,
    [TEMPS]    BIT           NOT NULL,
    [EDATE]    DATETIME      NOT NULL,
    CONSTRAINT [PK_CARDAPP] PRIMARY KEY CLUSTERED ([NOBR] ASC, [CARDNO] ASC, [BDATE] ASC)
);

