CREATE TABLE [dbo].[CARDLOSD] (
    [CODE]     NVARCHAR (50) NOT NULL,
    [DESCR]    NVARCHAR (50) NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL,
    [ATT]      BIT           CONSTRAINT [DF_CARDLOSD_ATT] DEFAULT ((0)) NOT NULL,
    [SORT]     INT           NOT NULL,
    CONSTRAINT [PK_CARDLOSD] PRIMARY KEY CLUSTERED ([CODE] ASC)
);

