CREATE TABLE [dbo].[CARTIME] (
    [CARCD]    NVARCHAR (50) NOT NULL,
    [ADATE]    DATETIME      NOT NULL,
    [ONTIME]   NVARCHAR (50) NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL
);

