CREATE TABLE [dbo].[CERTIFI] (
    [NOBR]     NVARCHAR (50) NOT NULL,
    [COMP]     NVARCHAR (50) NOT NULL,
    [DESCR]    NVARCHAR (50) NOT NULL,
    [CONT]     NVARCHAR (80) NOT NULL,
    [EFF_DATE] DATETIME      NOT NULL,
    [LFF_DATE] DATETIME      NOT NULL,
    [PRIVATE]  BIT           NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL
);

