CREATE TABLE [dbo].[CHE_NOBR] (
    [OLD_NOBR] NVARCHAR (50) CONSTRAINT [DF_CHE_NOBR_OLD_NOBR] DEFAULT ('') NOT NULL,
    [NAME_C]   NVARCHAR (50) CONSTRAINT [DF_CHE_NOBR_NAME_C] DEFAULT ('') NOT NULL,
    [NEW_NOBR] NVARCHAR (50) CONSTRAINT [DF_CHE_NOBR_NEW_NOBR] DEFAULT ('') NOT NULL
);

