CREATE TABLE [dbo].[CODE_GROUP] (
    [CODEGROUP] NVARCHAR (50)  NOT NULL,
    [GROUPNAME] NVARCHAR (50)  NOT NULL,
    [NOTE]      NVARCHAR (500) NOT NULL,
    [KEY_DATE]  DATETIME       NOT NULL,
    [KEY_MAN]   NVARCHAR (50)  NOT NULL,
    CONSTRAINT [PK_CODE_GROUP] PRIMARY KEY CLUSTERED ([CODEGROUP] ASC)
);

