CREATE TABLE [dbo].[COMP_CODE_GROUP] (
    [COMP]        NVARCHAR (50)  NOT NULL,
    [CODEGROUP]   NVARCHAR (50)  NOT NULL,
    [NOTE]        NVARCHAR (500) NOT NULL,
    [KEY_DATE]    DATETIME       NOT NULL,
    [KEY_MAN]     NVARCHAR (50)  NOT NULL,
    [DefaultCode] BIT            CONSTRAINT [DF_COMP_CODE_GROUP_DefaultCode] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_COMP_CODE_GROUP] PRIMARY KEY CLUSTERED ([COMP] ASC, [CODEGROUP] ASC)
);

