CREATE TABLE [dbo].[COMP_DATAGROUP] (
    [COMP]      NVARCHAR (50)  NOT NULL,
    [DATAGROUP] NVARCHAR (50)  NOT NULL,
    [NOTE]      NVARCHAR (500) NOT NULL,
    [KEY_DATE]  DATETIME       NOT NULL,
    [KEY_MAN]   NVARCHAR (50)  NOT NULL,
    CONSTRAINT [PK_COMP_DATAGROUP] PRIMARY KEY CLUSTERED ([COMP] ASC, [DATAGROUP] ASC),
    CONSTRAINT [FK_COMP_DATAGROUP_COMP] FOREIGN KEY ([COMP]) REFERENCES [dbo].[COMP] ([COMP]),
    CONSTRAINT [FK_COMP_DATAGROUP_DATAGROUP] FOREIGN KEY ([DATAGROUP]) REFERENCES [dbo].[DATAGROUP] ([DATAGROUP])
);

