CREATE TABLE [dbo].[COST] (
    [NOBR]     NVARCHAR (50)   NOT NULL,
    [DEPTS]    NVARCHAR (50)   NOT NULL,
    [RATE]     DECIMAL (16, 2) NOT NULL,
    [KEY_DATE] DATETIME        NOT NULL,
    [KEY_MAN]  NVARCHAR (50)   NOT NULL,
    [CADATE]   DATETIME        CONSTRAINT [DF_COST_CADATE] DEFAULT (getdate()) NOT NULL,
    [CDDATE]   DATETIME        CONSTRAINT [DF_COST_CDDATE] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_cost] PRIMARY KEY CLUSTERED ([NOBR] ASC, [DEPTS] ASC, [CADATE] ASC)
);



