CREATE TABLE [dbo].[COUNTRY] (
    [NOBR]      NVARCHAR (50) NOT NULL,
    [NAME_C]    NVARCHAR (50) NOT NULL,
    [COUNTRY]   NVARCHAR (50) NOT NULL,
    [PROVINCE]  NVARCHAR (50) NOT NULL,
    [BORN_ADDR] NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_COUNTRY] PRIMARY KEY CLUSTERED ([NOBR] ASC)
);

