CREATE TABLE [dbo].[COUNTCD] (
    [CODE]     NVARCHAR (50) NOT NULL,
    [DESCR]    NVARCHAR (50) NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL,
    CONSTRAINT [PK_COUNTCD] PRIMARY KEY CLUSTERED ([CODE] ASC)
);

