CREATE TABLE [dbo].[DATA_PA] (
    [DATA_PASS] DATETIME      CONSTRAINT [DF_DATA_PA_DATA_PASS] DEFAULT (getdate()) NOT NULL,
    [SALADR]    NVARCHAR (50) CONSTRAINT [DF_DATA_PA_SALADR] DEFAULT ('') NOT NULL,
    [KEY_DATE]  DATETIME      CONSTRAINT [DF_DATA_PA_KEY_DATE] DEFAULT (getdate()) NULL
);

