CREATE TABLE [dbo].[DATA_PASS] (
    [DATA_PASS] DATETIME      CONSTRAINT [DF_DATA_PASS_DATA_PASS] DEFAULT (getdate()) NOT NULL,
    [SALADR]    NVARCHAR (50) CONSTRAINT [DF_DATA_PASS_SALADR] DEFAULT ('') NOT NULL,
    [KEY_DAT4E] DATETIME      CONSTRAINT [DF_DATA_PASS_KEY_DAT4E] DEFAULT (getdate()) NULL
);

