CREATE TABLE [dbo].[DEPTS] (
    [D_NO]      NVARCHAR (50) CONSTRAINT [DF_DEPTS_D_NO] DEFAULT ('') NOT NULL,
    [D_NAME]    NVARCHAR (50) CONSTRAINT [DF_DEPTS_D_NAME] DEFAULT ('') NOT NULL,
    [KEY_DATE]  DATETIME      CONSTRAINT [DF_DEPTS_KEY_DATE] DEFAULT (getdate()) NULL,
    [KEY_MAN]   NVARCHAR (50) CONSTRAINT [DF_DEPTS_KEY_MAN] DEFAULT ('') NULL,
    [DR_ACNO]   NVARCHAR (50) CONSTRAINT [DF_DEPTS_DR_ACNO] DEFAULT ('') NULL,
    [CR_ACNO]   NVARCHAR (50) CONSTRAINT [DF_DEPTS_CR_ACNO] DEFAULT ('') NULL,
    [ADATE]     DATETIME      CONSTRAINT [DF_DEPTS_ADATE] DEFAULT (getdate()) NULL,
    [DDATE]     DATETIME      CONSTRAINT [DF_DEPTS_DDATE] DEFAULT (getdate()) NULL,
    [OLD_DEPT]  NVARCHAR (50) CONSTRAINT [DF_DEPTS_OLD_DEPT] DEFAULT ('') NULL,
    [SUBS]      NVARCHAR (50) CONSTRAINT [DF_DEPTS_SUBS] DEFAULT ('') NULL,
    [D_NO_DISP] NVARCHAR (50) NULL,
    [I_CODE]    NVARCHAR (50) NULL,
    [D_CODE]    NVARCHAR (50) NULL,
    CONSTRAINT [PK_DEPTS] PRIMARY KEY CLUSTERED ([D_NO] ASC)
);

