CREATE TABLE [dbo].[DEPT] (
    [D_NO]       NVARCHAR (50)   CONSTRAINT [DF_DEPT_D_NO] DEFAULT ('') NOT NULL,
    [D_NAME]     NVARCHAR (50)   CONSTRAINT [DF_DEPT_D_NAME] DEFAULT ('') NOT NULL,
    [D_ENAME]    NVARCHAR (50)   CONSTRAINT [DF_DEPT_D_ENAME] DEFAULT ('') NOT NULL,
    [PNS]        DECIMAL (16, 2) CONSTRAINT [DF_DEPT_PNS] DEFAULT ((0)) NULL,
    [DEPT_TREE]  NVARCHAR (50)   CONSTRAINT [DF_DEPT_DEPT_TREE] DEFAULT ('') NULL,
    [KEY_DATE]   DATETIME        CONSTRAINT [DF_DEPT_KEY_DATE] DEFAULT (getdate()) NULL,
    [KEY_MAN]    NVARCHAR (50)   CONSTRAINT [DF_DEPT_KEY_MAN] DEFAULT ('') NULL,
    [OLD_DEPT]   NVARCHAR (50)   CONSTRAINT [DF_DEPT_OLD_DEPT] DEFAULT ('') NULL,
    [NEW_DEPT]   NVARCHAR (50)   CONSTRAINT [DF_DEPT_NEW_DEPT] DEFAULT ('') NULL,
    [ADATE]      DATETIME        CONSTRAINT [DF_DEPT_ADATE] DEFAULT (getdate()) NULL,
    [DDATE]      DATETIME        CONSTRAINT [DF_DEPT_DDATE] DEFAULT (getdate()) NULL,
    [DEPT_GROUP] NVARCHAR (50)   CONSTRAINT [DF_DEPT_DEPT_GROUP] DEFAULT ('') NULL,
    [NOBR]       NVARCHAR (50)   NULL,
    [AMT]        DECIMAL (16, 2) NULL,
    [EMAIL]      NVARCHAR (500)  NULL,
    [RES]        BIT             CONSTRAINT [DF_DEPT_RES] DEFAULT ((0)) NULL,
    [D_NO_DISP]  NVARCHAR (50)   NULL,
    CONSTRAINT [PK_DEPT] PRIMARY KEY CLUSTERED ([D_NO] ASC)
);

