CREATE TABLE [dbo].[DEPTA] (
    [D_NO]       NVARCHAR (50)  CONSTRAINT [DF_DEPTA_D_NO] DEFAULT ('') NOT NULL,
    [D_NAME]     NVARCHAR (50)  CONSTRAINT [DF_DEPTA_D_NAME] DEFAULT ('') NOT NULL,
    [D_ENAME]    NVARCHAR (50)  CONSTRAINT [DF_DEPTA_D_ENAME] DEFAULT ('') NOT NULL,
    [KEY_DATE]   DATETIME       CONSTRAINT [DF_DEPTA_KEY_DATE] DEFAULT (getdate()) NULL,
    [KEY_MAN]    NVARCHAR (50)  CONSTRAINT [DF_DEPTA_KEY_MAN] DEFAULT ('') NULL,
    [OLD_DEPT]   NVARCHAR (50)  CONSTRAINT [DF_DEPTA_OLD_DEPT] DEFAULT ('') NULL,
    [DEPT_GROUP] NVARCHAR (50)  CONSTRAINT [DF_DEPTA_DEPT_GROUP] DEFAULT ('') NULL,
    [DEPT_TREE]  NVARCHAR (50)  CONSTRAINT [DF_DEPTA_DEPT_TREE] DEFAULT ('') NULL,
    [NOBR]       NVARCHAR (50)  NULL,
    [EMAIL]      NVARCHAR (500) NULL,
    [MANGEMAIL]  NVARCHAR (50)  NULL,
    [ADATE]      DATETIME       NULL,
    [DDATE]      DATETIME       NULL,
    [D_NO_DISP]  NVARCHAR (50)  CONSTRAINT [DF_DEPTA_D_NO1] DEFAULT ('') NULL,
    [SIGN_GROUP] NVARCHAR (50)  NULL,
    [DEPT_CATE]  NVARCHAR (50)  NULL,
    CONSTRAINT [PK_DEPTA] PRIMARY KEY CLUSTERED ([D_NO] ASC)
);

