CREATE TABLE [dbo].[EFFEMPLOY] (
    [YYMM]     NVARCHAR (50)   NOT NULL,
    [NOBR]     NVARCHAR (50)   NOT NULL,
    [EFFSCORE] DECIMAL (16, 2) NOT NULL,
    [EFFLVL]   NVARCHAR (50)   NOT NULL,
    [IMPORT]   BIT             NOT NULL,
    [KEY_DATE] DATETIME        NOT NULL,
    [KEY_MAN]  NVARCHAR (50)   NOT NULL,
    [EFFTYPE]  NVARCHAR (50)   NULL,
    [AUTOKEY]  INT             IDENTITY (1, 1) NOT NULL,
    PRIMARY KEY CLUSTERED ([AUTOKEY] ASC)
);



