CREATE TABLE [dbo].[EFFECT] (
    [APCD]     NVARCHAR (50)   NOT NULL,
    [APCDNAME] NVARCHAR (50)   NOT NULL,
    [EFFB]     DECIMAL (16, 2) NOT NULL,
    [EFFE]     DECIMAL (16, 2) NOT NULL,
    [KEY_DATE] DATETIME        NOT NULL,
    [KEY_MAN]  NVARCHAR (50)   NOT NULL,
    CONSTRAINT [PK_EFFECT] PRIMARY KEY CLUSTERED ([APCD] ASC)
);

