CREATE TABLE [dbo].[EFFLVL] (
    [EFFLVL]      NVARCHAR (50)   NOT NULL,
    [EFFLVL_DISP] NVARCHAR (50)   NOT NULL,
    [EFFLVL_NAME] NVARCHAR (50)   NOT NULL,
    [EFFB]        DECIMAL (16, 2) NOT NULL,
    [EFFE]        DECIMAL (16, 2) NOT NULL,
    [KEY_DATE]    DATETIME        NOT NULL,
    [KEY_MAN]     NVARCHAR (50)   NOT NULL,
    PRIMARY KEY CLUSTERED ([EFFLVL] ASC)
);



