CREATE TABLE [dbo].[EFFS_Fun] (
    [auto_key]  INT            IDENTITY (1, 1) NOT NULL,
    [templetID] NVARCHAR (4)   NULL,
    [fun1]      BIT            NULL,
    [fun1_name] NVARCHAR (100) NULL,
    [fun2]      BIT            NULL,
    [fun2_name] NVARCHAR (100) NULL,
    [fun3]      BIT            NULL,
    [fun3_name] NVARCHAR (100) NULL,
    [fun4]      BIT            NULL,
    [fun4_name] NVARCHAR (100) NULL,
    [fun5]      BIT            NULL,
    [fun5_name] NVARCHAR (100) NULL,
    [fun6]      BIT            NULL,
    [fun6_name] NVARCHAR (100) NULL,
    [fun7]      BIT            NULL,
    [fun7_name] NVARCHAR (100) NULL,
    [fun8]      BIT            NULL,
    [fun8_name] NVARCHAR (100) NULL,
    [fun9]      BIT            NULL,
    [fun9_name] NVARCHAR (100) NULL,
    [selfcheck] BIT            NULL,
    [fun10]     BIT            NULL,
    [fun11]     BIT            NULL,
    [fun12]     BIT            NULL,
    [fun13]     BIT            NULL,
    [fun14]     BIT            NULL,
    [fun15]     BIT            NULL
);

