CREATE TABLE [dbo].[EFFTYPE] (
    [EFFTYPE]      NVARCHAR (50) NOT NULL,
    [EFFTYPE_DISP] NVARCHAR (50) NOT NULL,
    [EFFTYPE_NAME] NVARCHAR (50) NOT NULL,
    [KEY_DATE]     DATETIME      NOT NULL,
    [KEY_MAN]      NVARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([EFFTYPE] ASC)
);



