CREATE TABLE [dbo].[EMPCD] (
    [EMPCD]    NVARCHAR (50) NOT NULL,
    [EMPDESCR] NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    [NEMPCD]   NVARCHAR (50) NOT NULL,
    [EMPCD_B]  NVARCHAR (50) NOT NULL,
    [FORMAL]   BIT           CONSTRAINT [DF_EMPCD_FORMAL] DEFAULT ((0)) NOT NULL,
    [OLDEMPCD] NVARCHAR (50) CONSTRAINT [DF_EMPCD_OLDEMPCD] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_EMPCD] PRIMARY KEY CLUSTERED ([EMPCD] ASC)
);

