CREATE TABLE [dbo].[ENCODINGTABLE] (
    [AUTOKEY]  INT           IDENTITY (1, 1) NOT NULL,
    [CODEPAGE] INT           NOT NULL,
    [CODEDSP]  NVARCHAR (50) NOT NULL,
    [CODENAME] NVARCHAR (50) NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NULL,
    [KEY_DATE] DATETIME      NULL,
    CONSTRAINT [PK_ENCODINGTABLE] PRIMARY KEY CLUSTERED ([AUTOKEY] ASC)
);

