CREATE TABLE [dbo].[ERPCODE] (
    [ERP_CODE] NVARCHAR (50) NOT NULL,
    [ERP_NAME] NVARCHAR (50) NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL,
    CONSTRAINT [PK_ERPCODE] PRIMARY KEY CLUSTERED ([ERP_CODE] ASC)
);

