CREATE TABLE [dbo].[EXPCOMP] (
    [YYMM]     NVARCHAR (50)   CONSTRAINT [DF_EXPCOMP_YYMM] DEFAULT ('') NOT NULL,
    [S_NO]     NVARCHAR (50)   CONSTRAINT [DF_EXPCOMP_S_NO] DEFAULT ('') NOT NULL,
    [L_EMP]    DECIMAL (16, 2) NOT NULL,
    [L_EXP]    DECIMAL (16, 2) NOT NULL,
    [H_EMP]    DECIMAL (16, 2) NOT NULL,
    [H_EXP]    DECIMAL (16, 2) NOT NULL,
    [KEY_DATE] DATETIME        NOT NULL,
    [KEY_MAN]  NVARCHAR (50)   NOT NULL,
    CONSTRAINT [PK_EXPCOMP] PRIMARY KEY CLUSTERED ([YYMM] ASC, [S_NO] ASC, [L_EMP] ASC)
);

