CREATE TABLE [dbo].[EXPLAB] (
    [NOBR]       NVARCHAR (50)   NOT NULL,
    [FA_IDNO]    NVARCHAR (50)   NOT NULL,
    [YYMM]       NVARCHAR (50)   NOT NULL,
    [EXP]        DECIMAL (16, 2) NOT NULL,
    [COMP]       DECIMAL (16, 2) CONSTRAINT [DF_EXPLAB_COMP] DEFAULT ((0)) NOT NULL,
    [NOTEDIT]    BIT             NOT NULL,
    [KEY_DATE]   DATETIME        NOT NULL,
    [KEY_MAN]    NVARCHAR (50)   NOT NULL,
    [ADATE]      DATETIME        NOT NULL,
    [DAYS]       DECIMAL (16, 2) NOT NULL,
    [RATE_CODE]  NVARCHAR (50)   NOT NULL,
    [INSUR_TYPE] NVARCHAR (50)   NOT NULL,
    [INSCD]      DECIMAL (16, 2) NOT NULL,
    [SAL_CODE]   NVARCHAR (50)   NOT NULL,
    [JOBAMT]     DECIMAL (16, 2) CONSTRAINT [DF_EXPLAB_JOBAMT] DEFAULT ((0)) NOT NULL,
    [FUNDAMT]    DECIMAL (16, 2) CONSTRAINT [DF_EXPLAB_FUNDAMT] DEFAULT ((0)) NOT NULL,
    [S_NO]       NVARCHAR (50)   CONSTRAINT [DF_EXPLAB_S_NO] DEFAULT ('') NOT NULL,
    [SAL_YYMM]   NVARCHAR (50)   NOT NULL,
    [SALADR]     NVARCHAR (50)   NULL,
    CONSTRAINT [PK_EXPLAB] PRIMARY KEY CLUSTERED ([NOBR] ASC, [FA_IDNO] ASC, [YYMM] ASC, [INSUR_TYPE] ASC)
);



