CREATE TABLE [dbo].[EXPSUP] (
    [NOBR]      NVARCHAR (50)   NOT NULL,
    [YYMM]      NVARCHAR (50)   NOT NULL,
    [SEQ]       NVARCHAR (50)   NOT NULL,
    [SAL_CODE]  NVARCHAR (50)   NOT NULL,
    [PAY_DATE]  DATETIME        NOT NULL,
    [FORMAT]    NVARCHAR (50)   NOT NULL,
    [PAY_AMT]   DECIMAL (14, 4) NOT NULL,
    [SUP_AMT]   DECIMAL (14, 4) NOT NULL,
    [INS_HAMT]  DECIMAL (14, 4) NOT NULL,
    [ADATE]     DATETIME        NOT NULL,
    [DDATE]     DATETIME        NOT NULL,
    [TOTAL_AMT] DECIMAL (14, 4) NOT NULL,
    [S_NO]      NVARCHAR (50)   NOT NULL,
    [KEY_DATE]  DATETIME        NOT NULL,
    [KEY_MAN]   NVARCHAR (50)   NOT NULL,
    [SALADR]    NVARCHAR (50)   NULL,
    CONSTRAINT [PK_EXPSUP] PRIMARY KEY CLUSTERED ([NOBR] ASC, [YYMM] ASC, [SEQ] ASC, [SAL_CODE] ASC)
);



