CREATE TABLE [dbo].[EXTTABLE] (
    [AUTO]           INT            IDENTITY (1, 1) NOT NULL,
    [TABLENAME]      NVARCHAR (50)  NOT NULL,
    [KEYCOLUMNNAME]  NVARCHAR (50)  NOT NULL,
    [KEYCOLUMNVALUE] NVARCHAR (50)  NOT NULL,
    [COLUMNNAME]     NVARCHAR (50)  NOT NULL,
    [COLUMNVALUE]    NVARCHAR (200) NOT NULL,
    [COLUMNDESC]     NVARCHAR (200) NULL,
    [KEY_MAN]        NVARCHAR (50)  NULL,
    [KEY_DATE]       DATETIME       NULL,
    CONSTRAINT [PK_EXTTABLE] PRIMARY KEY CLUSTERED ([AUTO] ASC)
);

