CREATE TABLE [dbo].[FAMILY] (
    [FA_IDNO]    NVARCHAR (50) NOT NULL,
    [FA_NAME]    NVARCHAR (50) NOT NULL,
    [REL_CODE]   NVARCHAR (50) NOT NULL,
    [FA_BIRDT]   DATETIME      NULL,
    [NOBR]       NVARCHAR (50) NOT NULL,
    [KEY_DATE]   DATETIME      NOT NULL,
    [KEY_MAN]    NVARCHAR (50) NOT NULL,
    [ADDR]       NVARCHAR (60) CONSTRAINT [DF_FAMILY_ADDR] DEFAULT ('') NOT NULL,
    [TEL]        NVARCHAR (50) CONSTRAINT [DF_FAMILY_TEL] DEFAULT ('') NOT NULL,
    [GSM]        NVARCHAR (50) CONSTRAINT [DF_FAMILY_GSM] DEFAULT ('') NOT NULL,
    [BBC]        NVARCHAR (50) CONSTRAINT [DF_FAMILY_BBC] DEFAULT ('') NOT NULL,
    [TAX]        BIT           CONSTRAINT [DF_FAMILY_TAX] DEFAULT ((0)) NOT NULL,
    [AUTOINSLAB] AS            ([dbo].[CheckFaInslab]([nobr],[fa_idno],getdate())),
    [LIVE]       BIT           CONSTRAINT [DF_FAMILY_LIVE] DEFAULT ((0)) NOT NULL,
    [EDUCODE]    NVARCHAR (50) CONSTRAINT [DF_FAMILY_EDUCODE] DEFAULT ('') NOT NULL,
    [COMPNY]     NVARCHAR (50) CONSTRAINT [DF_FAMILY_COMPNY] DEFAULT ('') NULL,
    [TITLE]      NVARCHAR (50) CONSTRAINT [DF_FAMILY_TITLE] DEFAULT ('') NOT NULL,
    [FAMFORN]    AS            ([dbo].[CheckFaInsgrf]([nobr],[fa_idno],getdate())),
    [AUTOINSGRF] AS            ([dbo].[CheckFaInsgrf]([nobr],[fa_idno],getdate())),
    CONSTRAINT [PK_FAMILY] PRIMARY KEY CLUSTERED ([FA_IDNO] ASC, [NOBR] ASC)
);

