CREATE TABLE [dbo].[HARCODE] (
    [RATE_CODE]  NVARCHAR (50)   NOT NULL,
    [RATE_NAME]  NVARCHAR (50)   NOT NULL,
    [SELFCHARGE] DECIMAL (16, 2) NOT NULL,
    [COMPCHARGE] DECIMAL (16, 2) NOT NULL,
    [PARTIAL]    DECIMAL (16, 2) NOT NULL,
    [FIX_AMT]    DECIMAL (16, 2) NOT NULL,
    [KEY_MAN]    NVARCHAR (50)   NOT NULL,
    [KEY_DATE]   DATETIME        NOT NULL,
    [ADATE]      DATETIME        NOT NULL,
    [NOPAYTOP]   DECIMAL (16, 2) CONSTRAINT [DF_HARCODE_NOPAYTOP] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_HARCODE] PRIMARY KEY CLUSTERED ([RATE_CODE] ASC)
);

