CREATE TABLE [dbo].[HCODES] (
    [H_CODE]     NVARCHAR (50)   NOT NULL,
    [SAL_CODE]   NVARCHAR (50)   NOT NULL,
    [RATE]       DECIMAL (16, 2) NOT NULL,
    [MLSSALCODE] NVARCHAR (50)   NOT NULL,
    [KEY_DATE]   DATETIME        NOT NULL,
    [KEY_MAN]    NVARCHAR (50)   NOT NULL,
    CONSTRAINT [PK_HCODES] PRIMARY KEY CLUSTERED ([H_CODE] ASC, [SAL_CODE] ASC)
);

