CREATE TABLE [dbo].[HCODESRATE] (
    [H_CODE]   NVARCHAR (50)   NOT NULL,
    [SAL_CODE] NVARCHAR (50)   NOT NULL,
    [YEAR_B]   DECIMAL (16, 2) NOT NULL,
    [YEAR_E]   DECIMAL (16, 2) NOT NULL,
    [DAY_B]    DECIMAL (16, 2) NOT NULL,
    [DAY_E]    DECIMAL (16, 2) NOT NULL,
    [RATE]     DECIMAL (16, 2) NOT NULL,
    [KEY_DATE] DATETIME        NOT NULL,
    [KEY_MAN]  NVARCHAR (50)   NOT NULL,
    CONSTRAINT [PK_HCODESRATE] PRIMARY KEY CLUSTERED ([H_CODE] ASC, [SAL_CODE] ASC, [YEAR_B] ASC, [DAY_B] ASC)
);

