CREATE TABLE [dbo].[HOLI] (
    [H_DATE]    DATETIME      NOT NULL,
    [ATT_CODE]  NVARCHAR (50) NOT NULL,
    [HOLI]      BIT           NOT NULL,
    [KEY_MAN]   NVARCHAR (50) NOT NULL,
    [KEY_DATE]  DATETIME      NOT NULL,
    [HOLI_CODE] NVARCHAR (50) NOT NULL,
    [OTHCODE]   NVARCHAR (50) CONSTRAINT [DF_HOLI_OTHCODE] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_HOLI] PRIMARY KEY CLUSTERED ([H_DATE] ASC, [HOLI_CODE] ASC)
);

