CREATE TABLE [dbo].[HPX_OLD_BASETTS] (
    [NOBR]      NVARCHAR (10)   NOT NULL,
    [ANAME]     NVARCHAR (40)   NOT NULL,
    [ADATE]     DATETIME        NOT NULL,
    [C_REASON]  NVARCHAR (20)   NULL,
    [C_FIELD]   NVARCHAR (30)   NULL,
    [FD_BEFORE] NVARCHAR (100)  NULL,
    [FD_AFTER]  NVARCHAR (100)  NULL,
    [MEMO]      NVARCHAR (2000) NULL,
    [C_DESC]    NVARCHAR (50)   NULL,
    [DONE_DATE] DATETIME        NULL,
    CONSTRAINT [PK_HPX_OLD_BASETTS] PRIMARY KEY CLUSTERED ([NOBR] ASC, [ADATE] ASC) WITH (IGNORE_DUP_KEY = ON)
);

