CREATE TABLE [dbo].[INPOLAB] (
    [NOBR]       NVARCHAR (50)   NOT NULL,
    [FA_IDNO]    NVARCHAR (50)   NOT NULL,
    [YYMM]       NVARCHAR (50)   NOT NULL,
    [EXP]        DECIMAL (16, 2) NOT NULL,
    [COMP]       DECIMAL (16, 2) NOT NULL,
    [KEY_DATE]   DATETIME        NOT NULL,
    [KEY_MAN]    NVARCHAR (50)   NOT NULL,
    [ADATE]      DATETIME        NOT NULL,
    [DAYS]       DECIMAL (16, 2) NOT NULL,
    [RATE_CODE]  NVARCHAR (50)   NOT NULL,
    [INSUR_TYPE] NVARCHAR (50)   NOT NULL,
    [INSCD]      DECIMAL (16, 2) NOT NULL,
    [SALADR]     NVARCHAR (50)   CONSTRAINT [DF_INPOLAB_SALADR] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_INPOLAB] PRIMARY KEY CLUSTERED ([NOBR] ASC, [FA_IDNO] ASC, [YYMM] ASC, [INSUR_TYPE] ASC)
);

