CREATE TABLE [dbo].[INSCOUNTRY] (
    [S_NO]     NVARCHAR (50) CONSTRAINT [DF_INSCOUNTRY_S_NO] DEFAULT ('') NOT NULL,
    [S_NAME]   NVARCHAR (50) CONSTRAINT [DF_INSCOUNTRY_S_NAME] DEFAULT ('') NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_INSCOUNTRY] PRIMARY KEY CLUSTERED ([S_NO] ASC)
);

