CREATE TABLE [dbo].[INSCOMP] (
    [S_NO]       NVARCHAR (50)   NOT NULL,
    [INSNO]      NVARCHAR (50)   NOT NULL,
    [INSPO]      NVARCHAR (50)   NOT NULL,
    [INSIDNO]    NVARCHAR (50)   NOT NULL,
    [INSSUB]     NVARCHAR (50)   NOT NULL,
    [INSTEL]     NVARCHAR (50)   NOT NULL,
    [INSNAME]    NVARCHAR (50)   NOT NULL,
    [INSADDR]    NVARCHAR (50)   NOT NULL,
    [KEY_MAN]    NVARCHAR (50)   NOT NULL,
    [KEY_DATE]   DATETIME        NOT NULL,
    [INSMAN]     NVARCHAR (50)   CONSTRAINT [DF_INSCOMP_INSMAN] DEFAULT ('') NOT NULL,
    [REL_MAN]    NVARCHAR (50)   CONSTRAINT [DF_INSCOMP_REL_MAN] DEFAULT ('') NOT NULL,
    [REL_TEL]    NVARCHAR (50)   CONSTRAINT [DF_INSCOMP_REL_TEL] DEFAULT ('') NOT NULL,
    [DEFA]       BIT             CONSTRAINT [DF_INSCOMP_DEFA] DEFAULT ((0)) NOT NULL,
    [S_NO_DISP]  NVARCHAR (50)   NULL,
    [JOBACCRATE] DECIMAL (14, 4) NULL,
    CONSTRAINT [PK_INSCOMP] PRIMARY KEY CLUSTERED ([S_NO] ASC)
);

