CREATE TABLE [dbo].[INSGRF] (
    [NOBR]     NVARCHAR (50) NOT NULL,
    [FA_IDNO]  NVARCHAR (50) NOT NULL,
    [IN_DATE]  DATETIME      NOT NULL,
    [OUT_DATE] DATETIME      NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL,
    CONSTRAINT [PK_INSGRF_1] PRIMARY KEY CLUSTERED ([NOBR] ASC, [FA_IDNO] ASC, [IN_DATE] ASC)
);

