CREATE TABLE [dbo].[INSNAME] (
    [NO]       NVARCHAR (50) NOT NULL,
    [NAME]     NVARCHAR (50) NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL,
    [NO1]      NVARCHAR (50) CONSTRAINT [DF_INSNAME_NO1] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_INSNAME] PRIMARY KEY CLUSTERED ([NO] ASC)
);

