CREATE TABLE [dbo].[INSURLV] (
    [AMT]       DECIMAL (16, 2) NOT NULL,
    [EFF_DATEL] DATETIME        NOT NULL,
    [LFF_DATEL] DATETIME        NOT NULL,
    [EFF_DATEH] DATETIME        NOT NULL,
    [LFF_DATEH] DATETIME        NOT NULL,
    [KEY_MAN]   NVARCHAR (50)   NOT NULL,
    [KEY_DATE]  DATETIME        NOT NULL,
    [EFF_DATER] DATETIME        CONSTRAINT [DF_INSURLV_EFF_DATER] DEFAULT (getdate()) NOT NULL,
    [LFF_DATER] DATETIME        CONSTRAINT [DF_INSURLV_LFF_DATER] DEFAULT (getdate()) NOT NULL,
    [EFF_RATE]  DECIMAL (10, 5) CONSTRAINT [DF_INSURLV_EFF_RATE] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_INSURLV_1] PRIMARY KEY CLUSTERED ([AMT] ASC)
);

