CREATE TABLE [dbo].[IPCONTROL] (
    [IPADD]    NVARCHAR (50) CONSTRAINT [DF_IPCONTROL_IPADD] DEFAULT ('') NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    [IPNAME]   NVARCHAR (50) CONSTRAINT [DF_IPCONTROL_IPNAME] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_IPCONTROL] PRIMARY KEY CLUSTERED ([IPADD] ASC)
);

