CREATE TABLE [dbo].[JOB] (
    [JOB]       NVARCHAR (50) CONSTRAINT [DF_JOB_JOB] DEFAULT ('') NOT NULL,
    [JOB_NAME]  NVARCHAR (50) CONSTRAINT [DF_JOB_JOB_NAME] DEFAULT ('') NOT NULL,
    [JOB_ENAME] NVARCHAR (50) CONSTRAINT [DF_JOB_JOB_ENAME] DEFAULT ('') NOT NULL,
    [KEY_DATE]  DATETIME      CONSTRAINT [DF_JOB_KEY_DATE] DEFAULT (getdate()) NULL,
    [KEY_MAN]   NVARCHAR (50) CONSTRAINT [DF_JOB_KEY_MAN] DEFAULT ('') NULL,
    [JOB_TREE]  NVARCHAR (50) CONSTRAINT [DF_JOB_JOB_TREE] DEFAULT ('') NULL,
    [JOBL]      NVARCHAR (50) CONSTRAINT [DF_JOB_JOBL] DEFAULT ('') NULL,
    [JOBLB]     NVARCHAR (50) CONSTRAINT [DF_JOB_JOBLB] DEFAULT ('') NULL,
    [JOBLE]     NVARCHAR (50) CONSTRAINT [DF_JOB_JOBLE] DEFAULT ('') NULL,
    [OLD_JOB]   NVARCHAR (50) CONSTRAINT [DF_JOB_OLD_JOB] DEFAULT ('') NULL,
    [WORKAMT]   BIT           CONSTRAINT [DF_JOB_WORKAMT] DEFAULT ((0)) NULL,
    [JOB_DISP]  NVARCHAR (50) CONSTRAINT [DF_JOB_JOB1] DEFAULT ('') NULL,
    CONSTRAINT [PK_JOB] PRIMARY KEY CLUSTERED ([JOB] ASC)
);

