CREATE TABLE [dbo].[JOBL] (
    [JOBL]      NVARCHAR (50)   NOT NULL,
    [JOB_NAME]  NVARCHAR (50)   CONSTRAINT [DF_JOBL_JOB_NAME] DEFAULT ('') NOT NULL,
    [B_SAL]     DECIMAL (16, 2) CONSTRAINT [DF_JOBL_B_SAL] DEFAULT ((0)) NOT NULL,
    [E_SAL]     DECIMAL (16, 2) CONSTRAINT [DF_JOBL_E_SAL] DEFAULT ((0)) NOT NULL,
    [KEY_DATE]  DATETIME        CONSTRAINT [DF_JOBL_KEY_DATE] DEFAULT (getdate()) NOT NULL,
    [KEY_MAN]   NVARCHAR (50)   CONSTRAINT [DF_JOBL_KEY_MAN] DEFAULT ('') NOT NULL,
    [OLD_JOBL]  NVARCHAR (50)   CONSTRAINT [DF_JOBL_OLD_JOBL] DEFAULT ('') NOT NULL,
    [B_SAL1]    DECIMAL (16, 2) CONSTRAINT [DF_JOBL_B_SAL1] DEFAULT ((0)) NOT NULL,
    [B_SAL2]    DECIMAL (16, 2) CONSTRAINT [DF_JOBL_B_SAL2] DEFAULT ((0)) NOT NULL,
    [E_SAL1]    DECIMAL (16, 2) CONSTRAINT [DF_JOBL_E_SAL1] DEFAULT ((0)) NOT NULL,
    [E_SAL2]    DECIMAL (16, 2) CONSTRAINT [DF_JOBL_E_SAL2] DEFAULT ((0)) NOT NULL,
    [JOBL_GRUP] NVARCHAR (50)   CONSTRAINT [DF_JOBL_JOBL_GRUP] DEFAULT ('') NOT NULL,
    [JOBL_DISP] NVARCHAR (50)   NULL,
    CONSTRAINT [PK_JOBL] PRIMARY KEY CLUSTERED ([JOBL] ASC)
);

