CREATE TABLE [dbo].[JOBO] (
    [JOBO]     NVARCHAR (50) CONSTRAINT [DF_JOBO_JOBO] DEFAULT ('') NOT NULL,
    [JOB_NAME] NVARCHAR (50) CONSTRAINT [DF_JOBO_JOB_NAME] DEFAULT ('') NOT NULL,
    [KEY_DATE] DATETIME      CONSTRAINT [DF_JOBO_KEY_DATE] DEFAULT (getdate()) NOT NULL,
    [KEY_MAN]  NVARCHAR (50) CONSTRAINT [DF_JOBO_KEY_MAN] DEFAULT ('') NOT NULL,
    [JOB_TREE] NVARCHAR (50) CONSTRAINT [DF_JOBO_JOB_TREE] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_JOBO] PRIMARY KEY CLUSTERED ([JOBO] ASC)
);

