CREATE TABLE [dbo].[JOBS] (
    [JOBS]      NVARCHAR (50) CONSTRAINT [DF_JOBS_JOBS] DEFAULT ('') NOT NULL,
    [JOB_NAME]  NVARCHAR (50) NOT NULL,
    [KEY_DATE]  DATETIME      NOT NULL,
    [KEY_MAN]   NVARCHAR (50) NOT NULL,
    [JOBS_DISP] NVARCHAR (50) NULL,
    CONSTRAINT [PK_JOBS] PRIMARY KEY CLUSTERED ([JOBS] ASC)
);

