CREATE TABLE [dbo].[LICAN] (
    [NOBR]     NVARCHAR (50) NOT NULL,
    [DESCS]    NVARCHAR (50) CONSTRAINT [DF_LICAN_DESCS] DEFAULT ('') NOT NULL,
    [COMP]     NVARCHAR (50) NOT NULL,
    [MDATE]    DATETIME      NOT NULL,
    [OWNER]    BIT           NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL,
    [lican_id] INT           NOT NULL,
    [LIC_NO]   NVARCHAR (50) CONSTRAINT [DF_LICAN_LIC_NO] DEFAULT ('') NOT NULL,
    [LIC_NOTE] NVARCHAR (60) CONSTRAINT [DF_LICAN_LIC_NOTE] DEFAULT ('') NOT NULL,
    [LIC_PASS] BIT           CONSTRAINT [DF_LICAN_LIC_PASS] DEFAULT ((0)) NOT NULL,
    [EDATE]    DATETIME      CONSTRAINT [DF_LICAN_EDATE] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_LICAN] PRIMARY KEY CLUSTERED ([NOBR] ASC, [DESCS] ASC)
);

