CREATE TABLE [dbo].[LNG] (
    [LNG]      NVARCHAR (50) NOT NULL,
    [LNG_NAME] NVARCHAR (50) NOT NULL,
    [FONT]     NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_LNG] PRIMARY KEY CLUSTERED ([LNG] ASC)
);

