CREATE TABLE [dbo].[LOCK_WAGE] (
    [YYMM]     NVARCHAR (10) NOT NULL,
    [SEQ]      NVARCHAR (2)  NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL,
    [SALADR]   NVARCHAR (50) CONSTRAINT [DF_LOCK_WAGE_SALADR] DEFAULT ('') NOT NULL,
    [MENO]     NVARCHAR (50) CONSTRAINT [DF_LOCK_WAGE_MENO] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_LOCK_WAGE] PRIMARY KEY CLUSTERED ([YYMM] ASC, [SEQ] ASC, [SALADR] ASC)
);

