CREATE TABLE [dbo].[MA_FOOD] (
    [COMP]     NVARCHAR (50)   CONSTRAINT [DF_MA_FOOD_COMP] DEFAULT ('') NOT NULL,
    [ROTE]     NVARCHAR (50)   CONSTRAINT [DF_MA_FOOD_ROTE] DEFAULT ('') NOT NULL,
    [NOT_ROTE] BIT             CONSTRAINT [DF_MA_FOOD_NOT_ROTE] DEFAULT ((0)) NOT NULL,
    [MA_AMT]   DECIMAL (16, 2) CONSTRAINT [DF_MA_FOOD_MA_AMT] DEFAULT ((0)) NOT NULL,
    [KEY_MAN]  NVARCHAR (50)   CONSTRAINT [DF_MA_FOOD_KEY_MAN] DEFAULT ('') NOT NULL,
    [KEY_DATE] DATETIME        CONSTRAINT [DF_MA_FOOD_KEY_DATE] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_MA_FOOD] PRIMARY KEY CLUSTERED ([COMP] ASC)
);

