CREATE TABLE [dbo].[MAILQUEUE] (
    [ID]          INT            IDENTITY (1, 1) NOT NULL,
    [GUID]        NVARCHAR (50)  NOT NULL,
    [FROM_ADDR]   NVARCHAR (50)  NOT NULL,
    [FROM_NAME]   NVARCHAR (50)  NULL,
    [TO_ADDR]     NVARCHAR (50)  NOT NULL,
    [TO_NAME]     NVARCHAR (50)  NULL,
    [SUBJECT]     NVARCHAR (500) NOT NULL,
    [BODY]        NVARCHAR (MAX) NOT NULL,
    [RETRY]       INT            NOT NULL,
    [SUCCESS]     BIT            NOT NULL,
    [SUSPEND]     BIT            NOT NULL,
    [FREEZE_TIME] DATETIME       NOT NULL,
    [KEY_DATE]    DATETIME       NOT NULL,
    [KEY_MAN]     NVARCHAR (50)  NOT NULL,
    [NOTE]        NVARCHAR (50)  NULL,
    [NOTE1]       NVARCHAR (50)  NULL,
    [NOTE2]       NVARCHAR (50)  NULL,
    [NOTE3]       NVARCHAR (50)  NULL,
    [NOTE4]       NVARCHAR (50)  NULL,
    [NOTE5]       NVARCHAR (50)  NULL,
    CONSTRAINT [PK_MAILQUEUE] PRIMARY KEY CLUSTERED ([ID] ASC)
);

