CREATE TABLE [dbo].[MAILSEND] (
    [FORMNAME]  CHAR (10) NULL,
    [NOBR_REC]  CHAR (10) NULL,
    [FORMNO]    CHAR (10) NULL,
    [ADATE]     CHAR (9)  NULL,
    [NOBR_SEND] CHAR (10) NULL,
    [OK_STAT]   CHAR (1)  NULL,
    [SEND_TIME] DATETIME  NULL,
    [OK_TIME]   DATETIME  NULL
);

