CREATE TABLE [dbo].[MASTER] (
    [NOBR]        NVARCHAR (50)  NOT NULL,
    [MASTER]      NVARCHAR (50)  NOT NULL,
    [KEY_MAN]     NVARCHAR (50)  NOT NULL,
    [KEY_DATE]    DATETIME       NOT NULL,
    [RELISH_CODE] NVARCHAR (50)  CONSTRAINT [DF_MASTER_RELISH_CODE] DEFAULT ('') NOT NULL,
    [RELISH]      NVARCHAR (60)  CONSTRAINT [DF_MASTER_RELISH] DEFAULT ('') NOT NULL,
    [CORPORATION] NVARCHAR (60)  CONSTRAINT [DF_MASTER_CORPORATION] DEFAULT ('') NOT NULL,
    [LANGUAGE]    NVARCHAR (50)  CONSTRAINT [DF_MASTER_LANGUAGE] DEFAULT ('') NOT NULL,
    [master_id]   INT            NOT NULL,
    [MEMO]        NVARCHAR (500) NULL,
    CONSTRAINT [PK_MASTER] PRIMARY KEY CLUSTERED ([NOBR] ASC, [MASTER] ASC)
);

