CREATE TABLE [dbo].[MealType] (
    [MEALTYPE_CODE] NVARCHAR (50)  NOT NULL,
    [MEALGROUP]     NVARCHAR (50)  NOT NULL,
    [MEALTYPE_NAME] NVARCHAR (50)  NOT NULL,
    [BTIME]         NVARCHAR (50)  NOT NULL,
    [ETIME]         NVARCHAR (50)  NOT NULL,
    [NOTE]          NVARCHAR (500) NULL,
    [KEY_MAN]       NVARCHAR (50)  NOT NULL,
    [KEY_DATE]      DATETIME       NOT NULL,
    [CBTIME]        NVARCHAR (50)  NULL,
    [CETIME]        NVARCHAR (50)  NULL,
    CONSTRAINT [PK_MealType] PRIMARY KEY CLUSTERED ([MEALTYPE_CODE] ASC, [MEALGROUP] ASC)
);

