CREATE TABLE [dbo].[MENUSTRIPSTRUCTURE] (
    [AK]            INT              IDENTITY (1, 1) NOT NULL,
    [MENUSTRIPID]   UNIQUEIDENTIFIER NOT NULL,
    [MENUSTRIPNAME] NVARCHAR (50)    NOT NULL,
    [MENUSTRIPTEXT] NVARCHAR (50)    NOT NULL,
    [PARENTID]      UNIQUEIDENTIFIER NULL,
    [ITEMINDEX]     INT              NOT NULL,
    [COMMONITEM]    BIT              NOT NULL,
    [SHORTCUTKEYS]  NVARCHAR (50)    NULL,
    [ENABLE]        BIT              NOT NULL,
    [ASSEMBLYNAME]  NVARCHAR (50)    NULL,
    [KEY_MAN]       NVARCHAR (50)    NULL,
    [KEY_DATE]      DATETIME         NULL,
    [MENUGROUPID]   UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK_MENUSTRIPSTRUCTURE] PRIMARY KEY CLUSTERED ([AK] ASC)
);

