CREATE TABLE [dbo].[MENUGROUP] (
    [AK]            INT              IDENTITY (1, 1) NOT NULL,
    [MENUGROUPID]   UNIQUEIDENTIFIER NOT NULL,
    [MENUGROUPNAME] NVARCHAR (50)    NOT NULL,
    [NOTE]          NVARCHAR (500)   NULL,
    [KEY_MAN]       NVARCHAR (50)    NULL,
    [KEY_DATE]      DATETIME         NULL,
    CONSTRAINT [PK_MENUGROUP] PRIMARY KEY CLUSTERED ([MENUGROUPID] ASC)
);

