CREATE TABLE [dbo].[MTCODE] (
    [CATEGORY] NVARCHAR (50)  NOT NULL,
    [CODE]     NVARCHAR (50)  NOT NULL,
    [NAME]     NVARCHAR (200) NOT NULL,
    [SORT]     INT            NOT NULL,
    [DISPLAY]  BIT            CONSTRAINT [DF_MTCODE_DISPLAY] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_MTCODE] PRIMARY KEY CLUSTERED ([CATEGORY] ASC, [CODE] ASC)
);

