CREATE TABLE [dbo].[MTDICT] (
    [CATEGORY]    NVARCHAR (50)  NOT NULL,
    [CODE]        NVARCHAR (50)  NOT NULL,
    [LANGUAGE]    NVARCHAR (50)  NOT NULL,
    [DESCRIPTION] NVARCHAR (MAX) NOT NULL,
    [DISP]        BIT            NOT NULL,
    [KEY_DATE]    DATETIME       NOT NULL,
    [KEY_MAN]     NVARCHAR (50)  NOT NULL,
    CONSTRAINT [PK_MTDICT] PRIMARY KEY CLUSTERED ([CATEGORY] ASC, [CODE] ASC, [LANGUAGE] ASC)
);

