CREATE TABLE [dbo].[MTLNG] (
    [CATEGORY]     NVARCHAR (50) NOT NULL,
    [CODE]         NVARCHAR (50) NOT NULL,
    [LANGUAGE]     NVARCHAR (50) NOT NULL,
    [DISPLAY_NAME] NVARCHAR (50) NOT NULL,
    [KEY_DATE]     DATETIME      NOT NULL,
    [KEY_MAN]      NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_MTLNG] PRIMARY KEY CLUSTERED ([CATEGORY] ASC, [CODE] ASC, [LANGUAGE] ASC)
);

