CREATE TABLE [dbo].[NIG_FOOD] (
    [COMP]     NVARCHAR (50)   CONSTRAINT [DF_NIG_FOOD_COMP] DEFAULT ('') NOT NULL,
    [ROTE]     NVARCHAR (50)   CONSTRAINT [DF_NIG_FOOD_ROTE] DEFAULT ('') NOT NULL,
    [BTIME]    NVARCHAR (50)   CONSTRAINT [DF_NIG_FOOD_BTIME] DEFAULT ('') NOT NULL,
    [ETIME]    NVARCHAR (50)   CONSTRAINT [DF_NIG_FOOD_ETIME] DEFAULT ('') NOT NULL,
    [FOODAMT]  DECIMAL (16, 2) CONSTRAINT [DF_NIG_FOOD_FOODAMT] DEFAULT ((0)) NOT NULL,
    [KEY_MAN]  NVARCHAR (50)   CONSTRAINT [DF_NIG_FOOD_KEY_MAN] DEFAULT ('') NOT NULL,
    [KEY_DATE] DATETIME        CONSTRAINT [DF_NIG_FOOD_KEY_DATE] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_NIG_FOOD] PRIMARY KEY CLUSTERED ([COMP] ASC, [ROTE] ASC, [BTIME] ASC)
);

