CREATE TABLE [dbo].[NOEAT] (
    [NOBR]     NVARCHAR (50) NOT NULL,
    [YYMM]     NVARCHAR (50) NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL,
    CONSTRAINT [PK_NOEAT] PRIMARY KEY CLUSTERED ([NOBR] ASC, [YYMM] ASC)
);

