CREATE TABLE [dbo].[ONDUTY] (
    [NOBR]     NVARCHAR (50) CONSTRAINT [DF_ONDUTY_NOBR] DEFAULT ('') NOT NULL,
    [ADATE]    DATETIME      NOT NULL,
    [NOTE]     NVARCHAR (60) NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL,
    [YYMM]     NVARCHAR (50) CONSTRAINT [DF_ONDUTY_YYMM] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_ONDUTY] PRIMARY KEY CLUSTERED ([NOBR] ASC, [ADATE] ASC, [YYMM] ASC)
);

