CREATE TABLE [dbo].[OTC] (
    [AK]        INT             IDENTITY (1, 1) NOT NULL,
    [NOBR]      NVARCHAR (50)   NOT NULL,
    [BDATE]     DATETIME        NOT NULL,
    [BTIME]     NVARCHAR (50)   NOT NULL,
    [ETIME]     NVARCHAR (50)   NOT NULL,
    [TOT_HOURS] DECIMAL (16, 2) NOT NULL,
    [OT_HRS]    DECIMAL (16, 2) NOT NULL,
    [REST_HRS]  DECIMAL (16, 2) NOT NULL,
    [KEY_MAN]   NVARCHAR (50)   NOT NULL,
    [KEY_DATE]  DATETIME        NOT NULL,
    [NOTE]      NVARCHAR (3500) NOT NULL,
    [YYMM]      NVARCHAR (50)   NOT NULL,
    [SERNO]     NVARCHAR (50)   NOT NULL,
    CONSTRAINT [PK_OTC] PRIMARY KEY CLUSTERED ([AK] ASC)
);

