CREATE TABLE [dbo].[OTHCODE] (
    [OTHCODE]  NVARCHAR (50)   NOT NULL,
    [OTHNAME]  NVARCHAR (50)   CONSTRAINT [DF_OTHCODE_OTHNAME] DEFAULT ('') NOT NULL,
    [OTHCOLOR] DECIMAL (16, 2) CONSTRAINT [DF_OTHCODE_OTHCOLOR] DEFAULT ((0)) NOT NULL,
    [OTHHOLI]  BIT             CONSTRAINT [DF_OTHCODE_OTHHOLI] DEFAULT ((0)) NOT NULL,
    [KEY_MAN]  NVARCHAR (50)   CONSTRAINT [DF_OTHCODE_KEY_MAN] DEFAULT ('') NOT NULL,
    [KEY_DATE] DATETIME        CONSTRAINT [DF_OTHCODE_KEY_DATE] DEFAULT (getdate()) NOT NULL,
    [STDHOLI]  BIT             NOT NULL,
    [ROTE]     NVARCHAR (50)   CONSTRAINT [DF_OTHCODE_ROTE] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_OTHCODE] PRIMARY KEY CLUSTERED ([OTHCODE] ASC)
);



