CREATE TABLE [dbo].[OTHERDA] (
    [NOBR]     NVARCHAR (50)   NOT NULL,
    [CODE]     NVARCHAR (50)   NOT NULL,
    [ADATE]    DATETIME        NOT NULL,
    [NOTE]     NVARCHAR (60)   NOT NULL,
    [KEY_MAN]  NVARCHAR (50)   NOT NULL,
    [KEY_DATE] DATETIME        NOT NULL,
    [AMT]      DECIMAL (16, 2) CONSTRAINT [DF_OTHERDA_AMT] DEFAULT ((0)) NOT NULL,
    [YYMM]     NVARCHAR (50)   CONSTRAINT [DF_OTHERDA_YYMM] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_OTHERDA] PRIMARY KEY CLUSTERED ([NOBR] ASC)
);

