CREATE TABLE [dbo].[OTHERCD] (
    [CODE]     NVARCHAR (50) NOT NULL,
    [NAME]     NVARCHAR (50) NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL,
    [SAL_CODE] NVARCHAR (50) CONSTRAINT [DF_OTHERCD_SAL_CODE] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_OTHERCD] PRIMARY KEY CLUSTERED ([CODE] ASC)
);

