CREATE TABLE [dbo].[OTPRE] (
    [NOBR]     NVARCHAR (50)   CONSTRAINT [DF_OTPRE_NOBR] DEFAULT ('') NOT NULL,
    [ADATE]    DATETIME        NOT NULL,
    [BTIME]    NVARCHAR (50)   NOT NULL,
    [ETIME]    NVARCHAR (50)   NOT NULL,
    [SUG_HRS]  DECIMAL (16, 2) NOT NULL,
    [OT_HRS]   DECIMAL (16, 2) NOT NULL,
    [OT1_HRS]  DECIMAL (16, 2) NOT NULL,
    [OT2_HRS]  DECIMAL (16, 2) NOT NULL,
    [TRANS]    BIT             NOT NULL,
    [OT_DEPT]  NVARCHAR (50)   NOT NULL,
    [KEY_DATE] DATETIME        NOT NULL,
    [KEY_MAN]  NVARCHAR (50)   NOT NULL,
    [YYMM]     NVARCHAR (50)   NOT NULL,
    [OT_ROTE]  NVARCHAR (50)   CONSTRAINT [DF_OTPRE_OT_ROTE] DEFAULT ('') NOT NULL,
    [TRANP]    BIT             CONSTRAINT [DF_OTPRE_TRANP] DEFAULT ((0)) NOT NULL,
    [REST_HRS] DECIMAL (16, 2) CONSTRAINT [DF_OTPRE_REST_HRS] DEFAULT ((0)) NOT NULL,
    [SYS_OT]   BIT             CONSTRAINT [DF_OTPRE_SYS_OT] DEFAULT ((0)) NOT NULL,
    [OTRCD]    NVARCHAR (50)   NOT NULL,
    [NOTE]     NVARCHAR (200)  NOT NULL,
    CONSTRAINT [PK_OTPRE] PRIMARY KEY CLUSTERED ([NOBR] ASC, [ADATE] ASC, [BTIME] ASC, [ETIME] ASC)
);

