CREATE TABLE [dbo].[OUTCD] (
    [OUTCD]    NVARCHAR (50) NOT NULL,
    [OUTNAME]  NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_OUTCD] PRIMARY KEY CLUSTERED ([OUTCD] ASC)
);

