CREATE TABLE [dbo].[OutPost] (
    [Code]        NVARCHAR (50) NOT NULL,
    [OutPostName] NVARCHAR (50) NOT NULL,
    [KEY_DATE]    DATETIME      NOT NULL,
    [KEY_MAN]     NVARCHAR (50) NOT NULL,
    [CODE_DISP]   NVARCHAR (50) NULL,
    CONSTRAINT [PK_OutPost] PRIMARY KEY CLUSTERED ([Code] ASC)
);

