CREATE TABLE [dbo].[OVERTIME_TYPE] (
    [CATEGORY]  NVARCHAR (50) NOT NULL,
    [CODE]      NVARCHAR (50) NOT NULL,
    [TYPE_NAME] NVARCHAR (50) NOT NULL,
    [MEAL]      BIT           NOT NULL,
    [FREQUENCY] DECIMAL (18)  NULL,
    [COM_LEAVE] BIT           NOT NULL,
    [KEY_MAN]   NVARCHAR (50) NULL,
    [KEY_DATE]  DATETIME      NULL,
    [SORT]      INT           NULL,
    [DISPLAY]   BIT           NULL,
    [IS_OT]     BIT           NOT NULL,
    CONSTRAINT [PK_OVERTIME_TYPE_1] PRIMARY KEY CLUSTERED ([CODE] ASC)
);

