CREATE TABLE [dbo].[PARAMETER_TREE] (
    [AUTO]     INT           IDENTITY (1, 1) NOT NULL,
    [PID]      INT           NOT NULL,
    [CODE]     NVARCHAR (50) NOT NULL,
    [NAME]     NVARCHAR (50) NOT NULL,
    [DISPLAY]  BIT           NOT NULL,
    [SORT]     INT           NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    [NOTE]     NVARCHAR (50) NULL,
    [NOTE1]    NVARCHAR (50) NULL,
    [NOTE2]    NVARCHAR (50) NULL,
    [NOTE3]    NVARCHAR (50) NULL,
    [NOTE4]    NVARCHAR (50) NULL,
    CONSTRAINT [PK_PARAMETER_TREE] PRIMARY KEY CLUSTERED ([AUTO] ASC)
);

