CREATE TABLE [dbo].[PROVCD] (
    [PROV_CODE] NVARCHAR (50) NOT NULL,
    [DESCR]     NVARCHAR (50) NOT NULL,
    [KEY_MAN]   NVARCHAR (50) NULL,
    [KEY_DATE]  DATETIME      NULL,
    CONSTRAINT [PK_PROVCD] PRIMARY KEY CLUSTERED ([PROV_CODE] ASC)
);

