CREATE TABLE [dbo].[RANGE_SET] (
    [ID]          INT           IDENTITY (1, 1) NOT NULL,
    [PID]         INT           NOT NULL,
    [RANGE_BEGIN] NVARCHAR (50) NOT NULL,
    [RANGE_END]   NVARCHAR (50) NOT NULL,
    [NOTE]        NVARCHAR (50) NULL,
    [NOTE1]       NVARCHAR (50) NULL,
    [NOTE2]       NVARCHAR (50) NULL,
    [NOTE3]       NVARCHAR (50) NULL,
    [NOTE4]       NVARCHAR (50) NULL,
    [NOTE5]       NVARCHAR (50) NULL,
    [KEY_DATE]    DATETIME      NOT NULL,
    [KEY_MAN]     NVARCHAR (50) NOT NULL,
    [MEMO]        NCHAR (10)    NULL,
    CONSTRAINT [PK_RANGE_SET_1] PRIMARY KEY CLUSTERED ([ID] ASC)
);

