CREATE TABLE [dbo].[RELAYTABLE] (
    [AK]           INT           IDENTITY (1, 1) NOT NULL,
    [PARENTKEY]    NVARCHAR (50) NOT NULL,
    [PARENTSOURCE] NVARCHAR (50) NOT NULL,
    [CHILDKEY]     NVARCHAR (50) NOT NULL,
    [CHILDBSOURCE] NVARCHAR (50) NOT NULL,
    [CREATEMAN]    NVARCHAR (50) NOT NULL,
    [CREATEDATE]   DATETIME      NOT NULL,
    CONSTRAINT [PK_RELAYTABLE] PRIMARY KEY CLUSTERED ([AK] ASC)
);

