CREATE TABLE [dbo].[RELCODE] (
    [REL_CODE] NVARCHAR (50) NOT NULL,
    [REL_NAME] NVARCHAR (50) NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL,
    [GRPRELCD] NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_RELCODE] PRIMARY KEY CLUSTERED ([REL_CODE] ASC)
);

