CREATE TABLE [dbo].[RELISHCD] (
    [RELISH_CODE] NVARCHAR (50) NOT NULL,
    [RELISH]      NVARCHAR (50) CONSTRAINT [DF_RELISHCD_RELISH] DEFAULT ('') NOT NULL,
    [KEY_DATE]    DATETIME      NOT NULL,
    [KEY_MAN]     NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_RELISHCD] PRIMARY KEY CLUSTERED ([RELISH_CODE] ASC)
);

