CREATE TABLE [dbo].[ROTET] (
    [ROTET]        NVARCHAR (50)   NOT NULL,
    [ROTETNAME]    NVARCHAR (50)   NOT NULL,
    [R1]           NVARCHAR (50)   NOT NULL,
    [R2]           NVARCHAR (50)   NOT NULL,
    [R3]           NVARCHAR (50)   NOT NULL,
    [R4]           NVARCHAR (50)   NOT NULL,
    [R5]           NVARCHAR (50)   NOT NULL,
    [R6]           NVARCHAR (50)   NOT NULL,
    [R7]           NVARCHAR (50)   NOT NULL,
    [R8]           NVARCHAR (50)   NOT NULL,
    [KEY_DATE]     DATETIME        NOT NULL,
    [KEY_MAN]      NVARCHAR (50)   NOT NULL,
    [FREQ]         NVARCHAR (50)   NOT NULL,
    [INHOLI]       NVARCHAR (50)   NOT NULL,
    [SAL_HRS]      DECIMAL (16, 2) NOT NULL,
    [FREQ_DATE]    DECIMAL (16, 2) NOT NULL,
    [FREQ_START]   NVARCHAR (50)   NOT NULL,
    [R9]           NVARCHAR (50)   CONSTRAINT [DF_ROTET_R9] DEFAULT ('') NOT NULL,
    [R10]          NVARCHAR (50)   CONSTRAINT [DF_ROTET_R10] DEFAULT ('') NOT NULL,
    [YRREST_HRS]   DECIMAL (16, 2) CONSTRAINT [DF_ROTET_YRREST_HRS] DEFAULT ((0)) NOT NULL,
    [R1T]          INT             NOT NULL,
    [R2T]          INT             NOT NULL,
    [R3T]          INT             NOT NULL,
    [R4T]          INT             NOT NULL,
    [R5T]          INT             NOT NULL,
    [R6T]          INT             NOT NULL,
    [R7T]          INT             NOT NULL,
    [R8T]          INT             NOT NULL,
    [R9T]          INT             NOT NULL,
    [R10T]         INT             NOT NULL,
    [ROTET_DISP]   NVARCHAR (50)   NULL,
    [NIGHTAMT]     DECIMAL (16, 2) NULL,
    [NIGHTSALCODE] NVARCHAR (50)   NULL,
    [FOODAMT]      DECIMAL (16, 2) NULL,
    [FOODSALCODE]  NVARCHAR (50)   NULL,
    [FOODAMT1]     DECIMAL (16, 2) NULL,
    [FATTAMT]      DECIMAL (16, 2) NULL,
    CONSTRAINT [PK_ROTET] PRIMARY KEY CLUSTERED ([ROTET] ASC)
);

