CREATE TABLE [dbo].[ROTECHG] (
    [ADATE]    DATETIME      NOT NULL,
    [NOBR]     NVARCHAR (50) NOT NULL,
    [ROTE]     NVARCHAR (50) NOT NULL,
    [CODE]     NVARCHAR (50) NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL,
    [AUTOKEY]  INT           IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_ROTECHG] PRIMARY KEY CLUSTERED ([ADATE] ASC, [NOBR] ASC)
);



