CREATE TABLE [dbo].[RSADVTP] (
    [ADVTPCD]   NVARCHAR (50) NOT NULL,
    [ADVTPNAME] NVARCHAR (50) NOT NULL,
    [KEY_MAN]   NVARCHAR (50) NOT NULL,
    [KEY_DATE]  DATETIME      NOT NULL,
    CONSTRAINT [PK_RSADVTP] PRIMARY KEY CLUSTERED ([ADVTPCD] ASC)
);

