CREATE TABLE [dbo].[RSADVUN] (
    [ADVUNCD]    NVARCHAR (50) NOT NULL,
    [ADVUNSNAME] NVARCHAR (50) NOT NULL,
    [ADVUNNAME]  NVARCHAR (50) NOT NULL,
    [ADVCMID]    NVARCHAR (50) NOT NULL,
    [ADVCMTEL]   NVARCHAR (50) NOT NULL,
    [ADVCMSUB]   NVARCHAR (50) CONSTRAINT [DF_RSADVUN_ADVCMSUB] DEFAULT ('') NOT NULL,
    [ADVCMFAX]   NVARCHAR (50) NOT NULL,
    [ADVCMADR1]  CHAR (60)     NOT NULL,
    [ADVCMADR2]  CHAR (60)     NOT NULL,
    [ADVCONTMAN] NVARCHAR (50) NOT NULL,
    [ADVCONTJOB] NVARCHAR (50) NOT NULL,
    [ADVCMEMAIL] NVARCHAR (50) NOT NULL,
    [ADVCMWWW]   NVARCHAR (50) NOT NULL,
    [ADVTPCD]    NVARCHAR (50) NOT NULL,
    [KEY_MAN]    NVARCHAR (50) NOT NULL,
    [KEY_DATE]   DATETIME      NOT NULL,
    CONSTRAINT [PK_RSADVUN] PRIMARY KEY CLUSTERED ([ADVUNCD] ASC)
);

