CREATE TABLE [dbo].[RSEMP] (
    [EMPID]     CHAR (10)       NOT NULL,
    [NAME_C]    CHAR (10)       NOT NULL,
    [NAME_E]    CHAR (30)       NULL,
    [BIRDT]     DATETIME        NOT NULL,
    [IDNO]      CHAR (10)       NOT NULL,
    [SEX]       CHAR (1)        NOT NULL,
    [TEL1]      CHAR (15)       NOT NULL,
    [ADDR1]     CHAR (60)       NOT NULL,
    [POSTCODE1] CHAR (5)        NOT NULL,
    [TEL2]      CHAR (15)       NOT NULL,
    [ADDR2]     CHAR (60)       NOT NULL,
    [POSTCODE2] CHAR (5)        NOT NULL,
    [BBCALL]    CHAR (10)       NOT NULL,
    [PASSWORD]  CHAR (8)        NULL,
    [GSM]       CHAR (10)       NOT NULL,
    [ARMY]      CHAR (4)        NULL,
    [EMAIL]     CHAR (40)       NOT NULL,
    [BORN_ADDR] CHAR (10)       NOT NULL,
    [BLOOD]     CHAR (2)        NULL,
    [PROVINCE]  CHAR (10)       NOT NULL,
    [KEY_MAN]   CHAR (8)        NOT NULL,
    [KEY_DATE]  DATETIME        NOT NULL,
    [DEPT]      CHAR (10)       NOT NULL,
    [JOB]       CHAR (4)        NOT NULL,
    [EMP_DATE]  DATETIME        NOT NULL,
    [RSOKTP]    CHAR (3)        NOT NULL,
    [MARRY]     CHAR (4)        NOT NULL,
    [LA_MAN]    BIT             NULL,
    [FA_MAN]    BIT             NULL,
    [OK_MAN]    BIT             NULL,
    [IN_MAN]    BIT             NULL,
    [GOOD_MAN]  BIT             NULL,
    [RESNO]     CHAR (4)        NULL,
    [A01]       DECIMAL (10)    NULL,
    [A02]       DECIMAL (10)    NULL,
    [A03]       DECIMAL (10)    NULL,
    [A04]       DECIMAL (10)    NULL,
    [MENO]      CHAR (20)       NULL,
    [LANG_E]    CHAR (1)        NULL,
    [LANG_J]    CHAR (1)        NULL,
    [LANG_T]    CHAR (1)        NULL,
    [LANG_M1]   CHAR (20)       NULL,
    [LANG_M2]   CHAR (20)       NULL,
    [LANG_T1]   CHAR (1)        NULL,
    [LANG_T2]   CHAR (1)        NULL,
    [BOODY]     CHAR (1)        NULL,
    [CAR]       BIT             NULL,
    [MOTOR]     BIT             NULL,
    [RS_NAME]   CHAR (12)       NULL,
    [RS_DEPT]   CHAR (20)       NULL,
    [RS_JOB]    CHAR (20)       NULL,
    [RS_IN]     BIT             NULL,
    [WORDEXCL]  CHAR (1)        NULL,
    [RS_SCHL1]  BIT             NULL,
    [RS_SCHL2]  BIT             NULL,
    [RS_SCHLN]  DECIMAL (18, 2) NULL,
    [SALADR]    CHAR (2)        NULL
);

