CREATE TABLE [dbo].[RSEMPREQ] (
    [DEPT]      NVARCHAR (50)   NOT NULL,
    [JOB]       NVARCHAR (50)   NOT NULL,
    [JOBL]      NVARCHAR (50)   NOT NULL,
    [RSJOBNAME] NVARCHAR (50)   NOT NULL,
    [PNS]       DECIMAL (16, 2) NOT NULL,
    [NAME_C]    NVARCHAR (50)   NOT NULL,
    [STAT]      NVARCHAR (50)   NOT NULL,
    [ADATE]     DATETIME        NOT NULL,
    [NOTE]      NVARCHAR (50)   NOT NULL,
    [ADRES]     NVARCHAR (50)   NOT NULL,
    [WORKADR]   NVARCHAR (50)   NOT NULL,
    [BDATE]     DATETIME        NOT NULL,
    [EDATE]     DATETIME        NOT NULL,
    [SALADR]    NVARCHAR (50)   NOT NULL,
    [BBODDY]    BIT             NOT NULL,
    [NSTUD]     BIT             NOT NULL,
    [SCHL1]     BIT             NOT NULL,
    [SCHL2]     BIT             NOT NULL,
    [SCHL3]     BIT             NOT NULL,
    [SCHL4]     BIT             NOT NULL,
    [SCHL5]     BIT             NOT NULL,
    [SUBJ1]     BIT             NOT NULL,
    [SUBJ2]     BIT             NOT NULL,
    [SUBJ3]     BIT             NOT NULL,
    [SUBJ4]     BIT             NOT NULL,
    [SUBJ5]     BIT             NOT NULL,
    [SUBJ6]     BIT             NOT NULL,
    [SUBJ7]     BIT             NOT NULL,
    [SUBJ8]     BIT             NOT NULL,
    [SUBJ9]     BIT             NOT NULL,
    [SUBJ10]    BIT             NOT NULL,
    [SUBJ11]    BIT             NOT NULL,
    [SUBJ12]    NVARCHAR (50)   NOT NULL,
    [SEX1]      BIT             NOT NULL,
    [SEX2]      BIT             NOT NULL,
    [SEX3]      BIT             NOT NULL,
    [LANG1]     BIT             NOT NULL,
    [LANG2]     BIT             NOT NULL,
    [LANG3]     BIT             NOT NULL,
    [LANG4]     BIT             NOT NULL,
    [LANG5]     BIT             NOT NULL,
    [WK_YRS]    DECIMAL (16, 2) NOT NULL,
    [BWK_YRS]   DECIMAL (16, 2) NOT NULL,
    [EWK_YRS]   DECIMAL (16, 2) NOT NULL,
    [MASTER]    NVARCHAR (60)   NOT NULL,
    [SPECIAL]   NVARCHAR (60)   NOT NULL,
    [KEY_MAN]   NVARCHAR (50)   NOT NULL,
    [KEY_DATE]  DATETIME        NOT NULL,
    [PLANNO]    NVARCHAR (50)   CONSTRAINT [DF_RSEMPREQ_PLANNO] DEFAULT ('') NOT NULL,
    [PROJNO]    NVARCHAR (50)   CONSTRAINT [DF_RSEMPREQ_PROJNO] DEFAULT ('') NOT NULL,
    [APPNO]     NVARCHAR (50)   CONSTRAINT [DF_RSEMPREQ_APPNO] DEFAULT ('') NOT NULL,
    [LICAN]     NVARCHAR (50)   CONSTRAINT [DF_RSEMPREQ_LICAN] DEFAULT ('') NOT NULL,
    [NOBR]      NVARCHAR (50)   CONSTRAINT [DF_RSEMPREQ_NOBR] DEFAULT ('') NOT NULL
);

