CREATE TABLE [dbo].[RSEPINT] (
    [EMPID]      NVARCHAR (50) NOT NULL,
    [RSEPINTSEQ] NVARCHAR (50) NOT NULL,
    [ADATE]      DATETIME      NOT NULL,
    [NOBR]       NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_RSEPINT] PRIMARY KEY CLUSTERED ([NOBR] ASC)
);

