CREATE TABLE [dbo].[RSEVLCD] (
    [EVLCD]    NVARCHAR (50) NOT NULL,
    [EVLNAME]  NVARCHAR (50) NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL,
    CONSTRAINT [PK_RSEVLCD] PRIMARY KEY CLUSTERED ([EVLCD] ASC)
);

