CREATE TABLE [dbo].[RSEVLGP] (
    [RSEVLGPCD] NVARCHAR (50) NOT NULL,
    [RSEVLGPNA] NVARCHAR (50) NOT NULL,
    [KEY_MAN]   NVARCHAR (50) NOT NULL,
    [KEY_DATE]  DATETIME      NOT NULL,
    CONSTRAINT [PK_RSEVLGP] PRIMARY KEY CLUSTERED ([RSEVLGPCD] ASC)
);

