CREATE TABLE [dbo].[RSINTPS] (
    [RSINTPSNO] NVARCHAR (50) NOT NULL,
    [RSINTPSNA] NVARCHAR (50) NOT NULL,
    [KEY_MAN]   NVARCHAR (50) NOT NULL,
    [KEY_DATE]  DATETIME      NOT NULL,
    CONSTRAINT [PK_RSINTPS] PRIMARY KEY CLUSTERED ([RSINTPSNO] ASC)
);

