CREATE TABLE [dbo].[RSOKTP] (
    [RSOKTP]   NVARCHAR (50) NOT NULL,
    [RSOKNAME] NVARCHAR (50) NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL,
    [RSDESC]   NVARCHAR (50) CONSTRAINT [DF_RSOKTP_RSDESC] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_RSOKTP] PRIMARY KEY CLUSTERED ([RSOKTP] ASC)
);

