CREATE TABLE [dbo].[RSRESD] (
    [RESNO]    NVARCHAR (50)   NOT NULL,
    [JOB]      NVARCHAR (50)   NOT NULL,
    [DEPT]     NVARCHAR (50)   NOT NULL,
    [JOBPNS]   DECIMAL (16, 2) NOT NULL,
    [RESITVNO] NVARCHAR (50)   NOT NULL,
    [RESTSTNO] NVARCHAR (50)   NOT NULL,
    [FEE]      INT             NOT NULL,
    [REJOB]    NVARCHAR (50)   CONSTRAINT [DF_RSRESD_REJOB] DEFAULT ('') NOT NULL
);

