CREATE TABLE [dbo].[RSRES] (
    [RESNO]    NVARCHAR (50)   NOT NULL,
    [ADVUNCD]  NVARCHAR (50)   NOT NULL,
    [ADVTPCD]  NVARCHAR (50)   NOT NULL,
    [ADVDATE]  DATETIME        NOT NULL,
    [ADEDATE]  DATETIME        CONSTRAINT [DF_RSRES_ADEDATE] DEFAULT (getdate()) NOT NULL,
    [WDVDATE]  DATETIME        CONSTRAINT [DF_RSRES_WDVDATE] DEFAULT (getdate()) NOT NULL,
    [WDEDATE]  DATETIME        CONSTRAINT [DF_RSRES_WDEDATE] DEFAULT (getdate()) NOT NULL,
    [ADVFEE]   DECIMAL (16, 2) NOT NULL,
    [ADVQTY]   DECIMAL (16, 2) CONSTRAINT [DF_RSRES_ADVQTY] DEFAULT ((0)) NOT NULL,
    [KEY_MAN]  NVARCHAR (50)   NOT NULL,
    [KEY_DATE] DATETIME        NOT NULL
);

