CREATE TABLE [dbo].[RSWORKS] (
    [EMPID]    NVARCHAR (50)   NOT NULL,
    [COMPANY]  NVARCHAR (50)   NOT NULL,
    [TITLE]    NVARCHAR (50)   NOT NULL,
    [BDATE]    DATETIME        NOT NULL,
    [EDATE]    DATETIME        NOT NULL,
    [JOB]      NVARCHAR (50)   NOT NULL,
    [NOTE]     NVARCHAR (50)   NOT NULL,
    [KEY_MAN]  NVARCHAR (50)   NOT NULL,
    [KEY_DATE] DATETIME        NOT NULL,
    [WYEAR]    DECIMAL (16, 2) CONSTRAINT [DF_RSWORKS_WYEAR] DEFAULT ((0)) NOT NULL,
    [SALAMT]   INT             CONSTRAINT [DF_RSWORKS_SALAMT] DEFAULT ((0)) NOT NULL,
    [LEAVE]    NVARCHAR (50)   CONSTRAINT [DF_RSWORKS_LEAVE] DEFAULT ('') NOT NULL,
    [SHOP]     BIT             CONSTRAINT [DF_RSWORKS_SHOP] DEFAULT ((0)) NOT NULL
);

