CREATE TABLE [dbo].[RULES] (
    [RULES]      NVARCHAR (50)   NOT NULL,
    [RULE_CODE]  NVARCHAR (50)   NOT NULL,
    [TIME_BEGIN] NVARCHAR (5)    NOT NULL,
    [TIME_END]   NVARCHAR (5)    NOT NULL,
    [HOUR_BEGIN] DECIMAL (16, 2) NOT NULL,
    [HOUR_END]   DECIMAL (16, 2) NOT NULL,
    [FIXAMT]     DECIMAL (16, 2) NOT NULL,
    [FIXRATE]    DECIMAL (16, 2) NOT NULL,
    [KEY_DATE]   DATETIME        NOT NULL,
    [KEY_MAN]    NVARCHAR (50)   NOT NULL,
    [TYPE1]      NVARCHAR (50)   NOT NULL,
    [TYPE2]      NVARCHAR (50)   NOT NULL,
    CONSTRAINT [PK_RULES] PRIMARY KEY CLUSTERED ([RULES] ASC, [RULE_CODE] ASC)
);

