CREATE TABLE [dbo].[RULE] (
    [RULE_CODE] NVARCHAR (50) NOT NULL,
    [RULE_NAME] NVARCHAR (50) NOT NULL,
    [ISFIX]     BIT           NOT NULL,
    [ISRATE]    BIT           NOT NULL,
    [ISFIXRATE] BIT           NOT NULL,
    [KEY_DATE]  DATETIME      NOT NULL,
    [KEY_MAN]   NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_RULE] PRIMARY KEY CLUSTERED ([RULE_CODE] ASC)
);

