CREATE TABLE [dbo].[SALATTR] (
    [SALATTR]   NVARCHAR (50) NOT NULL,
    [ATTR_NAME] NVARCHAR (50) NOT NULL,
    [NOT_DISP]  BIT           NOT NULL,
    [BASIC]     BIT           NOT NULL,
    [TYPE]      NVARCHAR (50) NOT NULL,
    [FLAG]      NVARCHAR (50) NOT NULL,
    [TAX]       BIT           NOT NULL,
    CONSTRAINT [PK_SALATTR] PRIMARY KEY CLUSTERED ([SALATTR] ASC)
);

