CREATE TABLE [dbo].[SALABS] (
    [YYMM]       NVARCHAR (50)   NOT NULL,
    [NOBR]       NVARCHAR (50)   NOT NULL,
    [ADATE]      DATETIME        NOT NULL,
    [BTIME]      NVARCHAR (50)   CONSTRAINT [DF_SALABS_BTIME] DEFAULT ('') NOT NULL,
    [H_CODE]     NVARCHAR (50)   NOT NULL,
    [SAL_CODE]   NVARCHAR (50)   NOT NULL,
    [AMT]        DECIMAL (16, 2) NOT NULL,
    [ADJ_CODE]   NVARCHAR (50)   NOT NULL,
    [MLSSALCODE] NVARCHAR (50)   NOT NULL,
    [KEY_DATE]   DATETIME        NOT NULL,
    [KEY_MAN]    NVARCHAR (50)   NOT NULL,
    [SALSEQ]     NVARCHAR (50)   NOT NULL,
    CONSTRAINT [PK_SALABS] PRIMARY KEY CLUSTERED ([YYMM] ASC, [NOBR] ASC, [ADATE] ASC, [BTIME] ASC, [H_CODE] ASC, [SAL_CODE] ASC, [MLSSALCODE] ASC)
);

