CREATE TABLE [dbo].[SALADR] (
    [SALADR]   NVARCHAR (50) NOT NULL,
    [SALNAME]  NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_SALADR] PRIMARY KEY CLUSTERED ([SALADR] ASC)
);

