CREATE TABLE [dbo].[SALATT] (
    [AUTO]      INT             IDENTITY (1, 1) NOT NULL,
    [SOURCE]    NVARCHAR (50)   NOT NULL,
    [NOBR]      NVARCHAR (50)   NOT NULL,
    [ADATE]     DATETIME        NOT NULL,
    [ROTE]      NVARCHAR (50)   NOT NULL,
    [YYMM]      NVARCHAR (50)   NOT NULL,
    [SEQ]       NVARCHAR (50)   NOT NULL,
    [SAL_CODE]  NVARCHAR (50)   NOT NULL,
    [AMT]       DECIMAL (14, 4) NOT NULL,
    [KEY_DATE]  DATETIME        NOT NULL,
    [KEY_MAN]   NVARCHAR (50)   NOT NULL,
    [NOTE]      NVARCHAR (500)  NOT NULL,
    [BTIME]     NVARCHAR (50)   NULL,
    [ETIME]     NVARCHAR (50)   NULL,
    [CALC_TYPE] NVARCHAR (50)   NULL,
    CONSTRAINT [PK_SALATT] PRIMARY KEY CLUSTERED ([AUTO] ASC)
);



