CREATE TABLE [dbo].[SALBASTD] (
    [ADATE]    DATETIME        CONSTRAINT [DF_SALBASTD_ADATE] DEFAULT (getdate()) NOT NULL,
    [NOBR]     NVARCHAR (50)   CONSTRAINT [DF_SALBASTD_NOBR] DEFAULT ('') NOT NULL,
    [SAL_CODE] NVARCHAR (50)   CONSTRAINT [DF_SALBASTD_SAL_CODE] DEFAULT ('') NOT NULL,
    [AMT]      DECIMAL (16, 2) CONSTRAINT [DF_SALBASTD_AMT] DEFAULT ((0)) NOT NULL,
    [KEY_MAN]  NVARCHAR (50)   CONSTRAINT [DF_SALBASTD_KEY_MAN] DEFAULT ('') NOT NULL,
    [KEY_DATE] DATETIME        CONSTRAINT [DF_SALBASTD_KEY_DATE] DEFAULT (getdate()) NOT NULL,
    [AMTB]     DECIMAL (16, 2) CONSTRAINT [DF_SALBASTD_AMTB] DEFAULT ((0)) NOT NULL,
    [MENO]     NVARCHAR (50)   CONSTRAINT [DF_SALBASTD_MENO] DEFAULT ('') NOT NULL,
    [DDATE]    DATETIME        CONSTRAINT [DF_SALBASTD_DDATE] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_SALBASTD] PRIMARY KEY CLUSTERED ([ADATE] ASC, [NOBR] ASC, [SAL_CODE] ASC)
);

