CREATE TABLE [dbo].[SALBASD1] (
    [YYMM]     NVARCHAR (50)   CONSTRAINT [DF_Table_1_ADATE] DEFAULT (getdate()) NOT NULL,
    [NOBR]     NVARCHAR (50)   CONSTRAINT [DF_SALBASD1_NOBR] DEFAULT ('') NOT NULL,
    [SAL_CODE] NVARCHAR (50)   CONSTRAINT [DF_SALBASD1_SAL_CODE] DEFAULT ('') NOT NULL,
    [AMT]      DECIMAL (16, 2) CONSTRAINT [DF_SALBASD1_AMT] DEFAULT ((0)) NOT NULL,
    [KEY_MAN]  NVARCHAR (50)   CONSTRAINT [DF_SALBASD1_KEY_MAN] DEFAULT ('') NOT NULL,
    [KEY_DATE] DATETIME        CONSTRAINT [DF_SALBASD1_KEY_DATE] DEFAULT (getdate()) NOT NULL,
    [AMTB]     DECIMAL (16, 2) CONSTRAINT [DF_SALBASD1_AMTB] DEFAULT ((0)) NOT NULL,
    [MENO]     NVARCHAR (50)   CONSTRAINT [DF_SALBASD1_MENO] DEFAULT ('') NOT NULL,
    [SEQ]      NVARCHAR (50)   CONSTRAINT [DF_Table_1_DDATE] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_SALBASD1] PRIMARY KEY CLUSTERED ([YYMM] ASC, [NOBR] ASC, [SAL_CODE] ASC, [SEQ] ASC)
);

