CREATE TABLE [dbo].[SALBASE] (
    [AUTO]        INT            IDENTITY (1, 1) NOT NULL,
    [CALCTYPE]    NVARCHAR (50)  CONSTRAINT [DF_SALBASE_CALCTYPE] DEFAULT ('') NOT NULL,
    [SALNAME]     NVARCHAR (50)  NOT NULL,
    [REFFUNCTION] NVARCHAR (MAX) CONSTRAINT [DF_SALBASE_REFFUNCTION] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_SALBASE] PRIMARY KEY CLUSTERED ([AUTO] ASC)
);

