CREATE TABLE [dbo].[SALCODE] (
    [SAL_CODE]      NVARCHAR (50)   NOT NULL,
    [SAL_NAME]      NVARCHAR (50)   NOT NULL,
    [SAL_ATTR]      NVARCHAR (50)   NOT NULL,
    [KEY_MAN]       NVARCHAR (50)   NOT NULL,
    [KEY_DATE]      DATETIME        NOT NULL,
    [SOS_ID]        NVARCHAR (50)   NOT NULL,
    [WEL]           BIT             NOT NULL,
    [OT]            BIT             NOT NULL,
    [MAX_AMT]       DECIMAL (16, 2) NOT NULL,
    [MIN_AMT]       DECIMAL (16, 2) NOT NULL,
    [CAL_FREQ]      NVARCHAR (50)   NOT NULL,
    [CAL_TYPE]      NVARCHAR (50)   NOT NULL,
    [HRS]           DECIMAL (16, 2) NOT NULL,
    [MONTHTYPE]     NVARCHAR (50)   NOT NULL,
    [DEFINEDAYS]    DECIMAL (16, 2) NOT NULL,
    [ADVPAY]        BIT             NOT NULL,
    [ACCCD]         NVARCHAR (50)   NOT NULL,
    [ATT]           BIT             NOT NULL,
    [DAILY]         BIT             NOT NULL,
    [RETIRE]        BIT             NOT NULL,
    [FORBANK]       BIT             NOT NULL,
    [FORCASH]       BIT             NOT NULL,
    [NOTFREQ]       BIT             NOT NULL,
    [TAXRATE]       DECIMAL (16, 2) NOT NULL,
    [YEARPAY]       BIT             NOT NULL,
    [ABSPAY]        BIT             NOT NULL,
    [INSLAB]        BIT             NOT NULL,
    [LATER]         BIT             CONSTRAINT [DF_SALCODE_LATER] DEFAULT ((0)) NOT NULL,
    [SAL_ENAME]     NVARCHAR (60)   CONSTRAINT [DF_SALCODE_SAL_ENAME] DEFAULT ('') NOT NULL,
    [OLDRETIRE]     BIT             NOT NULL,
    [SALBASD1]      BIT             NOT NULL,
    [SAL_CODE_DISP] NVARCHAR (50)   NULL,
    [SUP]           BIT             NOT NULL,
    [SAL_NAME_VN]   NVARCHAR (50)   NOT NULL,
    [SALCODE_GROUP] NVARCHAR (50)   NULL,
    [SALBASE]       NVARCHAR (50)   CONSTRAINT [DF_SALCODE_SALBASE] DEFAULT ('') NULL,
    [NOTFREQSEQ]    BIT             DEFAULT ((0)) NOT NULL,
    [SORT]          INT             NULL,
    [SALSEQ]        NVARCHAR (50)   DEFAULT ('') NOT NULL,
    [ImportSEQ2]    BIT             DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_SALCODE] PRIMARY KEY CLUSTERED ([SAL_CODE] ASC)
);



