CREATE TABLE [dbo].[SALFUNCTION] (
    [AUTO]     INT            IDENTITY (1000, 1) NOT NULL,
    [CALCTYPE] NVARCHAR (50)  CONSTRAINT [DF_SALFUNCTION_CALTYPE] DEFAULT ('') NOT NULL,
    [ITEM]     NVARCHAR (50)  NOT NULL,
    [SCRIPT]   NVARCHAR (MAX) NOT NULL,
    [SORT]     INT            CONSTRAINT [DF_SALFUNCTION_SORT] DEFAULT ((0)) NOT NULL,
    [CALC]     BIT            CONSTRAINT [DF_SALFUNCTION_USER] DEFAULT ((1)) NOT NULL,
    [REF]      BIT            CONSTRAINT [DF_SALFUNCTION_REF] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_SALFUNCTION] PRIMARY KEY CLUSTERED ([AUTO] ASC)
);

