CREATE TABLE [dbo].[SALTYCD] (
    [SALTYCD]   NVARCHAR (50)   NOT NULL,
    [SALTYNAME] NVARCHAR (50)   NOT NULL,
    [PARA1]     NVARCHAR (50)   NOT NULL,
    [DEFINE1]   DECIMAL (16, 2) NOT NULL,
    [PARA2]     NVARCHAR (50)   NOT NULL,
    [DEFINE2]   DECIMAL (16, 2) NOT NULL,
    [PARA3]     NVARCHAR (50)   NOT NULL,
    [DEFINE3]   DECIMAL (16, 2) NOT NULL,
    [KEY_DATE]  DATETIME        NOT NULL,
    [KEY_MAN]   NVARCHAR (50)   NOT NULL,
    CONSTRAINT [PK_SALTYCD] PRIMARY KEY CLUSTERED ([SALTYCD] ASC)
);

