CREATE TABLE [dbo].[SCHL] (
    [AUTO]        INT            IDENTITY (1, 1) NOT NULL,
    [NOBR]        NVARCHAR (50)  NOT NULL,
    [EDUCCODE]    NVARCHAR (50)  NOT NULL,
    [ADATE]       DATETIME       NOT NULL,
    [OK]          BIT            NOT NULL,
    [SCHL]        NVARCHAR (100) CONSTRAINT [DF_SCHL_SCHL] DEFAULT ('') NOT NULL,
    [SUBJ]        NVARCHAR (100) CONSTRAINT [DF_SCHL_SUBJ] DEFAULT ('') NOT NULL,
    [DATE_B]      NVARCHAR (50)  NOT NULL,
    [DATE_E]      NVARCHAR (50)  NOT NULL,
    [KEY_DATE]    DATETIME       NOT NULL,
    [KEY_MAN]     NVARCHAR (50)  NOT NULL,
    [SUBJCODE]    NVARCHAR (50)  CONSTRAINT [DF_SCHL_SUBJCODE] DEFAULT ('') NOT NULL,
    [schl_id]     INT            NOT NULL,
    [DayOrNight]  NVARCHAR (50)  NULL,
    [SUBJ_DETAIL] NVARCHAR (MAX) NULL,
    [Graduated]   BIT            NOT NULL,
    [MEMO]        NVARCHAR (500) NULL,
    CONSTRAINT [PK_SCHL] PRIMARY KEY CLUSTERED ([AUTO] ASC)
);

