CREATE TABLE [dbo].[SQLUPDATETABLE] (
    [AUTOKEY]  INT            IDENTITY (1, 1) NOT NULL,
    [FILENAME] NVARCHAR (200) NOT NULL,
    [USERID]   NVARCHAR (50)  NOT NULL,
    [TIMEB]    DATETIME       NULL,
    [TIMEE]    DATETIME       NULL,
    [NOTE]     TEXT           NULL,
    CONSTRAINT [PK_SQLUPDATETABLE] PRIMARY KEY CLUSTERED ([AUTOKEY] ASC)
);

