CREATE TABLE [dbo].[STATCHG] (
    [ADATE]    DATETIME      NOT NULL,
    [NOBR]     NVARCHAR (50) NOT NULL,
    [STAT]     NVARCHAR (50) NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL,
    CONSTRAINT [PK_STATCHG] PRIMARY KEY CLUSTERED ([ADATE] ASC, [NOBR] ASC)
);

