CREATE TABLE [dbo].[STATION] (
    [Code]        NVARCHAR (50) NOT NULL,
    [StationName] NVARCHAR (50) NOT NULL,
    [KEY_DATE]    DATETIME      NOT NULL,
    [KEY_MAN]     NVARCHAR (50) NOT NULL,
    [AMT]         INT           NULL,
    [CODE_DISP]   NVARCHAR (50) NULL,
    CONSTRAINT [PK_STATION] PRIMARY KEY CLUSTERED ([Code] ASC)
);

