CREATE TABLE [dbo].[SUBCODE] (
    [SUBCODE]  NVARCHAR (50) NOT NULL,
    [SUBDESC]  NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_SUBCODE] PRIMARY KEY CLUSTERED ([SUBCODE] ASC)
);

