CREATE TABLE [dbo].[SYSLOG] (
    [ID]       INT            IDENTITY (1, 1) NOT NULL,
    [TYPE]     NVARCHAR (50)  NOT NULL,
    [SOURCE]   NVARCHAR (50)  NOT NULL,
    [SID]      INT            NULL,
    [GUID]     NVARCHAR (50)  NULL,
    [TITLE]    NVARCHAR (500) NOT NULL,
    [NOTE]     NVARCHAR (MAX) NULL,
    [NOTE1]    NVARCHAR (500) NULL,
    [NOTE2]    NVARCHAR (50)  NULL,
    [NOTE3]    NVARCHAR (50)  NULL,
    [NOTE4]    NVARCHAR (50)  NULL,
    [NOTE5]    NVARCHAR (50)  NULL,
    [KEY_DATE] DATETIME       NOT NULL,
    [KEY_MAN]  NVARCHAR (50)  NOT NULL,
    CONSTRAINT [PK_SYSLOG] PRIMARY KEY CLUSTERED ([ID] ASC)
);

