CREATE TABLE [dbo].[TableAtt] (
    [FIELDNAME] NVARCHAR (50) DEFAULT ('') NOT NULL,
    [CAPTION]   NVARCHAR (50) DEFAULT ('') NOT NULL,
    [DISPLAY]   BIT           CONSTRAINT [DF_TableAtt_DISPLAY] DEFAULT ((0)) NOT NULL,
    [KEY_DATE]  DATETIME      NULL,
    [KEY_MAN]   NVARCHAR (50) NULL,
    CONSTRAINT [PK_TableAtt] PRIMARY KEY CLUSTERED ([FIELDNAME] ASC)
);

