CREATE TABLE [dbo].[TAXLVL] (
    [YEAR]     NVARCHAR (50)   NOT NULL,
    [AMT_H]    DECIMAL (16, 2) NOT NULL,
    [AMT_L]    DECIMAL (16, 2) NOT NULL,
    [PER0]     DECIMAL (16, 2) NOT NULL,
    [PER1]     DECIMAL (16, 2) NOT NULL,
    [PER2]     DECIMAL (16, 2) NOT NULL,
    [PER3]     DECIMAL (16, 2) NOT NULL,
    [PER4]     DECIMAL (16, 2) NOT NULL,
    [PER5]     DECIMAL (16, 2) NOT NULL,
    [PER6]     DECIMAL (16, 2) NOT NULL,
    [PER7]     DECIMAL (16, 2) NOT NULL,
    [PER8]     DECIMAL (16, 2) NOT NULL,
    [PER9]     DECIMAL (16, 2) NOT NULL,
    [PER10]    DECIMAL (16, 2) NOT NULL,
    [PER11]    DECIMAL (16, 2) CONSTRAINT [DF_TAXLVL_PER11] DEFAULT ((0)) NOT NULL,
    [KEY_MAN]  NVARCHAR (50)   NOT NULL,
    [KEY_DATE] DATETIME        NOT NULL,
    CONSTRAINT [PK_TAXLVL] PRIMARY KEY CLUSTERED ([YEAR] ASC, [AMT_H] ASC)
);

