CREATE TABLE [dbo].[TBASE] (
    [INCOMP]    BIT           NOT NULL,
    [NOBR]      NVARCHAR (50) NOT NULL,
    [NAME_C]    NVARCHAR (50) NOT NULL,
    [ADDR]      NVARCHAR (60) NOT NULL,
    [TEL]       NVARCHAR (50) NOT NULL,
    [EMAIL]     NVARCHAR (50) NOT NULL,
    [GSM]       NVARCHAR (50) NOT NULL,
    [IDNO]      NVARCHAR (50) NOT NULL,
    [KEY_MAN]   NVARCHAR (50) NOT NULL,
    [KEY_DATE]  DATETIME      NOT NULL,
    [IDCODE]    NVARCHAR (50) CONSTRAINT [DF_TBASE_IDCODE] DEFAULT ('') NOT NULL,
    [POSTCODE1] NVARCHAR (50) CONSTRAINT [DF_TBASE_POSTCODE1] DEFAULT ('') NOT NULL,
    [POSTCODE2] NVARCHAR (50) CONSTRAINT [DF_TBASE_POSTCODE2] DEFAULT ('') NOT NULL,
    [SALADR]    NVARCHAR (50) NULL,
    [TAXNO]     NVARCHAR (50) CONSTRAINT [DF_TBASE_TAXNO] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_TBASE] PRIMARY KEY CLUSTERED ([INCOMP] ASC, [NOBR] ASC)
);



