CREATE TABLE [dbo].[TCODE] (
    [T_CODE]   NVARCHAR (50) NOT NULL,
    [T_NAME]   NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_TCODE] PRIMARY KEY CLUSTERED ([T_CODE] ASC)
);

