CREATE TABLE [dbo].[TMTABLE] (
    [YYMM]     NVARCHAR (50)   NOT NULL,
    [NOBR]     NVARCHAR (50)   NOT NULL,
    [D1]       NVARCHAR (50)   NOT NULL,
    [D2]       NVARCHAR (50)   NOT NULL,
    [D3]       NVARCHAR (50)   NOT NULL,
    [D4]       NVARCHAR (50)   NOT NULL,
    [D5]       NVARCHAR (50)   NOT NULL,
    [D6]       NVARCHAR (50)   NOT NULL,
    [D7]       NVARCHAR (50)   NOT NULL,
    [D8]       NVARCHAR (50)   NOT NULL,
    [D9]       NVARCHAR (50)   NOT NULL,
    [D10]      NVARCHAR (50)   NOT NULL,
    [D11]      NVARCHAR (50)   NOT NULL,
    [D12]      NVARCHAR (50)   NOT NULL,
    [D13]      NVARCHAR (50)   NOT NULL,
    [D14]      NVARCHAR (50)   NOT NULL,
    [D15]      NVARCHAR (50)   NOT NULL,
    [D16]      NVARCHAR (50)   NOT NULL,
    [D17]      NVARCHAR (50)   NOT NULL,
    [D18]      NVARCHAR (50)   NOT NULL,
    [D19]      NVARCHAR (50)   NOT NULL,
    [D20]      NVARCHAR (50)   NOT NULL,
    [D21]      NVARCHAR (50)   NOT NULL,
    [D22]      NVARCHAR (50)   NOT NULL,
    [D23]      NVARCHAR (50)   NOT NULL,
    [D24]      NVARCHAR (50)   NOT NULL,
    [D25]      NVARCHAR (50)   NOT NULL,
    [D26]      NVARCHAR (50)   NOT NULL,
    [D27]      NVARCHAR (50)   NOT NULL,
    [D28]      NVARCHAR (50)   NOT NULL,
    [D29]      NVARCHAR (50)   NOT NULL,
    [D30]      NVARCHAR (50)   NOT NULL,
    [D31]      NVARCHAR (50)   NOT NULL,
    [KEY_MAN]  NVARCHAR (50)   NOT NULL,
    [KEY_DATE] DATETIME        NOT NULL,
    [NO]       DECIMAL (16, 2) NOT NULL,
    [HOLIS]    DECIMAL (16, 2) NOT NULL,
    [FREQ_NO]  DECIMAL (16, 2) NOT NULL,
    CONSTRAINT [PK_TMTABLE] PRIMARY KEY CLUSTERED ([YYMM] ASC, [NOBR] ASC)
);

