CREATE TABLE [dbo].[TR2DOCD] (
    [TODOCODE]  NVARCHAR (50) NOT NULL,
    [TODODESCR] NVARCHAR (50) NOT NULL,
    [KEY_MAN]   NVARCHAR (50) NOT NULL,
    [KEY_DATE]  DATETIME      NOT NULL,
    [NOTE]      NVARCHAR (60) NOT NULL,
    [DAYS]      INT           NOT NULL,
    [USED]      BIT           NOT NULL,
    CONSTRAINT [PK_TR2DOCD] PRIMARY KEY CLUSTERED ([TODOCODE] ASC)
);

