CREATE TABLE [dbo].[TRADMITT] (
    [TR_NO]    NVARCHAR (50) NOT NULL,
    [TR_NAME]  NVARCHAR (50) NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL,
    [OLD]      NVARCHAR (50) CONSTRAINT [DF_TRADMITT_OLD] DEFAULT ('') NOT NULL,
    [DEPT]     NVARCHAR (50) CONSTRAINT [DF_TRADMITT_DEPT] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_TRADMITT] PRIMARY KEY CLUSTERED ([TR_NO] ASC)
);

