CREATE TABLE [dbo].[TRADDRCD] (
    [ADDRCD]    NVARCHAR (50)  NOT NULL,
    [ADDRDESCR] NVARCHAR (60)  NOT NULL,
    [KEY_MAN]   NVARCHAR (50)  NOT NULL,
    [KEY_DATE]  DATETIME       NOT NULL,
    [ADDR]      NVARCHAR (120) CONSTRAINT [DF_TRADDRCD_ADDR] DEFAULT ('') NOT NULL,
    [TEL]       NVARCHAR (50)  CONSTRAINT [DF_TRADDRCD_TEL] DEFAULT ('') NOT NULL,
    [NAME]      NVARCHAR (50)  CONSTRAINT [DF_TRADDRCD_NAME] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_TRADDRCD] PRIMARY KEY CLUSTERED ([ADDRCD] ASC)
);

