CREATE TABLE [dbo].[TRADECD] (
    [TRADE_CODE] NVARCHAR (50) NOT NULL,
    [TRADE]      NVARCHAR (50) CONSTRAINT [DF_TRADECD_TRADE] DEFAULT ('') NOT NULL,
    [KEY_DATE]   DATETIME      NOT NULL,
    [KEY_MAN]    NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_TRADECD] PRIMARY KEY CLUSTERED ([TRADE_CODE] ASC)
);

