CREATE TABLE [dbo].[TRADMIT] (
    [NOBR]     NVARCHAR (50) NOT NULL,
    [TR_DATE]  DATETIME      NOT NULL,
    [TR_NO]    NVARCHAR (50) NOT NULL,
    [TR_CHECK] NVARCHAR (50) NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL,
    [OLD]      NVARCHAR (50) CONSTRAINT [DF_TRADMIT_OLD] DEFAULT ('') NOT NULL
);

