CREATE TABLE [dbo].[TRAPPLY] (
    [TRYEARNO] NVARCHAR (50) NOT NULL,
    [REC]      NVARCHAR (50) NOT NULL,
    [APPLYNO]  NVARCHAR (50) NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL,
    [TRDATE]   DATETIME      CONSTRAINT [DF_TRAPPLY_TRDATE] DEFAULT (getdate()) NOT NULL
);

