CREATE TABLE [dbo].[TRASKCD] (
    [ASKCODE]   NVARCHAR (50) NOT NULL,
    [ASKDESCRC] NVARCHAR (60) NOT NULL,
    [ASKDESCRE] NVARCHAR (50) NOT NULL,
    [TEMPLATE]  NVARCHAR (50) NOT NULL,
    [KEY_MAN]   NVARCHAR (50) NOT NULL,
    [KEY_DATE]  DATETIME      NOT NULL,
    [VALCODE]   NVARCHAR (50) NOT NULL,
    [TCR_NO]    NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_TRASKCD] PRIMARY KEY CLUSTERED ([ASKCODE] ASC)
);

