CREATE TABLE [dbo].[TRASKDT] (
    [COSCODE]  NVARCHAR (50)   NOT NULL,
    [YYMM]     NVARCHAR (50)   NOT NULL,
    [SER]      NVARCHAR (50)   NOT NULL,
    [ASKCODE]  NVARCHAR (50)   NOT NULL,
    [L1]       SMALLINT        NOT NULL,
    [L2]       SMALLINT        NOT NULL,
    [L3]       SMALLINT        NOT NULL,
    [L4]       SMALLINT        NOT NULL,
    [L5]       SMALLINT        NOT NULL,
    [KEY_MAN]  NVARCHAR (50)   NOT NULL,
    [KEY_DATE] DATETIME        NOT NULL,
    [NOTE]     NVARCHAR (60)   NOT NULL,
    [VALCODE]  NVARCHAR (50)   NOT NULL,
    [TCR_NO]   NVARCHAR (50)   CONSTRAINT [DF_TRASKDT_TCR_NO] DEFAULT ('') NOT NULL,
    [LTOT]     DECIMAL (16, 2) CONSTRAINT [DF_TRASKDT_LTOT] DEFAULT ((0)) NOT NULL,
    [HRS]      DECIMAL (16, 2) CONSTRAINT [DF_TRASKDT_HRS] DEFAULT ((0)) NOT NULL,
    [ASKGRD]   NVARCHAR (50)   CONSTRAINT [DF_TRASKDT_ASKGRD] DEFAULT ('') NOT NULL
);

