CREATE TABLE [dbo].[TRASSCODE] (
    [TR_ASNO]      VARCHAR (50) NOT NULL,
    [TR_ASNO_DISP] VARCHAR (50) NOT NULL,
    [TR_ASNAME]    VARCHAR (50) NOT NULL,
    [TEL]          VARCHAR (50) NOT NULL,
    [KEY_MAN]      VARCHAR (50) NOT NULL,
    [KEY_DATE]     DATETIME     NOT NULL
);


GO
CREATE NONCLUSTERED INDEX [TR_ASNO]
    ON [dbo].[TRASSCODE]([TR_ASNO] ASC);

