CREATE TABLE [dbo].[TRCOSCD] (
    [COSCODE]   NVARCHAR (50)  NOT NULL,
    [DESCRC]    NVARCHAR (50)  NOT NULL,
    [SUBCODE]   NVARCHAR (50)  NOT NULL,
    [KEY_MAN]   NVARCHAR (50)  NOT NULL,
    [KEY_DATE]  DATETIME       NOT NULL,
    [COSINTRO]  NVARCHAR (200) NOT NULL,
    [TR_PERSON] NVARCHAR (200) NOT NULL,
    [TRADDR]    NVARCHAR (60)  NOT NULL,
    [DESCRE]    NVARCHAR (200) NOT NULL
);

