CREATE TABLE [dbo].[TRCOMPY] (
    [TR_COMP]      NVARCHAR (50) NOT NULL,
    [TR_COMP_DISP] NVARCHAR (50) NOT NULL,
    [TR_COMP_NAME] NVARCHAR (50) NOT NULL,
    [KEY_MAN]      NVARCHAR (50) NOT NULL,
    [KEY_DATE]     DATETIME      NOT NULL,
    [TEL]          NVARCHAR (50) NULL,
    CONSTRAINT [PK_TRCOMPY] PRIMARY KEY CLUSTERED ([TR_COMP] ASC)
);


GO
CREATE NONCLUSTERED INDEX [TR_COMP]
    ON [dbo].[TRCOMPY]([TR_COMP] ASC);

