CREATE TABLE [dbo].[TRCOSP] (
    [AUTO]      INT             IDENTITY (1, 1) NOT NULL,
    [NOBR]      NVARCHAR (50)   NOT NULL,
    [COURSE]    NVARCHAR (50)   NOT NULL,
    [CLOSE_]    BIT             NOT NULL,
    [AT_HRS]    DECIMAL (16, 2) NOT NULL,
    [TR_MEMO]   NVARCHAR (200)  NOT NULL,
    [PROVE]     NVARCHAR (50)   NOT NULL,
    [TR_REPO]   BIT             NOT NULL,
    [TR_ASDATE] DATETIME        NULL,
    [APPLYNO]   NVARCHAR (50)   NOT NULL,
    [RECEIVER]  NVARCHAR (50)   NOT NULL,
    [KAVL]      NVARCHAR (50)   NULL,
    [KEY_DATE]  DATETIME        NOT NULL,
    [KEY_MAN]   NVARCHAR (50)   NOT NULL,
    [ST_HRS]    DECIMAL (16, 2) NULL,
    CONSTRAINT [PK_TRCOSP] PRIMARY KEY CLUSTERED ([AUTO] ASC)
);

