CREATE TABLE [dbo].[TRCOSTR] (
    [TCR_NO]  NVARCHAR (50) NOT NULL,
    [COSCODE] NVARCHAR (50) NOT NULL,
    [SER]     NVARCHAR (50) NOT NULL,
    [YYMM]    NVARCHAR (50) NOT NULL,
    [NOTE]    NVARCHAR (50) NOT NULL
);

