CREATE TABLE [dbo].[TRCOSFEE] (
    [COSCODE]  NVARCHAR (50)   NOT NULL,
    [YYMM]     NVARCHAR (50)   NOT NULL,
    [SER]      NVARCHAR (50)   NOT NULL,
    [FEECODE]  NVARCHAR (50)   NOT NULL,
    [QTY]      DECIMAL (16, 2) NOT NULL,
    [PRICE]    DECIMAL (16, 2) NOT NULL,
    [TAX]      INT             NOT NULL,
    [AMT]      INT             NOT NULL,
    [FEETYPE]  NVARCHAR (50)   NOT NULL,
    [TCR_NO]   NVARCHAR (50)   CONSTRAINT [DF_TRCOSFEE_TCR_NO] DEFAULT ('') NOT NULL,
    [CAL]      BIT             NOT NULL,
    [KEY_MAN]  NVARCHAR (50)   CONSTRAINT [DF_TRCOSFEE_KEY_MAN] DEFAULT ('') NOT NULL,
    [KEY_DATE] DATETIME        CONSTRAINT [DF_TRCOSFEE_KEY_DATE] DEFAULT (getdate()) NOT NULL
);

