CREATE TABLE [dbo].[TRCOSF] (
    [AUTO]      INT             IDENTITY (1, 1) NOT NULL,
    [COURSE]    NVARCHAR (50)   NOT NULL,
    [DATE_B]    DATETIME        NOT NULL,
    [DATE_E]    DATETIME        NOT NULL,
    [COS_FEE]   DECIMAL (16, 2) NOT NULL,
    [NOBR]      NVARCHAR (50)   NOT NULL,
    [TR_COMP]   NVARCHAR (60)   NOT NULL,
    [TR_HRS]    DECIMAL (16, 2) NOT NULL,
    [ABORAD]    BIT             NOT NULL,
    [CLOSE_]    BIT             NOT NULL,
    [KEY_DATE]  DATETIME        NOT NULL,
    [KEY_MAN]   NVARCHAR (50)   NOT NULL,
    [COUNTRY]   NVARCHAR (50)   NOT NULL,
    [AT_HRS]    DECIMAL (16, 2) NOT NULL,
    [TR_TYPE]   NVARCHAR (50)   NOT NULL,
    [TR_MEMO]   NVARCHAR (200)  NOT NULL,
    [PROVE]     NVARCHAR (50)   NOT NULL,
    [TR_REPO]   BIT             NOT NULL,
    [TR_ASDATE] DATETIME        NULL,
    [TR_ASNO]   NVARCHAR (50)   NOT NULL,
    [APPLYNO]   NVARCHAR (50)   NOT NULL,
    [HANDOUT]   NVARCHAR (50)   NOT NULL,
    [RECEIVER]  NVARCHAR (50)   NOT NULL,
    [PLANIN]    BIT             NOT NULL,
    [PLANTO]    BIT             NOT NULL,
    [TR_PERSON] NVARCHAR (60)   NOT NULL,
    [TR_ISO]    NVARCHAR (60)   NOT NULL,
    [TR_INOUT]  NVARCHAR (50)   NOT NULL,
    [TR_TEACH]  NVARCHAR (50)   NOT NULL,
    [COSCODE]   NVARCHAR (50)   NULL,
    [KAVL]      NVARCHAR (50)   NULL,
    CONSTRAINT [PK_TRCOSF] PRIMARY KEY CLUSTERED ([AUTO] ASC)
);


GO
CREATE NONCLUSTERED INDEX [DATE_E]
    ON [dbo].[TRCOSF]([DATE_E] ASC);


GO
CREATE NONCLUSTERED INDEX [DATE_B]
    ON [dbo].[TRCOSF]([DATE_B] ASC);


GO
CREATE NONCLUSTERED INDEX [COURSE]
    ON [dbo].[TRCOSF]([COURSE] ASC);


GO
CREATE NONCLUSTERED INDEX [NOBR]
    ON [dbo].[TRCOSF]([NOBR] ASC);

