CREATE TABLE [dbo].[TRDUD] (
    [IDENNO] NVARCHAR (50) NOT NULL,
    [TRANTY] NVARCHAR (50) NOT NULL,
    [TOIDEN] NVARCHAR (50) NOT NULL,
    [EFFDAT] DATETIME      NOT NULL,
    [DUEDAT] DATETIME      NOT NULL,
    [CREUSR] NVARCHAR (50) NOT NULL,
    [CREDAT] DATETIME      NOT NULL,
    [UPDUSR] NVARCHAR (50) NOT NULL,
    [UPDDAT] DATETIME      NOT NULL
);

