CREATE TABLE [dbo].[TRDUR] (
    [TRANTY] NVARCHAR (50) NOT NULL,
    [TRANNA] NVARCHAR (50) NOT NULL,
    [CREUSR] NVARCHAR (50) NOT NULL,
    [CREDAT] DATETIME      NOT NULL,
    [UPDUSR] NVARCHAR (50) NOT NULL,
    [UPDDAT] DATETIME      NOT NULL
);

