CREATE TABLE [dbo].[TREMAIL] (
    [IDNO]       NVARCHAR (50) CONSTRAINT [DF_TREMAIL_IDNO] DEFAULT ('') NOT NULL,
    [INTEREMAIL] NVARCHAR (50) CONSTRAINT [DF_TREMAIL_INTEREMAIL] DEFAULT ('') NOT NULL,
    [NOTEEMAIL]  NVARCHAR (50) CONSTRAINT [DF_TREMAIL_NOTEEMAIL] DEFAULT ('') NOT NULL,
    [DEPT1MANG]  BIT           NOT NULL,
    [DEPT2MANG]  BIT           NOT NULL,
    [KEY_MAN]    NVARCHAR (50) CONSTRAINT [DF_TREMAIL_KEY_MAN] DEFAULT ('') NOT NULL,
    [KEY_DATE]   DATETIME      CONSTRAINT [DF_TREMAIL_KEY_DATE] DEFAULT (getdate()) NOT NULL,
    [DEPT]       NVARCHAR (50) CONSTRAINT [DF_TREMAIL_DEPT] DEFAULT ('') NOT NULL,
    [DEPT1]      NVARCHAR (50) CONSTRAINT [DF_TREMAIL_DEPT1] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_TREMAIL] PRIMARY KEY CLUSTERED ([IDNO] ASC)
);

