CREATE TABLE [dbo].[TREMLIF] (
    [EMLIFCODE] NVARCHAR (50)  CONSTRAINT [DF_TREMLIF_EMLIFCODE] DEFAULT ('') NOT NULL,
    [EMLIFCONT] NVARCHAR (254) CONSTRAINT [DF_TREMLIF_EMLIFCONT] DEFAULT ('') NOT NULL,
    [KEY_MAN]   NVARCHAR (50)  CONSTRAINT [DF_TREMLIF_KEY_MAN] DEFAULT ('') NOT NULL,
    [KEY_DATE]  DATETIME       CONSTRAINT [DF_TREMLIF_KEY_DATE] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_TREMLIF] PRIMARY KEY CLUSTERED ([EMLIFCODE] ASC)
);

