CREATE TABLE [dbo].[TRFEECD] (
    [FEECODE]  NVARCHAR (50) NOT NULL,
    [FEENAME]  NVARCHAR (50) NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL,
    [FEENAMEE] NVARCHAR (60) CONSTRAINT [DF_TRFEECD_FEENAMEE] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_TRFEECD] PRIMARY KEY CLUSTERED ([FEECODE] ASC)
);

