CREATE TABLE [dbo].[TRJBSET] (
    [JOBLEVEL] NVARCHAR (50) NOT NULL,
    [JOBCLASS] NVARCHAR (50) NOT NULL,
    [COSCODE]  NVARCHAR (50) NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL
);

