CREATE TABLE [dbo].[TRLEARNED] (
    [iAutoKey]      INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [sProcessID]    NVARCHAR (50)   NOT NULL,
    [idProcess]     INT             NOT NULL,
    [sNobr]         VARCHAR (50)    NOT NULL,
    [sName]         NVARCHAR (50)   NOT NULL,
    [sDept]         NVARCHAR (50)   NOT NULL,
    [sJob]          NVARCHAR (50)   NOT NULL,
    [sJobName]      NVARCHAR (50)   NOT NULL,
    [sJobl]         NVARCHAR (50)   NOT NULL,
    [sJoblName]     NVARCHAR (50)   NOT NULL,
    [sDeptName]     NVARCHAR (50)   NOT NULL,
    [sApplyNo]      NVARCHAR (50)   NOT NULL,
    [sCourseName]   NVARCHAR (50)   NOT NULL,
    [dDateB]        DATETIME        NOT NULL,
    [dDateE]        DATETIME        NOT NULL,
    [sTimeB]        NVARCHAR (50)   CONSTRAINT [DF_TRLEARNED_sTimeB] DEFAULT ('') NOT NULL,
    [sTimeE]        NVARCHAR (50)   CONSTRAINT [DF_TRLEARNED_sTimeE] DEFAULT ('') NOT NULL,
    [sAddress]      NVARCHAR (100)  NOT NULL,
    [sTcrName1]     NVARCHAR (50)   CONSTRAINT [DF_TRLEARNED_sTcrName1] DEFAULT ('') NOT NULL,
    [sTcrName2]     NVARCHAR (50)   CONSTRAINT [DF_TRLEARNED_sTcrName2] DEFAULT ('') NOT NULL,
    [sTcrName3]     NVARCHAR (50)   CONSTRAINT [DF_TRLEARNED_sTcrName3] DEFAULT ('') NOT NULL,
    [sTcrName4]     NVARCHAR (50)   CONSTRAINT [DF_TRLEARNED_sTcrName4] DEFAULT ('') NOT NULL,
    [sTcrName5]     NVARCHAR (50)   CONSTRAINT [DF_TRLEARNED_sTcrName5] DEFAULT ('') NOT NULL,
    [sContent]      NVARCHAR (2000) NOT NULL,
    [sLearned]      NVARCHAR (2000) NOT NULL,
    [sEffor1]       NVARCHAR (50)   CONSTRAINT [DF_TRLEARNED_sEffor1] DEFAULT ('') NOT NULL,
    [sEffor2]       NVARCHAR (50)   CONSTRAINT [DF_TRLEARNED_sEffor2] DEFAULT ('') NOT NULL,
    [sEffor3]       NVARCHAR (50)   CONSTRAINT [DF_TRLEARNED_sEffor3] DEFAULT ('') NOT NULL,
    [sEffor4]       NVARCHAR (50)   CONSTRAINT [DF_TRLEARNED_sEffor4] DEFAULT ('') NOT NULL,
    [sComment]      NVARCHAR (50)   NOT NULL,
    [sReason]       NVARCHAR (200)  NOT NULL,
    [sMangAppraise] NVARCHAR (2000) CONSTRAINT [DF_TRLEARNED_sMangAppraise] DEFAULT ('') NOT NULL,
    [sNote]         NVARCHAR (MAX)  CONSTRAINT [DF_TRLEARNED_sNote] DEFAULT ('') NOT NULL,
    [sReserve1]     NVARCHAR (50)   CONSTRAINT [DF_TRLEARNED_sReserve1] DEFAULT ('') NOT NULL,
    [sReserve2]     NVARCHAR (50)   CONSTRAINT [DF_TRLEARNED_sReserve2] DEFAULT ('') NOT NULL,
    [sReserve3]     NVARCHAR (50)   CONSTRAINT [DF_TRLEARNED_sReserve3] DEFAULT ('') NOT NULL,
    [bAuth]         BIT             NOT NULL,
    [bSign]         BIT             NOT NULL,
    [iTotalHour]    DECIMAL (16, 2) CONSTRAINT [DF_TRLEARNED_iTotalHour] DEFAULT ((0)) NOT NULL,
    [sState]        NVARCHAR (50)   NOT NULL,
    [sConditions1]  NVARCHAR (50)   CONSTRAINT [DF_TRLEARNED_sConditions1] DEFAULT ('') NOT NULL,
    [sConditions2]  NVARCHAR (50)   CONSTRAINT [DF_TRLEARNED_sConditions2] DEFAULT ('') NOT NULL,
    [sConditions3]  NVARCHAR (50)   CONSTRAINT [DF_TRLEARNED_sConditions3] DEFAULT ('') NOT NULL,
    [sConditions4]  NVARCHAR (50)   CONSTRAINT [DF_TRLEARNED_sConditions4] DEFAULT ('') NOT NULL,
    [sConditions5]  NVARCHAR (50)   CONSTRAINT [DF_TRLEARNED_sConditions5] DEFAULT ('') NOT NULL,
    [sKeyMan]       NVARCHAR (50)   NOT NULL,
    [dKeyDate]      DATETIME        NOT NULL,
    CONSTRAINT [PK_TRLEARNED] PRIMARY KEY CLUSTERED ([iAutoKey] ASC)
);

