CREATE TABLE [dbo].[TROVER] (
    [COSCODE]  NVARCHAR (50)  NOT NULL,
    [YYMM]     NVARCHAR (50)  NOT NULL,
    [SER]      NVARCHAR (50)  NOT NULL,
    [TRGROUP]  NVARCHAR (50)  NOT NULL,
    [TRNAME]   NVARCHAR (MAX) NOT NULL,
    [KEY_MAN]  NVARCHAR (50)  NOT NULL,
    [KEY_DATE] DATETIME       NOT NULL
);

