CREATE TABLE [dbo].[TRQ] (
    [AUTOKEY]  INT            IDENTITY (1, 1) NOT NULL,
    [TRQCODE]  NVARCHAR (50)  NOT NULL,
    [TRQNAME]  NVARCHAR (50)  NOT NULL,
    [HEADER]   NVARCHAR (MAX) CONSTRAINT [DF_TRQ_HEADER] DEFAULT ('') NOT NULL,
    [FOOTER]   NVARCHAR (MAX) CONSTRAINT [DF_TRQ_FOOTER] DEFAULT ('') NOT NULL,
    [CONTENT]  NVARCHAR (MAX) CONSTRAINT [DF_TRQ_CONTENT] DEFAULT ('') NOT NULL,
    [KEY_MAN]  NVARCHAR (50)  CONSTRAINT [DF_TRQ_KEY_MAN] DEFAULT ('') NOT NULL,
    [KEY_DATE] DATETIME       CONSTRAINT [DF_TRQ_KEY_DATE] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_TRQ] PRIMARY KEY CLUSTERED ([AUTOKEY] ASC)
);

