CREATE TABLE [dbo].[TRQG] (
    [AUTOKEY] INT           IDENTITY (1, 1) NOT NULL,
    [TRQCODE] NVARCHAR (50) NOT NULL,
    [VALCODE] NVARCHAR (50) NOT NULL,
    [SORT]    INT           NOT NULL,
    CONSTRAINT [PK_TRQG] PRIMARY KEY CLUSTERED ([AUTOKEY] ASC)
);

