CREATE TABLE [dbo].[TRREJTCD] (
    [REJCD]    NVARCHAR (50) NOT NULL,
    [REJNAME]  NVARCHAR (50) NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL,
    CONSTRAINT [PK_TRREJTCD] PRIMARY KEY CLUSTERED ([REJCD] ASC)
);

