CREATE TABLE [dbo].[TRSUB] (
    [SUBCODE]  NVARCHAR (50) NOT NULL,
    [DESCR]    NVARCHAR (50) NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL,
    CONSTRAINT [PK_TRSUB] PRIMARY KEY CLUSTERED ([SUBCODE] ASC)
);

