CREATE TABLE [dbo].[TRTCR] (
    [TCR_NO]     NVARCHAR (50)  NOT NULL,
    [TCR_NAME]   NVARCHAR (50)  NOT NULL,
    [ADDR1]      NVARCHAR (60)  NOT NULL,
    [ADDR2]      NVARCHAR (60)  NOT NULL,
    [TEL1]       NVARCHAR (50)  NOT NULL,
    [TEL2]       NVARCHAR (50)  NOT NULL,
    [GSM]        NVARCHAR (50)  NOT NULL,
    [BBC]        NVARCHAR (50)  NOT NULL,
    [EMAIL]      NVARCHAR (50)  NOT NULL,
    [KEY_MAN]    NVARCHAR (50)  NOT NULL,
    [KEY_DATE]   DATETIME       NOT NULL,
    [IDNO]       NVARCHAR (50)  NOT NULL,
    [INCOMP]     BIT            NOT NULL,
    [SPECIALITY] NVARCHAR (255) NOT NULL,
    [SCHOOL]     NVARCHAR (50)  CONSTRAINT [DF_TRTCR_SCHOOL] DEFAULT ('') NOT NULL,
    [TCR_NAMEE]  NVARCHAR (60)  CONSTRAINT [DF_TRTCR_TCR_NAMEE] DEFAULT ('') NOT NULL,
    [FAX]        NVARCHAR (50)  CONSTRAINT [DF_TRTCR_FAX] DEFAULT ('') NOT NULL,
    [TRUSE]      BIT            NOT NULL,
    [TAXNO]      NVARCHAR (50)  CONSTRAINT [DF_TRTCR_TAXNO] DEFAULT ('') NOT NULL,
    [COMPY]      NVARCHAR (50)  CONSTRAINT [DF_TRTCR_COMPY] DEFAULT ('') NOT NULL,
    [CONT_MA]    NVARCHAR (50)  CONSTRAINT [DF_TRTCR_CONT_MA] DEFAULT ('') NOT NULL
);

