CREATE TABLE [dbo].[TRTYPE] (
    [TR_TYPE]      NVARCHAR (50) NOT NULL,
    [TR_TYPE_DISP] NVARCHAR (50) NOT NULL,
    [DESCR]        NVARCHAR (50) NOT NULL,
    [KEY_MAN]      NVARCHAR (50) NOT NULL,
    [KEY_DATE]     DATETIME      NOT NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_TRTYPE]
    ON [dbo].[TRTYPE]([TR_TYPE] ASC);

