CREATE TABLE [dbo].[TRVALGD] (
    [VALCODE]  NVARCHAR (50)  CONSTRAINT [DF_TRVALGD_VALCODE] DEFAULT ((1)) NOT NULL,
    [VALNAME]  NVARCHAR (200) NOT NULL,
    [KEY_MAN]  NVARCHAR (50)  NOT NULL,
    [KEY_DATE] DATETIME       NOT NULL,
    [CATE]     NVARCHAR (50)  CONSTRAINT [DF_TRVALGD_CATE] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_TRVALGD] PRIMARY KEY CLUSTERED ([VALCODE] ASC)
);

