CREATE TABLE [dbo].[TRVALCD] (
    [VALCODE]  NVARCHAR (50) NOT NULL,
    [L1CAP]    NVARCHAR (50) NOT NULL,
    [L2CAP]    NVARCHAR (50) NOT NULL,
    [L3CAP]    NVARCHAR (50) NOT NULL,
    [L4CAP]    NVARCHAR (50) NOT NULL,
    [L5CAP]    NVARCHAR (50) NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL,
    [L1CAPE]   NVARCHAR (60) CONSTRAINT [DF_TRVALCD_L1CAPE] DEFAULT ('') NOT NULL,
    [L2CAPE]   NVARCHAR (60) CONSTRAINT [DF_TRVALCD_L2CAPE] DEFAULT ('') NOT NULL,
    [L3CAPE]   NVARCHAR (60) CONSTRAINT [DF_TRVALCD_L3CAPE] DEFAULT ('') NOT NULL,
    [L4CAPE]   NVARCHAR (60) CONSTRAINT [DF_TRVALCD_L4CAPE] DEFAULT ('') NOT NULL,
    [L5CAPE]   NVARCHAR (60) CONSTRAINT [DF_TRVALCD_L5CAPE] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_TRVALCD] PRIMARY KEY CLUSTERED ([VALCODE] ASC)
);

