CREATE TABLE [dbo].[TRVALGDG] (
    [AUTOKEY] INT           IDENTITY (1, 1) NOT NULL,
    [VALCODE] NVARCHAR (50) NOT NULL,
    [ASKCODE] NVARCHAR (50) NOT NULL,
    [SORT]    INT           NOT NULL,
    CONSTRAINT [PK_TRVALGDG] PRIMARY KEY CLUSTERED ([AUTOKEY] ASC)
);

