CREATE TABLE [dbo].[TRYEARPA] (
    [TRYEARNO] NVARCHAR (50)   NOT NULL,
    [COSCODE]  NVARCHAR (50)   NOT NULL,
    [TRTYPE]   NVARCHAR (50)   CONSTRAINT [DF_TRYEARPA_TRTYPE] DEFAULT ('') NOT NULL,
    [TRISOSUB] NVARCHAR (50)   CONSTRAINT [DF_TRYEARPA_TRISOSUB] DEFAULT ('') NOT NULL,
    [TRSUB]    NVARCHAR (50)   NOT NULL,
    [TRDESC]   NVARCHAR (50)   NOT NULL,
    [TRTER]    NVARCHAR (50)   NOT NULL,
    [TRSER]    NVARCHAR (50)   NOT NULL,
    [TRDATE]   DATETIME        NOT NULL,
    [TRDATE1]  NVARCHAR (50)   NOT NULL,
    [TRPER]    NVARCHAR (50)   NOT NULL,
    [TRCER]    NVARCHAR (50)   NOT NULL,
    [TRHRS]    DECIMAL (16, 2) NOT NULL,
    [TRNO1]    DECIMAL (16, 2) NOT NULL,
    [TRNO2]    DECIMAL (16, 2) NOT NULL,
    [TRTHRS]   DECIMAL (16, 2) NOT NULL,
    [TRAMT]    DECIMAL (16, 2) NOT NULL,
    [TRMENO]   NVARCHAR (50)   NOT NULL,
    [KEY_MAN]  NVARCHAR (50)   NOT NULL,
    [KEY_DATE] DATETIME        NOT NULL
);

