CREATE TABLE [dbo].[TTSCD] (
    [TTSCD]      NVARCHAR (50) NOT NULL,
    [TTSNAME]    NVARCHAR (50) NOT NULL,
    [KEY_DATE]   DATETIME      NOT NULL,
    [KEY_MAN]    NVARCHAR (50) NOT NULL,
    [TTSCD_DISP] NVARCHAR (50) NULL,
    CONSTRAINT [PK_TTSCD] PRIMARY KEY CLUSTERED ([TTSCD] ASC)
);

