CREATE TABLE [dbo].[TW_TAX] (
    [AUTO]       INT             IDENTITY (1, 1) NOT NULL,
    [SUBJECT]    NVARCHAR (100)  NOT NULL,
    [YEARMONTH]  NVARCHAR (50)   NOT NULL,
    [DATEBEGIN]  DATETIME        NOT NULL,
    [DATEEND]    DATETIME        NOT NULL,
    [REMARK]     NVARCHAR (1000) NOT NULL,
    [KEY_DATE]   DATETIME        NOT NULL,
    [KEY_MAN]    NVARCHAR (50)   NOT NULL,
    [ISLOCK]     BIT             NOT NULL,
    [RELASEDATE] DATETIME        NULL,
    CONSTRAINT [PK_YEARTAXSETTING] PRIMARY KEY CLUSTERED ([AUTO] ASC)
);

