CREATE TABLE [dbo].[TW_TAX_SUBCODE] (
    [AUTO]       INT           IDENTITY (1, 1) NOT NULL,
    [M_FORMAT]   NVARCHAR (50) NOT NULL,
    [M_FORSUB]   NVARCHAR (50) NOT NULL,
    [M_SUB_NAME] NVARCHAR (50) NOT NULL,
    [KEY_MAN]    NVARCHAR (50) NOT NULL,
    [KEY_DATE]   DATETIME      NOT NULL,
    CONSTRAINT [PK_TW_TAX_SUBCODE] PRIMARY KEY CLUSTERED ([AUTO] ASC)
);

