CREATE TABLE [dbo].[TWAGED] (
    [NOBR]     NVARCHAR (50)   NOT NULL,
    [YYMM]     NVARCHAR (50)   NOT NULL,
    [SEQ]      NVARCHAR (50)   NOT NULL,
    [SAL_CODE] NVARCHAR (50)   NOT NULL,
    [AMT]      DECIMAL (16, 2) CONSTRAINT [DF_TWAGED_AMT] DEFAULT ((0)) NOT NULL,
    [D_AMT]    DECIMAL (16, 2) CONSTRAINT [DF_TWAGED_D_AMT] DEFAULT ((0)) NOT NULL,
    [TR_TYPE]  NVARCHAR (50)   CONSTRAINT [DF_TWAGED_TR_TYPE] DEFAULT ('') NOT NULL,
    [FORMAT]   NVARCHAR (50)   CONSTRAINT [DF_TWAGED_FORMAT] DEFAULT ('') NOT NULL,
    [MENO]     NVARCHAR (120)  CONSTRAINT [DF_TWAGED_MENO] DEFAULT ('') NOT NULL,
    [KEY_MAN]  NVARCHAR (50)   NOT NULL,
    [KEY_DATE] DATETIME        NOT NULL,
    [INA_ID]   NVARCHAR (50)   CONSTRAINT [DF_TWAGED_INA_ID] DEFAULT ('') NOT NULL,
    [TAXNO]    NVARCHAR (50)   CONSTRAINT [DF_TWAGED_TAXNO] DEFAULT ('') NOT NULL,
    [SUBCODE]  NVARCHAR (50)   CONSTRAINT [DF_TWAGED_SUBCODE] DEFAULT ('') NOT NULL,
    [FORSUB]   NVARCHAR (50)   CONSTRAINT [DF_TWAGED_FORSUB] DEFAULT ('') NOT NULL,
    [COMP]     NVARCHAR (50)   CONSTRAINT [DF_TWAGED_COMP] DEFAULT ('') NOT NULL,
    [SUP_AMT]  DECIMAL (16, 2) NOT NULL,
    CONSTRAINT [PK_TWAGED] PRIMARY KEY CLUSTERED ([NOBR] ASC, [YYMM] ASC, [SEQ] ASC, [SAL_CODE] ASC)
);

