CREATE TABLE [dbo].[U_CODE] (
    [AUTOKEY]  INT             IDENTITY (1, 1) NOT NULL,
    [Q_CODE]   NVARCHAR (50)   NOT NULL,
    [Q_NAME]   NVARCHAR (50)   NOT NULL,
    [Q_FIELD]  NVARCHAR (50)   NOT NULL,
    [Q_LENS]   DECIMAL (16, 2) NOT NULL,
    [Q_ATTR]   NVARCHAR (50)   NOT NULL,
    [Q_ORDER]  BIT             NOT NULL,
    [FORMNAME] NVARCHAR (50)   NOT NULL,
    [KEY_DATE] DATETIME        NOT NULL,
    [KEY_MAN]  NVARCHAR (50)   NOT NULL,
    [SYSTEM]   NVARCHAR (50)   NOT NULL,
    [Q_VAR]    BIT             NOT NULL,
    [FIELD1]   NVARCHAR (500)  NOT NULL,
    [FIELD2]   NVARCHAR (500)  NOT NULL,
    CONSTRAINT [PK_U_CODE] PRIMARY KEY CLUSTERED ([AUTOKEY] ASC)
);

