CREATE TABLE [dbo].[U_DATAID] (
    [USER_ID]  NVARCHAR (50) NOT NULL,
    [DEPT]     NVARCHAR (50) NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL,
    [SYSTEM]   NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_U_DATAID] PRIMARY KEY CLUSTERED ([USER_ID] ASC, [DEPT] ASC, [SYSTEM] ASC)
);

