CREATE TABLE [dbo].[U_DATAGROUP] (
    [USER_ID]   NVARCHAR (50)  NOT NULL,
    [COMPANY]   NVARCHAR (50)  NOT NULL,
    [DATAGROUP] NVARCHAR (50)  NOT NULL,
    [READRULE]  BIT            NOT NULL,
    [WRITERULE] BIT            NOT NULL,
    [NOTE]      NVARCHAR (500) NOT NULL,
    [KEY_DATE]  DATETIME       NOT NULL,
    [KEY_MAN]   NVARCHAR (50)  NOT NULL,
    CONSTRAINT [PK_DATAGG1_1] PRIMARY KEY CLUSTERED ([USER_ID] ASC, [COMPANY] ASC, [DATAGROUP] ASC),
    CONSTRAINT [FK_U_DATAGROUP_COMP] FOREIGN KEY ([COMPANY]) REFERENCES [dbo].[COMP] ([COMP]),
    CONSTRAINT [FK_U_DATAGROUP_COMP_DATAGROUP] FOREIGN KEY ([COMPANY], [DATAGROUP]) REFERENCES [dbo].[COMP_DATAGROUP] ([COMP], [DATAGROUP]),
    CONSTRAINT [FK_U_DATAGROUP_DATAGROUP] FOREIGN KEY ([DATAGROUP]) REFERENCES [dbo].[DATAGROUP] ([DATAGROUP]),
    CONSTRAINT [FK_U_DATAGROUP_U_USERCOMP] FOREIGN KEY ([USER_ID], [COMPANY]) REFERENCES [dbo].[U_USERCOMP] ([USER_ID], [COMPANY])
);

