CREATE TABLE [dbo].[U_FILTER] (
    [AUTOKEY]    INT            IDENTITY (1, 1) NOT NULL,
    [U_CODE]     INT            NULL,
    [Q_NAME]     NVARCHAR (50)  NOT NULL,
    [Q_KEYCONTB] NVARCHAR (50)  NOT NULL,
    [Q_KEYCONTE] NVARCHAR (50)  NOT NULL,
    [Q_VARVAL]   NVARCHAR (60)  NOT NULL,
    [Q_COND]     NVARCHAR (120) NOT NULL,
    [Q_COND1]    NVARCHAR (120) NOT NULL,
    [Q_ORDER]    NVARCHAR (50)  NOT NULL,
    [Q_SUBQ]     NVARCHAR (160) NOT NULL,
    [Q_HAVING]   NVARCHAR (80)  NOT NULL,
    [Q_CODE]     NVARCHAR (50)  NOT NULL,
    [Q_ATTR]     NVARCHAR (50)  NOT NULL,
    [USERNOBR]   NVARCHAR (50)  NOT NULL,
    [FORMNAME]   NVARCHAR (50)  NOT NULL,
    [SYSTEM]     NVARCHAR (50)  NOT NULL,
    CONSTRAINT [PK_U_FILTER] PRIMARY KEY CLUSTERED ([AUTOKEY] ASC)
);

