CREATE TABLE [dbo].[U_ORDER] (
    [Q_NAME]   NVARCHAR (50)   NOT NULL,
    [Q_FIELD]  NVARCHAR (50)   NOT NULL,
    [Q_ASC]    NVARCHAR (50)   NOT NULL,
    [USERNOBR] NVARCHAR (50)   NOT NULL,
    [FORMNAME] NVARCHAR (50)   NOT NULL,
    [SEQ]      DECIMAL (16, 2) NOT NULL,
    [SYSTEM]   NVARCHAR (50)   CONSTRAINT [DF_U_ORDER_SYSTEM] DEFAULT ('') NOT NULL
);

