CREATE TABLE [dbo].[U_PRG] (
    [PROG]      NVARCHAR (50) NOT NULL,
    [PROG_NAME] NVARCHAR (50) NOT NULL,
    [SYSTEM]    NVARCHAR (50) NOT NULL,
    [ROOT]      BIT           NOT NULL,
    [KEY_MAN]   NVARCHAR (50) NOT NULL,
    [KEY_DATE]  DATETIME      NOT NULL,
    CONSTRAINT [PK_U_PRG] PRIMARY KEY CLUSTERED ([PROG] ASC)
);

