CREATE TABLE [dbo].[U_QUERY] (
    [SYS2007]  NVARCHAR (50) NOT NULL,
    [CONT]     NVARCHAR (50) NOT NULL,
    [FORMNAME] NVARCHAR (50) NOT NULL,
    [SYSTEM]   NVARCHAR (50) NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL
);

