CREATE TABLE [dbo].[U_SYS5] (
    [Comp]                 NVARCHAR (50)   NOT NULL,
    [HSALCODE]             NVARCHAR (50)   NULL,
    [HEALTHOVERSALCODE]    NVARCHAR (50)   NULL,
    [HEALTHREPAIRSALCODE]  NVARCHAR (50)   NULL,
    [EMPFAMILYCNT]         DECIMAL (16, 2) NULL,
    [COMPERSONCNT]         DECIMAL (16, 2) NULL,
    [HEACOMPRATE]          DECIMAL (16, 4) NULL,
    [SUPPLEHINSLABSALCODE] NVARCHAR (50)   NULL,
    [SUPPLEINSLABRATE]     DECIMAL (16, 4) NULL,
    [BONUSYEARRATEMAX]     DECIMAL (16, 2) NULL,
    CONSTRAINT [PK_U_SYS5] PRIMARY KEY CLUSTERED ([Comp] ASC)
);

