CREATE TABLE [dbo].[U_SYS3] (
    [Comp]           NVARCHAR (50)   NOT NULL,
    [NOTAXSALCODE]   NVARCHAR (50)   NULL,
    [TOTAXSALCODE]   NVARCHAR (50)   NULL,
    [OTFOODSALCODE]  NVARCHAR (50)   NULL,
    [OTFOODSALCODE1] NVARCHAR (50)   NULL,
    [OTTRASALCODE]   NVARCHAR (50)   NULL,
    [MALEMAXHRS]     DECIMAL (16, 2) NULL,
    [FEMALEMAXHRS]   DECIMAL (16, 2) NULL,
    [OTUNIT]         DECIMAL (16, 2) NULL,
    CONSTRAINT [PK_U_SYS3] PRIMARY KEY CLUSTERED ([Comp] ASC)
);

