CREATE TABLE [dbo].[U_SYS10] (
    [Comp]       NVARCHAR (50) NOT NULL,
    [SMTPSERVER] NVARCHAR (50) NULL,
    [SENDMAIL]   NVARCHAR (50) NULL,
    [SMTPID]     NVARCHAR (50) NULL,
    [SMTPPW]     NVARCHAR (50) NULL,
    CONSTRAINT [PK_U_SYS10] PRIMARY KEY CLUSTERED ([Comp] ASC)
);

