CREATE TABLE [dbo].[U_SYS] (
    [AUTO]                INT             IDENTITY (1, 1) NOT NULL,
    [COMPANY]             NVARCHAR (50)   NULL,
    [COMPADDR]            NVARCHAR (50)   NULL,
    [COMPTEL]             NVARCHAR (50)   NULL,
    [COMPFAX]             NVARCHAR (50)   NULL,
    [COMPLABID]           NVARCHAR (50)   NULL,
    [COMPHELID]           NVARCHAR (50)   NULL,
    [COMPID]              NVARCHAR (50)   NULL,
    [COMPMAN]             NVARCHAR (50)   NULL,
    [HELORGNAME]          NVARCHAR (50)   NULL,
    [FF103]               NVARCHAR (50)   NULL,
    [FF0407]              NVARCHAR (50)   NULL,
    [COMPANYBANKAC]       NVARCHAR (50)   NULL,
    [COMPANYBANKNO]       NVARCHAR (50)   NULL,
    [BANKNO]              NVARCHAR (50)   NULL,
    [SYSDISK]             NVARCHAR (50)   NULL,
    [COMPANY1]            NVARCHAR (50)   NULL,
    [COMPID1]             NVARCHAR (50)   NULL,
    [FF04071]             NVARCHAR (50)   NULL,
    [WELSALCODE]          NVARCHAR (50)   NULL,
    [WELPAY]              DECIMAL (16, 2) NULL,
    [ATTMONTH]            INT             NULL,
    [EATSALCODE]          NVARCHAR (50)   NULL,
    [FOODSALCODE]         NVARCHAR (50)   NULL,
    [EMPSALCODE]          NVARCHAR (50)   NULL,
    [INDAY]               INT             NULL,
    [ONDUTYSALCODE]       NVARCHAR (50)   NULL,
    [ONDUTYAMT]           DECIMAL (16, 2) NULL,
    [ATTAWARDSALCODE]     NVARCHAR (50)   NULL,
    [ATTMONAMT]           DECIMAL (16, 2) NULL,
    [ATTQTY]              DECIMAL (16, 2) NULL,
    [ATTQTY1]             DECIMAL (16, 2) NULL,
    [ATTAMT]              DECIMAL (16, 2) NULL,
    [ATTAMT1]             DECIMAL (16, 2) NULL,
    [LATTQTY]             DECIMAL (16, 2) NULL,
    [LATTQTY1]            DECIMAL (16, 2) NULL,
    [LATTAMT]             DECIMAL (16, 2) NULL,
    [LATTAMT1]            DECIMAL (16, 2) NULL,
    [FATTQTY]             DECIMAL (16, 2) NULL,
    [FATTQTY1]            DECIMAL (16, 2) NULL,
    [FATTAMT]             DECIMAL (16, 2) NULL,
    [FATTAMT1]            DECIMAL (16, 2) NULL,
    [LJOBPER]             DECIMAL (16, 3) NULL,
    [LJOBPER1]            DECIMAL (16, 3) NULL,
    [RETIRERATE]          DECIMAL (16, 3) NULL,
    [RETIRERATE1]         DECIMAL (16, 3) NULL,
    [NRETIRERATE]         DECIMAL (16, 3) NULL,
    [NRETIRERATE1]        DECIMAL (16, 3) NULL,
    [RETSALCODE]          NVARCHAR (50)   NULL,
    [NOTAXSALCODE]        NVARCHAR (50)   NULL,
    [TOTAXSALCODE]        NVARCHAR (50)   NULL,
    [OTFOODSALCODE]       NVARCHAR (50)   NULL,
    [OTFOODSALCODE1]      NVARCHAR (50)   NULL,
    [OTTRASALCODE]        NVARCHAR (50)   NULL,
    [MALEMAXHRS]          DECIMAL (16, 2) NULL,
    [FEMALEMAXHRS]        DECIMAL (16, 2) NULL,
    [OTUNIT]              DECIMAL (16, 2) NULL,
    [LSALCODE]            NVARCHAR (50)   NULL,
    [LABOVERSALCODE]      NVARCHAR (50)   NULL,
    [LABREPAIRSALCODE]    NVARCHAR (50)   NULL,
    [HSALCODE]            NVARCHAR (50)   NULL,
    [EMPFAMILYCNT]        DECIMAL (16, 2) NULL,
    [COMPERSONCNT]        DECIMAL (16, 2) NULL,
    [HEACOMPRATE]         DECIMAL (16, 4) NULL,
    [HEALTHOVERSALCODE]   NVARCHAR (50)   NULL,
    [HEALTHREPAIRSALCODE] NVARCHAR (50)   NULL,
    [GROUPSALCD]          NVARCHAR (50)   NULL,
    [GROUPEXP1]           DECIMAL (16, 2) NULL,
    [GROUPEXP2]           DECIMAL (16, 2) NULL,
    [GROUPEXP51]          DECIMAL (16, 2) NULL,
    [GROUPEXP52]          DECIMAL (16, 2) NULL,
    [CARDTYPE]            NVARCHAR (50)   NULL,
    [CARDFILENAME]        NVARCHAR (50)   NULL,
    [NOBR_POS]            INT             NULL,
    [NOBR_LEN]            INT             NULL,
    [SER_POS]             INT             NULL,
    [SER_LEN]             INT             NULL,
    [DATE_POS]            INT             NULL,
    [DATE_LEN]            INT             NULL,
    [TIME_POS]            INT             NULL,
    [TIME_LEN]            INT             NULL,
    [CARDDATEFORMAT]      NVARCHAR (50)   NULL,
    [CARDNOEUQALNOBR]     BIT             NULL,
    [SPECIALCALTYPE]      INT             NULL,
    [YEAR11]              DECIMAL (16, 2) NULL,
    [YEAR12]              DECIMAL (16, 2) NULL,
    [VACATIONDAYS01]      DECIMAL (16, 2) NULL,
    [YEAR21]              DECIMAL (16, 2) NULL,
    [YEAR22]              DECIMAL (16, 2) NULL,
    [VACATIONDAYS02]      DECIMAL (16, 2) NULL,
    [YEAR31]              DECIMAL (16, 2) NULL,
    [YEAR32]              DECIMAL (16, 2) NULL,
    [VACATIONDAYS03]      DECIMAL (16, 2) NULL,
    [YEAR41]              DECIMAL (16, 2) NULL,
    [YEAR42]              DECIMAL (16, 2) NULL,
    [VACATIONDAYS04]      DECIMAL (16, 2) NULL,
    [YEAR51]              DECIMAL (16, 2) NULL,
    [NEXTYEARDAY]         DECIMAL (16, 2) NULL,
    [MAXDAYS]             INT             NULL,
    [YEARBASE]            INT             NULL,
    [YEAR0TYPE1]          INT             NULL,
    [YEAR01]              DECIMAL (16, 2) NULL,
    [YEAR0EFFTYPE1]       INT             NULL,
    [MONTH01DAY1]         DECIMAL (16, 2) NULL,
    [MONTH02DAY1]         DECIMAL (16, 2) NULL,
    [MONTH03DAY1]         DECIMAL (16, 2) NULL,
    [MONTH04DAY1]         DECIMAL (16, 2) NULL,
    [MONTH05DAY1]         DECIMAL (16, 2) NULL,
    [MONTH06DAY1]         DECIMAL (16, 2) NULL,
    [MONTH07DAY1]         DECIMAL (16, 2) NULL,
    [MONTH08DAY1]         DECIMAL (16, 2) NULL,
    [MONTH09DAY1]         DECIMAL (16, 2) NULL,
    [MONTH10DAY1]         DECIMAL (16, 2) NULL,
    [MONTH11DAY1]         DECIMAL (16, 2) NULL,
    [MONTH12DAY1]         DECIMAL (16, 2) NULL,
    [YEAR0TYPE2]          INT             NULL,
    [YEAR02]              DECIMAL (16, 2) NULL,
    [YEAR0EFFTYPE2]       INT             NULL,
    [MONTH01DAY2]         DECIMAL (16, 2) NULL,
    [MONTH02DAY2]         DECIMAL (16, 2) NULL,
    [MONTH03DAY2]         DECIMAL (16, 2) NULL,
    [MONTH04DAY2]         DECIMAL (16, 2) NULL,
    [MONTH05DAY2]         DECIMAL (16, 2) NULL,
    [MONTH06DAY2]         DECIMAL (16, 2) NULL,
    [MONTH07DAY2]         DECIMAL (16, 2) NULL,
    [MONTH08DAY2]         DECIMAL (16, 2) NULL,
    [MONTH09DAY2]         DECIMAL (16, 2) NULL,
    [MONTH10DAY2]         DECIMAL (16, 2) NULL,
    [MONTH11DAY2]         DECIMAL (16, 2) NULL,
    [MONTH12DAY2]         DECIMAL (16, 2) NULL,
    [YEAR0TYPE3]          INT             NULL,
    [YEAR03]              DECIMAL (16, 2) NULL,
    [YEAR0EFFTYPE3]       INT             NULL,
    [MONTH01DAY3]         DECIMAL (16, 2) NULL,
    [MONTH02DAY3]         DECIMAL (16, 2) NULL,
    [MONTH03DAY3]         DECIMAL (16, 2) NULL,
    [MONTH04DAY3]         DECIMAL (16, 2) NULL,
    [MONTH05DAY3]         DECIMAL (16, 2) NULL,
    [MONTH06DAY3]         DECIMAL (16, 2) NULL,
    [MONTH07DAY3]         DECIMAL (16, 2) NULL,
    [MONTH08DAY3]         DECIMAL (16, 2) NULL,
    [MONTH09DAY3]         DECIMAL (16, 2) NULL,
    [MONTH10DAY3]         DECIMAL (16, 2) NULL,
    [MONTH11DAY3]         DECIMAL (16, 2) NULL,
    [MONTH12DAY3]         DECIMAL (16, 2) NULL,
    [YEAR0TYPE4]          INT             NULL,
    [YEAR04]              DECIMAL (16, 2) NULL,
    [YEAR0EFFTYPE4]       INT             NULL,
    [MONTH01DAY4]         DECIMAL (16, 2) NULL,
    [MONTH02DAY4]         DECIMAL (16, 2) NULL,
    [MONTH03DAY4]         DECIMAL (16, 2) NULL,
    [MONTH04DAY4]         DECIMAL (16, 2) NULL,
    [MONTH05DAY4]         DECIMAL (16, 2) NULL,
    [MONTH06DAY4]         DECIMAL (16, 2) NULL,
    [MONTH07DAY4]         DECIMAL (16, 2) NULL,
    [MONTH08DAY4]         DECIMAL (16, 2) NULL,
    [MONTH09DAY4]         DECIMAL (16, 2) NULL,
    [MONTH10DAY4]         DECIMAL (16, 2) NULL,
    [MONTH11DAY4]         DECIMAL (16, 2) NULL,
    [MONTH12DAY4]         DECIMAL (16, 2) NULL,
    [TAXTYPE]             INT             NULL,
    [STDEDUETAMTNMAR]     DECIMAL (16, 2) NULL,
    [STDEDUETAMTMAR]      DECIMAL (16, 2) NULL,
    [TAXFREE70DOWN]       DECIMAL (16, 2) NULL,
    [TAXFREE70UP]         DECIMAL (16, 2) NULL,
    [SALARYDEDUTAMT]      DECIMAL (16, 2) NULL,
    [TAXSALCODE]          NVARCHAR (50)   NULL,
    [TAXAMTAMONTH]        DECIMAL (16, 2) NULL,
    [FIXTAXRATE]          DECIMAL (16, 2) NULL,
    [NETTAXAMT01]         DECIMAL (16, 2) NULL,
    [NETTAXAMT02]         DECIMAL (16, 2) NULL,
    [NETTAXAMT03]         DECIMAL (16, 2) NULL,
    [NETTAXAMT04]         DECIMAL (16, 2) NULL,
    [NETTAXAMT05]         DECIMAL (16, 2) NULL,
    [NETTAXAMT06]         DECIMAL (16, 2) NULL,
    [NETTAXAMT07]         DECIMAL (16, 2) NULL,
    [NETTAXAMT08]         DECIMAL (16, 2) NULL,
    [NETTAXAMT09]         DECIMAL (16, 2) NULL,
    [NETTAXAMT10]         DECIMAL (16, 2) NULL,
    [NETTAXRATE01]        DECIMAL (16, 2) NULL,
    [NETTAXRATE02]        DECIMAL (16, 2) NULL,
    [NETTAXRATE03]        DECIMAL (16, 2) NULL,
    [NETTAXRATE04]        DECIMAL (16, 2) NULL,
    [NETTAXRATE05]        DECIMAL (16, 2) NULL,
    [ADDUPAMT01]          DECIMAL (16, 2) NULL,
    [ADDUPAMT02]          DECIMAL (16, 2) NULL,
    [ADDUPAMT03]          DECIMAL (16, 2) NULL,
    [ADDUPAMT04]          DECIMAL (16, 2) NULL,
    [ADDUPAMT05]          DECIMAL (16, 2) NULL,
    [FORSALBASD]          DECIMAL (16, 2) NULL,
    [FORTAXRATE03]        DECIMAL (16, 2) NULL,
    [ENTRYDAY]            DECIMAL (16, 2) NULL,
    [FORTAXRATE01]        DECIMAL (16, 2) NULL,
    [FORTAXRATE02]        DECIMAL (16, 2) NULL,
    [SMTPSERVER]          NVARCHAR (50)   NULL,
    [SENDMAIL]            NVARCHAR (50)   NULL,
    [SMTPID]              NVARCHAR (50)   NULL,
    [SMTPPW]              NVARCHAR (50)   NULL,
    CONSTRAINT [PK_U_SYS_1] PRIMARY KEY CLUSTERED ([AUTO] ASC)
);

