CREATE TABLE [dbo].[U_SYS7A] (
    [AUTO]            INT            IDENTITY (1, 1) NOT NULL,
    [CARD_NAME]       NVARCHAR (50)  NOT NULL,
    [DATA_SOURCE]     NVARCHAR (50)  NOT NULL,
    [INITAIL_CATALOG] NVARCHAR (50)  NOT NULL,
    [USER_ID]         NVARCHAR (50)  NOT NULL,
    [PASSWORD]        NVARCHAR (50)  NULL,
    [DATATABLE]       NVARCHAR (50)  NOT NULL,
    [COL_NOBR]        NVARCHAR (50)  NULL,
    [COL_ADATE]       NVARCHAR (50)  NULL,
    [COL_ONTIME]      NVARCHAR (50)  NULL,
    [COL_CARDNO]      NVARCHAR (50)  NULL,
    [COL_CHECKTIME]   NVARCHAR (50)  NULL,
    [KEY_DATE]        DATETIME       NOT NULL,
    [KEY_MAN]         NVARCHAR (50)  NOT NULL,
    [LATEST_CHECK]    DATETIME       NOT NULL,
    [COL_SOURCE]      NVARCHAR (50)  NULL,
    [COL_IPADD]       NVARCHAR (50)  NULL,
    [SQL]             NVARCHAR (500) NULL,
    [COL_TEMPERATURE] NVARCHAR (50)  NULL,
    CONSTRAINT [PK_U_SYS7A] PRIMARY KEY CLUSTERED ([AUTO] ASC)
);



