CREATE TABLE [dbo].[U_SYS6] (
    [Comp]       NVARCHAR (50)   NOT NULL,
    [GROUPSALCD] NVARCHAR (50)   NULL,
    [GROUPEXP1]  DECIMAL (16, 2) NULL,
    [GROUPEXP2]  DECIMAL (16, 2) NULL,
    [GROUPEXP51] DECIMAL (16, 2) NULL,
    [GROUPEXP52] DECIMAL (16, 2) NULL,
    CONSTRAINT [PK_U_SYS6] PRIMARY KEY CLUSTERED ([Comp] ASC)
);

