CREATE TABLE [dbo].[U_SYS1] (
    [Comp]          NVARCHAR (50) NOT NULL,
    [COMPANY]       NVARCHAR (50) NULL,
    [COMPADDR]      NVARCHAR (50) NULL,
    [COMPTEL]       NVARCHAR (50) NULL,
    [COMPFAX]       NVARCHAR (50) NULL,
    [COMPLABID]     NVARCHAR (50) NULL,
    [COMPHELID]     NVARCHAR (50) NULL,
    [COMPID]        NVARCHAR (50) NULL,
    [COMPMAN]       NVARCHAR (50) NULL,
    [HELORGNAME]    NVARCHAR (50) NULL,
    [FF103]         NVARCHAR (50) NULL,
    [FF0407]        NVARCHAR (50) NULL,
    [COMPANYBANKAC] NVARCHAR (50) NULL,
    [COMPANYBANKNO] NVARCHAR (50) NULL,
    [COMPANY1]      NVARCHAR (50) NULL,
    [COMPID1]       NVARCHAR (50) NULL,
    [FF04071]       NVARCHAR (50) NULL,
    CONSTRAINT [PK_U_SYS1_1] PRIMARY KEY CLUSTERED ([Comp] ASC)
);

