CREATE TABLE [dbo].[U_SYS2] (
    [Comp]            NVARCHAR (50)   NOT NULL,
    [WELSALCODE]      NVARCHAR (50)   NULL,
    [WELPAY]          DECIMAL (16, 3) NULL,
    [ATTMONTH]        INT             NULL,
    [SALMONTH]        INT             NULL,
    [EATSALCODE]      NVARCHAR (50)   NULL,
    [FOODSALCODE]     NVARCHAR (50)   NULL,
    [EMPSALCODE]      NVARCHAR (50)   NULL,
    [INDAY]           INT             NULL,
    [ONDUTYSALCODE]   NVARCHAR (50)   NULL,
    [ONDUTYAMT]       DECIMAL (16, 2) NULL,
    [ATTAWARDSALCODE] NVARCHAR (50)   NULL,
    [ATTMONAMT]       DECIMAL (16, 2) NULL,
    [ATTQTY]          DECIMAL (16, 2) NULL,
    [ATTQTY1]         DECIMAL (16, 2) NULL,
    [ATTAMT]          DECIMAL (16, 2) NULL,
    [ATTAMT1]         DECIMAL (16, 2) NULL,
    [LATTQTY]         DECIMAL (16, 2) NULL,
    [LATTQTY1]        DECIMAL (16, 2) NULL,
    [LATTAMT]         DECIMAL (16, 2) NULL,
    [LATTAMT1]        DECIMAL (16, 2) NULL,
    [FATTQTY]         DECIMAL (16, 2) NULL,
    [FATTQTY1]        DECIMAL (16, 2) NULL,
    [FATTAMT]         DECIMAL (16, 2) NULL,
    [FATTAMT1]        DECIMAL (16, 2) NULL,
    [Decimals]        INT             NULL,
    CONSTRAINT [PK_U_SYS2] PRIMARY KEY CLUSTERED ([Comp] ASC)
);

