CREATE TABLE [dbo].[U_USER] (
    [USER_ID]   NVARCHAR (50) NOT NULL,
    [PASSWORD]  NVARCHAR (50) NOT NULL,
    [SUPER]     BIT           NOT NULL,
    [NAME]      NVARCHAR (50) NOT NULL,
    [SYSTEM]    NVARCHAR (50) NOT NULL,
    [KEY_DATE]  DATETIME      NOT NULL,
    [KEY_MAN]   NVARCHAR (50) NOT NULL,
    [PROCSUPER] BIT           NOT NULL,
    [WORKADR]   NVARCHAR (50) NOT NULL,
    [MANGSUPER] BIT           NOT NULL,
    [E_MAIL]    NVARCHAR (50) NOT NULL,
    [ADMIN]     BIT           NOT NULL,
    [NOBR]      NVARCHAR (50) NULL,
    CONSTRAINT [PK_U_USER_1] PRIMARY KEY CLUSTERED ([USER_ID] ASC, [SYSTEM] ASC)
);

