CREATE TABLE [dbo].[U_USERCOMP] (
    [USER_ID]  NVARCHAR (50)  NOT NULL,
    [COMPANY]  NVARCHAR (50)  NOT NULL,
    [NOTE]     NVARCHAR (500) NOT NULL,
    [KEY_DATE] DATETIME       NOT NULL,
    [KEY_MAN]  NVARCHAR (50)  NOT NULL,
    CONSTRAINT [PK_DATAGG2_1] PRIMARY KEY CLUSTERED ([USER_ID] ASC, [COMPANY] ASC),
    CONSTRAINT [FK_U_USERCOMP_COMP] FOREIGN KEY ([COMPANY]) REFERENCES [dbo].[COMP] ([COMP])
);

