CREATE TABLE [dbo].[U_WKID] (
    [USER_ID]   NVARCHAR (50) CONSTRAINT [DF_U_WKID_USER_ID] DEFAULT ('') NOT NULL,
    [WORK_CODE] NVARCHAR (50) CONSTRAINT [DF_U_WKID_WORK_CODE] DEFAULT ('') NOT NULL,
    [SYSTEM]    NVARCHAR (50) CONSTRAINT [DF_U_WKID_SYSTEM] DEFAULT ('') NOT NULL
);

