CREATE TABLE [dbo].[UPFILE] (
    [AUTOKEY]        INT            IDENTITY (1, 1) NOT NULL,
    [NEWSFILEID]     NVARCHAR (50)  NOT NULL,
    [UPFILENAME]     NVARCHAR (500) CONSTRAINT [DF_UPFILE_UPFILENAME] DEFAULT ('') NOT NULL,
    [SERVERFILENAME] NVARCHAR (500) CONSTRAINT [DF_UPFILE_SERVERFILENAME] DEFAULT ('') NOT NULL,
    [FILETYPE]       NVARCHAR (200) CONSTRAINT [DF_UPFILE_FILETYPE] DEFAULT ('') NOT NULL,
    [FILESIZE]       NVARCHAR (100) CONSTRAINT [DF_UPFILE_FILESIZE] DEFAULT ('') NOT NULL,
    [UPFILEDATE]     DATETIME       CONSTRAINT [DF_UPFILE_UPFILEDATE] DEFAULT (getdate()) NOT NULL,
    [FILEDESC]       NVARCHAR (500) CONSTRAINT [DF_UPFILE_FILEDESC] DEFAULT ('') NOT NULL,
    [UPTYPE]         NVARCHAR (50)  CONSTRAINT [DF_UPFILE_UPTYPE] DEFAULT ('') NOT NULL,
    [NOBR]           NVARCHAR (50)  NULL,
    CONSTRAINT [PK_UPFILE] PRIMARY KEY CLUSTERED ([AUTOKEY] ASC)
);

