CREATE TABLE [dbo].[UPTYPE] (
    [UPTYPE]   NVARCHAR (50) NOT NULL,
    [UP_NAME]  NVARCHAR (50) NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL,
    CONSTRAINT [PK_UPTYPE] PRIMARY KEY CLUSTERED ([UPTYPE] ASC)
);

