CREATE TABLE [dbo].[USERDEFINESOURCE] (
    [AK]            INT              IDENTITY (1, 1) NOT NULL,
    [SOURCEID]      UNIQUEIDENTIFIER NOT NULL,
    [SOURCENAME]    NVARCHAR (50)    NOT NULL,
    [SOURCETYPE]    NVARCHAR (50)    NOT NULL,
    [VALUEMEMBER]   NVARCHAR (50)    NULL,
    [DISPLAYMEMBER] NVARCHAR (100)   NULL,
    [SOURCESCRIPT]  NVARCHAR (MAX)   NULL,
    [SortFeild]     NVARCHAR (MAX)   NULL,
    [WhereFeild]    NVARCHAR (MAX)   NULL,
    CONSTRAINT [PK_USERDEFINESOURCE] PRIMARY KEY CLUSTERED ([AK] ASC)
);

