CREATE TABLE [dbo].[USERDEFINEVALUE] (
    [AK]        INT              IDENTITY (1, 1) NOT NULL,
    [CODE]      NVARCHAR (50)    NOT NULL,
    [CONTROLID] UNIQUEIDENTIFIER NOT NULL,
    [SOURCEID]  UNIQUEIDENTIFIER NULL,
    [VALUETYPE] NVARCHAR (50)    NOT NULL,
    [VALUE]     NVARCHAR (50)    NULL,
    [KEY_MAN]   NVARCHAR (50)    NULL,
    [KEY_DATE]  DATETIME         NULL,
    CONSTRAINT [PK_USERDEFINEVALUE] PRIMARY KEY CLUSTERED ([AK] ASC)
);

