CREATE TABLE [dbo].[WAGED_B] (
    [NOBR]     NVARCHAR (50)   NOT NULL,
    [YYMM]     NVARCHAR (50)   NOT NULL,
    [SEQ]      NVARCHAR (50)   NOT NULL,
    [SAL_CODE] NVARCHAR (50)   NOT NULL,
    [AMT]      DECIMAL (16, 2) NOT NULL,
    CONSTRAINT [PK_WAGED_B] PRIMARY KEY CLUSTERED ([NOBR] ASC, [YYMM] ASC, [SEQ] ASC, [SAL_CODE] ASC)
);

