CREATE TABLE [dbo].[WAGE_B] (
    [YYMM]       NVARCHAR (50)   NOT NULL,
    [SEQ]        NVARCHAR (50)   NOT NULL,
    [NOBR]       NVARCHAR (50)   NOT NULL,
    [ADATE]      DATETIME        CONSTRAINT [DF_WAGE_B_ADATE] DEFAULT (getdate()) NOT NULL,
    [BANKNO]     NVARCHAR (50)   CONSTRAINT [DF_WAGE_B_BANKNO] DEFAULT ('') NOT NULL,
    [ACCOUNT_NO] NVARCHAR (50)   CONSTRAINT [DF_WAGE_B_ACCOUNT_NO] DEFAULT ('') NOT NULL,
    [WK_DAYS]    DECIMAL (16, 2) CONSTRAINT [DF_WAGE_B_WK_DAYS] DEFAULT ((0)) NOT NULL,
    [CASH]       BIT             CONSTRAINT [DF_WAGE_B_CASH] DEFAULT ((0)) NOT NULL,
    [NOTE]       NVARCHAR (500)  CONSTRAINT [DF_WAGE_B_NOTE] DEFAULT ('') NOT NULL,
    [KEY_MAN]    NVARCHAR (50)   CONSTRAINT [DF_WAGE_B_KEY_MAN] DEFAULT ('') NOT NULL,
    [KEY_DATE]   DATETIME        CONSTRAINT [DF_WAGE_B_KEY_DATE] DEFAULT (getdate()) NOT NULL,
    [DATE_B]     DATETIME        CONSTRAINT [DF_WAGE_B_DATE_B] DEFAULT (getdate()) NOT NULL,
    [DATE_E]     DATETIME        CONSTRAINT [DF_WAGE_B_DATE_E] DEFAULT (getdate()) NOT NULL,
    [FORMAT]     NVARCHAR (50)   CONSTRAINT [DF_WAGE_B_FORMAT] DEFAULT ('') NOT NULL,
    [TAXRATE]    DECIMAL (16, 2) CONSTRAINT [DF_WAGE_B_TAXRATE] DEFAULT ((0)) NOT NULL,
    [SALADR]     NVARCHAR (50)   CONSTRAINT [DF_WAGE_B_SALADR] DEFAULT ('') NOT NULL,
    [COMP]       NVARCHAR (50)   CONSTRAINT [DF_WAGE_B_COMP] DEFAULT ('') NOT NULL,
    [ATT_DATEB]  DATETIME        NULL,
    [ATT_DATEE]  DATETIME        NULL,
    CONSTRAINT [PK_WAGE_B] PRIMARY KEY CLUSTERED ([YYMM] ASC, [SEQ] ASC, [NOBR] ASC)
);

