CREATE TABLE [dbo].[WAGEDD] (
    [NOBR]     NVARCHAR (50)   NOT NULL,
    [YYMM]     NVARCHAR (50)   NOT NULL,
    [SEQ]      NVARCHAR (50)   NOT NULL,
    [SAL_CODE] NVARCHAR (50)   NOT NULL,
    [AMT]      DECIMAL (16, 2) NOT NULL,
    [ACNO]     NVARCHAR (50)   CONSTRAINT [DF_WAGEDD_ACNO] DEFAULT ('') NOT NULL,
    [KEY_MAN]  NVARCHAR (50)   NOT NULL,
    [KEY_DATE] DATETIME        NOT NULL,
    CONSTRAINT [PK_WAGEDD] PRIMARY KEY CLUSTERED ([NOBR] ASC, [YYMM] ASC, [SEQ] ASC, [ACNO] ASC)
);

