CREATE TABLE [dbo].[WAGESOS] (
    [SOS_ID]    NVARCHAR (50) NOT NULL,
    [SOS_DESCR] NVARCHAR (50) NOT NULL,
    [SYSTEM]    NVARCHAR (50) NOT NULL,
    [SUBSYSTEM] NVARCHAR (50) NOT NULL,
    [FIELD]     NVARCHAR (50) NOT NULL
);

