CREATE TABLE [dbo].[WAGE] (
    [YYMM]       NVARCHAR (50)   NOT NULL,
    [SEQ]        NVARCHAR (50)   NOT NULL,
    [NOBR]       NVARCHAR (50)   NOT NULL,
    [ADATE]      DATETIME        CONSTRAINT [DF_WAGE_ADATE] DEFAULT (getdate()) NOT NULL,
    [BANKNO]     NVARCHAR (50)   CONSTRAINT [DF_WAGE_BANKNO] DEFAULT ('') NOT NULL,
    [ACCOUNT_NO] NVARCHAR (50)   CONSTRAINT [DF_WAGE_ACCOUNT_NO] DEFAULT ('') NOT NULL,
    [WK_DAYS]    DECIMAL (16, 2) CONSTRAINT [DF_WAGE_WK_DAYS] DEFAULT ((0)) NOT NULL,
    [CASH]       BIT             CONSTRAINT [DF_WAGE_CASH] DEFAULT ((0)) NOT NULL,
    [NOTE]       NVARCHAR (500)  CONSTRAINT [DF_WAGE_NOTE] DEFAULT ('') NOT NULL,
    [KEY_MAN]    NVARCHAR (50)   CONSTRAINT [DF_WAGE_KEY_MAN] DEFAULT ('') NOT NULL,
    [KEY_DATE]   DATETIME        CONSTRAINT [DF_WAGE_KEY_DATE] DEFAULT (getdate()) NOT NULL,
    [DATE_B]     DATETIME        CONSTRAINT [DF_WAGE_DATE_B] DEFAULT (getdate()) NOT NULL,
    [DATE_E]     DATETIME        CONSTRAINT [DF_WAGE_DATE_E] DEFAULT (getdate()) NOT NULL,
    [FORMAT]     NVARCHAR (50)   CONSTRAINT [DF_WAGE_FORMAT] DEFAULT ('') NOT NULL,
    [TAXRATE]    DECIMAL (16, 2) CONSTRAINT [DF_WAGE_TAXRATE] DEFAULT ((0)) NOT NULL,
    [SALADR]     NVARCHAR (50)   CONSTRAINT [DF_WAGE_SALADR] DEFAULT ('') NOT NULL,
    [COMP]       NVARCHAR (50)   CONSTRAINT [DF_WAGE_COMP] DEFAULT ('') NOT NULL,
    [ATT_DATEB]  DATETIME        NULL,
    [ATT_DATEE]  DATETIME        NULL,
    CONSTRAINT [PK_WAGE] PRIMARY KEY CLUSTERED ([YYMM] ASC, [SEQ] ASC, [NOBR] ASC)
);

