CREATE TABLE [dbo].[WCODE] (
    [W_CODE]   NVARCHAR (50) NOT NULL,
    [W_NAME]   NVARCHAR (50) NOT NULL,
    [KEY_DATE] DATETIME      NOT NULL,
    [KEY_MAN]  NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_WCODE] PRIMARY KEY CLUSTERED ([W_CODE] ASC)
);

