CREATE TABLE [dbo].[WELF] (
    [NOBR]     NVARCHAR (50)   NOT NULL,
    [YYMM]     NVARCHAR (50)   NOT NULL,
    [SEQ]      NVARCHAR (50)   NOT NULL,
    [SAL_CODE] NVARCHAR (50)   NOT NULL,
    [AMT]      DECIMAL (16, 2) NOT NULL,
    [D_AMT]    DECIMAL (16, 2) CONSTRAINT [DF_WELF_D_AMT] DEFAULT ((0)) NOT NULL,
    [KEY_MAN]  NVARCHAR (50)   NOT NULL,
    [KEY_DATE] DATETIME        NOT NULL,
    [FORMAT]   NVARCHAR (50)   CONSTRAINT [DF_WELF_FORMAT] DEFAULT ('') NOT NULL,
    [TR_TYPE]  NVARCHAR (50)   CONSTRAINT [DF_WELF_TR_TYPE] DEFAULT ('') NOT NULL,
    [SALADR]   NVARCHAR (50)   CONSTRAINT [DF_WELF_SALADR] DEFAULT ('') NOT NULL,
    [AUTO]     INT             IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_WELF] PRIMARY KEY CLUSTERED ([AUTO] ASC)
);



