CREATE TABLE [dbo].[WORKCD] (
    [WORK_CODE] NVARCHAR (50) NOT NULL,
    [WORK_ADDR] NVARCHAR (50) NOT NULL,
    [KEY_DATE]  DATETIME      NOT NULL,
    [KEY_MAN]   NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_WORKCD] PRIMARY KEY CLUSTERED ([WORK_CODE] ASC)
);

