CREATE TABLE [dbo].[WORKS] (
    [NOBR]       NVARCHAR (50)   NOT NULL,
    [COMPANY]    NVARCHAR (50)   NOT NULL,
    [TITLE]      NVARCHAR (50)   NOT NULL,
    [BDATE]      DATETIME        NOT NULL,
    [EDATE]      DATETIME        NOT NULL,
    [JOB]        NVARCHAR (50)   NOT NULL,
    [NOTE]       NVARCHAR (300)  CONSTRAINT [DF_WORKS_NOTE] DEFAULT ('') NOT NULL,
    [KEY_MAN]    NVARCHAR (50)   NOT NULL,
    [KEY_DATE]   DATETIME        NOT NULL,
    [TRADE_CODE] NVARCHAR (50)   CONSTRAINT [DF_WORKS_TRADE_CODE] DEFAULT ('') NOT NULL,
    [IN_MARK]    BIT             CONSTRAINT [DF_WORKS_IN_MARK] DEFAULT ((0)) NOT NULL,
    [IN_CABINET] BIT             CONSTRAINT [DF_WORKS_IN_CABINET] DEFAULT ((0)) NOT NULL,
    [VOLUME]     DECIMAL (16, 2) CONSTRAINT [DF_WORKS_VOLUME] DEFAULT ((0)) NOT NULL,
    [DIR_TITLE]  NVARCHAR (50)   CONSTRAINT [DF_WORKS_DIR_TITLE] DEFAULT ('') NOT NULL,
    [SEC_TITLE]  NVARCHAR (50)   CONSTRAINT [DF_WORKS_SEC_TITLE] DEFAULT ('') NOT NULL,
    [PEOPLE]     DECIMAL (16, 2) CONSTRAINT [DF_WORKS_PEOPLE] DEFAULT ((0)) NOT NULL,
    [TEL_NO]     NVARCHAR (50)   CONSTRAINT [DF_WORKS_TEL_NO] DEFAULT ('') NOT NULL,
    [ADDR]       NVARCHAR (60)   CONSTRAINT [DF_WORKS_ADDR] DEFAULT ('') NOT NULL,
    [work_id]    INT             NOT NULL,
    CONSTRAINT [PK_WORKS] PRIMARY KEY CLUSTERED ([NOBR] ASC, [COMPANY] ASC, [BDATE] ASC)
);

