CREATE TABLE [dbo].[WRITERULENOBRTABLE] (
    [AUTOKEY]  INT              IDENTITY (1, 1) NOT NULL,
    [GUID]     UNIQUEIDENTIFIER NOT NULL,
    [EMPID]    NVARCHAR (50)    NOT NULL,
    [KEY_DATE] DATETIME         NOT NULL,
    PRIMARY KEY CLUSTERED ([AUTOKEY] ASC)
);

