CREATE TABLE [dbo].[YRFORSUB] (
    [M_FORMAT]   NVARCHAR (50) NOT NULL,
    [M_FORSUB]   NVARCHAR (50) NOT NULL,
    [M_SUB_NAME] NVARCHAR (50) NOT NULL,
    [KEY_MAN]    NVARCHAR (50) CONSTRAINT [DF_YRFORSUB_KEY_MAN] DEFAULT ('') NOT NULL,
    [KEY_DATE]   DATETIME      CONSTRAINT [DF_YRFORSUB_KEY_DATE] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_YRFORSUB] PRIMARY KEY CLUSTERED ([M_FORSUB] ASC)
);

