CREATE TABLE [dbo].[YRHSN] (
    [CO_CTID]    NVARCHAR (50) NOT NULL,
    [CO_ARID]    NVARCHAR (50) NOT NULL,
    [H_HSN_NAME] NVARCHAR (62) NOT NULL,
    [KEY_MAN]    NVARCHAR (50) CONSTRAINT [DF_YRHSN_KEY_MAN] DEFAULT ('') NOT NULL,
    [KEY_DATE]   DATETIME      CONSTRAINT [DF_YRHSN_KEY_DATE] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_YRHSN] PRIMARY KEY CLUSTERED ([CO_CTID] ASC, [CO_ARID] ASC)
);

