CREATE TABLE [dbo].[YRINA] (
    [INA_ID]   NVARCHAR (50) NOT NULL,
    [INA_NAME] NVARCHAR (50) NOT NULL,
    [KEY_MAN]  NVARCHAR (50) CONSTRAINT [DF_YRINA_KEY_MAN] DEFAULT ('') NOT NULL,
    [KEY_DATE] DATETIME      CONSTRAINT [DF_YRINA_KEY_DATE] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_YRINA] PRIMARY KEY CLUSTERED ([INA_ID] ASC)
);

