CREATE TABLE [dbo].[YRINSUR] (
    [AUTO]     INT             IDENTITY (1, 1) NOT NULL,
    [YEAR]     NVARCHAR (50)   NOT NULL,
    [NOBR]     NVARCHAR (50)   NOT NULL,
    [FA_IDNO]  NVARCHAR (50)   NOT NULL,
    [REL_LAB]  DECIMAL (16, 2) NOT NULL,
    [REL_HEL]  DECIMAL (16, 2) NOT NULL,
    [REL_GRP]  DECIMAL (16, 2) NOT NULL,
    [KEY_MAN]  NVARCHAR (50)   NOT NULL,
    [KEY_DATE] DATETIME        NOT NULL,
    [EQUAL]    BIT             NOT NULL,
    [SALADR]   NVARCHAR (50)   NULL,
    [REL_SUP]  DECIMAL (16, 2) NULL,
    CONSTRAINT [PK_YRINSUR] PRIMARY KEY CLUSTERED ([AUTO] ASC)
);



