#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JBHR.Wel
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="waferhr")]
	public partial class WelDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 擴充性方法定義
    partial void OnCreated();
    #endregion
		
		public WelDataClassesDataContext() : 
				base(global::JBHR.Properties.Settings.Default.JBHRConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public WelDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WelDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WelDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WelDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<U_PRGID> U_PRGID
		{
			get
			{
				return this.GetTable<U_PRGID>();
			}
		}
		
		public System.Data.Linq.Table<V_BASE> V_BASE
		{
			get
			{
				return this.GetTable<V_BASE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.U_PRGID")]
	public partial class U_PRGID
	{
		
		private string _USER_ID;
		
		private string _PROG;
		
		private bool _ADD_;
		
		private bool _EDIT;
		
		private bool _DELE;
		
		private bool _PRINT_;
		
		private string _SYSTEM;
		
		private string _KEY_MAN;
		
		private System.DateTime _KEY_DATE;
		
		public U_PRGID()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string USER_ID
		{
			get
			{
				return this._USER_ID;
			}
			set
			{
				if ((this._USER_ID != value))
				{
					this._USER_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROG", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PROG
		{
			get
			{
				return this._PROG;
			}
			set
			{
				if ((this._PROG != value))
				{
					this._PROG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADD_", DbType="Bit NOT NULL")]
		public bool ADD_
		{
			get
			{
				return this._ADD_;
			}
			set
			{
				if ((this._ADD_ != value))
				{
					this._ADD_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDIT", DbType="Bit NOT NULL")]
		public bool EDIT
		{
			get
			{
				return this._EDIT;
			}
			set
			{
				if ((this._EDIT != value))
				{
					this._EDIT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DELE", DbType="Bit NOT NULL")]
		public bool DELE
		{
			get
			{
				return this._DELE;
			}
			set
			{
				if ((this._DELE != value))
				{
					this._DELE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRINT_", DbType="Bit NOT NULL")]
		public bool PRINT_
		{
			get
			{
				return this._PRINT_;
			}
			set
			{
				if ((this._PRINT_ != value))
				{
					this._PRINT_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYSTEM", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SYSTEM
		{
			get
			{
				return this._SYSTEM;
			}
			set
			{
				if ((this._SYSTEM != value))
				{
					this._SYSTEM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEY_MAN", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string KEY_MAN
		{
			get
			{
				return this._KEY_MAN;
			}
			set
			{
				if ((this._KEY_MAN != value))
				{
					this._KEY_MAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEY_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime KEY_DATE
		{
			get
			{
				return this._KEY_DATE;
			}
			set
			{
				if ((this._KEY_DATE != value))
				{
					this._KEY_DATE = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_BASE")]
	public partial class V_BASE
	{
		
		private string _NOBR;
		
		private string _NAME_C;
		
		private string _NAME_E;
		
		private string _NAME_P;
		
		private string _SALADR;
		
		private string _IDNO;
		
		public V_BASE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOBR", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOBR
		{
			get
			{
				return this._NOBR;
			}
			set
			{
				if ((this._NOBR != value))
				{
					this._NOBR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME_C", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NAME_C
		{
			get
			{
				return this._NAME_C;
			}
			set
			{
				if ((this._NAME_C != value))
				{
					this._NAME_C = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME_E", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NAME_E
		{
			get
			{
				return this._NAME_E;
			}
			set
			{
				if ((this._NAME_E != value))
				{
					this._NAME_E = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME_P", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NAME_P
		{
			get
			{
				return this._NAME_P;
			}
			set
			{
				if ((this._NAME_P != value))
				{
					this._NAME_P = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALADR", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SALADR
		{
			get
			{
				return this._SALADR;
			}
			set
			{
				if ((this._SALADR != value))
				{
					this._SALADR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string IDNO
		{
			get
			{
				return this._IDNO;
			}
			set
			{
				if ((this._IDNO != value))
				{
					this._IDNO = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
