<?xml version="1.0" encoding="utf-8"?><Database Name="PHOENIXHR" Class="HrContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.,1485;Initial Catalog=PHOENIXHR;User ID=jb" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="HRSqlServer" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SalaryPassWord" Member="SalaryPassWord">
    <Type Name="SalaryPassWord">
      <Column Name="iAutoKey" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="sNobr" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sPassWord" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="sIP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="dKeyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="dLoginDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="sLoginIP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>