<%@ Page Language="C#" AutoEventWireup="true" CodeFile="test.aspx.cs" Inherits="eTraining_test" %>

<%@ Register assembly="Telerik.Web.UI" namespace="Telerik.Web.UI" tagprefix="telerik" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>

</head>
<body>
    <form id="form1" runat="server">
    <div>    
        <telerik:RadScriptManager ID="RadScriptManager1" Runat="server">
        </telerik:RadScriptManager>
                 <asp:Button ID="Button8" runat="server" onclick="Button8_Click" 
            Text="Button" />
                 <script language="javascript" type="text/javascript">
                     function OnClientSelectedIndexChanged(sender, eventArgs) {
                         var item = eventArgs.get_item();
                         sender.set_text("You selected " + item.get_text());
                     }
</script>
        <br />
        <br />
        <asp:Button ID="Button6" runat="server" onclick="Button6_Click" 
            Text="testttttt" />
        <telerik:RadButton ID="RadButton6" runat="server" onclick="RadButton6_Click" 
            Text="testtttt">
        </telerik:RadButton>
        <telerik:RadGrid ID="RadGrid1" runat="server" AutoGenerateDeleteColumn="True" 
            AutoGenerateEditColumn="True" CellSpacing="0" Culture="zh-TW" GridLines="None" 
            onneeddatasource="RadGrid1_NeedDataSource" AllowAutomaticDeletes="True" 
            ondeletecommand="RadGrid1_DeleteCommand">
<MasterTableView AutoGenerateColumns="False" DataKeyNames="c.iAutoKey">
<CommandItemSettings ExportToPdfText="Export to PDF"></CommandItemSettings>

<RowIndicatorColumn FilterControlAltText="Filter RowIndicator column">
</RowIndicatorColumn>

<ExpandCollapseColumn FilterControlAltText="Filter ExpandColumn column">
</ExpandCollapseColumn>

    <Columns>
        <telerik:GridBoundColumn DataField="c.iAutoKey" DataType="System.Int32" 
            FilterControlAltText="Filter iAutoKey column" HeaderText="iAutoKey" 
            ReadOnly="True" SortExpression="iAutoKey" UniqueName="iAutoKey">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="c.sCode" 
            FilterControlAltText="Filter sCode column" HeaderText="sCode" 
            SortExpression="sCode" UniqueName="sCode">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="c.sName" 
            FilterControlAltText="Filter sName column" HeaderText="sName" 
            SortExpression="sName" UniqueName="sName">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="c.sKeyMan" 
            FilterControlAltText="Filter sKeyMan column" HeaderText="sKeyMan" 
            SortExpression="sKeyMan" UniqueName="sKeyMan">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="c.dKeyDate" DataType="System.DateTime" 
            FilterControlAltText="Filter dKeyDate column" HeaderText="dKeyDate" 
            SortExpression="dKeyDate" UniqueName="dKeyDate">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="i.iiKey" 
            FilterControlAltText="Filter iiKey column" HeaderText="iiKey" 
            UniqueName="iiKey">
        </telerik:GridBoundColumn>
    </Columns>

<EditFormSettings>
<EditColumn FilterControlAltText="Filter EditCommandColumn column"></EditColumn>
</EditFormSettings>
</MasterTableView>

<FilterMenu EnableImageSprites="False"></FilterMenu>

<HeaderContextMenu CssClass="GridContextMenu GridContextMenu_Default"></HeaderContextMenu>
        </telerik:RadGrid>
    
    </div>
    <asp:LinqDataSource ID="LinqDataSource1" runat="server" 
        ContextTypeName="dcTrainingDataContext" EnableDelete="True" EnableInsert="True" 
        EnableUpdate="True" EntityTypeName="" onselecting="LinqDataSource1_Selecting" 
        TableName="trNotifyTemplate">
    </asp:LinqDataSource>
    <br />
    <br />
    <telerik:RadGrid ID="RadGrid2" runat="server" AllowAutomaticDeletes="True" 
        CellSpacing="0" Culture="zh-TW" 
        GridLines="None" DataSourceID="LinqDataSource2">
<ClientSettings>
<Selecting CellSelectionMode="None"></Selecting>
</ClientSettings>

<MasterTableView autogeneratecolumns="False" datakeynames="iAutoKey" 
            DataSourceID="LinqDataSource2">
<CommandItemSettings ExportToPdfText="Export to PDF"></CommandItemSettings>

<RowIndicatorColumn FilterControlAltText="Filter RowIndicator column">
<HeaderStyle Width="20px"></HeaderStyle>
</RowIndicatorColumn>

<ExpandCollapseColumn FilterControlAltText="Filter ExpandColumn column">
<HeaderStyle Width="20px"></HeaderStyle>
</ExpandCollapseColumn>

<EditFormSettings>
<EditColumn FilterControlAltText="Filter EditCommandColumn column"></EditColumn>
</EditFormSettings>
</MasterTableView>

<FilterMenu EnableImageSprites="False"></FilterMenu>

<HeaderContextMenu CssClass="GridContextMenu GridContextMenu_Default"></HeaderContextMenu>
    </telerik:RadGrid>
    <asp:LinqDataSource ID="LinqDataSource2" runat="server" 
        ContextTypeName="dcTrainingDataContext" EnableDelete="True" EnableInsert="True" 
        EnableUpdate="True" EntityTypeName="" TableName="trNotifyTemplate">
    </asp:LinqDataSource>
    <asp:Button ID="Button7" runat="server" onclick="Button7_Click" 
        Text="export excel" />
    <telerik:RadGrid ID="RadGrid3" runat="server" CellSpacing="0" Culture="zh-TW" 
        GridLines="None" AutoGenerateHierarchy="True" 
        onitemdatabound="RadGrid3_ItemDataBound" 
        onneeddatasource="RadGrid3_NeedDataSource" ShowFooter="True">
<ClientSettings>
<Selecting CellSelectionMode="None"></Selecting>
</ClientSettings>

<MasterTableView ShowFooter="False">
<CommandItemSettings ExportToPdfText="Export to PDF"></CommandItemSettings>

<RowIndicatorColumn FilterControlAltText="Filter RowIndicator column">
<HeaderStyle Width="20px"></HeaderStyle>
</RowIndicatorColumn>

<ExpandCollapseColumn FilterControlAltText="Filter ExpandColumn column">
<HeaderStyle Width="20px"></HeaderStyle>
</ExpandCollapseColumn>

<EditFormSettings>
<EditColumn FilterControlAltText="Filter EditCommandColumn column"></EditColumn>
</EditFormSettings>
</MasterTableView>

<FilterMenu EnableImageSprites="False"></FilterMenu>

<HeaderContextMenu CssClass="GridContextMenu GridContextMenu_Default"></HeaderContextMenu>
    </telerik:RadGrid>
    <br />
                    <telerik:RadComboBox ID="cbxYear" runat="server" Width="70px">
            </telerik:RadComboBox>
             <telerik:RadOrgChart ID="RadOrgChart1" runat="server" Skin="Forest" 
        ongroupitemdatabound="RadOrgChart1_GroupItemDataBound" 
        onnodedatabound="RadOrgChart1_NodeDataBound">
             <ItemTemplate>                          
                  <asp:Panel runat="server" ID="Panel1" CssClass="TemplateHolder">
              <div class="rocCustomTextWrap">
                        <div>
                     <%# Eval("D_NAME")%>                 
                        </div>                         
                    </div>
                    <span class="rocCustomImageWrap">
                       <telerik:RadBinaryImage runat="server" ID="RadBinaryImage1"  Height="64px" Width="64px"
                       ImageUrl='<%#"~/TestEmpPhoto.aspx?Nobr="+Eval("Nobr")%>' />
                    </span>

                </asp:Panel>
                            
             </ItemTemplate>
                </telerik:RadOrgChart>
    <asp:LinqDataSource ID="LinqDataSource3" runat="server" 
        ContextTypeName="dcTrainingDataContext" EntityTypeName="" 
        Select="new (D_NO, D_NAME, D_ENAME, DEPT_GROUP)" TableName="DEPT">
    </asp:LinqDataSource>
    <br />
    <asp:Button ID="Button3" runat="server" onclick="Button3_Click" Text="Button" />
    <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
    <telerik:RadTreeView ID="RadTreeView1" Runat="server" SingleExpandPath="True">
        <Nodes>
            <telerik:RadTreeNode runat="server" Text="Root RadTreeNode1">
            </telerik:RadTreeNode>
            <telerik:RadTreeNode runat="server" Text="Root RadTreeNode2">
            </telerik:RadTreeNode>
            <telerik:RadTreeNode runat="server" Text="Root RadTreeNode3">
                <Nodes>
                    <telerik:RadTreeNode runat="server" Text="Child RadTreeNode 1">
                        <Nodes>
                            <telerik:RadTreeNode runat="server" Text="Child RadTreeNode 1">
                            </telerik:RadTreeNode>
                            <telerik:RadTreeNode runat="server" Text="Child RadTreeNode 2">
                            </telerik:RadTreeNode>
                            <telerik:RadTreeNode runat="server" Text="Child RadTreeNode 3">
                            </telerik:RadTreeNode>
                        </Nodes>
                    </telerik:RadTreeNode>
                    <telerik:RadTreeNode runat="server" Text="Child RadTreeNode 2">
                    </telerik:RadTreeNode>
                    <telerik:RadTreeNode runat="server" Text="Child RadTreeNode 3">
                    </telerik:RadTreeNode>
                </Nodes>
            </telerik:RadTreeNode>
        </Nodes>
        <ContextMenus>
            <telerik:RadTreeViewContextMenu ID="RadTreeViewContextMenu1" runat="server">
            </telerik:RadTreeViewContextMenu>
            <telerik:RadTreeViewContextMenu ID="RadTreeViewContextMenu2" runat="server">
            </telerik:RadTreeViewContextMenu>
            <telerik:RadTreeViewContextMenu ID="RadTreeViewContextMenu3" runat="server">
            </telerik:RadTreeViewContextMenu>
        </ContextMenus>
    </telerik:RadTreeView>
    <br />
    <telerik:RadButton ID="RadButton4" runat="server" onclick="RadButton4_Click" 
        Text="RadButton">
    </telerik:RadButton>
    <asp:Button ID="Button4" runat="server" onclick="Button4_Click" Text="draw" />
    <br />
    <telerik:RadButton ID="RadButton2" runat="server" Text="test" 
        onclick="RadButton2_Click">
    </telerik:RadButton>
    <asp:TreeView ID="TreeView1" runat="server" ShowLines="True" >
        <Nodes>
            <asp:TreeNode Text="新節點" Value="新節點"></asp:TreeNode>
            <asp:TreeNode Text="新節點" Value="新節點"></asp:TreeNode>
            <asp:TreeNode Text="新節點" Value="新節點">
                <asp:TreeNode Text="新節點" Value="新節點">
                    <asp:TreeNode Text="新節點" Value="新節點">
                        <asp:TreeNode Text="新節點" Value="新節點">
                            <asp:TreeNode Text="新節點" Value="新節點"></asp:TreeNode>
                        </asp:TreeNode>
                    </asp:TreeNode>
                </asp:TreeNode>
            </asp:TreeNode>
            <asp:TreeNode Text="新節點" Value="新節點"></asp:TreeNode>
        </Nodes>
    </asp:TreeView>
    <br />

    <telerik:RadAjaxPanel ID="RadAjaxPanel1" runat="server" height="200px" 
        width="527px">
        <telerik:RadComboBox ID="RadComboBox2" Runat="server" EnableLoadOnDemand="True" 
        LoadingMessage="載入中..." MinFilterLength="3" 
        onitemsrequested="RadComboBox2_ItemsRequested" 
    style="margin-bottom: 0px" AutoPostBack="True" 
            onselectedindexchanged="RadComboBox2_SelectedIndexChanged" 
            DataTextField="NAME_C" DataValueField="NOBR" ShowToggleImage="False" >
        </telerik:RadComboBox>
        <asp:Label ID="Label2" runat="server" Text="Label"></asp:Label>
        <asp:Label ID="Label3" runat="server" Text="Label"></asp:Label>
        <telerik:RadButton ID="RadButton5" runat="server" onclick="RadButton5_Click" 
            Text="RadButton">
        </telerik:RadButton>
        <asp:Button ID="Button5" runat="server" onclick="Button5_Click" Text="Button" />
        <br />
        <asp:Button ID="Button1" runat="server" Height="69px" onclick="Button1_Click" 
            Text="Button" />
        <telerik:RadWindow ID="RadWindow1" runat="server">
            <ContentTemplate>
                <telerik:RadButton ID="RadButton1" runat="server" Text="RadButton">
                </telerik:RadButton>
                <asp:Button ID="Button2" runat="server" Text="Button" />
                <asp:Calendar ID="Calendar1" runat="server"></asp:Calendar>
            </ContentTemplate>
        </telerik:RadWindow>
        <telerik:RadWindow ID="RadWindow2" runat="server">
        </telerik:RadWindow>
        <telerik:RadTabStrip ID="RadTabStrip1" runat="server" 
            MultiPageID="RadMultiPage1" SelectedIndex="1">
            <tabs>
                <telerik:RadTab runat="server" PageViewID="pv1" Text="Root RadTab1">
                </telerik:RadTab>
                <telerik:RadTab runat="server" 
                    NavigateUrl="~/eTraining/Admin/Do/DoCourseList.aspx" PageViewID="pv2" 
                    Selected="True" Text="Root RadTab2">
                </telerik:RadTab>
                <telerik:RadTab runat="server" 
                    NavigateUrl="~/eTraining/Admin/Do/DoCourseList.aspx" Owner="RadTabStrip1" 
                    Text="Root RadTab3">
                </telerik:RadTab>
                <telerik:RadTab runat="server" 
                    NavigateUrl="~/eTraining/Admin/Do/DoCourseList.aspx" Owner="RadTabStrip1" 
                    Text="Root RadTab4">
                </telerik:RadTab>
            </tabs>
        </telerik:RadTabStrip>
        <telerik:RadMultiPage ID="RadMultiPage1" Runat="server" SelectedIndex="1" 
            Width="417px">
            <telerik:RadPageView ID="pv1" runat="server">RadPa<telerik:RadTextBox 
                ID="RadTextBox1" Runat="server" EmptyMessage=" ">
        <passwordstrengthsettings calculationweightings="50;15;15;20" 
                indicatorelementbasestyle="riStrengthBar" indicatorelementid="" 
                minimumlowercasecharacters="2" minimumnumericcharacters="2" 
                minimumsymbolcharacters="2" minimumuppercasecharacters="2" 
                onclientpasswordstrengthcalculating="" preferredpasswordlength="10" 
                requiresupperandlowercasecharacters="True" showindicator="False" 
                textstrengthdescriptions="Very Weak;Weak;Medium;Strong;Very Strong" 
                textstrengthdescriptionstyles="riStrengthBarL0;riStrengthBarL1;riStrengthBarL2;riStrengthBarL3;riStrengthBarL4;riStrengthBarL5;" />
        <emptymessagestyle backcolor="#FF9900" bordercolor="#FF9900" />
        </telerik:RadTextBox>
        <telerik:RadButton ID="RadButton3" runat="server" onclick="RadButton3_Click1" 
                Text="RadButton">
        </telerik:RadButton>
        <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" 
                ControlToValidate="RadTextBox1" Display="Dynamic" ErrorMessage="必須要有值"></asp:RequiredFieldValidator>
        <br />
        testtttt&nbsp; geView</telerik:RadPageView>
            <telerik:RadPageView ID="pv2" runat="server">
</telerik:RadPageView>
            <telerik:RadPageView ID="RadPageView3" runat="server" 
                ContentUrl="~/eTraining/Admin/Do/DoCourseList.aspx">
</telerik:RadPageView>
        </telerik:RadMultiPage>
        <asp:ObjectDataSource ID="ObjectDataSource1" runat="server" 
            OldValuesParameterFormatString="original_{0}" SelectMethod="GetLastEmp" 
            TypeName="JBComboBoxData"></asp:ObjectDataSource>
    </telerik:RadAjaxPanel>
    <br />
    </form>
</body>
</html>
