//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.239
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JBHR.Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Bas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Bas() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JBHR.Resources.Bas", typeof(Bas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 生效日期不可空白。 的當地語系化字串。
        /// </summary>
        internal static string CADATEReqErr {
            get {
                return ResourceManager.GetString("CADATEReqErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 失效日期不可空白。 的當地語系化字串。
        /// </summary>
        internal static string CDDATEReqErr {
            get {
                return ResourceManager.GetString("CDDATEReqErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公司名稱不可空白。 的當地語系化字串。
        /// </summary>
        internal static string COMPANYReqErr {
            get {
                return ResourceManager.GetString("COMPANYReqErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發照單位不可空白。 的當地語系化字串。
        /// </summary>
        internal static string COMPReqErr {
            get {
                return ResourceManager.GetString("COMPReqErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 費用分攤資料尚有未通過驗正的欄位。 的當地語系化字串。
        /// </summary>
        internal static string COSTErr {
            get {
                return ResourceManager.GetString("COSTErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 費用分攤比率設定不可大於 100。 的當地語系化字串。
        /// </summary>
        internal static string CostRateMaxLimitErr {
            get {
                return ResourceManager.GetString("CostRateMaxLimitErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 徹銷日期不可小於成立日期。 的當地語系化字串。
        /// </summary>
        internal static string DeptDateErr {
            get {
                return ResourceManager.GetString("DeptDateErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選取成本部門。 的當地語系化字串。
        /// </summary>
        internal static string DEPTSReqErr {
            get {
                return ResourceManager.GetString("DEPTSReqErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 證照內容不可空白。 的當地語系化字串。
        /// </summary>
        internal static string DESCSReqErr {
            get {
                return ResourceManager.GetString("DESCSReqErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 此筆異動不可刪除。 的當地語系化字串。
        /// </summary>
        internal static string DontDelThisTTS {
            get {
                return ResourceManager.GetString("DontDelThisTTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 有效內容不可空白。 的當地語系化字串。
        /// </summary>
        internal static string EDATEReqErr {
            get {
                return ResourceManager.GetString("EDATEReqErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選取教育程度。 的當地語系化字串。
        /// </summary>
        internal static string EducCodeReqErr {
            get {
                return ResourceManager.GetString("EducCodeReqErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 眷屬生日不可空白。 的當地語系化字串。
        /// </summary>
        internal static string FA_BIRDTReqErr {
            get {
                return ResourceManager.GetString("FA_BIRDTReqErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 眷屬身分字號不可重覆。 的當地語系化字串。
        /// </summary>
        internal static string FA_IDNO_RPT_Err {
            get {
                return ResourceManager.GetString("FA_IDNO_RPT_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 眷屬姓名不可空白。 的當地語系化字串。
        /// </summary>
        internal static string FA_NameReqErr {
            get {
                return ResourceManager.GetString("FA_NameReqErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 眷屬資料尚有未通過驗正的欄位。 的當地語系化字串。
        /// </summary>
        internal static string FamilyErr {
            get {
                return ResourceManager.GetString("FamilyErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 身分證號錯誤。 的當地語系化字串。
        /// </summary>
        internal static string IDNOErr {
            get {
                return ResourceManager.GetString("IDNOErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 身分證號不可空白。 的當地語系化字串。
        /// </summary>
        internal static string IDNORequiredErr {
            get {
                return ResourceManager.GetString("IDNORequiredErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 證照編號不可空白。 的當地語系化字串。
        /// </summary>
        internal static string LIC_NOReqErr {
            get {
                return ResourceManager.GetString("LIC_NOReqErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 證照資料尚有未通過驗正的欄位。 的當地語系化字串。
        /// </summary>
        internal static string LICANErr {
            get {
                return ResourceManager.GetString("LICANErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 專長與興趣資料尚有未通過驗正的欄位。 的當地語系化字串。
        /// </summary>
        internal static string MASTERErr {
            get {
                return ResourceManager.GetString("MASTERErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 專長與興趣不可空白。 的當地語系化字串。
        /// </summary>
        internal static string MasterReqErr {
            get {
                return ResourceManager.GetString("MasterReqErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 生效內容不可空白。 的當地語系化字串。
        /// </summary>
        internal static string MDATEReqErr {
            get {
                return ResourceManager.GetString("MDATEReqErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 此工號已經存在。 的當地語系化字串。
        /// </summary>
        internal static string NOBRREPETITION {
            get {
                return ResourceManager.GetString("NOBRREPETITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 分攤比率不可空白。 的當地語系化字串。
        /// </summary>
        internal static string RATEReqErr {
            get {
                return ResourceManager.GetString("RATEReqErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選取眷屬種類。 的當地語系化字串。
        /// </summary>
        internal static string REL_CODEReqErr {
            get {
                return ResourceManager.GetString("REL_CODEReqErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 教育程度資料尚有未通過驗正的欄位。 的當地語系化字串。
        /// </summary>
        internal static string SCHLErr {
            get {
                return ResourceManager.GetString("SCHLErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 學校不可空白。 的當地語系化字串。
        /// </summary>
        internal static string SCHLReqErr {
            get {
                return ResourceManager.GetString("SCHLReqErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 職稱不可空白。 的當地語系化字串。
        /// </summary>
        internal static string TITLEReqErr {
            get {
                return ResourceManager.GetString("TITLEReqErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 異動生效日不可小於已存在的異動生效日。 的當地語系化字串。
        /// </summary>
        internal static string TTSAdateErr {
            get {
                return ResourceManager.GetString("TTSAdateErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 異動日期不可重覆。 的當地語系化字串。
        /// </summary>
        internal static string TTSDateErr {
            get {
                return ResourceManager.GetString("TTSDateErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 經歷資料尚有未通過驗正的欄位。 的當地語系化字串。
        /// </summary>
        internal static string WORKSErr {
            get {
                return ResourceManager.GetString("WORKSErr", resourceCulture);
            }
        }
    }
}
