#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitorShareMail
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EMC_HR")]
	public partial class dcMainDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 擴充性方法定義
    partial void OnCreated();
    partial void InsertMAILQUEUE(MAILQUEUE instance);
    partial void UpdateMAILQUEUE(MAILQUEUE instance);
    partial void DeleteMAILQUEUE(MAILQUEUE instance);
    #endregion
		
		public dcMainDataContext() : 
				base(global::MonitorShareMail.Properties.Settings.Default.EMC_HRConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dcMainDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcMainDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcMainDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcMainDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MAILQUEUE> MAILQUEUE
		{
			get
			{
				return this.GetTable<MAILQUEUE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MAILQUEUE")]
	public partial class MAILQUEUE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _GUID;
		
		private string _FROM_ADDR;
		
		private string _FROM_NAME;
		
		private string _TO_ADDR;
		
		private string _TO_NAME;
		
		private string _SUBJECT;
		
		private string _BODY;
		
		private int _RETRY;
		
		private bool _SUCCESS;
		
		private bool _SUSPEND;
		
		private System.DateTime _FREEZE_TIME;
		
		private System.DateTime _KEY_DATE;
		
		private string _KEY_MAN;
		
		private string _NOTE;
		
		private string _NOTE1;
		
		private string _NOTE2;
		
		private string _NOTE3;
		
		private string _NOTE4;
		
		private string _NOTE5;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnGUIDChanging(string value);
    partial void OnGUIDChanged();
    partial void OnFROM_ADDRChanging(string value);
    partial void OnFROM_ADDRChanged();
    partial void OnFROM_NAMEChanging(string value);
    partial void OnFROM_NAMEChanged();
    partial void OnTO_ADDRChanging(string value);
    partial void OnTO_ADDRChanged();
    partial void OnTO_NAMEChanging(string value);
    partial void OnTO_NAMEChanged();
    partial void OnSUBJECTChanging(string value);
    partial void OnSUBJECTChanged();
    partial void OnBODYChanging(string value);
    partial void OnBODYChanged();
    partial void OnRETRYChanging(int value);
    partial void OnRETRYChanged();
    partial void OnSUCCESSChanging(bool value);
    partial void OnSUCCESSChanged();
    partial void OnSUSPENDChanging(bool value);
    partial void OnSUSPENDChanged();
    partial void OnFREEZE_TIMEChanging(System.DateTime value);
    partial void OnFREEZE_TIMEChanged();
    partial void OnKEY_DATEChanging(System.DateTime value);
    partial void OnKEY_DATEChanged();
    partial void OnKEY_MANChanging(string value);
    partial void OnKEY_MANChanged();
    partial void OnNOTEChanging(string value);
    partial void OnNOTEChanged();
    partial void OnNOTE1Changing(string value);
    partial void OnNOTE1Changed();
    partial void OnNOTE2Changing(string value);
    partial void OnNOTE2Changed();
    partial void OnNOTE3Changing(string value);
    partial void OnNOTE3Changed();
    partial void OnNOTE4Changing(string value);
    partial void OnNOTE4Changed();
    partial void OnNOTE5Changing(string value);
    partial void OnNOTE5Changed();
    #endregion
		
		public MAILQUEUE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string GUID
		{
			get
			{
				return this._GUID;
			}
			set
			{
				if ((this._GUID != value))
				{
					this.OnGUIDChanging(value);
					this.SendPropertyChanging();
					this._GUID = value;
					this.SendPropertyChanged("GUID");
					this.OnGUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FROM_ADDR", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FROM_ADDR
		{
			get
			{
				return this._FROM_ADDR;
			}
			set
			{
				if ((this._FROM_ADDR != value))
				{
					this.OnFROM_ADDRChanging(value);
					this.SendPropertyChanging();
					this._FROM_ADDR = value;
					this.SendPropertyChanged("FROM_ADDR");
					this.OnFROM_ADDRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FROM_NAME", DbType="NVarChar(50)")]
		public string FROM_NAME
		{
			get
			{
				return this._FROM_NAME;
			}
			set
			{
				if ((this._FROM_NAME != value))
				{
					this.OnFROM_NAMEChanging(value);
					this.SendPropertyChanging();
					this._FROM_NAME = value;
					this.SendPropertyChanged("FROM_NAME");
					this.OnFROM_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TO_ADDR", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TO_ADDR
		{
			get
			{
				return this._TO_ADDR;
			}
			set
			{
				if ((this._TO_ADDR != value))
				{
					this.OnTO_ADDRChanging(value);
					this.SendPropertyChanging();
					this._TO_ADDR = value;
					this.SendPropertyChanged("TO_ADDR");
					this.OnTO_ADDRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TO_NAME", DbType="NVarChar(50)")]
		public string TO_NAME
		{
			get
			{
				return this._TO_NAME;
			}
			set
			{
				if ((this._TO_NAME != value))
				{
					this.OnTO_NAMEChanging(value);
					this.SendPropertyChanging();
					this._TO_NAME = value;
					this.SendPropertyChanged("TO_NAME");
					this.OnTO_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBJECT", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string SUBJECT
		{
			get
			{
				return this._SUBJECT;
			}
			set
			{
				if ((this._SUBJECT != value))
				{
					this.OnSUBJECTChanging(value);
					this.SendPropertyChanging();
					this._SUBJECT = value;
					this.SendPropertyChanged("SUBJECT");
					this.OnSUBJECTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BODY", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string BODY
		{
			get
			{
				return this._BODY;
			}
			set
			{
				if ((this._BODY != value))
				{
					this.OnBODYChanging(value);
					this.SendPropertyChanging();
					this._BODY = value;
					this.SendPropertyChanged("BODY");
					this.OnBODYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RETRY", DbType="Int NOT NULL")]
		public int RETRY
		{
			get
			{
				return this._RETRY;
			}
			set
			{
				if ((this._RETRY != value))
				{
					this.OnRETRYChanging(value);
					this.SendPropertyChanging();
					this._RETRY = value;
					this.SendPropertyChanged("RETRY");
					this.OnRETRYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUCCESS", DbType="Bit NOT NULL")]
		public bool SUCCESS
		{
			get
			{
				return this._SUCCESS;
			}
			set
			{
				if ((this._SUCCESS != value))
				{
					this.OnSUCCESSChanging(value);
					this.SendPropertyChanging();
					this._SUCCESS = value;
					this.SendPropertyChanged("SUCCESS");
					this.OnSUCCESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUSPEND", DbType="Bit NOT NULL")]
		public bool SUSPEND
		{
			get
			{
				return this._SUSPEND;
			}
			set
			{
				if ((this._SUSPEND != value))
				{
					this.OnSUSPENDChanging(value);
					this.SendPropertyChanging();
					this._SUSPEND = value;
					this.SendPropertyChanged("SUSPEND");
					this.OnSUSPENDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FREEZE_TIME", DbType="DateTime NOT NULL")]
		public System.DateTime FREEZE_TIME
		{
			get
			{
				return this._FREEZE_TIME;
			}
			set
			{
				if ((this._FREEZE_TIME != value))
				{
					this.OnFREEZE_TIMEChanging(value);
					this.SendPropertyChanging();
					this._FREEZE_TIME = value;
					this.SendPropertyChanged("FREEZE_TIME");
					this.OnFREEZE_TIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEY_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime KEY_DATE
		{
			get
			{
				return this._KEY_DATE;
			}
			set
			{
				if ((this._KEY_DATE != value))
				{
					this.OnKEY_DATEChanging(value);
					this.SendPropertyChanging();
					this._KEY_DATE = value;
					this.SendPropertyChanged("KEY_DATE");
					this.OnKEY_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEY_MAN", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string KEY_MAN
		{
			get
			{
				return this._KEY_MAN;
			}
			set
			{
				if ((this._KEY_MAN != value))
				{
					this.OnKEY_MANChanging(value);
					this.SendPropertyChanging();
					this._KEY_MAN = value;
					this.SendPropertyChanged("KEY_MAN");
					this.OnKEY_MANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE", DbType="NVarChar(50)")]
		public string NOTE
		{
			get
			{
				return this._NOTE;
			}
			set
			{
				if ((this._NOTE != value))
				{
					this.OnNOTEChanging(value);
					this.SendPropertyChanging();
					this._NOTE = value;
					this.SendPropertyChanged("NOTE");
					this.OnNOTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE1", DbType="NVarChar(50)")]
		public string NOTE1
		{
			get
			{
				return this._NOTE1;
			}
			set
			{
				if ((this._NOTE1 != value))
				{
					this.OnNOTE1Changing(value);
					this.SendPropertyChanging();
					this._NOTE1 = value;
					this.SendPropertyChanged("NOTE1");
					this.OnNOTE1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE2", DbType="NVarChar(50)")]
		public string NOTE2
		{
			get
			{
				return this._NOTE2;
			}
			set
			{
				if ((this._NOTE2 != value))
				{
					this.OnNOTE2Changing(value);
					this.SendPropertyChanging();
					this._NOTE2 = value;
					this.SendPropertyChanged("NOTE2");
					this.OnNOTE2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE3", DbType="NVarChar(50)")]
		public string NOTE3
		{
			get
			{
				return this._NOTE3;
			}
			set
			{
				if ((this._NOTE3 != value))
				{
					this.OnNOTE3Changing(value);
					this.SendPropertyChanging();
					this._NOTE3 = value;
					this.SendPropertyChanged("NOTE3");
					this.OnNOTE3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE4", DbType="NVarChar(50)")]
		public string NOTE4
		{
			get
			{
				return this._NOTE4;
			}
			set
			{
				if ((this._NOTE4 != value))
				{
					this.OnNOTE4Changing(value);
					this.SendPropertyChanging();
					this._NOTE4 = value;
					this.SendPropertyChanged("NOTE4");
					this.OnNOTE4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE5", DbType="NVarChar(50)")]
		public string NOTE5
		{
			get
			{
				return this._NOTE5;
			}
			set
			{
				if ((this._NOTE5 != value))
				{
					this.OnNOTE5Changing(value);
					this.SendPropertyChanging();
					this._NOTE5 = value;
					this.SendPropertyChanged("NOTE5");
					this.OnNOTE5Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
