CREATE FUNCTION [dbo].[DECODE](@VALUE DECIMAL(16,2))
RETURNS DECIMAL(16,2)
AS
BEGIN
	DECLARE @KEY VARCHAR(50)
	DECLARE @LCFLAG varchar(50)
	DECLARE @VALSTR varchar(50)
	DECLARE @LL varchar(50)
	DECLARE @VALLEN INT
	DECLARE @STARTPOS INT
	DECLARE @I INT
	DECLARE @AA VARCHAR(50)
	DECLARE @ITMP INT
	DECLARE @INDEX INT
	DECLARE @YY INT
	DECLARE @WW INT
	DECLARE @ZZ INT
	DECLARE @DIG DECIMAL(12,2)
	SET @LL=''
	SET @DIG=ABS(@VALUE)%1
	SET @KEY='3761532470658472653034873'
	IF(@VALUE=0)SET @LL=0
	ELSE
		BEGIN
		IF @VALUE<0 
			SET @LCFLAG='-'
		ELSE
		SET @LCFLAG='+'
		SET @VALSTR=RTRIM(LTRIM(ABS(CONVERT(INT,@VALUE))))
		SET @VALLEN=LEN(@VALSTR)
		IF @VALLEN>=2
			SET @ITMP=@VALLEN-2
		ELSE
			SET @ITMP=0
		SET @AA=SUBSTRING(@VALSTR,@ITMP+1,2)
		IF LEN(@AA)>=1
			SET @ITMP=LEN(@AA)-1
		ELSE
			SET @ITMP=0	
		SET @STARTPOS=CONVERT(INT,SUBSTRING(@AA,@ITMP+1,1))
		SET @VALLEN=CONVERT(INT,SUBSTRING(@AA,1,1))
		SET @VALSTR=SUBSTRING(@VALSTR,1,LEN(@VALSTR)-2)
		IF LEN(@VALSTR)<@VALLEN
			SET @VALSTR=CONVERT(VARCHAR,RIGHT(POWER(10,@VALLEN)+CONVERT(INT,@VALSTR),@VALLEN))
		SET @I=0
		WHILE (@I<@VALLEN)
		BEGIN		
			SET @ZZ=0--
			SET @ZZ=CONVERT(INT,SUBSTRING(@VALSTR,@I+1,1))--
			SET @INDEX=@STARTPOS+@I-1
			SET @YY=0
			IF @INDEX>=0
				SET @YY=CONVERT(INT,SUBSTRING(@KEY,@INDEX+1,1))
			SET @WW=@ZZ-@YY
			IF @WW<0
				SET @WW=10+@WW
			SET @ITMP=(ABS(@WW))%10
			SET @LL=@LL+CONVERT(VARCHAR,@ITMP)
			SET @I=@I+1
			IF (@I>=@VALLEN)
				BREAK
			ELSE
				CONTINUE
		END
			IF LEN(@LL)=0
				SET @LL=0
			SET @LL=@LCFLAG+@LL
	END
	DECLARE @RESULT DECIMAL(16,2)
	IF(@VALUE>0)
		SET @RESULT= CONVERT(DECIMAL,@LL)+@DIG
		ELSE
		SET @RESULT= CONVERT(DECIMAL,@LL)-@DIG
		RETURN @RESULT
END
--select dbo.DECODE(74433.26)
