CREATE function [dbo].[EATITEMCARDAMT](
 @ETYPE nvarchar(10),@ISSP BIT
,@AAMT  DECIMAL(5,2),@ASPAMT DECIMAL(5,2)
,@BAMT  DECIMAL(5,2),@BSPAMT DECIMAL(5,2)
,@CAMT  DECIMAL(5,2),@CSPAMT DECIMAL(5,2)
,@DAMT  DECIMAL(5,2),@DSPAMT DECIMAL(5,2)
,@EAMT  DECIMAL(5,2),@ESPAMT DECIMAL(5,2)
,@EMPTYPE nvarchar(10)
,@ESP1AMT DECIMAL(5,2)
,@ESP1BMT DECIMAL(5,2)
,@ESP1CMT DECIMAL(5,2)
,@ESP1DMT DECIMAL(5,2)
,@ESP1EMT DECIMAL(5,2)
)

RETURNS DECIMAL(5,2)
as
begin
		DECLARE @RESULT DECIMAL(5,2)
	-- Add the T-SQL statements to compute the return value here

	IF(@EMPTYPE='1' AND @ETYPE='早餐' )
	SET @RESULT= @ESP1AMT
	ELSE IF(@EMPTYPE='1' AND @ETYPE='中餐' )
	SET @RESULT= @ESP1BMT
	ELSE IF(@EMPTYPE='1' AND @ETYPE='晚餐' )
	SET @RESULT= @ESP1CMT
	ELSE IF(@EMPTYPE='1' AND @ETYPE='宵夜' )
	SET @RESULT= @ESP1DMT
	ELSE IF(@EMPTYPE='1' AND @ETYPE='大夜宵' )
	SET @RESULT= @ESP1EMT

	ELSE IF(@EMPTYPE='0' AND @ETYPE='早餐' AND @ISSP=0)
	 SET @RESULT= @AAMT
	ELSE IF(@EMPTYPE='0' AND @ETYPE='早餐' AND @ISSP=1)
	 SET @RESULT= @ASPAMT
	 
	ELSE IF(@EMPTYPE='0' AND @ETYPE='中餐' AND @ISSP=0)
	 SET @RESULT= @BAMT
	ELSE IF(@EMPTYPE='0' AND @ETYPE='中餐' AND @ISSP=1)
	 SET @RESULT= @BSPAMT
	 
	ELSE IF(@EMPTYPE='0' AND @ETYPE='晚餐' AND @ISSP=0)
	 SET @RESULT= @CAMT
	ELSE IF(@EMPTYPE='0' AND @ETYPE='晚餐' AND @ISSP=1)
	 SET @RESULT= @CSPAMT
	 
	ELSE IF(@EMPTYPE='0' AND @ETYPE='宵夜' AND @ISSP=0)
	 SET @RESULT= @DAMT
	ELSE IF(@EMPTYPE='0' AND @ETYPE='宵夜' AND @ISSP=1)
	 SET @RESULT= @DSPAMT
	 
	ELSE IF(@EMPTYPE='0' AND @ETYPE='大夜宵' AND @ISSP=0)
	 SET @RESULT= @EAMT
	ELSE IF(@EMPTYPE='0' AND @ETYPE='大夜宵' AND @ISSP=1)
	 SET @RESULT= @ESPAMT

	 
	
	return @RESULT
end