CREATE function [dbo].[EATITEMCARD](
 @NOBR nvarchar(10),@ADATE  datetime,@ETYPE nvarchar(10)
,@ABTIME nvarchar(10),@AETIME nvarchar(10)
,@BBTIME nvarchar(10),@BETIME nvarchar(10)
,@CBTIME nvarchar(10),@CETIME nvarchar(10)
,@DBTIME nvarchar(10),@DETIME nvarchar(10)
,@EBTIME nvarchar(10),@EETIME nvarchar(10)
)

RETURNS NVARCHAR(10)
as
begin
		DECLARE @RESULT NVARCHAR(10)
	-- Add the T-SQL statements to compute the return value here
	
	IF(@ETYPE='早餐')
	select @RESULT=isnull(ONTIME,'') from EATITEM_CARD WHERE CODE='EATCARD' AND NOBR=@NOBR AND ADATE =@ADATE AND ONTIME BETWEEN @ABTIME AND @AETIME
	ELSE IF(@ETYPE='中餐')
	select @RESULT=isnull(ONTIME,'') from EATITEM_CARD WHERE CODE='EATCARD' AND  NOBR=@NOBR AND ADATE =@ADATE AND ONTIME BETWEEN @BBTIME AND @BETIME
	ELSE IF(@ETYPE='晚餐')
	select @RESULT=isnull(ONTIME,'') from EATITEM_CARD WHERE  CODE='EATCARD' AND   NOBR=@NOBR AND ADATE =@ADATE AND ONTIME BETWEEN @CBTIME AND @CETIME
	ELSE IF(@ETYPE='宵夜')
	select @RESULT=isnull(ONTIME,'') from EATITEM_CARD WHERE CODE='EATCARD' AND  NOBR=@NOBR AND ADATE =@ADATE AND ONTIME BETWEEN @DBTIME AND @DETIME
	ELSE IF(@ETYPE='大夜宵')
	select @RESULT=isnull(ONTIME,'') from EATITEM_CARD WHERE CODE='EATCARD' AND  NOBR=@NOBR AND ADATE =DATEADD(DAY, 1,@ADATE) AND ONTIME BETWEEN @EBTIME AND @EETIME


	
	return @RESULT
end