

CREATE FUNCTION [DBO].[GetMixDaysByCindt](@LOWESTDATE DATETIME,@HIGHESTDATE DATETIME,@ADATE DATETIME,@DDATE DATETIME,@CINDT DATETIME,@TTSCODE NVARCHAR)
RETURNS DECIMAL
AS
BEGIN
	DECLARE @VALUE DECIMAL
	DECLARE @VALUE1 DATETIME
	DECLARE @VALUE2 DATETIME

	--IF(@LOWESTDATE>@ADATE)
	--SET @VALUE1=@LOWESTDATE
	--ELSE SET @VALUE1=@ADATE
	
	--IF(@HIGHESTDATE<@DDATE)
	--SET @VALUE2=@HIGHESTDATE
	--ELSE SET @VALUE2=@DDATE

	IF(@TTSCODE = '1')
	  BEGIN
	  IF(@DDATE < @CINDT) --如果迄日小於
	    BEGIN
		SET @VALUE1 = @CINDT
		SET @VALUE2 = @CINDT - 1
		END
	  ELSE IF(@CINDT > @HIGHESTDATE)
	    BEGIN
		SET @VALUE1 = @CINDT
		SET @VALUE2 = @CINDT - 1
		END
	  ELSE IF(@DDATE > @HIGHESTDATE AND @CINDT <= @HIGHESTDATE)
	    BEGIN
		SET @VALUE1 = @CINDT
		SET @VALUE2 = @HIGHESTDATE
		END
	  ELSE
	    BEGIN
		SET @VALUE1 = @CINDT
		SET @VALUE2 = @DDATE
		END
	  END
	ELSE
	  BEGIN
	  IF(@ADATE > @HIGHESTDATE)
	    BEGIN
		SET @VALUE1 = @HIGHESTDATE
		SET @VALUE2 = @HIGHESTDATE - 1
		END
	  ELSE IF(@ADATE = @HIGHESTDATE)
	    BEGIN
		SET @VALUE1 = @HIGHESTDATE
		SET @VALUE2 = @HIGHESTDATE
		END
	  ELSE IF(@DDATE < @CINDT)
	    BEGIN
	    SET @VALUE1 = @CINDT
		SET @VALUE2 = @CINDT - 1
	    END
	  ELSE IF(@DDATE = @CINDT)
	    BEGIN
	    SET @VALUE1 = @CINDT
		SET @VALUE2 = @CINDT
	    END
	  ELSE IF(@ADATE < @CINDT AND @DDATE > @CINDT)
	    BEGIN
		SET @VALUE1 = @CINDT
		IF(@DDATE > @HIGHESTDATE)
		  BEGIN
		  SET @VALUE2 = @HIGHESTDATE
		  END
		ELSE
		  BEGIN
		  SET @VALUE2 = @DDATE
		  END
		END
	  ELSE IF(@ADATE > @CINDT AND @DDATE > @CINDT)
	    BEGIN
		SET @VALUE1 = @ADATE
	    IF(@DDATE > @HIGHESTDATE)
		  BEGIN
		  SET @VALUE2 = @HIGHESTDATE
		  END
		ELSE
		  BEGIN
		  SET @VALUE2 = @DDATE
		  END
		END
	  END

	SET @VALUE=CONVERT(DECIMAL,@VALUE2-@VALUE1+1)
	RETURN @VALUE
END


