CREATE FUNCTION [dbo].[GetNewACNO]()
RETURNS VARCHAR(50)
AS
BEGIN
	DECLARE @I INT
	DECLARE @C VARCHAR(50)
	SELECT @I=isnull(CONVERT(INT,MAX(ACNO)),0) FROM SALBASND
	SET @I=@I+1
	SET @C=CONVERT(VARCHAR,@I)
	SET @C=REPLICATE('0',5-LEN(@C))+@C
	RETURN @C
END
