CREATE FUNCTION [dbo].[HOLI_TYPE](@OTRCD NVARCHAR(50),@SYS_OT BIT,@OTRCD_SYSOT BIT,@ROTE NVARCHAR(50))
RETURNS NVARCHAR(50)
AS
BEGIN
	DECLARE @RESULT NVARCHAR(50)
	IF(@OTRCD IN ('18','19')) SET @RESULT='國定假日加班'
	ELSE IF(@OTRCD IN ('20','21','22')) SELECT @RESULT=OTRNAME FROM OTRCD WHERE OTRCD=@OTRCD
	ELSE IF(@SYS_OT=1 OR @ROTE='00' OR @OTRCD_SYSOT=1) SET @RESULT='假日加班'
	ELSE  SET @RESULT='平日加班'
	return @RESULT
END
