CREATE FUNCTION [dbo].[OT_TYPE](@OT_HRS DECIMAL,@REST_HRS DECIMAL)
RETURNS NVARCHAR(50)
AS
BEGIN
	DECLARE @RESULT NVARCHAR(50)
	IF(@OT_HRS>0) SET @RESULT='加班費'
	ELSE IF(@REST_HRS>0) SET @RESULT='補休'
	ELSE  SET @RESULT='無'
	return @RESULT
END
