//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JBHR.HPX_WebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiResultOfArrayOfMtcodeDtoMTRdQN6P", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class ApiResultOfArrayOfMtcodeDtoMTRdQN6P : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JBHR.HPX_WebService.MtcodeDto[] ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JBHR.HPX_WebService.MtcodeDto[] Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MtcodeDto", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class MtcodeDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CATEGORYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DISPLAYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SORTField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CATEGORY {
            get {
                return this.CATEGORYField;
            }
            set {
                if ((object.ReferenceEquals(this.CATEGORYField, value) != true)) {
                    this.CATEGORYField = value;
                    this.RaisePropertyChanged("CATEGORY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODE {
            get {
                return this.CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.CODEField, value) != true)) {
                    this.CODEField = value;
                    this.RaisePropertyChanged("CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DISPLAY {
            get {
                return this.DISPLAYField;
            }
            set {
                if ((this.DISPLAYField.Equals(value) != true)) {
                    this.DISPLAYField = value;
                    this.RaisePropertyChanged("DISPLAY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NAME {
            get {
                return this.NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.NAMEField, value) != true)) {
                    this.NAMEField = value;
                    this.RaisePropertyChanged("NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SORT {
            get {
                return this.SORTField;
            }
            set {
                if ((this.SORTField.Equals(value) != true)) {
                    this.SORTField = value;
                    this.RaisePropertyChanged("SORT");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiResultOfMtcodeDtoMTRdQN6P", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class ApiResultOfMtcodeDtoMTRdQN6P : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JBHR.HPX_WebService.MtcodeDto ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JBHR.HPX_WebService.MtcodeDto Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiResultOfHPXPlateDtoMTRdQN6P", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class ApiResultOfHPXPlateDtoMTRdQN6P : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JBHR.HPX_WebService.HPXPlateDto ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JBHR.HPX_WebService.HPXPlateDto Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HPXPlateDto", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class HPXPlateDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastUpdateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastUpdatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlateNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VehicleTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VehicleTypeNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeName {
            get {
                return this.EmployeeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeNameField, value) != true)) {
                    this.EmployeeNameField = value;
                    this.RaisePropertyChanged("EmployeeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeNo {
            get {
                return this.EmployeeNoField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeNoField, value) != true)) {
                    this.EmployeeNoField = value;
                    this.RaisePropertyChanged("EmployeeNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdateDate {
            get {
                return this.LastUpdateDateField;
            }
            set {
                if ((this.LastUpdateDateField.Equals(value) != true)) {
                    this.LastUpdateDateField = value;
                    this.RaisePropertyChanged("LastUpdateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastUpdatedBy {
            get {
                return this.LastUpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.LastUpdatedByField, value) != true)) {
                    this.LastUpdatedByField = value;
                    this.RaisePropertyChanged("LastUpdatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlateNumber {
            get {
                return this.PlateNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PlateNumberField, value) != true)) {
                    this.PlateNumberField = value;
                    this.RaisePropertyChanged("PlateNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sno {
            get {
                return this.SnoField;
            }
            set {
                if ((this.SnoField.Equals(value) != true)) {
                    this.SnoField = value;
                    this.RaisePropertyChanged("Sno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VehicleType {
            get {
                return this.VehicleTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.VehicleTypeField, value) != true)) {
                    this.VehicleTypeField = value;
                    this.RaisePropertyChanged("VehicleType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VehicleTypeName {
            get {
                return this.VehicleTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.VehicleTypeNameField, value) != true)) {
                    this.VehicleTypeNameField = value;
                    this.RaisePropertyChanged("VehicleTypeName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetHPXPlateEntryDto", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class GetHPXPlateEntryDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeId_EndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeId_StartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlateNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] VehicleTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeId_End {
            get {
                return this.EmployeeId_EndField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeId_EndField, value) != true)) {
                    this.EmployeeId_EndField = value;
                    this.RaisePropertyChanged("EmployeeId_End");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeId_Start {
            get {
                return this.EmployeeId_StartField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeId_StartField, value) != true)) {
                    this.EmployeeId_StartField = value;
                    this.RaisePropertyChanged("EmployeeId_Start");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlateNumber {
            get {
                return this.PlateNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PlateNumberField, value) != true)) {
                    this.PlateNumberField = value;
                    this.RaisePropertyChanged("PlateNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] VehicleType {
            get {
                return this.VehicleTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.VehicleTypeField, value) != true)) {
                    this.VehicleTypeField = value;
                    this.RaisePropertyChanged("VehicleType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiResultOfArrayOfHPXPlateDtoMTRdQN6P", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class ApiResultOfArrayOfHPXPlateDtoMTRdQN6P : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JBHR.HPX_WebService.HPXPlateDto[] ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JBHR.HPX_WebService.HPXPlateDto[] Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiResultOfstring", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class ApiResultOfstring : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetHPXPointEntryDto", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class GetHPXPointEntryDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActivityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeId_EndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeId_StartField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActivityName {
            get {
                return this.ActivityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ActivityNameField, value) != true)) {
                    this.ActivityNameField = value;
                    this.RaisePropertyChanged("ActivityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeId_End {
            get {
                return this.EmployeeId_EndField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeId_EndField, value) != true)) {
                    this.EmployeeId_EndField = value;
                    this.RaisePropertyChanged("EmployeeId_End");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeId_Start {
            get {
                return this.EmployeeId_StartField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeId_StartField, value) != true)) {
                    this.EmployeeId_StartField = value;
                    this.RaisePropertyChanged("EmployeeId_Start");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiResultOfArrayOfHPXPointDtoMTRdQN6P", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class ApiResultOfArrayOfHPXPointDtoMTRdQN6P : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JBHR.HPX_WebService.HPXPointDto[] ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JBHR.HPX_WebService.HPXPointDto[] Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HPXPointDto", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class HPXPointDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActivityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BookUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GetPointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastUpdateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastUpdatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonJoinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RelativesCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RemainingPointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UseDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UsePointField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActivityName {
            get {
                return this.ActivityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ActivityNameField, value) != true)) {
                    this.ActivityNameField = value;
                    this.RaisePropertyChanged("ActivityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BookUser {
            get {
                return this.BookUserField;
            }
            set {
                if ((object.ReferenceEquals(this.BookUserField, value) != true)) {
                    this.BookUserField = value;
                    this.RaisePropertyChanged("BookUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeName {
            get {
                return this.EmployeeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeNameField, value) != true)) {
                    this.EmployeeNameField = value;
                    this.RaisePropertyChanged("EmployeeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeNo {
            get {
                return this.EmployeeNoField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeNoField, value) != true)) {
                    this.EmployeeNoField = value;
                    this.RaisePropertyChanged("EmployeeNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GetPoint {
            get {
                return this.GetPointField;
            }
            set {
                if ((this.GetPointField.Equals(value) != true)) {
                    this.GetPointField = value;
                    this.RaisePropertyChanged("GetPoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdateDate {
            get {
                return this.LastUpdateDateField;
            }
            set {
                if ((this.LastUpdateDateField.Equals(value) != true)) {
                    this.LastUpdateDateField = value;
                    this.RaisePropertyChanged("LastUpdateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastUpdatedBy {
            get {
                return this.LastUpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.LastUpdatedByField, value) != true)) {
                    this.LastUpdatedByField = value;
                    this.RaisePropertyChanged("LastUpdatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Leader {
            get {
                return this.LeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.LeaderField, value) != true)) {
                    this.LeaderField = value;
                    this.RaisePropertyChanged("Leader");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonJoin {
            get {
                return this.PersonJoinField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonJoinField, value) != true)) {
                    this.PersonJoinField = value;
                    this.RaisePropertyChanged("PersonJoin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RelativesCount {
            get {
                return this.RelativesCountField;
            }
            set {
                if ((this.RelativesCountField.Equals(value) != true)) {
                    this.RelativesCountField = value;
                    this.RaisePropertyChanged("RelativesCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RemainingPoint {
            get {
                return this.RemainingPointField;
            }
            set {
                if ((this.RemainingPointField.Equals(value) != true)) {
                    this.RemainingPointField = value;
                    this.RaisePropertyChanged("RemainingPoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sno {
            get {
                return this.SnoField;
            }
            set {
                if ((this.SnoField.Equals(value) != true)) {
                    this.SnoField = value;
                    this.RaisePropertyChanged("Sno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UseDate {
            get {
                return this.UseDateField;
            }
            set {
                if ((this.UseDateField.Equals(value) != true)) {
                    this.UseDateField = value;
                    this.RaisePropertyChanged("UseDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UsePoint {
            get {
                return this.UsePointField;
            }
            set {
                if ((this.UsePointField.Equals(value) != true)) {
                    this.UsePointField = value;
                    this.RaisePropertyChanged("UsePoint");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiResultOfHPXPointDtoMTRdQN6P", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class ApiResultOfHPXPointDtoMTRdQN6P : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JBHR.HPX_WebService.HPXPointDto ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JBHR.HPX_WebService.HPXPointDto Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiResultOfint", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class ApiResultOfint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://jbjob.com.tw/Flow", ConfigurationName="HPX_WebService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/GetData", ReplyAction="http://jbjob.com.tw/Flow/IService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/GetHPXPlateVehicleType", ReplyAction="http://jbjob.com.tw/Flow/IService/GetHPXPlateVehicleTypeResponse")]
        JBHR.HPX_WebService.ApiResultOfArrayOfMtcodeDtoMTRdQN6P GetHPXPlateVehicleType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/GetHPXPlateVehicleTypeByCode", ReplyAction="http://jbjob.com.tw/Flow/IService/GetHPXPlateVehicleTypeByCodeResponse")]
        JBHR.HPX_WebService.ApiResultOfMtcodeDtoMTRdQN6P GetHPXPlateVehicleTypeByCode(string Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/GetHPXPlateBySno", ReplyAction="http://jbjob.com.tw/Flow/IService/GetHPXPlateBySnoResponse")]
        JBHR.HPX_WebService.ApiResultOfHPXPlateDtoMTRdQN6P GetHPXPlateBySno(int Sno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/GetHPXPlate", ReplyAction="http://jbjob.com.tw/Flow/IService/GetHPXPlateResponse")]
        JBHR.HPX_WebService.ApiResultOfArrayOfHPXPlateDtoMTRdQN6P GetHPXPlate(JBHR.HPX_WebService.GetHPXPlateEntryDto getHPXPlateEntryDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/InsertHPXPlate", ReplyAction="http://jbjob.com.tw/Flow/IService/InsertHPXPlateResponse")]
        JBHR.HPX_WebService.ApiResultOfstring InsertHPXPlate(JBHR.HPX_WebService.HPXPlateDto hPXPlateDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/UpdateHPXPlate", ReplyAction="http://jbjob.com.tw/Flow/IService/UpdateHPXPlateResponse")]
        JBHR.HPX_WebService.ApiResultOfstring UpdateHPXPlate(JBHR.HPX_WebService.HPXPlateDto hPXPlateDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/DeleteHPXPlate", ReplyAction="http://jbjob.com.tw/Flow/IService/DeleteHPXPlateResponse")]
        JBHR.HPX_WebService.ApiResultOfstring DeleteHPXPlate(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/GetHPXPoint", ReplyAction="http://jbjob.com.tw/Flow/IService/GetHPXPointResponse")]
        JBHR.HPX_WebService.ApiResultOfArrayOfHPXPointDtoMTRdQN6P GetHPXPoint(JBHR.HPX_WebService.GetHPXPointEntryDto getHPXPointEntryDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/GetHPXPointBySno", ReplyAction="http://jbjob.com.tw/Flow/IService/GetHPXPointBySnoResponse")]
        JBHR.HPX_WebService.ApiResultOfHPXPointDtoMTRdQN6P GetHPXPointBySno(int Sno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/CalHPXPoint", ReplyAction="http://jbjob.com.tw/Flow/IService/CalHPXPointResponse")]
        JBHR.HPX_WebService.ApiResultOfint CalHPXPoint(JBHR.HPX_WebService.HPXPointDto hPXPointDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/InsertHPXPoint", ReplyAction="http://jbjob.com.tw/Flow/IService/InsertHPXPointResponse")]
        JBHR.HPX_WebService.ApiResultOfstring InsertHPXPoint(JBHR.HPX_WebService.HPXPointDto hPXPointDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/UpdateHPXPoint", ReplyAction="http://jbjob.com.tw/Flow/IService/UpdateHPXPointResponse")]
        JBHR.HPX_WebService.ApiResultOfstring UpdateHPXPoint(JBHR.HPX_WebService.HPXPointDto hPXPointDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/DeleteHPXPoint", ReplyAction="http://jbjob.com.tw/Flow/IService/DeleteHPXPointResponse")]
        JBHR.HPX_WebService.ApiResultOfstring DeleteHPXPoint(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/GetDataUsingDataContract", ReplyAction="http://jbjob.com.tw/Flow/IService/GetDataUsingDataContractResponse")]
        JBHR.HPX_WebService.CompositeType GetDataUsingDataContract(JBHR.HPX_WebService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/GetFormTreeToList", ReplyAction="http://jbjob.com.tw/Flow/IService/GetFormTreeToListResponse")]
        Bll.Flow.Vdb.FormTreeTable[] GetFormTreeToList(string sNobr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/GetFlowProgressFlow", ReplyAction="http://jbjob.com.tw/Flow/IService/GetFlowProgressFlowResponse")]
        Bll.Flow.Vdb.FlowSignTable[] GetFlowProgressFlow(string sNobr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/GetFlowProgressFlowCount", ReplyAction="http://jbjob.com.tw/Flow/IService/GetFlowProgressFlowCountResponse")]
        int GetFlowProgressFlowCount(string sNobr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/GetFlowProgressFlowAll", ReplyAction="http://jbjob.com.tw/Flow/IService/GetFlowProgressFlowAllResponse")]
        Bll.Flow.Vdb.FlowSignTable[] GetFlowProgressFlowAll(string sNobr, string sAppNobr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/GetFlowProgressFlowComplete", ReplyAction="http://jbjob.com.tw/Flow/IService/GetFlowProgressFlowCompleteResponse")]
        Bll.Flow.Vdb.FlowSignCompleteTable[] GetFlowProgressFlowComplete(string sNobr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/SetProcessApParm", ReplyAction="http://jbjob.com.tw/Flow/IService/SetProcessApParmResponse")]
        bool SetProcessApParm(string sNobr, int iApParmID, int iProcessCheckAuto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/GetFlowSearchIng", ReplyAction="http://jbjob.com.tw/Flow/IService/GetFlowSearchIngResponse")]
        Bll.Flow.Vdb.FlowSearchIngTable[] GetFlowSearchIng(string sNobr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/GetFlowSearchComplete", ReplyAction="http://jbjob.com.tw/Flow/IService/GetFlowSearchCompleteResponse")]
        Bll.Flow.Vdb.FlowSearchCompleteTable[] GetFlowSearchComplete(string sNobr, System.DateTime dAppB, System.DateTime dAppE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/GetRoles", ReplyAction="http://jbjob.com.tw/Flow/IService/GetRolesResponse")]
        Bll.Flow.Vdb.RolesTable[] GetRoles(string sNobr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/GetAgent", ReplyAction="http://jbjob.com.tw/Flow/IService/GetAgentResponse")]
        Bll.Flow.Vdb.CheckAgentDefaultTable[] GetAgent(string sNobr, string sRole);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/SetAgent", ReplyAction="http://jbjob.com.tw/Flow/IService/SetAgentResponse")]
        bool SetAgent(string sNobr, string sRole, string sAgentNobr1, string sAgentNobr2, string sAgentNobr3, System.DateTime dDateB, System.DateTime dDateE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/GetFlowAbs", ReplyAction="http://jbjob.com.tw/Flow/IService/GetFlowAbsResponse")]
        Bll.Flow.Vdb.FlowAbsTable[] GetFlowAbs(System.DateTime dDateB, System.DateTime dDateE, string sCat, string[] lsDept, string[] lsNobr, string[] lsState);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/GetFlowAbs1", ReplyAction="http://jbjob.com.tw/Flow/IService/GetFlowAbs1Response")]
        Bll.Flow.Vdb.FlowAbsTable[] GetFlowAbs1(System.DateTime dDateB, System.DateTime dDateE, string sHcode, string sCat, string[] lsDept, string[] lsNobr, string[] lsState);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/GetFlowOt", ReplyAction="http://jbjob.com.tw/Flow/IService/GetFlowOtResponse")]
        Bll.Flow.Vdb.FlowOtTable[] GetFlowOt(System.DateTime dDateB, System.DateTime dDateE, string[] lsDept, string[] lsNobr, string[] lsState);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/GetFlowOt1", ReplyAction="http://jbjob.com.tw/Flow/IService/GetFlowOt1Response")]
        Bll.Flow.Vdb.FlowOtTable[] GetFlowOt1(System.DateTime dDateB, System.DateTime dDateE, string[] lsDept, string[] lsNobr, string[] lsState, string sOtType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/WorkFinish", ReplyAction="http://jbjob.com.tw/Flow/IService/WorkFinishResponse")]
        int[] WorkFinish(int[] lsApParm, string sSignNobr, string sNote, bool bSign);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/SetCancelForm", ReplyAction="http://jbjob.com.tw/Flow/IService/SetCancelFormResponse")]
        int[] SetCancelForm(Bll.Flow.Vdb.FormCategroy FormName, int[] lsProcessID, bool bCancel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/SetResetForm", ReplyAction="http://jbjob.com.tw/Flow/IService/SetResetFormResponse")]
        int[] SetResetForm(Bll.Flow.Vdb.FormCategroy FormName, int[] lsProcessID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/SetCancelFormByHr", ReplyAction="http://jbjob.com.tw/Flow/IService/SetCancelFormByHrResponse")]
        int[] SetCancelFormByHr(Bll.Flow.Vdb.FormCategroy FormName, string sNobr, System.DateTime dDateB, string sTimeB, string sType, bool bCancel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/SetCancelProcess", ReplyAction="http://jbjob.com.tw/Flow/IService/SetCancelProcessResponse")]
        int[] SetCancelProcess(int[] lsProcessID, bool bCancel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/GetHocde", ReplyAction="http://jbjob.com.tw/Flow/IService/GetHocdeResponse")]
        Bll.Att.Vdb.HcodeTable[] GetHocde(string sCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/GetYearAbsenceDetail", ReplyAction="http://jbjob.com.tw/Flow/IService/GetYearAbsenceDetailResponse")]
        JBModule.Data.Repo.SpecialLeaveOfYear[] GetYearAbsenceDetail(string[] EmployeeList, System.DateTime DateBegin, System.DateTime DateEnd, System.DateTime DDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/GetBasettsByDate", ReplyAction="http://jbjob.com.tw/Flow/IService/GetBasettsByDateResponse")]
        JBModule.Data.Linq.BASETTS GetBasettsByDate(string Nobr, System.DateTime Date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/AddBasetts", ReplyAction="http://jbjob.com.tw/Flow/IService/AddBasettsResponse")]
        bool AddBasetts(JBModule.Data.Linq.BASETTS basettsSet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/GetAbsEntitleByTakenGuid", ReplyAction="http://jbjob.com.tw/Flow/IService/GetAbsEntitleByTakenGuidResponse")]
        JBModule.Data.Dto.AbsenceDetail[] GetAbsEntitleByTakenGuid(string TakenGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/GetAbsTakenByEntitleGuid", ReplyAction="http://jbjob.com.tw/Flow/IService/GetAbsTakenByEntitleGuidResponse")]
        JBModule.Data.Dto.AbsenceDto[] GetAbsTakenByEntitleGuid(string EntitleGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/GetAbsTakenByByEmployeeIdList", ReplyAction="http://jbjob.com.tw/Flow/IService/GetAbsTakenByByEmployeeIdListResponse")]
        JBModule.Data.Dto.AbsenceDto[] GetAbsTakenByByEmployeeIdList(System.DateTime DateBegin, System.DateTime DateEnd, bool WithFlowData, string[] EmployeeIdList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/GetAbsEntitleByEmployeeIdList", ReplyAction="http://jbjob.com.tw/Flow/IService/GetAbsEntitleByEmployeeIdListResponse")]
        JBModule.Data.Dto.AbsenceDetail[] GetAbsEntitleByEmployeeIdList(System.DateTime DateBegin, System.DateTime DateEnd, bool WithFlowData, string[] EmployeeIdList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/GetAbsTakenByByEmployeeIdListHcodeType", ReplyAction="http://jbjob.com.tw/Flow/IService/GetAbsTakenByByEmployeeIdListHcodeTypeResponse")]
        JBModule.Data.Dto.AbsenceDto[] GetAbsTakenByByEmployeeIdListHcodeType(System.DateTime DateBegin, System.DateTime DateEnd, bool WithFlowData, string[] EmployeeIdList, string[] HtypeList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/GetAbsEntitleByEmployeeIdListHcodeType", ReplyAction="http://jbjob.com.tw/Flow/IService/GetAbsEntitleByEmployeeIdListHcodeTypeResponse")]
        JBModule.Data.Dto.AbsenceDetail[] GetAbsEntitleByEmployeeIdListHcodeType(System.DateTime DateBegin, System.DateTime DateEnd, bool WithFlowData, string[] EmployeeIdList, string[] HtypeList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jbjob.com.tw/Flow/IService/GetHoliType", ReplyAction="http://jbjob.com.tw/Flow/IService/GetHoliTypeResponse")]
        System.Collections.Generic.Dictionary<string, string> GetHoliType();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : JBHR.HPX_WebService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<JBHR.HPX_WebService.IService>, JBHR.HPX_WebService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public JBHR.HPX_WebService.ApiResultOfArrayOfMtcodeDtoMTRdQN6P GetHPXPlateVehicleType() {
            return base.Channel.GetHPXPlateVehicleType();
        }
        
        public JBHR.HPX_WebService.ApiResultOfMtcodeDtoMTRdQN6P GetHPXPlateVehicleTypeByCode(string Code) {
            return base.Channel.GetHPXPlateVehicleTypeByCode(Code);
        }
        
        public JBHR.HPX_WebService.ApiResultOfHPXPlateDtoMTRdQN6P GetHPXPlateBySno(int Sno) {
            return base.Channel.GetHPXPlateBySno(Sno);
        }
        
        public JBHR.HPX_WebService.ApiResultOfArrayOfHPXPlateDtoMTRdQN6P GetHPXPlate(JBHR.HPX_WebService.GetHPXPlateEntryDto getHPXPlateEntryDto) {
            return base.Channel.GetHPXPlate(getHPXPlateEntryDto);
        }
        
        public JBHR.HPX_WebService.ApiResultOfstring InsertHPXPlate(JBHR.HPX_WebService.HPXPlateDto hPXPlateDto) {
            return base.Channel.InsertHPXPlate(hPXPlateDto);
        }
        
        public JBHR.HPX_WebService.ApiResultOfstring UpdateHPXPlate(JBHR.HPX_WebService.HPXPlateDto hPXPlateDto) {
            return base.Channel.UpdateHPXPlate(hPXPlateDto);
        }
        
        public JBHR.HPX_WebService.ApiResultOfstring DeleteHPXPlate(int id) {
            return base.Channel.DeleteHPXPlate(id);
        }
        
        public JBHR.HPX_WebService.ApiResultOfArrayOfHPXPointDtoMTRdQN6P GetHPXPoint(JBHR.HPX_WebService.GetHPXPointEntryDto getHPXPointEntryDto) {
            return base.Channel.GetHPXPoint(getHPXPointEntryDto);
        }
        
        public JBHR.HPX_WebService.ApiResultOfHPXPointDtoMTRdQN6P GetHPXPointBySno(int Sno) {
            return base.Channel.GetHPXPointBySno(Sno);
        }
        
        public JBHR.HPX_WebService.ApiResultOfint CalHPXPoint(JBHR.HPX_WebService.HPXPointDto hPXPointDto) {
            return base.Channel.CalHPXPoint(hPXPointDto);
        }
        
        public JBHR.HPX_WebService.ApiResultOfstring InsertHPXPoint(JBHR.HPX_WebService.HPXPointDto hPXPointDto) {
            return base.Channel.InsertHPXPoint(hPXPointDto);
        }
        
        public JBHR.HPX_WebService.ApiResultOfstring UpdateHPXPoint(JBHR.HPX_WebService.HPXPointDto hPXPointDto) {
            return base.Channel.UpdateHPXPoint(hPXPointDto);
        }
        
        public JBHR.HPX_WebService.ApiResultOfstring DeleteHPXPoint(int id) {
            return base.Channel.DeleteHPXPoint(id);
        }
        
        public JBHR.HPX_WebService.CompositeType GetDataUsingDataContract(JBHR.HPX_WebService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public Bll.Flow.Vdb.FormTreeTable[] GetFormTreeToList(string sNobr) {
            return base.Channel.GetFormTreeToList(sNobr);
        }
        
        public Bll.Flow.Vdb.FlowSignTable[] GetFlowProgressFlow(string sNobr) {
            return base.Channel.GetFlowProgressFlow(sNobr);
        }
        
        public int GetFlowProgressFlowCount(string sNobr) {
            return base.Channel.GetFlowProgressFlowCount(sNobr);
        }
        
        public Bll.Flow.Vdb.FlowSignTable[] GetFlowProgressFlowAll(string sNobr, string sAppNobr) {
            return base.Channel.GetFlowProgressFlowAll(sNobr, sAppNobr);
        }
        
        public Bll.Flow.Vdb.FlowSignCompleteTable[] GetFlowProgressFlowComplete(string sNobr) {
            return base.Channel.GetFlowProgressFlowComplete(sNobr);
        }
        
        public bool SetProcessApParm(string sNobr, int iApParmID, int iProcessCheckAuto) {
            return base.Channel.SetProcessApParm(sNobr, iApParmID, iProcessCheckAuto);
        }
        
        public Bll.Flow.Vdb.FlowSearchIngTable[] GetFlowSearchIng(string sNobr) {
            return base.Channel.GetFlowSearchIng(sNobr);
        }
        
        public Bll.Flow.Vdb.FlowSearchCompleteTable[] GetFlowSearchComplete(string sNobr, System.DateTime dAppB, System.DateTime dAppE) {
            return base.Channel.GetFlowSearchComplete(sNobr, dAppB, dAppE);
        }
        
        public Bll.Flow.Vdb.RolesTable[] GetRoles(string sNobr) {
            return base.Channel.GetRoles(sNobr);
        }
        
        public Bll.Flow.Vdb.CheckAgentDefaultTable[] GetAgent(string sNobr, string sRole) {
            return base.Channel.GetAgent(sNobr, sRole);
        }
        
        public bool SetAgent(string sNobr, string sRole, string sAgentNobr1, string sAgentNobr2, string sAgentNobr3, System.DateTime dDateB, System.DateTime dDateE) {
            return base.Channel.SetAgent(sNobr, sRole, sAgentNobr1, sAgentNobr2, sAgentNobr3, dDateB, dDateE);
        }
        
        public Bll.Flow.Vdb.FlowAbsTable[] GetFlowAbs(System.DateTime dDateB, System.DateTime dDateE, string sCat, string[] lsDept, string[] lsNobr, string[] lsState) {
            return base.Channel.GetFlowAbs(dDateB, dDateE, sCat, lsDept, lsNobr, lsState);
        }
        
        public Bll.Flow.Vdb.FlowAbsTable[] GetFlowAbs1(System.DateTime dDateB, System.DateTime dDateE, string sHcode, string sCat, string[] lsDept, string[] lsNobr, string[] lsState) {
            return base.Channel.GetFlowAbs1(dDateB, dDateE, sHcode, sCat, lsDept, lsNobr, lsState);
        }
        
        public Bll.Flow.Vdb.FlowOtTable[] GetFlowOt(System.DateTime dDateB, System.DateTime dDateE, string[] lsDept, string[] lsNobr, string[] lsState) {
            return base.Channel.GetFlowOt(dDateB, dDateE, lsDept, lsNobr, lsState);
        }
        
        public Bll.Flow.Vdb.FlowOtTable[] GetFlowOt1(System.DateTime dDateB, System.DateTime dDateE, string[] lsDept, string[] lsNobr, string[] lsState, string sOtType) {
            return base.Channel.GetFlowOt1(dDateB, dDateE, lsDept, lsNobr, lsState, sOtType);
        }
        
        public int[] WorkFinish(int[] lsApParm, string sSignNobr, string sNote, bool bSign) {
            return base.Channel.WorkFinish(lsApParm, sSignNobr, sNote, bSign);
        }
        
        public int[] SetCancelForm(Bll.Flow.Vdb.FormCategroy FormName, int[] lsProcessID, bool bCancel) {
            return base.Channel.SetCancelForm(FormName, lsProcessID, bCancel);
        }
        
        public int[] SetResetForm(Bll.Flow.Vdb.FormCategroy FormName, int[] lsProcessID) {
            return base.Channel.SetResetForm(FormName, lsProcessID);
        }
        
        public int[] SetCancelFormByHr(Bll.Flow.Vdb.FormCategroy FormName, string sNobr, System.DateTime dDateB, string sTimeB, string sType, bool bCancel) {
            return base.Channel.SetCancelFormByHr(FormName, sNobr, dDateB, sTimeB, sType, bCancel);
        }
        
        public int[] SetCancelProcess(int[] lsProcessID, bool bCancel) {
            return base.Channel.SetCancelProcess(lsProcessID, bCancel);
        }
        
        public Bll.Att.Vdb.HcodeTable[] GetHocde(string sCode) {
            return base.Channel.GetHocde(sCode);
        }
        
        public JBModule.Data.Repo.SpecialLeaveOfYear[] GetYearAbsenceDetail(string[] EmployeeList, System.DateTime DateBegin, System.DateTime DateEnd, System.DateTime DDate) {
            return base.Channel.GetYearAbsenceDetail(EmployeeList, DateBegin, DateEnd, DDate);
        }
        
        public JBModule.Data.Linq.BASETTS GetBasettsByDate(string Nobr, System.DateTime Date) {
            return base.Channel.GetBasettsByDate(Nobr, Date);
        }
        
        public bool AddBasetts(JBModule.Data.Linq.BASETTS basettsSet) {
            return base.Channel.AddBasetts(basettsSet);
        }
        
        public JBModule.Data.Dto.AbsenceDetail[] GetAbsEntitleByTakenGuid(string TakenGuid) {
            return base.Channel.GetAbsEntitleByTakenGuid(TakenGuid);
        }
        
        public JBModule.Data.Dto.AbsenceDto[] GetAbsTakenByEntitleGuid(string EntitleGuid) {
            return base.Channel.GetAbsTakenByEntitleGuid(EntitleGuid);
        }
        
        public JBModule.Data.Dto.AbsenceDto[] GetAbsTakenByByEmployeeIdList(System.DateTime DateBegin, System.DateTime DateEnd, bool WithFlowData, string[] EmployeeIdList) {
            return base.Channel.GetAbsTakenByByEmployeeIdList(DateBegin, DateEnd, WithFlowData, EmployeeIdList);
        }
        
        public JBModule.Data.Dto.AbsenceDetail[] GetAbsEntitleByEmployeeIdList(System.DateTime DateBegin, System.DateTime DateEnd, bool WithFlowData, string[] EmployeeIdList) {
            return base.Channel.GetAbsEntitleByEmployeeIdList(DateBegin, DateEnd, WithFlowData, EmployeeIdList);
        }
        
        public JBModule.Data.Dto.AbsenceDto[] GetAbsTakenByByEmployeeIdListHcodeType(System.DateTime DateBegin, System.DateTime DateEnd, bool WithFlowData, string[] EmployeeIdList, string[] HtypeList) {
            return base.Channel.GetAbsTakenByByEmployeeIdListHcodeType(DateBegin, DateEnd, WithFlowData, EmployeeIdList, HtypeList);
        }
        
        public JBModule.Data.Dto.AbsenceDetail[] GetAbsEntitleByEmployeeIdListHcodeType(System.DateTime DateBegin, System.DateTime DateEnd, bool WithFlowData, string[] EmployeeIdList, string[] HtypeList) {
            return base.Channel.GetAbsEntitleByEmployeeIdListHcodeType(DateBegin, DateEnd, WithFlowData, EmployeeIdList, HtypeList);
        }
        
        public System.Collections.Generic.Dictionary<string, string> GetHoliType() {
            return base.Channel.GetHoliType();
        }
    }
}
