#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JBModule.Message
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SUNLITHR")]
	public partial class DBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 擴充性方法定義
    partial void OnCreated();
    partial void InsertSYSLOG(SYSLOG instance);
    partial void UpdateSYSLOG(SYSLOG instance);
    partial void DeleteSYSLOG(SYSLOG instance);
    partial void InsertMAILQUEUE(MAILQUEUE instance);
    partial void UpdateMAILQUEUE(MAILQUEUE instance);
    partial void DeleteMAILQUEUE(MAILQUEUE instance);
    partial void InsertPARAMETER(PARAMETER instance);
    partial void UpdatePARAMETER(PARAMETER instance);
    partial void DeletePARAMETER(PARAMETER instance);
    partial void InsertPARAMETER_TREE(PARAMETER_TREE instance);
    partial void UpdatePARAMETER_TREE(PARAMETER_TREE instance);
    partial void DeletePARAMETER_TREE(PARAMETER_TREE instance);
    partial void InsertHR_File(HR_File instance);
    partial void UpdateHR_File(HR_File instance);
    partial void DeleteHR_File(HR_File instance);
    partial void InsertFileStreamInfo(FileStreamInfo instance);
    partial void UpdateFileStreamInfo(FileStreamInfo instance);
    partial void DeleteFileStreamInfo(FileStreamInfo instance);
    partial void InsertNotifyClass(NotifyClass instance);
    partial void UpdateNotifyClass(NotifyClass instance);
    partial void DeleteNotifyClass(NotifyClass instance);
    partial void InsertBASE(BASE instance);
    partial void UpdateBASE(BASE instance);
    partial void DeleteBASE(BASE instance);
    partial void InsertBASETTS(BASETTS instance);
    partial void UpdateBASETTS(BASETTS instance);
    partial void DeleteBASETTS(BASETTS instance);
    partial void InsertDEPT(DEPT instance);
    partial void UpdateDEPT(DEPT instance);
    partial void DeleteDEPT(DEPT instance);
    partial void InsertU_USER(U_USER instance);
    partial void UpdateU_USER(U_USER instance);
    partial void DeleteU_USER(U_USER instance);
    partial void InsertNotifyTemplate(NotifyTemplate instance);
    partial void UpdateNotifyTemplate(NotifyTemplate instance);
    partial void DeleteNotifyTemplate(NotifyTemplate instance);
    partial void InsertU_USERCOMP(U_USERCOMP instance);
    partial void UpdateU_USERCOMP(U_USERCOMP instance);
    partial void DeleteU_USERCOMP(U_USERCOMP instance);
    #endregion
		
		public DBDataContext() : 
				base(global::JBModule.Message.Properties.Settings.Default.MailConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SYSLOG> SYSLOG
		{
			get
			{
				return this.GetTable<SYSLOG>();
			}
		}
		
		public System.Data.Linq.Table<MAILQUEUE> MAILQUEUE
		{
			get
			{
				return this.GetTable<MAILQUEUE>();
			}
		}
		
		public System.Data.Linq.Table<PARAMETER> PARAMETER
		{
			get
			{
				return this.GetTable<PARAMETER>();
			}
		}
		
		public System.Data.Linq.Table<PARAMETER_TREE> PARAMETER_TREE
		{
			get
			{
				return this.GetTable<PARAMETER_TREE>();
			}
		}
		
		public System.Data.Linq.Table<HR_File> HR_File
		{
			get
			{
				return this.GetTable<HR_File>();
			}
		}
		
		public System.Data.Linq.Table<FileStreamInfo> FileStreamInfo
		{
			get
			{
				return this.GetTable<FileStreamInfo>();
			}
		}
		
		public System.Data.Linq.Table<NotifyClass> NotifyClass
		{
			get
			{
				return this.GetTable<NotifyClass>();
			}
		}
		
		public System.Data.Linq.Table<BASE> BASE
		{
			get
			{
				return this.GetTable<BASE>();
			}
		}
		
		public System.Data.Linq.Table<BASETTS> BASETTS
		{
			get
			{
				return this.GetTable<BASETTS>();
			}
		}
		
		public System.Data.Linq.Table<DEPT> DEPT
		{
			get
			{
				return this.GetTable<DEPT>();
			}
		}
		
		public System.Data.Linq.Table<U_USER> U_USER
		{
			get
			{
				return this.GetTable<U_USER>();
			}
		}
		
		public System.Data.Linq.Table<NotifyTemplate> NotifyTemplate
		{
			get
			{
				return this.GetTable<NotifyTemplate>();
			}
		}
		
		public System.Data.Linq.Table<U_USERCOMP> U_USERCOMP
		{
			get
			{
				return this.GetTable<U_USERCOMP>();
			}
		}
		
		public System.Data.Linq.Table<NotifyClassTemp> NotifyClassTemp
		{
			get
			{
				return this.GetTable<NotifyClassTemp>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SYSLOG")]
	public partial class SYSLOG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _TYPE;
		
		private string _SOURCE;
		
		private System.Nullable<int> _SID;
		
		private string _GUID;
		
		private string _TITLE;
		
		private string _NOTE;
		
		private string _NOTE1;
		
		private string _NOTE2;
		
		private string _NOTE3;
		
		private string _NOTE4;
		
		private string _NOTE5;
		
		private System.DateTime _KEY_DATE;
		
		private string _KEY_MAN;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTYPEChanging(string value);
    partial void OnTYPEChanged();
    partial void OnSOURCEChanging(string value);
    partial void OnSOURCEChanged();
    partial void OnSIDChanging(System.Nullable<int> value);
    partial void OnSIDChanged();
    partial void OnGUIDChanging(string value);
    partial void OnGUIDChanged();
    partial void OnTITLEChanging(string value);
    partial void OnTITLEChanged();
    partial void OnNOTEChanging(string value);
    partial void OnNOTEChanged();
    partial void OnNOTE1Changing(string value);
    partial void OnNOTE1Changed();
    partial void OnNOTE2Changing(string value);
    partial void OnNOTE2Changed();
    partial void OnNOTE3Changing(string value);
    partial void OnNOTE3Changed();
    partial void OnNOTE4Changing(string value);
    partial void OnNOTE4Changed();
    partial void OnNOTE5Changing(string value);
    partial void OnNOTE5Changed();
    partial void OnKEY_DATEChanging(System.DateTime value);
    partial void OnKEY_DATEChanged();
    partial void OnKEY_MANChanging(string value);
    partial void OnKEY_MANChanged();
    #endregion
		
		public SYSLOG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this.OnTYPEChanging(value);
					this.SendPropertyChanging();
					this._TYPE = value;
					this.SendPropertyChanged("TYPE");
					this.OnTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOURCE", DbType="NVarChar(50) NOT NULL")]
		public string SOURCE
		{
			get
			{
				return this._SOURCE;
			}
			set
			{
				if ((this._SOURCE != value))
				{
					this.OnSOURCEChanging(value);
					this.SendPropertyChanging();
					this._SOURCE = value;
					this.SendPropertyChanged("SOURCE");
					this.OnSOURCEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SID", DbType="Int")]
		public System.Nullable<int> SID
		{
			get
			{
				return this._SID;
			}
			set
			{
				if ((this._SID != value))
				{
					this.OnSIDChanging(value);
					this.SendPropertyChanging();
					this._SID = value;
					this.SendPropertyChanged("SID");
					this.OnSIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID", DbType="NVarChar(50)")]
		public string GUID
		{
			get
			{
				return this._GUID;
			}
			set
			{
				if ((this._GUID != value))
				{
					this.OnGUIDChanging(value);
					this.SendPropertyChanging();
					this._GUID = value;
					this.SendPropertyChanged("GUID");
					this.OnGUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TITLE", DbType="NVarChar(500) NOT NULL")]
		public string TITLE
		{
			get
			{
				return this._TITLE;
			}
			set
			{
				if ((this._TITLE != value))
				{
					this.OnTITLEChanging(value);
					this.SendPropertyChanging();
					this._TITLE = value;
					this.SendPropertyChanged("TITLE");
					this.OnTITLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE", DbType="NVarChar(MAX)")]
		public string NOTE
		{
			get
			{
				return this._NOTE;
			}
			set
			{
				if ((this._NOTE != value))
				{
					this.OnNOTEChanging(value);
					this.SendPropertyChanging();
					this._NOTE = value;
					this.SendPropertyChanged("NOTE");
					this.OnNOTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE1", DbType="NVarChar(500)")]
		public string NOTE1
		{
			get
			{
				return this._NOTE1;
			}
			set
			{
				if ((this._NOTE1 != value))
				{
					this.OnNOTE1Changing(value);
					this.SendPropertyChanging();
					this._NOTE1 = value;
					this.SendPropertyChanged("NOTE1");
					this.OnNOTE1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE2", DbType="NVarChar(50)")]
		public string NOTE2
		{
			get
			{
				return this._NOTE2;
			}
			set
			{
				if ((this._NOTE2 != value))
				{
					this.OnNOTE2Changing(value);
					this.SendPropertyChanging();
					this._NOTE2 = value;
					this.SendPropertyChanged("NOTE2");
					this.OnNOTE2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE3", DbType="NVarChar(50)")]
		public string NOTE3
		{
			get
			{
				return this._NOTE3;
			}
			set
			{
				if ((this._NOTE3 != value))
				{
					this.OnNOTE3Changing(value);
					this.SendPropertyChanging();
					this._NOTE3 = value;
					this.SendPropertyChanged("NOTE3");
					this.OnNOTE3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE4", DbType="NVarChar(50)")]
		public string NOTE4
		{
			get
			{
				return this._NOTE4;
			}
			set
			{
				if ((this._NOTE4 != value))
				{
					this.OnNOTE4Changing(value);
					this.SendPropertyChanging();
					this._NOTE4 = value;
					this.SendPropertyChanged("NOTE4");
					this.OnNOTE4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE5", DbType="NVarChar(50)")]
		public string NOTE5
		{
			get
			{
				return this._NOTE5;
			}
			set
			{
				if ((this._NOTE5 != value))
				{
					this.OnNOTE5Changing(value);
					this.SendPropertyChanging();
					this._NOTE5 = value;
					this.SendPropertyChanged("NOTE5");
					this.OnNOTE5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEY_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime KEY_DATE
		{
			get
			{
				return this._KEY_DATE;
			}
			set
			{
				if ((this._KEY_DATE != value))
				{
					this.OnKEY_DATEChanging(value);
					this.SendPropertyChanging();
					this._KEY_DATE = value;
					this.SendPropertyChanged("KEY_DATE");
					this.OnKEY_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEY_MAN", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string KEY_MAN
		{
			get
			{
				return this._KEY_MAN;
			}
			set
			{
				if ((this._KEY_MAN != value))
				{
					this.OnKEY_MANChanging(value);
					this.SendPropertyChanging();
					this._KEY_MAN = value;
					this.SendPropertyChanged("KEY_MAN");
					this.OnKEY_MANChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MAILQUEUE")]
	public partial class MAILQUEUE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _GUID;
		
		private string _FROM_ADDR;
		
		private string _FROM_NAME;
		
		private string _TO_ADDR;
		
		private string _TO_NAME;
		
		private string _SUBJECT;
		
		private string _BODY;
		
		private int _RETRY;
		
		private bool _SUCCESS;
		
		private bool _SUSPEND;
		
		private System.DateTime _FREEZE_TIME;
		
		private System.DateTime _KEY_DATE;
		
		private string _KEY_MAN;
		
		private string _NOTE;
		
		private string _NOTE1;
		
		private string _NOTE2;
		
		private string _NOTE3;
		
		private string _NOTE4;
		
		private string _NOTE5;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnGUIDChanging(string value);
    partial void OnGUIDChanged();
    partial void OnFROM_ADDRChanging(string value);
    partial void OnFROM_ADDRChanged();
    partial void OnFROM_NAMEChanging(string value);
    partial void OnFROM_NAMEChanged();
    partial void OnTO_ADDRChanging(string value);
    partial void OnTO_ADDRChanged();
    partial void OnTO_NAMEChanging(string value);
    partial void OnTO_NAMEChanged();
    partial void OnSUBJECTChanging(string value);
    partial void OnSUBJECTChanged();
    partial void OnBODYChanging(string value);
    partial void OnBODYChanged();
    partial void OnRETRYChanging(int value);
    partial void OnRETRYChanged();
    partial void OnSUCCESSChanging(bool value);
    partial void OnSUCCESSChanged();
    partial void OnSUSPENDChanging(bool value);
    partial void OnSUSPENDChanged();
    partial void OnFREEZE_TIMEChanging(System.DateTime value);
    partial void OnFREEZE_TIMEChanged();
    partial void OnKEY_DATEChanging(System.DateTime value);
    partial void OnKEY_DATEChanged();
    partial void OnKEY_MANChanging(string value);
    partial void OnKEY_MANChanged();
    partial void OnNOTEChanging(string value);
    partial void OnNOTEChanged();
    partial void OnNOTE1Changing(string value);
    partial void OnNOTE1Changed();
    partial void OnNOTE2Changing(string value);
    partial void OnNOTE2Changed();
    partial void OnNOTE3Changing(string value);
    partial void OnNOTE3Changed();
    partial void OnNOTE4Changing(string value);
    partial void OnNOTE4Changed();
    partial void OnNOTE5Changing(string value);
    partial void OnNOTE5Changed();
    #endregion
		
		public MAILQUEUE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string GUID
		{
			get
			{
				return this._GUID;
			}
			set
			{
				if ((this._GUID != value))
				{
					this.OnGUIDChanging(value);
					this.SendPropertyChanging();
					this._GUID = value;
					this.SendPropertyChanged("GUID");
					this.OnGUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FROM_ADDR", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FROM_ADDR
		{
			get
			{
				return this._FROM_ADDR;
			}
			set
			{
				if ((this._FROM_ADDR != value))
				{
					this.OnFROM_ADDRChanging(value);
					this.SendPropertyChanging();
					this._FROM_ADDR = value;
					this.SendPropertyChanged("FROM_ADDR");
					this.OnFROM_ADDRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FROM_NAME", DbType="NVarChar(50)")]
		public string FROM_NAME
		{
			get
			{
				return this._FROM_NAME;
			}
			set
			{
				if ((this._FROM_NAME != value))
				{
					this.OnFROM_NAMEChanging(value);
					this.SendPropertyChanging();
					this._FROM_NAME = value;
					this.SendPropertyChanged("FROM_NAME");
					this.OnFROM_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TO_ADDR", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TO_ADDR
		{
			get
			{
				return this._TO_ADDR;
			}
			set
			{
				if ((this._TO_ADDR != value))
				{
					this.OnTO_ADDRChanging(value);
					this.SendPropertyChanging();
					this._TO_ADDR = value;
					this.SendPropertyChanged("TO_ADDR");
					this.OnTO_ADDRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TO_NAME", DbType="NVarChar(50)")]
		public string TO_NAME
		{
			get
			{
				return this._TO_NAME;
			}
			set
			{
				if ((this._TO_NAME != value))
				{
					this.OnTO_NAMEChanging(value);
					this.SendPropertyChanging();
					this._TO_NAME = value;
					this.SendPropertyChanged("TO_NAME");
					this.OnTO_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBJECT", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string SUBJECT
		{
			get
			{
				return this._SUBJECT;
			}
			set
			{
				if ((this._SUBJECT != value))
				{
					this.OnSUBJECTChanging(value);
					this.SendPropertyChanging();
					this._SUBJECT = value;
					this.SendPropertyChanged("SUBJECT");
					this.OnSUBJECTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BODY", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string BODY
		{
			get
			{
				return this._BODY;
			}
			set
			{
				if ((this._BODY != value))
				{
					this.OnBODYChanging(value);
					this.SendPropertyChanging();
					this._BODY = value;
					this.SendPropertyChanged("BODY");
					this.OnBODYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RETRY", DbType="Int NOT NULL")]
		public int RETRY
		{
			get
			{
				return this._RETRY;
			}
			set
			{
				if ((this._RETRY != value))
				{
					this.OnRETRYChanging(value);
					this.SendPropertyChanging();
					this._RETRY = value;
					this.SendPropertyChanged("RETRY");
					this.OnRETRYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUCCESS", DbType="Bit NOT NULL")]
		public bool SUCCESS
		{
			get
			{
				return this._SUCCESS;
			}
			set
			{
				if ((this._SUCCESS != value))
				{
					this.OnSUCCESSChanging(value);
					this.SendPropertyChanging();
					this._SUCCESS = value;
					this.SendPropertyChanged("SUCCESS");
					this.OnSUCCESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUSPEND", DbType="Bit NOT NULL")]
		public bool SUSPEND
		{
			get
			{
				return this._SUSPEND;
			}
			set
			{
				if ((this._SUSPEND != value))
				{
					this.OnSUSPENDChanging(value);
					this.SendPropertyChanging();
					this._SUSPEND = value;
					this.SendPropertyChanged("SUSPEND");
					this.OnSUSPENDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FREEZE_TIME", DbType="DateTime NOT NULL")]
		public System.DateTime FREEZE_TIME
		{
			get
			{
				return this._FREEZE_TIME;
			}
			set
			{
				if ((this._FREEZE_TIME != value))
				{
					this.OnFREEZE_TIMEChanging(value);
					this.SendPropertyChanging();
					this._FREEZE_TIME = value;
					this.SendPropertyChanged("FREEZE_TIME");
					this.OnFREEZE_TIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEY_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime KEY_DATE
		{
			get
			{
				return this._KEY_DATE;
			}
			set
			{
				if ((this._KEY_DATE != value))
				{
					this.OnKEY_DATEChanging(value);
					this.SendPropertyChanging();
					this._KEY_DATE = value;
					this.SendPropertyChanged("KEY_DATE");
					this.OnKEY_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEY_MAN", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string KEY_MAN
		{
			get
			{
				return this._KEY_MAN;
			}
			set
			{
				if ((this._KEY_MAN != value))
				{
					this.OnKEY_MANChanging(value);
					this.SendPropertyChanging();
					this._KEY_MAN = value;
					this.SendPropertyChanged("KEY_MAN");
					this.OnKEY_MANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE", DbType="NVarChar(50)")]
		public string NOTE
		{
			get
			{
				return this._NOTE;
			}
			set
			{
				if ((this._NOTE != value))
				{
					this.OnNOTEChanging(value);
					this.SendPropertyChanging();
					this._NOTE = value;
					this.SendPropertyChanged("NOTE");
					this.OnNOTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE1", DbType="NVarChar(50)")]
		public string NOTE1
		{
			get
			{
				return this._NOTE1;
			}
			set
			{
				if ((this._NOTE1 != value))
				{
					this.OnNOTE1Changing(value);
					this.SendPropertyChanging();
					this._NOTE1 = value;
					this.SendPropertyChanged("NOTE1");
					this.OnNOTE1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE2", DbType="NVarChar(50)")]
		public string NOTE2
		{
			get
			{
				return this._NOTE2;
			}
			set
			{
				if ((this._NOTE2 != value))
				{
					this.OnNOTE2Changing(value);
					this.SendPropertyChanging();
					this._NOTE2 = value;
					this.SendPropertyChanged("NOTE2");
					this.OnNOTE2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE3", DbType="NVarChar(50)")]
		public string NOTE3
		{
			get
			{
				return this._NOTE3;
			}
			set
			{
				if ((this._NOTE3 != value))
				{
					this.OnNOTE3Changing(value);
					this.SendPropertyChanging();
					this._NOTE3 = value;
					this.SendPropertyChanged("NOTE3");
					this.OnNOTE3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE4", DbType="NVarChar(50)")]
		public string NOTE4
		{
			get
			{
				return this._NOTE4;
			}
			set
			{
				if ((this._NOTE4 != value))
				{
					this.OnNOTE4Changing(value);
					this.SendPropertyChanging();
					this._NOTE4 = value;
					this.SendPropertyChanged("NOTE4");
					this.OnNOTE4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE5", DbType="NVarChar(50)")]
		public string NOTE5
		{
			get
			{
				return this._NOTE5;
			}
			set
			{
				if ((this._NOTE5 != value))
				{
					this.OnNOTE5Changing(value);
					this.SendPropertyChanging();
					this._NOTE5 = value;
					this.SendPropertyChanged("NOTE5");
					this.OnNOTE5Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PARAMETER")]
	public partial class PARAMETER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AUTO;
		
		private int _PARMGROUP_AUTO;
		
		private string _CODE;
		
		private string _TYPE;
		
		private string _VALUE;
		
		private System.DateTime _KEY_DATE;
		
		private string _KEY_MAN;
		
		private string _NOTE;
		
		private string _NOTE1;
		
		private string _NOTE2;
		
		private string _NOTE3;
		
		private string _NOTE4;
		
		private string _NOTE5;
		
		private bool _DISPLAY;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAUTOChanging(int value);
    partial void OnAUTOChanged();
    partial void OnPARMGROUP_AUTOChanging(int value);
    partial void OnPARMGROUP_AUTOChanged();
    partial void OnCODEChanging(string value);
    partial void OnCODEChanged();
    partial void OnTYPEChanging(string value);
    partial void OnTYPEChanged();
    partial void OnVALUEChanging(string value);
    partial void OnVALUEChanged();
    partial void OnKEY_DATEChanging(System.DateTime value);
    partial void OnKEY_DATEChanged();
    partial void OnKEY_MANChanging(string value);
    partial void OnKEY_MANChanged();
    partial void OnNOTEChanging(string value);
    partial void OnNOTEChanged();
    partial void OnNOTE1Changing(string value);
    partial void OnNOTE1Changed();
    partial void OnNOTE2Changing(string value);
    partial void OnNOTE2Changed();
    partial void OnNOTE3Changing(string value);
    partial void OnNOTE3Changed();
    partial void OnNOTE4Changing(string value);
    partial void OnNOTE4Changed();
    partial void OnNOTE5Changing(string value);
    partial void OnNOTE5Changed();
    partial void OnDISPLAYChanging(bool value);
    partial void OnDISPLAYChanged();
    #endregion
		
		public PARAMETER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AUTO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AUTO
		{
			get
			{
				return this._AUTO;
			}
			set
			{
				if ((this._AUTO != value))
				{
					this.OnAUTOChanging(value);
					this.SendPropertyChanging();
					this._AUTO = value;
					this.SendPropertyChanged("AUTO");
					this.OnAUTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARMGROUP_AUTO", DbType="Int NOT NULL")]
		public int PARMGROUP_AUTO
		{
			get
			{
				return this._PARMGROUP_AUTO;
			}
			set
			{
				if ((this._PARMGROUP_AUTO != value))
				{
					this.OnPARMGROUP_AUTOChanging(value);
					this.SendPropertyChanging();
					this._PARMGROUP_AUTO = value;
					this.SendPropertyChanged("PARMGROUP_AUTO");
					this.OnPARMGROUP_AUTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CODE
		{
			get
			{
				return this._CODE;
			}
			set
			{
				if ((this._CODE != value))
				{
					this.OnCODEChanging(value);
					this.SendPropertyChanging();
					this._CODE = value;
					this.SendPropertyChanged("CODE");
					this.OnCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this.OnTYPEChanging(value);
					this.SendPropertyChanging();
					this._TYPE = value;
					this.SendPropertyChanged("TYPE");
					this.OnTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALUE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string VALUE
		{
			get
			{
				return this._VALUE;
			}
			set
			{
				if ((this._VALUE != value))
				{
					this.OnVALUEChanging(value);
					this.SendPropertyChanging();
					this._VALUE = value;
					this.SendPropertyChanged("VALUE");
					this.OnVALUEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEY_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime KEY_DATE
		{
			get
			{
				return this._KEY_DATE;
			}
			set
			{
				if ((this._KEY_DATE != value))
				{
					this.OnKEY_DATEChanging(value);
					this.SendPropertyChanging();
					this._KEY_DATE = value;
					this.SendPropertyChanged("KEY_DATE");
					this.OnKEY_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEY_MAN", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string KEY_MAN
		{
			get
			{
				return this._KEY_MAN;
			}
			set
			{
				if ((this._KEY_MAN != value))
				{
					this.OnKEY_MANChanging(value);
					this.SendPropertyChanging();
					this._KEY_MAN = value;
					this.SendPropertyChanged("KEY_MAN");
					this.OnKEY_MANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE", DbType="NVarChar(50)")]
		public string NOTE
		{
			get
			{
				return this._NOTE;
			}
			set
			{
				if ((this._NOTE != value))
				{
					this.OnNOTEChanging(value);
					this.SendPropertyChanging();
					this._NOTE = value;
					this.SendPropertyChanged("NOTE");
					this.OnNOTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE1", DbType="NVarChar(50)")]
		public string NOTE1
		{
			get
			{
				return this._NOTE1;
			}
			set
			{
				if ((this._NOTE1 != value))
				{
					this.OnNOTE1Changing(value);
					this.SendPropertyChanging();
					this._NOTE1 = value;
					this.SendPropertyChanged("NOTE1");
					this.OnNOTE1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE2", DbType="NVarChar(50)")]
		public string NOTE2
		{
			get
			{
				return this._NOTE2;
			}
			set
			{
				if ((this._NOTE2 != value))
				{
					this.OnNOTE2Changing(value);
					this.SendPropertyChanging();
					this._NOTE2 = value;
					this.SendPropertyChanged("NOTE2");
					this.OnNOTE2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE3", DbType="NVarChar(50)")]
		public string NOTE3
		{
			get
			{
				return this._NOTE3;
			}
			set
			{
				if ((this._NOTE3 != value))
				{
					this.OnNOTE3Changing(value);
					this.SendPropertyChanging();
					this._NOTE3 = value;
					this.SendPropertyChanged("NOTE3");
					this.OnNOTE3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE4", DbType="NVarChar(50)")]
		public string NOTE4
		{
			get
			{
				return this._NOTE4;
			}
			set
			{
				if ((this._NOTE4 != value))
				{
					this.OnNOTE4Changing(value);
					this.SendPropertyChanging();
					this._NOTE4 = value;
					this.SendPropertyChanged("NOTE4");
					this.OnNOTE4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE5", DbType="NVarChar(50)")]
		public string NOTE5
		{
			get
			{
				return this._NOTE5;
			}
			set
			{
				if ((this._NOTE5 != value))
				{
					this.OnNOTE5Changing(value);
					this.SendPropertyChanging();
					this._NOTE5 = value;
					this.SendPropertyChanged("NOTE5");
					this.OnNOTE5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISPLAY", DbType="Bit NOT NULL")]
		public bool DISPLAY
		{
			get
			{
				return this._DISPLAY;
			}
			set
			{
				if ((this._DISPLAY != value))
				{
					this.OnDISPLAYChanging(value);
					this.SendPropertyChanging();
					this._DISPLAY = value;
					this.SendPropertyChanged("DISPLAY");
					this.OnDISPLAYChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PARAMETER_TREE")]
	public partial class PARAMETER_TREE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AUTO;
		
		private int _PID;
		
		private string _CODE;
		
		private string _NAME;
		
		private bool _DISPLAY;
		
		private int _SORT;
		
		private System.DateTime _KEY_DATE;
		
		private string _KEY_MAN;
		
		private string _NOTE;
		
		private string _NOTE1;
		
		private string _NOTE2;
		
		private string _NOTE3;
		
		private string _NOTE4;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAUTOChanging(int value);
    partial void OnAUTOChanged();
    partial void OnPIDChanging(int value);
    partial void OnPIDChanged();
    partial void OnCODEChanging(string value);
    partial void OnCODEChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnDISPLAYChanging(bool value);
    partial void OnDISPLAYChanged();
    partial void OnSORTChanging(int value);
    partial void OnSORTChanged();
    partial void OnKEY_DATEChanging(System.DateTime value);
    partial void OnKEY_DATEChanged();
    partial void OnKEY_MANChanging(string value);
    partial void OnKEY_MANChanged();
    partial void OnNOTEChanging(string value);
    partial void OnNOTEChanged();
    partial void OnNOTE1Changing(string value);
    partial void OnNOTE1Changed();
    partial void OnNOTE2Changing(string value);
    partial void OnNOTE2Changed();
    partial void OnNOTE3Changing(string value);
    partial void OnNOTE3Changed();
    partial void OnNOTE4Changing(string value);
    partial void OnNOTE4Changed();
    #endregion
		
		public PARAMETER_TREE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AUTO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AUTO
		{
			get
			{
				return this._AUTO;
			}
			set
			{
				if ((this._AUTO != value))
				{
					this.OnAUTOChanging(value);
					this.SendPropertyChanging();
					this._AUTO = value;
					this.SendPropertyChanged("AUTO");
					this.OnAUTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PID", DbType="Int NOT NULL")]
		public int PID
		{
			get
			{
				return this._PID;
			}
			set
			{
				if ((this._PID != value))
				{
					this.OnPIDChanging(value);
					this.SendPropertyChanging();
					this._PID = value;
					this.SendPropertyChanged("PID");
					this.OnPIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CODE
		{
			get
			{
				return this._CODE;
			}
			set
			{
				if ((this._CODE != value))
				{
					this.OnCODEChanging(value);
					this.SendPropertyChanging();
					this._CODE = value;
					this.SendPropertyChanged("CODE");
					this.OnCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISPLAY", DbType="Bit NOT NULL")]
		public bool DISPLAY
		{
			get
			{
				return this._DISPLAY;
			}
			set
			{
				if ((this._DISPLAY != value))
				{
					this.OnDISPLAYChanging(value);
					this.SendPropertyChanging();
					this._DISPLAY = value;
					this.SendPropertyChanged("DISPLAY");
					this.OnDISPLAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SORT", DbType="Int NOT NULL")]
		public int SORT
		{
			get
			{
				return this._SORT;
			}
			set
			{
				if ((this._SORT != value))
				{
					this.OnSORTChanging(value);
					this.SendPropertyChanging();
					this._SORT = value;
					this.SendPropertyChanged("SORT");
					this.OnSORTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEY_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime KEY_DATE
		{
			get
			{
				return this._KEY_DATE;
			}
			set
			{
				if ((this._KEY_DATE != value))
				{
					this.OnKEY_DATEChanging(value);
					this.SendPropertyChanging();
					this._KEY_DATE = value;
					this.SendPropertyChanged("KEY_DATE");
					this.OnKEY_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEY_MAN", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string KEY_MAN
		{
			get
			{
				return this._KEY_MAN;
			}
			set
			{
				if ((this._KEY_MAN != value))
				{
					this.OnKEY_MANChanging(value);
					this.SendPropertyChanging();
					this._KEY_MAN = value;
					this.SendPropertyChanged("KEY_MAN");
					this.OnKEY_MANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE", DbType="NVarChar(50)")]
		public string NOTE
		{
			get
			{
				return this._NOTE;
			}
			set
			{
				if ((this._NOTE != value))
				{
					this.OnNOTEChanging(value);
					this.SendPropertyChanging();
					this._NOTE = value;
					this.SendPropertyChanged("NOTE");
					this.OnNOTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE1", DbType="NVarChar(50)")]
		public string NOTE1
		{
			get
			{
				return this._NOTE1;
			}
			set
			{
				if ((this._NOTE1 != value))
				{
					this.OnNOTE1Changing(value);
					this.SendPropertyChanging();
					this._NOTE1 = value;
					this.SendPropertyChanged("NOTE1");
					this.OnNOTE1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE2", DbType="NVarChar(50)")]
		public string NOTE2
		{
			get
			{
				return this._NOTE2;
			}
			set
			{
				if ((this._NOTE2 != value))
				{
					this.OnNOTE2Changing(value);
					this.SendPropertyChanging();
					this._NOTE2 = value;
					this.SendPropertyChanged("NOTE2");
					this.OnNOTE2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE3", DbType="NVarChar(50)")]
		public string NOTE3
		{
			get
			{
				return this._NOTE3;
			}
			set
			{
				if ((this._NOTE3 != value))
				{
					this.OnNOTE3Changing(value);
					this.SendPropertyChanging();
					this._NOTE3 = value;
					this.SendPropertyChanged("NOTE3");
					this.OnNOTE3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE4", DbType="NVarChar(50)")]
		public string NOTE4
		{
			get
			{
				return this._NOTE4;
			}
			set
			{
				if ((this._NOTE4 != value))
				{
					this.OnNOTE4Changing(value);
					this.SendPropertyChanging();
					this._NOTE4 = value;
					this.SendPropertyChanged("NOTE4");
					this.OnNOTE4Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HR_File")]
	public partial class HR_File : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _GroupID;
		
		private System.Data.Linq.Binary _FileBinary;
		
		private bool _IsStoredInDB;
		
		private string _FileName;
		
		private string _Path;
		
		private string _FileType;
		
		private System.Nullable<int> _FileSize;
		
		private string _FileDesc;
		
		private string _FileNameExt;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private string _CreatedBy;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnGroupIDChanging(string value);
    partial void OnGroupIDChanged();
    partial void OnFileBinaryChanging(System.Data.Linq.Binary value);
    partial void OnFileBinaryChanged();
    partial void OnIsStoredInDBChanging(bool value);
    partial void OnIsStoredInDBChanged();
    partial void OnFileNameChanging(string value);
    partial void OnFileNameChanged();
    partial void OnPathChanging(string value);
    partial void OnPathChanged();
    partial void OnFileTypeChanging(string value);
    partial void OnFileTypeChanged();
    partial void OnFileSizeChanging(System.Nullable<int> value);
    partial void OnFileSizeChanged();
    partial void OnFileDescChanging(string value);
    partial void OnFileDescChanged();
    partial void OnFileNameExtChanging(string value);
    partial void OnFileNameExtChanged();
    partial void OnCreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedDateChanged();
    partial void OnCreatedByChanging(string value);
    partial void OnCreatedByChanged();
    #endregion
		
		public HR_File()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string GroupID
		{
			get
			{
				return this._GroupID;
			}
			set
			{
				if ((this._GroupID != value))
				{
					this.OnGroupIDChanging(value);
					this.SendPropertyChanging();
					this._GroupID = value;
					this.SendPropertyChanged("GroupID");
					this.OnGroupIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileBinary", DbType="VarBinary(MAX)", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary FileBinary
		{
			get
			{
				return this._FileBinary;
			}
			set
			{
				if ((this._FileBinary != value))
				{
					this.OnFileBinaryChanging(value);
					this.SendPropertyChanging();
					this._FileBinary = value;
					this.SendPropertyChanged("FileBinary");
					this.OnFileBinaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsStoredInDB", DbType="Bit NOT NULL")]
		public bool IsStoredInDB
		{
			get
			{
				return this._IsStoredInDB;
			}
			set
			{
				if ((this._IsStoredInDB != value))
				{
					this.OnIsStoredInDBChanging(value);
					this.SendPropertyChanging();
					this._IsStoredInDB = value;
					this.SendPropertyChanged("IsStoredInDB");
					this.OnIsStoredInDBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this.OnFileNameChanging(value);
					this.SendPropertyChanging();
					this._FileName = value;
					this.SendPropertyChanged("FileName");
					this.OnFileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Path", DbType="NVarChar(1000)")]
		public string Path
		{
			get
			{
				return this._Path;
			}
			set
			{
				if ((this._Path != value))
				{
					this.OnPathChanging(value);
					this.SendPropertyChanging();
					this._Path = value;
					this.SendPropertyChanged("Path");
					this.OnPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileType", DbType="NVarChar(200)")]
		public string FileType
		{
			get
			{
				return this._FileType;
			}
			set
			{
				if ((this._FileType != value))
				{
					this.OnFileTypeChanging(value);
					this.SendPropertyChanging();
					this._FileType = value;
					this.SendPropertyChanged("FileType");
					this.OnFileTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileSize", DbType="Int")]
		public System.Nullable<int> FileSize
		{
			get
			{
				return this._FileSize;
			}
			set
			{
				if ((this._FileSize != value))
				{
					this.OnFileSizeChanging(value);
					this.SendPropertyChanging();
					this._FileSize = value;
					this.SendPropertyChanged("FileSize");
					this.OnFileSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileDesc", DbType="NVarChar(500)")]
		public string FileDesc
		{
			get
			{
				return this._FileDesc;
			}
			set
			{
				if ((this._FileDesc != value))
				{
					this.OnFileDescChanging(value);
					this.SendPropertyChanging();
					this._FileDesc = value;
					this.SendPropertyChanged("FileDesc");
					this.OnFileDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileNameExt", DbType="NVarChar(10)")]
		public string FileNameExt
		{
			get
			{
				return this._FileNameExt;
			}
			set
			{
				if ((this._FileNameExt != value))
				{
					this.OnFileNameExtChanging(value);
					this.SendPropertyChanging();
					this._FileNameExt = value;
					this.SendPropertyChanged("FileNameExt");
					this.OnFileNameExtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="NVarChar(50)")]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FileStreamInfo")]
	public partial class FileStreamInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FileID;
		
		private string _FileName;
		
		private string _ExtensionName;
		
		private string _FullName;
		
		private System.Data.Linq.Binary _FileStream;
		
		private long _FileSize;
		
		private string _FileTicket;
		
		private string _CreateMan;
		
		private System.DateTime _CreateTime;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFileIDChanging(int value);
    partial void OnFileIDChanged();
    partial void OnFileNameChanging(string value);
    partial void OnFileNameChanged();
    partial void OnExtensionNameChanging(string value);
    partial void OnExtensionNameChanged();
    partial void OnFullNameChanging(string value);
    partial void OnFullNameChanged();
    partial void OnFileStreamChanging(System.Data.Linq.Binary value);
    partial void OnFileStreamChanged();
    partial void OnFileSizeChanging(long value);
    partial void OnFileSizeChanged();
    partial void OnFileTicketChanging(string value);
    partial void OnFileTicketChanged();
    partial void OnCreateManChanging(string value);
    partial void OnCreateManChanged();
    partial void OnCreateTimeChanging(System.DateTime value);
    partial void OnCreateTimeChanged();
    #endregion
		
		public FileStreamInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int FileID
		{
			get
			{
				return this._FileID;
			}
			set
			{
				if ((this._FileID != value))
				{
					this.OnFileIDChanging(value);
					this.SendPropertyChanging();
					this._FileID = value;
					this.SendPropertyChanged("FileID");
					this.OnFileIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this.OnFileNameChanging(value);
					this.SendPropertyChanging();
					this._FileName = value;
					this.SendPropertyChanged("FileName");
					this.OnFileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtensionName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ExtensionName
		{
			get
			{
				return this._ExtensionName;
			}
			set
			{
				if ((this._ExtensionName != value))
				{
					this.OnExtensionNameChanging(value);
					this.SendPropertyChanging();
					this._ExtensionName = value;
					this.SendPropertyChanged("ExtensionName");
					this.OnExtensionNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this.OnFullNameChanging(value);
					this.SendPropertyChanging();
					this._FullName = value;
					this.SendPropertyChanged("FullName");
					this.OnFullNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileStream", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary FileStream
		{
			get
			{
				return this._FileStream;
			}
			set
			{
				if ((this._FileStream != value))
				{
					this.OnFileStreamChanging(value);
					this.SendPropertyChanging();
					this._FileStream = value;
					this.SendPropertyChanged("FileStream");
					this.OnFileStreamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileSize", DbType="BigInt NOT NULL")]
		public long FileSize
		{
			get
			{
				return this._FileSize;
			}
			set
			{
				if ((this._FileSize != value))
				{
					this.OnFileSizeChanging(value);
					this.SendPropertyChanging();
					this._FileSize = value;
					this.SendPropertyChanged("FileSize");
					this.OnFileSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileTicket", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FileTicket
		{
			get
			{
				return this._FileTicket;
			}
			set
			{
				if ((this._FileTicket != value))
				{
					this.OnFileTicketChanging(value);
					this.SendPropertyChanging();
					this._FileTicket = value;
					this.SendPropertyChanged("FileTicket");
					this.OnFileTicketChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateMan", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CreateMan
		{
			get
			{
				return this._CreateMan;
			}
			set
			{
				if ((this._CreateMan != value))
				{
					this.OnCreateManChanging(value);
					this.SendPropertyChanging();
					this._CreateMan = value;
					this.SendPropertyChanged("CreateMan");
					this.OnCreateManChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateTime", DbType="DateTime NOT NULL")]
		public System.DateTime CreateTime
		{
			get
			{
				return this._CreateTime;
			}
			set
			{
				if ((this._CreateTime != value))
				{
					this.OnCreateTimeChanging(value);
					this.SendPropertyChanging();
					this._CreateTime = value;
					this.SendPropertyChanged("CreateTime");
					this.OnCreateTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NotifyClass")]
	public partial class NotifyClass : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Code;
		
		private string _Comp;
		
		private string _DisplayName;
		
		private string _AssemblyName;
		
		private string _ClassName;
		
		private string _Memo;
		
		private string _Title;
		
		private string _Message;
		
		private string _Status;
		
		private int _Sort;
		
		private System.DateTime _KeyDate;
		
		private string _KeyMan;
		
		private int _NotifyDay;
		
		private string _RelationApp;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnCompChanging(string value);
    partial void OnCompChanged();
    partial void OnDisplayNameChanging(string value);
    partial void OnDisplayNameChanged();
    partial void OnAssemblyNameChanging(string value);
    partial void OnAssemblyNameChanged();
    partial void OnClassNameChanging(string value);
    partial void OnClassNameChanged();
    partial void OnMemoChanging(string value);
    partial void OnMemoChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnMessageChanging(string value);
    partial void OnMessageChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnSortChanging(int value);
    partial void OnSortChanged();
    partial void OnKeyDateChanging(System.DateTime value);
    partial void OnKeyDateChanged();
    partial void OnKeyManChanging(string value);
    partial void OnKeyManChanged();
    partial void OnNotifyDayChanging(int value);
    partial void OnNotifyDayChanged();
    partial void OnRelationAppChanging(string value);
    partial void OnRelationAppChanged();
    #endregion
		
		public NotifyClass()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comp", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Comp
		{
			get
			{
				return this._Comp;
			}
			set
			{
				if ((this._Comp != value))
				{
					this.OnCompChanging(value);
					this.SendPropertyChanging();
					this._Comp = value;
					this.SendPropertyChanged("Comp");
					this.OnCompChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DisplayName
		{
			get
			{
				return this._DisplayName;
			}
			set
			{
				if ((this._DisplayName != value))
				{
					this.OnDisplayNameChanging(value);
					this.SendPropertyChanging();
					this._DisplayName = value;
					this.SendPropertyChanged("DisplayName");
					this.OnDisplayNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssemblyName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string AssemblyName
		{
			get
			{
				return this._AssemblyName;
			}
			set
			{
				if ((this._AssemblyName != value))
				{
					this.OnAssemblyNameChanging(value);
					this.SendPropertyChanging();
					this._AssemblyName = value;
					this.SendPropertyChanged("AssemblyName");
					this.OnAssemblyNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string ClassName
		{
			get
			{
				return this._ClassName;
			}
			set
			{
				if ((this._ClassName != value))
				{
					this.OnClassNameChanging(value);
					this.SendPropertyChanging();
					this._ClassName = value;
					this.SendPropertyChanged("ClassName");
					this.OnClassNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Memo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Memo
		{
			get
			{
				return this._Memo;
			}
			set
			{
				if ((this._Memo != value))
				{
					this.OnMemoChanging(value);
					this.SendPropertyChanging();
					this._Memo = value;
					this.SendPropertyChanged("Memo");
					this.OnMemoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this.OnMessageChanging(value);
					this.SendPropertyChanging();
					this._Message = value;
					this.SendPropertyChanged("Message");
					this.OnMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sort", DbType="Int NOT NULL")]
		public int Sort
		{
			get
			{
				return this._Sort;
			}
			set
			{
				if ((this._Sort != value))
				{
					this.OnSortChanging(value);
					this.SendPropertyChanging();
					this._Sort = value;
					this.SendPropertyChanged("Sort");
					this.OnSortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyDate", DbType="DateTime NOT NULL")]
		public System.DateTime KeyDate
		{
			get
			{
				return this._KeyDate;
			}
			set
			{
				if ((this._KeyDate != value))
				{
					this.OnKeyDateChanging(value);
					this.SendPropertyChanging();
					this._KeyDate = value;
					this.SendPropertyChanged("KeyDate");
					this.OnKeyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyMan", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string KeyMan
		{
			get
			{
				return this._KeyMan;
			}
			set
			{
				if ((this._KeyMan != value))
				{
					this.OnKeyManChanging(value);
					this.SendPropertyChanging();
					this._KeyMan = value;
					this.SendPropertyChanged("KeyMan");
					this.OnKeyManChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotifyDay", DbType="Int NOT NULL")]
		public int NotifyDay
		{
			get
			{
				return this._NotifyDay;
			}
			set
			{
				if ((this._NotifyDay != value))
				{
					this.OnNotifyDayChanging(value);
					this.SendPropertyChanging();
					this._NotifyDay = value;
					this.SendPropertyChanged("NotifyDay");
					this.OnNotifyDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RelationApp", DbType="NVarChar(50)")]
		public string RelationApp
		{
			get
			{
				return this._RelationApp;
			}
			set
			{
				if ((this._RelationApp != value))
				{
					this.OnRelationAppChanging(value);
					this.SendPropertyChanging();
					this._RelationApp = value;
					this.SendPropertyChanged("RelationApp");
					this.OnRelationAppChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BASE")]
	public partial class BASE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _NOBR;
		
		private string _NAME_C;
		
		private string _EMAIL;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNOBRChanging(string value);
    partial void OnNOBRChanged();
    partial void OnNAME_CChanging(string value);
    partial void OnNAME_CChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    #endregion
		
		public BASE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOBR", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string NOBR
		{
			get
			{
				return this._NOBR;
			}
			set
			{
				if ((this._NOBR != value))
				{
					this.OnNOBRChanging(value);
					this.SendPropertyChanging();
					this._NOBR = value;
					this.SendPropertyChanged("NOBR");
					this.OnNOBRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME_C", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NAME_C
		{
			get
			{
				return this._NAME_C;
			}
			set
			{
				if ((this._NAME_C != value))
				{
					this.OnNAME_CChanging(value);
					this.SendPropertyChanging();
					this._NAME_C = value;
					this.SendPropertyChanged("NAME_C");
					this.OnNAME_CChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BASETTS")]
	public partial class BASETTS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _NOBR;
		
		private System.DateTime _ADATE;
		
		private System.Nullable<System.DateTime> _DDATE;
		
		private string _DEPT;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNOBRChanging(string value);
    partial void OnNOBRChanged();
    partial void OnADATEChanging(System.DateTime value);
    partial void OnADATEChanged();
    partial void OnDDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnDDATEChanged();
    partial void OnDEPTChanging(string value);
    partial void OnDEPTChanged();
    #endregion
		
		public BASETTS()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOBR", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string NOBR
		{
			get
			{
				return this._NOBR;
			}
			set
			{
				if ((this._NOBR != value))
				{
					this.OnNOBRChanging(value);
					this.SendPropertyChanging();
					this._NOBR = value;
					this.SendPropertyChanged("NOBR");
					this.OnNOBRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADATE", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime ADATE
		{
			get
			{
				return this._ADATE;
			}
			set
			{
				if ((this._ADATE != value))
				{
					this.OnADATEChanging(value);
					this.SendPropertyChanging();
					this._ADATE = value;
					this.SendPropertyChanged("ADATE");
					this.OnADATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> DDATE
		{
			get
			{
				return this._DDATE;
			}
			set
			{
				if ((this._DDATE != value))
				{
					this.OnDDATEChanging(value);
					this.SendPropertyChanging();
					this._DDATE = value;
					this.SendPropertyChanged("DDATE");
					this.OnDDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DEPT
		{
			get
			{
				return this._DEPT;
			}
			set
			{
				if ((this._DEPT != value))
				{
					this.OnDEPTChanging(value);
					this.SendPropertyChanging();
					this._DEPT = value;
					this.SendPropertyChanged("DEPT");
					this.OnDEPTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DEPT")]
	public partial class DEPT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _D_NO;
		
		private string _D_NAME;
		
		private string _DEPT_GROUP;
		
		private string _NOBR;
		
		private string _EMAIL;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnD_NOChanging(string value);
    partial void OnD_NOChanged();
    partial void OnD_NAMEChanging(string value);
    partial void OnD_NAMEChanged();
    partial void OnDEPT_GROUPChanging(string value);
    partial void OnDEPT_GROUPChanged();
    partial void OnNOBRChanging(string value);
    partial void OnNOBRChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    #endregion
		
		public DEPT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D_NO", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string D_NO
		{
			get
			{
				return this._D_NO;
			}
			set
			{
				if ((this._D_NO != value))
				{
					this.OnD_NOChanging(value);
					this.SendPropertyChanging();
					this._D_NO = value;
					this.SendPropertyChanged("D_NO");
					this.OnD_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D_NAME", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string D_NAME
		{
			get
			{
				return this._D_NAME;
			}
			set
			{
				if ((this._D_NAME != value))
				{
					this.OnD_NAMEChanging(value);
					this.SendPropertyChanging();
					this._D_NAME = value;
					this.SendPropertyChanged("D_NAME");
					this.OnD_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_GROUP", DbType="NVarChar(50)")]
		public string DEPT_GROUP
		{
			get
			{
				return this._DEPT_GROUP;
			}
			set
			{
				if ((this._DEPT_GROUP != value))
				{
					this.OnDEPT_GROUPChanging(value);
					this.SendPropertyChanging();
					this._DEPT_GROUP = value;
					this.SendPropertyChanged("DEPT_GROUP");
					this.OnDEPT_GROUPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOBR", DbType="NVarChar(50)")]
		public string NOBR
		{
			get
			{
				return this._NOBR;
			}
			set
			{
				if ((this._NOBR != value))
				{
					this.OnNOBRChanging(value);
					this.SendPropertyChanging();
					this._NOBR = value;
					this.SendPropertyChanged("NOBR");
					this.OnNOBRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(500)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.U_USER")]
	public partial class U_USER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _USER_ID;
		
		private string _NAME;
		
		private string _SYSTEM;
		
		private string _E_MAIL;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUSER_IDChanging(string value);
    partial void OnUSER_IDChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnSYSTEMChanging(string value);
    partial void OnSYSTEMChanged();
    partial void OnE_MAILChanging(string value);
    partial void OnE_MAILChanged();
    #endregion
		
		public U_USER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string USER_ID
		{
			get
			{
				return this._USER_ID;
			}
			set
			{
				if ((this._USER_ID != value))
				{
					this.OnUSER_IDChanging(value);
					this.SendPropertyChanging();
					this._USER_ID = value;
					this.SendPropertyChanged("USER_ID");
					this.OnUSER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYSTEM", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SYSTEM
		{
			get
			{
				return this._SYSTEM;
			}
			set
			{
				if ((this._SYSTEM != value))
				{
					this.OnSYSTEMChanging(value);
					this.SendPropertyChanging();
					this._SYSTEM = value;
					this.SendPropertyChanged("SYSTEM");
					this.OnSYSTEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_MAIL", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string E_MAIL
		{
			get
			{
				return this._E_MAIL;
			}
			set
			{
				if ((this._E_MAIL != value))
				{
					this.OnE_MAILChanging(value);
					this.SendPropertyChanging();
					this._E_MAIL = value;
					this.SendPropertyChanged("E_MAIL");
					this.OnE_MAILChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NotifyTemplate")]
	public partial class NotifyTemplate : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AutoKey;
		
		private string _Comp;
		
		private string _NotifyType;
		
		private string _TargetType;
		
		private string _Target;
		
		private int _NotifyDay;
		
		private string _Memo;
		
		private System.DateTime _KeyDate;
		
		private string _KeyMan;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAutoKeyChanging(int value);
    partial void OnAutoKeyChanged();
    partial void OnCompChanging(string value);
    partial void OnCompChanged();
    partial void OnNotifyTypeChanging(string value);
    partial void OnNotifyTypeChanged();
    partial void OnTargetTypeChanging(string value);
    partial void OnTargetTypeChanged();
    partial void OnTargetChanging(string value);
    partial void OnTargetChanged();
    partial void OnNotifyDayChanging(int value);
    partial void OnNotifyDayChanged();
    partial void OnMemoChanging(string value);
    partial void OnMemoChanged();
    partial void OnKeyDateChanging(System.DateTime value);
    partial void OnKeyDateChanged();
    partial void OnKeyManChanging(string value);
    partial void OnKeyManChanged();
    #endregion
		
		public NotifyTemplate()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoKey", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AutoKey
		{
			get
			{
				return this._AutoKey;
			}
			set
			{
				if ((this._AutoKey != value))
				{
					this.OnAutoKeyChanging(value);
					this.SendPropertyChanging();
					this._AutoKey = value;
					this.SendPropertyChanged("AutoKey");
					this.OnAutoKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comp", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Comp
		{
			get
			{
				return this._Comp;
			}
			set
			{
				if ((this._Comp != value))
				{
					this.OnCompChanging(value);
					this.SendPropertyChanging();
					this._Comp = value;
					this.SendPropertyChanged("Comp");
					this.OnCompChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotifyType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NotifyType
		{
			get
			{
				return this._NotifyType;
			}
			set
			{
				if ((this._NotifyType != value))
				{
					this.OnNotifyTypeChanging(value);
					this.SendPropertyChanging();
					this._NotifyType = value;
					this.SendPropertyChanged("NotifyType");
					this.OnNotifyTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TargetType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TargetType
		{
			get
			{
				return this._TargetType;
			}
			set
			{
				if ((this._TargetType != value))
				{
					this.OnTargetTypeChanging(value);
					this.SendPropertyChanging();
					this._TargetType = value;
					this.SendPropertyChanged("TargetType");
					this.OnTargetTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Target", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Target
		{
			get
			{
				return this._Target;
			}
			set
			{
				if ((this._Target != value))
				{
					this.OnTargetChanging(value);
					this.SendPropertyChanging();
					this._Target = value;
					this.SendPropertyChanged("Target");
					this.OnTargetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotifyDay", DbType="Int NOT NULL")]
		public int NotifyDay
		{
			get
			{
				return this._NotifyDay;
			}
			set
			{
				if ((this._NotifyDay != value))
				{
					this.OnNotifyDayChanging(value);
					this.SendPropertyChanging();
					this._NotifyDay = value;
					this.SendPropertyChanged("NotifyDay");
					this.OnNotifyDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Memo", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Memo
		{
			get
			{
				return this._Memo;
			}
			set
			{
				if ((this._Memo != value))
				{
					this.OnMemoChanging(value);
					this.SendPropertyChanging();
					this._Memo = value;
					this.SendPropertyChanged("Memo");
					this.OnMemoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyDate", DbType="DateTime NOT NULL")]
		public System.DateTime KeyDate
		{
			get
			{
				return this._KeyDate;
			}
			set
			{
				if ((this._KeyDate != value))
				{
					this.OnKeyDateChanging(value);
					this.SendPropertyChanging();
					this._KeyDate = value;
					this.SendPropertyChanged("KeyDate");
					this.OnKeyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyMan", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string KeyMan
		{
			get
			{
				return this._KeyMan;
			}
			set
			{
				if ((this._KeyMan != value))
				{
					this.OnKeyManChanging(value);
					this.SendPropertyChanging();
					this._KeyMan = value;
					this.SendPropertyChanged("KeyMan");
					this.OnKeyManChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.U_USERCOMP")]
	public partial class U_USERCOMP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _USER_ID;
		
		private string _COMPANY;
		
		private string _NOTE;
		
		private System.DateTime _KEY_DATE;
		
		private string _KEY_MAN;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUSER_IDChanging(string value);
    partial void OnUSER_IDChanged();
    partial void OnCOMPANYChanging(string value);
    partial void OnCOMPANYChanged();
    partial void OnNOTEChanging(string value);
    partial void OnNOTEChanged();
    partial void OnKEY_DATEChanging(System.DateTime value);
    partial void OnKEY_DATEChanged();
    partial void OnKEY_MANChanging(string value);
    partial void OnKEY_MANChanged();
    #endregion
		
		public U_USERCOMP()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string USER_ID
		{
			get
			{
				return this._USER_ID;
			}
			set
			{
				if ((this._USER_ID != value))
				{
					this.OnUSER_IDChanging(value);
					this.SendPropertyChanging();
					this._USER_ID = value;
					this.SendPropertyChanged("USER_ID");
					this.OnUSER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPANY", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string COMPANY
		{
			get
			{
				return this._COMPANY;
			}
			set
			{
				if ((this._COMPANY != value))
				{
					this.OnCOMPANYChanging(value);
					this.SendPropertyChanging();
					this._COMPANY = value;
					this.SendPropertyChanged("COMPANY");
					this.OnCOMPANYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string NOTE
		{
			get
			{
				return this._NOTE;
			}
			set
			{
				if ((this._NOTE != value))
				{
					this.OnNOTEChanging(value);
					this.SendPropertyChanging();
					this._NOTE = value;
					this.SendPropertyChanged("NOTE");
					this.OnNOTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEY_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime KEY_DATE
		{
			get
			{
				return this._KEY_DATE;
			}
			set
			{
				if ((this._KEY_DATE != value))
				{
					this.OnKEY_DATEChanging(value);
					this.SendPropertyChanging();
					this._KEY_DATE = value;
					this.SendPropertyChanged("KEY_DATE");
					this.OnKEY_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEY_MAN", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string KEY_MAN
		{
			get
			{
				return this._KEY_MAN;
			}
			set
			{
				if ((this._KEY_MAN != value))
				{
					this.OnKEY_MANChanging(value);
					this.SendPropertyChanging();
					this._KEY_MAN = value;
					this.SendPropertyChanged("KEY_MAN");
					this.OnKEY_MANChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NotifyClassTemp")]
	public partial class NotifyClassTemp
	{
		
		private string _Code;
		
		private string _Comp;
		
		private string _DisplayName;
		
		private string _AssemblyName;
		
		private string _ClassName;
		
		private string _Memo;
		
		private string _Title;
		
		private string _Message;
		
		private string _Status;
		
		private int _Sort;
		
		private System.DateTime _KeyDate;
		
		private string _KeyMan;
		
		private int _NotifyDay;
		
		private string _RelationApp;
		
		public NotifyClassTemp()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comp", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Comp
		{
			get
			{
				return this._Comp;
			}
			set
			{
				if ((this._Comp != value))
				{
					this._Comp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DisplayName
		{
			get
			{
				return this._DisplayName;
			}
			set
			{
				if ((this._DisplayName != value))
				{
					this._DisplayName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssemblyName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string AssemblyName
		{
			get
			{
				return this._AssemblyName;
			}
			set
			{
				if ((this._AssemblyName != value))
				{
					this._AssemblyName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string ClassName
		{
			get
			{
				return this._ClassName;
			}
			set
			{
				if ((this._ClassName != value))
				{
					this._ClassName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Memo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Memo
		{
			get
			{
				return this._Memo;
			}
			set
			{
				if ((this._Memo != value))
				{
					this._Memo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this._Message = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sort", DbType="Int NOT NULL")]
		public int Sort
		{
			get
			{
				return this._Sort;
			}
			set
			{
				if ((this._Sort != value))
				{
					this._Sort = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyDate", DbType="DateTime NOT NULL")]
		public System.DateTime KeyDate
		{
			get
			{
				return this._KeyDate;
			}
			set
			{
				if ((this._KeyDate != value))
				{
					this._KeyDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyMan", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string KeyMan
		{
			get
			{
				return this._KeyMan;
			}
			set
			{
				if ((this._KeyMan != value))
				{
					this._KeyMan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotifyDay", DbType="Int NOT NULL")]
		public int NotifyDay
		{
			get
			{
				return this._NotifyDay;
			}
			set
			{
				if ((this._NotifyDay != value))
				{
					this._NotifyDay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RelationApp", DbType="NVarChar(50)")]
		public string RelationApp
		{
			get
			{
				return this._RelationApp;
			}
			set
			{
				if ((this._RelationApp != value))
				{
					this._RelationApp = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
