<?xml version="1.0" encoding="utf-8"?><Database Name="SUNLITHR" Class="DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=Mail;Integrated Security=True" SettingsObjectName="JBModule.Message.Properties.Settings" SettingsPropertyName="MailConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SYSLOG" Member="SYSLOG">
    <Type Name="SYSLOG">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TYPE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SOURCE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="true" />
      <Column Name="SID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GUID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TITLE" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="true" />
      <Column Name="NOTE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NOTE1" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NOTE2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NOTE3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NOTE4" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NOTE5" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KEY_DATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="KEY_MAN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MAILQUEUE" Member="MAILQUEUE">
    <Type Name="MAILQUEUE">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GUID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FROM_ADDR" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FROM_NAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TO_ADDR" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TO_NAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SUBJECT" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="BODY" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="RETRY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SUCCESS" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SUSPEND" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FREEZE_TIME" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="KEY_DATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="KEY_MAN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NOTE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NOTE1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NOTE2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NOTE3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NOTE4" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NOTE5" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PARAMETER" Member="PARAMETER">
    <Type Name="PARAMETER">
      <Column Name="AUTO" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PARMGROUP_AUTO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CODE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TYPE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="VALUE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="KEY_DATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="KEY_MAN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NOTE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NOTE1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NOTE2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NOTE3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NOTE4" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NOTE5" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DISPLAY" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PARAMETER_TREE" Member="PARAMETER_TREE">
    <Type Name="PARAMETER_TREE">
      <Column Name="AUTO" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CODE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DISPLAY" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SORT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KEY_DATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="KEY_MAN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NOTE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NOTE1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NOTE2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NOTE3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NOTE4" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HR_File" Member="HR_File">
    <Type Name="HR_File">
      <Column Name="ID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GroupID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FileBinary" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsStoredInDB" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="Path" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="FileType" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="FileSize" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FileDesc" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FileNameExt" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FileStreamInfo" Member="FileStreamInfo">
    <Type Name="FileStreamInfo">
      <Column Name="FileID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ExtensionName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="FileStream" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="FileSize" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FileTicket" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreateMan" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.NotifyClass" Member="NotifyClass">
    <Type Name="NotifyClass">
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Comp" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DisplayName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AssemblyName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ClassName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Memo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Sort" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KeyDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="KeyMan" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NotifyDay" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RelationApp" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BASE" Member="BASE">
    <Type Name="BASE">
      <Column Name="NOBR" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NAME_C" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EMAIL" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.BASETTS" Member="BASETTS">
    <Type Name="BASETTS">
      <Column Name="NOBR" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ADATE" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DEPT" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DEPT" Member="DEPT">
    <Type Name="DEPT">
      <Column Name="D_NO" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="D_NAME" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DEPT_GROUP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NOBR" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.U_USER" Member="U_USER">
    <Type Name="U_USER">
      <Column Name="USER_ID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SYSTEM" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="E_MAIL" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.NotifyTemplate" Member="NotifyTemplate">
    <Type Name="NotifyTemplate">
      <Column Name="AutoKey" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Comp" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NotifyType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TargetType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Target" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NotifyDay" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Memo" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="KeyDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="KeyMan" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.U_USERCOMP" Member="U_USERCOMP">
    <Type Name="U_USERCOMP">
      <Column Name="USER_ID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="COMPANY" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NOTE" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="KEY_DATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="KEY_MAN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.NotifyClassTemp" Member="NotifyClassTemp">
    <Type Name="NotifyClassTemp">
      <Column Name="Code" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Comp" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DisplayName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AssemblyName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ClassName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Memo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Sort" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KeyDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="KeyMan" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NotifyDay" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RelationApp" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>