<?xml version="1.0" encoding="utf-8"?><Database Name="ASMLHR" Class="dcHrDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=211.78.84.41;Initial Catalog=ASMLHR;Persist Security Info=True;User ID=jb" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="HrConnectionString" Provider="System.Data.SqlClient" />
</Database>