//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JBModule.Data.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=jb-develop;Initial Catalog=FEFCHR_T;Persist Security Info=True;User I" +
            "D=jb;Password=JB8421")]
        public string FEFCHR_TConnectionString {
            get {
                return ((string)(this["FEFCHR_TConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=JB-SP;Initial Catalog=FEFCHR;Persist Security Info=True;User ID=jb;Pa" +
            "ssword=JB8421")]
        public string FEFCHRConnectionString {
            get {
                return ((string)(this["FEFCHRConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=jb-sp;Initial Catalog=FEFCHR;Persist Security Info=True;User ID=jb;Pa" +
            "ssword=JB8421")]
        public string FEFCHRConnectionString1 {
            get {
                return ((string)(this["FEFCHRConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=JB-VSTS;Initial Catalog=BUWONHR;Persist Security Info=True;User ID=jb" +
            ";Password=JB8421")]
        public string BUWONHRConnectionString {
            get {
                return ((string)(this["BUWONHRConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=jb-vsts;Initial Catalog=CORSAIRHR;User ID=JB;Password=JB8421")]
        public string CORSAIRHRConnectionString {
            get {
                return ((string)(this["CORSAIRHRConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP\\SQLEXPRESS;Initial Catalog=SINHERHR_CN;Persist Security Info=" +
            "True;User ID=jb;Password=JB8421")]
        public string FEFCHR_DConnectionString {
            get {
                //return ((string)(this["FEFCHR_DConnectionString"]));
                return ConfigSetting.ConnectionString(ConfigSetting.AppSettingValue("JBModule.Data.HrDBConnectionString"));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=jb-vsts;Initial Catalog=HOLYHRDB;Persist Security Info=True;User ID=j" +
            "b;Password=JB8421")]
        public string HOLYHRDBConnectionString {
            get {
                return ((string)(this["HOLYHRDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=61.222.40.10;Initial Catalog=HOLYHRDB;Persist Security Info=True;User" +
            " ID=jb;Password=jb0000")]
        public string HOLYHRDBConnectionString1 {
            get {
                return ((string)(this["HOLYHRDBConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=jb-vsts;Initial Catalog=JBHRDB;Persist Security Info=True;User ID=jb;" +
            "Password=JB8421")]
        public string JBHRDBConnectionString {
            get {
                //return ((string)(this["JBHRDBConnectionString"]));
                return ConfigSetting.ConnectionString(ConfigSetting.AppSettingValue("JBModule.Data.HrDBConnectionString"));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.12;Initial Catalog=SIXXONHR;Persist Security Info=True;User" +
            " ID=jb;Password=JB8421")]
        public string SIXXONHRConnectionString {
            get {
                return ((string)(this["SIXXONHRConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=jb-vsts;Initial Catalog=GLOBALTEKHR;Persist Security Info=True;User I" +
            "D=jb;Password=JB8421")]
        public string GLOBALTEKHRConnectionString {
            get {
                return ((string)(this["GLOBALTEKHRConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=jb-vsts\\;Initial Catalog=HIYES2016HR;Persist Security Info=True;User " +
            "ID=jb;Password=JB8421")]
        public string HIYES2016HRConnectionString {
            get {
                return ((string)(this["HIYES2016HRConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP\\SQLEXPRESS;Initial Catalog=SINHERHR_CN;Persist Security Info=" +
            "True;User ID=jb;Password=JB8421")]
        public string SINHERHR_CNConnectionString {
            get {
                //return ((string)(this["SINHERHR_CNConnectionString"]));
                return ConfigSetting.ConnectionString(ConfigSetting.AppSettingValue("JBModule.Data.HrDBConnectionString"));
            }
        }
    }
}
