using System;
using System.Collections.Generic;

namespace JBAppService.Api.Dal.Models.HRContent
{
    public partial class QaAttendanceInfo
    {
        public string Nobr { get; set; }
        public DateTime Attdate { get; set; }
        public string Rote { get; set; }
        public string Rotename { get; set; }
        public decimal WkHrs { get; set; }
        public decimal AttHrs { get; set; }
        public decimal LateMins { get; set; }
        public decimal EMins { get; set; }
        public bool Abs { get; set; }
        public decimal Forget { get; set; }
        public decimal AbsHrs { get; set; }
        public decimal AbsC01 { get; set; }
        public decimal AbsC03 { get; set; }
        public decimal AbsC21 { get; set; }
        public decimal AbsC22 { get; set; }
        public decimal AbsC05 { get; set; }
        public decimal AbsC06 { get; set; }
        public decimal AbsC07 { get; set; }
        public decimal AbsC14 { get; set; }
        public decimal AbsC15 { get; set; }
        public decimal AbsC17 { get; set; }
        public decimal AbsC19 { get; set; }
        public decimal AbsC08 { get; set; }
        public decimal AbsC09 { get; set; }
        public decimal AbsC10 { get; set; }
        public decimal AbsC11 { get; set; }
        public decimal AbsC12 { get; set; }
        public decimal AbsC13 { get; set; }
        public decimal AbsC16 { get; set; }
        public decimal AbsC18 { get; set; }
        public decimal AbsC20 { get; set; }
        public decimal AbsC23 { get; set; }
        public decimal Ot1 { get; set; }
        public decimal Ot2 { get; set; }
        public decimal Ot3 { get; set; }
        public decimal OtHours { get; set; }
        public string Expr2 { get; set; }
        public string NameC { get; set; }
        public string Ttscode { get; set; }
        public string Ttsname { get; set; }
        public DateTime Adate { get; set; }
        public DateTime? Ddate { get; set; }
        public DateTime? Indt { get; set; }
        public DateTime? Oudt { get; set; }
        public DateTime? Cindt { get; set; }
        public DateTime? Stdt { get; set; }
        public DateTime? Stindt { get; set; }
        public DateTime? Stoudt { get; set; }
        public DateTime? ApDate { get; set; }
        public string Comp { get; set; }
        public string Compname { get; set; }
        public string Dept { get; set; }
        public string DeptName { get; set; }
        public string Depts { get; set; }
        public string DeptsName { get; set; }
        public string Deptm { get; set; }
        public string DeptaName { get; set; }
        public string Job { get; set; }
        public string JobName { get; set; }
        public string Rotet { get; set; }
        public string Card { get; set; }
        public string Di { get; set; }
        public string Workcd { get; set; }
        public string WorkAddr { get; set; }
        public string Nation { get; set; }
        public string NationName { get; set; }
        public decimal WkYrs { get; set; }
        public decimal? WorkYrs { get; set; }
        public string Saltyname { get; set; }
        public string Calsaltype { get; set; }
        public string CalsaltypeName { get; set; }
        public string Empcd { get; set; }
        public string EmpName { get; set; }
        public string Housetype { get; set; }
        public string HousetypeName { get; set; }
        public string Outcd { get; set; }
        public string Outname { get; set; }
        public DateTime? Birdt { get; set; }
        public string Addr1 { get; set; }
        public string Sex { get; set; }
        public string Email { get; set; }
        public string Idno { get; set; }
        public bool CountMa { get; set; }
        public bool Calabs { get; set; }
        public bool Noot { get; set; }
        public bool Noter { get; set; }
        public bool Nowage { get; set; }
        public string Memo { get; set; }
        public DateTime? Officialdate { get; set; }
        public string AccountNo { get; set; }
        public string NameE { get; set; }
        public DateTime? IdnoEdate { get; set; }
        public string Name { get; set; }
        public string Subtel { get; set; }
        public string Gsm { get; set; }
        public string Tel1 { get; set; }
        public string Postcode1 { get; set; }
        public string Marry { get; set; }
        public string Country { get; set; }
        public string CountryName { get; set; }
        public string Province { get; set; }
        public string BornAddr { get; set; }
        public string ContMan { get; set; }
        public string ContTel { get; set; }
        public string ContGsm { get; set; }
        public string ContMan2 { get; set; }
        public string ContTel2 { get; set; }
        public string ContGsm2 { get; set; }
        public string Ttscd { get; set; }
        public string Ttscdname { get; set; }
        public string Schl { get; set; }
    }
}
