using System;
using System.Collections.Generic;

namespace JBAppService.Api.Dal.Models.HRContent
{
    public partial class ReportEmp
    {
        public string 員工編號 { get; set; }
        public string 員工姓名 { get; set; }
        public string 英文姓名 { get; set; }
        public string 護照姓名 { get; set; }
        public string 性別 { get; set; }
        public DateTime? 出生日期 { get; set; }
        public string 通訊地址 { get; set; }
        public string 戶籍地址 { get; set; }
        public string 通訊電話 { get; set; }
        public string 戶籍電話 { get; set; }
        public string 電子郵件 { get; set; }
        public string 行動電話 { get; set; }
        public string 身分證號 { get; set; }
        public string 連絡人1姓名 { get; set; }
        public string 連絡人1電話 { get; set; }
        public string 連絡人1行動電話 { get; set; }
        public string 連絡人2姓名 { get; set; }
        public string 連絡人2電話 { get; set; }
        public string 連絡人2行動電話 { get; set; }
        public string 血型 { get; set; }
        public string 密碼 { get; set; }
        public string 通訊郵遞區號 { get; set; }
        public string 戶籍郵遞區號 { get; set; }
        public string 轉帳銀行 { get; set; }
        public string 轉帳帳號 { get; set; }
        public string 婚姻 { get; set; }
        public string 國籍 { get; set; }
        public bool 外籍員工 { get; set; }
        public string 兵役 { get; set; }
        public string 保證人1姓名 { get; set; }
        public string 保證人1住址 { get; set; }
        public string 保證人1身分證號 { get; set; }
        public string 保證人1電話 { get; set; }
        public string 保證人2姓名 { get; set; }
        public string 保證人2住址 { get; set; }
        public string 保證人2身分證號 { get; set; }
        public string 保證人2電話 { get; set; }
        public string 介紹人 { get; set; }
        public string 出生地 { get; set; }
        public decimal 扶養人數 { get; set; }
        public string 護照號碼 { get; set; }
        public decimal 所得稅預扣金額 { get; set; }
        public string 連絡人1關係 { get; set; }
        public string 連絡人2關係 { get; set; }
        public string 外勞帳號 { get; set; }
        public string 居留證號 { get; set; }
        public string 分機 { get; set; }
        public string 身分別 { get; set; }
        public string Ad帳號 { get; set; }
        public string 異動狀態 { get; set; }
        public DateTime? 異動失效日 { get; set; }
        public DateTime? 公司到職日 { get; set; }
        public DateTime? 集團到職日 { get; set; }
        public DateTime? 離職日 { get; set; }
        public string 離職原因代碼 { get; set; }
        public string 離職原因名稱 { get; set; }
        public DateTime? 停薪日期 { get; set; }
        public DateTime? 停復日期 { get; set; }
        public DateTime? 停離日期 { get; set; }
        public string 公司別 { get; set; }
        public string 刷卡 { get; set; }
        public string 直間接 { get; set; }
        public bool 部門主管 { get; set; }
        public decimal 外部年資 { get; set; }
        public string 薪別代碼 { get; set; }
        public string 薪別名稱 { get; set; }
        public bool 不計算請假 { get; set; }
        public bool 不計算工作獎金 { get; set; }
        public bool 不判斷遲到早退 { get; set; }
        public bool 不計算福利金 { get; set; }
        public bool 不計算退休金新制 { get; set; }
        public bool 不產生加班 { get; set; }
        public bool 不計算特休代金 { get; set; }
        public bool 不計算所得稅 { get; set; }
        public bool 可申請補休 { get; set; }
        public string 異動備註 { get; set; }
        public string 資料群組代碼 { get; set; }
        public string 資料群組名稱 { get; set; }
        public bool 不發薪 { get; set; }
        public bool 可知網頁人事資料 { get; set; }
        public decimal 員工勞退提撥比率 { get; set; }
        public DateTime? 勞退新制日期 { get; set; }
        public string 退休金制度 { get; set; }
        public DateTime? 勞退新制提撥日 { get; set; }
        public bool 只刷上班卡 { get; set; }
        public bool 可線上刷卡 { get; set; }
        public bool 可代申請表單 { get; set; }
        public DateTime? 試用期滿日 { get; set; }
        public DateTime? 居留証起始日 { get; set; }
        public DateTime? 居留証到期日 { get; set; }
        public bool 不計算三節獎金 { get; set; }
        public bool 所得稅固定稅率扣繳 { get; set; }
        public string 編制部門代碼 { get; set; }
        public string 編制部門名稱 { get; set; }
        public string 簽核部門代碼 { get; set; }
        public string 簽核部門名稱 { get; set; }
        public string 成本部門代碼 { get; set; }
        public string 成本部門名稱 { get; set; }
        public string 職稱代碼 { get; set; }
        public string 職稱名稱 { get; set; }
        public string 職等代碼 { get; set; }
        public string 職等名稱 { get; set; }
        public string 工作地代碼 { get; set; }
        public string 工作地名稱 { get; set; }
        public string 異動原因名稱 { get; set; }
        public string 輪班別代碼 { get; set; }
        public string 輪班別名稱 { get; set; }
        public string 行事曆代碼 { get; set; }
        public string 行事曆名稱 { get; set; }
        public string 員別代碼 { get; set; }
        public string 員別名稱 { get; set; }
        public string 加班比率代碼 { get; set; }
        public string 加班比率名稱 { get; set; }
    }
}
